### ISSUE TITLE
errors in examples: format %lx, %ld 

### ISSUE THREAD

**Issue by ghost** [luigirizzo/netmap#101]
arm-xilinx-linux-gnueabi-gcc -O2 -pipe -Werror -Wall -Wunused-function -I ../sys  -Wextra -DNO_PCAP   -c -o pkt-gen.o pkt-gen.c
	In file included from pkt-gen.c:43:0:
	pkt-gen.c: In function 'main':
	../sys/net/netmap_user.h:175:10: error: format '%lx' expects argument of type 'long unsigned int', but argument 8 has type 'int' [-Werror=format=]
	   struct timeval _t0;    \
			  ^
	pkt-gen.c:2159:4: note: in expansion of macro 'D'
		D("   TX%d at 0x%lx slots %d", i,
		^
	cc1: all warnings being treated as errors

`(char *)ring - (char *)nifp, ring->num_slots);`
substitute pkt-gen.c:2159
` (unsigned long)((char *)ring - (char *)nifp), ring->num_slots);`

	arm-xilinx-linux-gnueabi-gcc -O2 -pipe -Werror -Wall -Wunused-function -I ../sys  -Wextra -DNO_PCAP    testmmap.c  -lpthread -lrt	 -o testmmap
	testmmap.c: In function 'do_if':
	testmmap.c:540:3: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'ssize_t' [-Werror=format=]
	   printf("ring_ofs[%d] %ld\n", i, nifp->ring_ofs[i]);
	   ^
	cc1: all warnings being treated as errors

`printf("ring_ofs[%d] %ld\n", i, nifp->ring_ofs[i]);`
substitute testmmap.c:540
`printf("ring_ofs[%d] %ld\n", i, (unsigned long)nifp->ring_ofs[i]);`

**Comment by skiingyac** [comment]
my pull request fixes this:
https://github.com/luigirizzo/netmap/pull/97/files
