### ISSUE TITLE
pkt-gen stops receiving after 511 packets

### ISSUE THREAD

**Issue by john-gress** [luigirizzo/netmap#102]
Running on CentOS 6.5 with an updated kernel: 2.6.32-573.7.1.el6.x86_64: Using pkt-gen to receive packets, I consistently receive 510 to 512 packets, and after that the poll never returns with something to read. If I slow down the transmission, then poll will return repeatedly with something to read until I have read around 512 packets.

I appreciate any advice you might be able to give me to investigate what is going on.

In this output, the sender is transmitting 1400 byte packets at around 1Mpps.

<pre><code>
./pkt-gen -i eth7
946.440749 main [1918] interface is eth7
946.441737 main [2038] running on 1 cpus (have 48)
946.452937 extract_ip_range [366] range is 10.0.0.1:0 to 10.0.0.1:0
946.452949 extract_ip_range [366] range is 10.1.0.1:0 to 10.1.0.1:0
946.847153 main [2136] mapped 334980KB at 0x7f199cc95000
Receiving from netmap:eth7: 1 queues, 1 threads and 1 cpus.
946.847196 main [2223] Wait 2 secs for phy reset
948.847310 main [2225] Ready...
948.847462 receiver_body [1411] reading from netmap:eth7 fd 3 main_fd 3
949.848465 main_thread [1708] 511.000 pps (512.000 pkts 5.734 Mbps in 1001053 usec) 256.00 avg_batch
950.849563 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001098 usec) 0.00 avg_batch
951.850640 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001078 usec) 0.00 avg_batch
952.851720 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001080 usec) 0.00 avg_batch
953.852805 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001085 usec) 0.00 avg_batch
954.853889 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001083 usec) 0.00 avg_batch
955.854967 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001079 usec) 0.00 avg_batch
956.856045 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001078 usec) 0.00 avg_batch
957.857125 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001080 usec) 0.00 avg_batch
^C958.241153 sigint_h [403] received control-C on thread 0x7f19b1d86700
958.241189 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 384064 usec) 0.00 avg_batch
959.242246 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001057 usec) 0.00 avg_batch
Received 512 packets 716800 bytes 2 events 1400 bytes each in 10.01 seconds.
Speed: 51.143 pps Bandwidth: 572.800 Kbps (raw 582.619 Kbps). Average batch: 256.00 pkts
</code></pre>

In this output, the sender is transmitting 1400 byte packets at 100 packets/second.

<pre><code>
./pkt-gen -i eth7
139.811730 main [1918] interface is eth7
139.811858 main [2038] running on 1 cpus (have 48)
139.813924 extract_ip_range [366] range is 10.0.0.1:0 to 10.0.0.1:0
139.813936 extract_ip_range [366] range is 10.1.0.1:0 to 10.1.0.1:0
140.204171 main [2136] mapped 334980KB at 0x7f56b9c38000
Receiving from netmap:eth7: 1 queues, 1 threads and 1 cpus.
140.204209 main [2223] Wait 2 secs for phy reset
142.204318 main [2225] Ready...
142.204471 receiver_body [1411] reading from netmap:eth7 fd 3 main_fd 3
143.205469 main_thread [1708] 33.000 pps (33.000 pkts 369.600 Kbps in 1001053 usec) 3.00 avg_batch
144.206567 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001097 usec) 1.00 avg_batch
145.207648 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001081 usec) 1.00 avg_batch
146.208724 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
147.209811 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001087 usec) 1.00 avg_batch
148.210907 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001097 usec) 1.00 avg_batch
149.211983 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001077 usec) 1.00 avg_batch
150.213064 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001080 usec) 1.00 avg_batch
151.214146 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001082 usec) 1.00 avg_batch
152.215218 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001073 usec) 1.00 avg_batch
153.216303 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001085 usec) 1.00 avg_batch
154.217390 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001087 usec) 1.00 avg_batch
155.218476 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001085 usec) 1.00 avg_batch
156.219560 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001085 usec) 1.00 avg_batch
157.220634 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001074 usec) 1.00 avg_batch
158.221717 main_thread [1708] 9.000 pps (9.000 pkts 100.800 Kbps in 1001083 usec) 1.00 avg_batch
159.222797 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001080 usec) 1.00 avg_batch
160.223872 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001075 usec) 1.00 avg_batch
161.224955 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001083 usec) 1.00 avg_batch
162.226029 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001073 usec) 1.00 avg_batch
163.227130 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001102 usec) 1.00 avg_batch
164.228205 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001075 usec) 1.00 avg_batch
165.229293 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001088 usec) 1.00 avg_batch
166.230365 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001072 usec) 1.00 avg_batch
167.231450 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001084 usec) 1.00 avg_batch
168.232521 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001072 usec) 1.00 avg_batch
169.233610 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001089 usec) 1.00 avg_batch
170.234691 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001081 usec) 1.00 avg_batch
171.235774 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001083 usec) 1.00 avg_batch
172.236869 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001095 usec) 1.00 avg_batch
173.237952 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001083 usec) 1.00 avg_batch
174.239032 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001080 usec) 1.00 avg_batch
175.240132 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001099 usec) 1.00 avg_batch
176.241207 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
177.242279 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001071 usec) 1.00 avg_batch
178.243349 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001071 usec) 1.00 avg_batch
179.244424 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001075 usec) 1.00 avg_batch
180.245501 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001077 usec) 1.00 avg_batch
181.246579 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001078 usec) 1.00 avg_batch
182.247655 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
183.248730 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001075 usec) 1.00 avg_batch
184.249806 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
185.250884 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001078 usec) 1.00 avg_batch
186.251959 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001075 usec) 1.00 avg_batch
187.253038 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001079 usec) 1.00 avg_batch
188.254114 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
189.255196 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001082 usec) 1.00 avg_batch
190.256272 main_thread [1708] 10.000 pps (10.000 pkts 112.000 Kbps in 1001076 usec) 1.00 avg_batch
191.257349 main_thread [1708] 9.000 pps (9.000 pkts 100.800 Kbps in 1001077 usec) 1.00 avg_batch
192.258420 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001070 usec) 0.00 avg_batch
193.259496 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001077 usec) 0.00 avg_batch
194.260568 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001071 usec) 0.00 avg_batch
195.261645 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001078 usec) 0.00 avg_batch
196.262724 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001078 usec) 0.00 avg_batch
197.263798 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001075 usec) 0.00 avg_batch
198.264890 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001092 usec) 0.00 avg_batch
199.265965 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001074 usec) 0.00 avg_batch
200.267045 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001080 usec) 0.00 avg_batch
^C200.628149 sigint_h [403] received control-C on thread 0x7f56ced29700
200.628182 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 361138 usec) 0.00 avg_batch
201.629248 main_thread [1708] 0.000 pps (0.000 pkts 0.000 bps in 1001066 usec) 0.00 avg_batch
Received 511 packets 715400 bytes 489 events 1400 bytes each in 58.93 seconds.
Speed: 8.671 pps Bandwidth: 97.119 Kbps (raw 98.783 Kbps). Average batch: 1.04 pkts
</code></pre>

**Comment by vmaffione** [comment]
What kind of interface is eth7? This is the output of the receiver, not the one of the sender.

**Comment by pcherenkov** [comment]
I'm seeing a similar issue running pkg-gen of the most recent version (git-pulled on Jan 2nd, 2016), on  FreeBSD 10.2-RELEASE, using re0: <RealTek 8168/8111 B/C/CP/D/DP/E/F/G PCIe Gigabit Ethernet> driver. I start sending UDP packets to the re0-bound address from another box at 3 Kb/sec, after around 50 packets passed in (by pkt-gen) I see nothing of the UDP traffic, just a stream of ARP requests. Stopping and re-starting the traffic generator does not work, the UDP traffic is still NOT received by pkt-gen (run as: sudo ./pkt-gen -i 're0' -f rx -X). Would appreciate your help, I was planning to use netmap for a (really fast) app relaying video point-to-point.

**Comment by huangh901218** [comment]
@john-gress    Did you solve?   I met the same problem
