### ISSUE TITLE
examples/bridge to pass from stack to nic does not work on e1000e

### ISSUE THREAD

**Issue by samiruor** [luigirizzo/netmap#105]
Hi,

Facing the same issue for e1000 on git head: add1e50
Only ~49 packets are transferred, then bridge application hangs with timeouts prints. Also I observed that if I keep the application running, after sometime another burst of 49 packets are transferred followed by timeouts.

Note: I am running the example inside a virtual machine.

Thanks,
Samir

**Comment by vmaffione** [comment]
Have you've put the two network interfaces in promiscuous mode?
