### ISSUE TITLE
NS_RMOREFRAG not set in RX with IXGBE

### ISSUE THREAD

**Issue by tbarbette** [luigirizzo/netmap#106]
Hi,

With LRO enabled, my Intel X520 NIC (ixgbe driver) is producing large packets that Netmap seems to split accross multiple buffers (well, it's the NIC which does it). But the NS_MOREFRAG is not set and I have no way to know that some packets are continuing on the next buffer.

sudo ethtool -K eth2 lro off
avoid the problem...

Thanks,
Tom

**Comment by giuseppelettieri** [comment]
Hi Tom,

may we close this issue thanks to your solution which is now in master?

**Comment by tbarbette** [comment]
Yes ! Thanks !
