### ISSUE TITLE
Kernel Panic When Hot Removing Netmap-Enabled VirtIO Interface

### ISSUE THREAD

**Issue by mtang2cisco** [luigirizzo/netmap#109]
There are two issues when hot removing netmap-enabled virtio interface:
1) If an interface is first registered and then unregistered, then removing the interface would cause kernel panic.
2). If an interface is registered and not unregistered, then removing it would cause continuous rcu_sched self-detected stall.

**Comment by giuseppelettieri** [comment]
May you please check whether afab3f281 fixes point 1?

Note that, at the moment, we have no plan to fix 2. If you want to remove a driver that is currently used by netmap, you should first terminate all netmap applications.

**Comment by giuseppelettieri** [comment]
Sorry, I have messed up things a bit. The commit should have fixed your second point.

**Comment by vmaffione** [comment]
@mtang2cisco  Can you try to reproduce the problem with current code?
