### ISSUE TITLE
Porting netmap to custom driver

### ISSUE THREAD

**Issue by jobolanos** [luigirizzo/netmap#113]
Hello,

I'm a OpenSwitch developer working for Hewlett Packard Enterprise, I was assigned the task of enabling native netmap support for a custom driver as graduation project of Computer Engineering (CE) major.

I have a problem at dvr_netmap_config because PNMB function launches a NULL pointer dereference, indeed, after a few tests I realized that na->na_lut was NULL. Do you have any idea of what's causing this error?

I'm already using next branch due to an issue that raised earlier. I've implemented the functions required for native support using if_ixgbe_netmap_linux.h as guideline. Also, I'd like to review the places where I put the patches to see whether or not I'm right:
    -> The function drv_netmap_attach is called at the end of the method that creates each network interface (I wondered if the attach and detach methods should be called just on the base net_device or on each net_device, I think the right answer is the last one).
    -> The function netmap_detach is called at the end of the method that removes each network interface (before calling unregister_netdev and free_netdev).
    -> The function drv_netmap_config is called in the method that opens each network interface.
    -> Finally, the functions netmap_tx_irq and netmap_tx_irq are called on the respective interrupt dispatch routine.

That flow assures that netmap_attach is called first over a determined network interface when it is created. Then, when using pkt-gen app the netmap_do_regif (where na->na_lut is set) method succeeds and calls drv_netmap_reg. Finally, that function issues the open method over the network interface and it launches drv_netmap_config and leads to the point I'm stuck (the failure of the function PNMB).

Any help would help appreciated.

Best Regards,
Jorge Bolaños Solís
CE, Costa Rica Institute of Technology

**Comment by vmaffione** [comment]
Hi,

2015-11-25 1:26 GMT+01:00 jobolanos <notifications@github.com>:

> Hello,
>
> I'm a OpenSwitch developer working for Hewlett Packard Enterprise, I was
> assigned the task of enabling native netmap support for a custom driver as
> graduation project of Computer Engineering (CE) major.
>
> I have a problem at dvr_netmap_config because PNMB function launches a
> NULL pointer dereference, indeed, after a few tests I realized that
> na->na_lut was NULL. Do you have any idea of what's causing this error?
>
> I'm already using next branch due to an issue that raised earlier.
>
  There is no "next" branch anymore, you should use the master branch of
this repository (https://github.com/luigirizzo/netmap). So maybe you're
using a wrong starting point?

> I've implemented the functions required for native support using
> if_ixgbe_netmap_linux.h as guideline. Also, I'd like to review the places
> where I put the patches to see whether or not I'm right:
> -> The function drv_netmap_attach is called at the end of the method that
> creates each network interface (I wondered if the attach and detach methods
> should be called just on the base net_device or on each net_device, I think
> the right answer is the last one).
>

netmap_attach() is called at the end of each driver "probe routine" , so
one per network device.

> -> The function netmap_detach is called at the end of the method that
> removes each network interface (before calling unregister_netdev and
> free_netdev).
>
I guess you meant "at the beginning" of the driver "remove routine".

> -> The function drv_netmap_config is called in the method that opens each
> network interface.
>
netmap_attach() and netmap_detach() are generic functions called in the way
explained above for all NIC drivers.
Instead, there is no generic netmap_config() routine. But what a netmap
enabled driver generally has to do in the ndo_open() method is to connect
the descriptors in the RX ring(s) to netmap buffers, instead that
connecting them to sk_buffs. This is what ixgbe_netmap_configure_rx_ring()
does, for instance.

> -> Finally, the functions netmap_tx_irq and netmap_tx_irq are called on
> the respective interrupt dispatch routine.
>
It's a possibility. They may also called in the NAPI poll callback.


> That flow assures
>
that netmap_attach is called first over a determined network interface when
> it is created. Then, when using pkt-gen app the netmap_do_regif (where
> na->na_lut is set) method succeeds and calls drv_netmap_reg. Finally, that
> function issues the open method over the network interface and it launches
> drv_netmap_config and leads to the point I'm stuck (the failure of the
> function PNMB).
>
The flow seems correct. Are you sure the  interface is in native netmap
mode when the failing function is called (you can use the  nm_native_on())
function).

> Any help would help appreciated.
>
> Best Regards,
> Jorge Bolaños Solís
> CE, Costa Rica Institute of Technology
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/113>.
>



-- 
Vincenzo Maffione

**Comment by jobolanos** [comment]
On 11/25/2015 02:25 AM, Vincenzo Maffione wrote:
Hi,

2015-11-25 1:26 GMT+01:00 jobolanos <notifications@github.com><mailto:notifications@github.com>:

> Hello,
>
> I'm a OpenSwitch developer working for Hewlett Packard Enterprise, I was
> assigned the task of enabling native netmap support for a custom driver as
> graduation project of Computer Engineering (CE) major.
>
> I have a problem at dvr_netmap_config because PNMB function launches a
> NULL pointer dereference, indeed, after a few tests I realized that
> na->na_lut was NULL. Do you have any idea of what's causing this error?
>
> I'm already using next branch due to an issue that raised earlier.
>
There is no "next" branch anymore, you should use the master branch of
this repository (https://github.com/luigirizzo/netmap). So maybe you're
using a wrong starting point?

> I've implemented the functions required for native support using
> if_ixgbe_netmap_linux.h as guideline. Also, I'd like to review the places
> where I put the patches to see whether or not I'm right:
> -> The function drv_netmap_attach is called at the end of the method that
> creates each network interface (I wondered if the attach and detach methods
> should be called just on the base net_device or on each net_device, I think
> the right answer is the last one).
>

netmap_attach() is called at the end of each driver "probe routine" , so
one per network device.

> -> The function netmap_detach is called at the end of the method that
> removes each network interface (before calling unregister_netdev and
> free_netdev).
>
I guess you meant "at the beginning" of the driver "remove routine".

> -> The function drv_netmap_config is called in the method that opens each
> network interface.
>
netmap_attach() and netmap_detach() are generic functions called in the way
explained above for all NIC drivers.
Instead, there is no generic netmap_config() routine. But what a netmap
enabled driver generally has to do in the ndo_open() method is to connect
the descriptors in the RX ring(s) to netmap buffers, instead that
connecting them to sk_buffs. This is what ixgbe_netmap_configure_rx_ring()
does, for instance.

> -> Finally, the functions netmap_tx_irq and netmap_tx_irq are called on
> the respective interrupt dispatch routine.
>
It's a possibility. They may also called in the NAPI poll callback.


> That flow assures
>
that netmap_attach is called first over a determined network interface when
> it is created. Then, when using pkt-gen app the netmap_do_regif (where
> na->na_lut is set) method succeeds and calls drv_netmap_reg. Finally, that
> function issues the open method over the network interface and it launches
> drv_netmap_config and leads to the point I'm stuck (the failure of the
> function PNMB).
>
The flow seems correct. Are you sure the interface is in native netmap
mode when the failing function is called (you can use the nm_native_on())
function).

> Any help would help appreciated.
>
> Best Regards,
> Jorge Bolaños Solís
> CE, Costa Rica Institute of Technology
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/113><https://github.com/luigirizzo/netmap/issues/113>.
>



--
Vincenzo Maffione

—
Reply to this email directly or view it on GitHub<https://github.com/luigirizzo/netmap/issues/113#issuecomment-159532652>.

Hi,

First, I'd like to say thanks for your help. As you suggested, I changed the source from which the netmap code is fetched to the following repository: https://github.com/luigirizzo/netmap.git

I attached an image where you can see the point in the flow where the app fails. Also, it is shown that nm_native_on returns true before the custom bcm_netmap_config routine is called.

Also I attached my implementation of the functions bcm_netmap_reg and bcm_netmap_config, as I told you, I used if_ixgbe_netmap.h as guideline.

Finally, the driver I'm working with can be found in the following link: https://github.com/Broadcom-Switch/OpenNSL/blob/master/sdk-6.4.6-gpl-modules/systems/linux/kernel/modules/bcm-knet/bcm-knet.c

The patch that calls bcm_netmap_config custom routine is placed in bkn_open routine, which is called to set a network interface up. The patch that calls bcm_netmap_attach custom routine is placed in bkn_knet_netif_create and the patch that calls netmap_detach custom routine is placed in bkn_knet_netif_destroy routine. Those routines are called on a network interface creation and deletion respectively.

I think I have studied quite well the execution flow of the driver and how to modify it in order to enable netmap native support, but I've not been able to identify the error which crashes the application.

Best regards,

Jorge Bolaños Solís
CE, Costa Rica Institute of Technology.

**Comment by vmaffione** [comment]
I'm closing this since is not specific to netmap.
