### ISSUE TITLE
Kernel panic after 'Keep adaptor's rings either in normal or netmap mode' commit

### ISSUE THREAD

**Issue by matiaselo** [luigirizzo/netmap#122]
Hi,

We are using netmap packet I/O in [ODP](https://git.linaro.org/lng/odp.git/blob/32198b0a76079c57e3bdd124a8b253d581c71127:/platform/linux-generic/pktio/netmap.c) project. Since the commit 'Keep adaptor's rings either in normal or netmap mode' netmap has started crashing and causing kernel panics.

We are creating separate RX and TX descriptors for each NIC ring to enable lockless multi queue operation. Any ideas which change in this commit is causing the crashes?

UPDATE:
The same crash happens also with the pkt-gen example if thread count is increased.

For example: sudo ./pkt-gen -f pong -i p2p1 -p 16

Kernel log from the crash:
´´´
Dec 21 09:30:20 mchp03 kernel: [  729.776241] 020.695173 [1047] generic_netmap_dtor       Restored native NA           (null)
Dec 21 09:30:20 mchp03 kernel: [  729.783333] 020.702271 [2046] netmap_do_regif           lut ffffc90019a01000 bufs 163840 size 2048
Dec 21 09:30:20 mchp03 kernel: [  729.790398] 020.709341 [1047] generic_netmap_dtor       Restored native NA           (null)
Dec 21 09:30:20 mchp03 kernel: [  729.798062] 020.717011 [2046] netmap_do_regif           lut ffffc90019a01000 bufs 163840 size 2048
Dec 21 09:30:20 mchp03 kernel: [  729.805547] 020.724502 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.813230] 020.732191 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.820956] 020.739923 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.828709] 020.747682 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.836426] 020.755405 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.844074] 020.763060 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.851728] 020.770719 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.859574] 020.778571 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.867265] 020.786268 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.875110] 020.794119 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.882783] 020.801798 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.890519] 020.809539 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.898390] 020.817416 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.906102] 020.825135 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.913834] 020.832873 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.921571] 020.840616 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.929355] 020.848406 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.937163] 020.856220 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.944887] 020.863950 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.952675] 020.871743 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.960381] 020.879455 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.968168] 020.887249 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.975883] 020.894969 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.983688] 020.902781 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.991417] 020.910516 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  729.999125] 020.918230 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  730.006897] 020.926007 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:20 mchp03 kernel: [  730.014611] 020.933728 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:21 mchp03 kernel: [  731.022507] 021.942395 [2046] netmap_do_regif           lut ffffc90019a01000 bufs 163840 size 2048
Dec 21 09:30:21 mchp03 kernel: [  731.030914] 021.950810 [1047] generic_netmap_dtor       Restored native NA           (null)
Dec 21 09:30:21 mchp03 kernel: [  731.039984] 021.959888 [2046] netmap_do_regif           lut ffffc90019a01000 bufs 163840 size 2048
Dec 21 09:30:21 mchp03 kernel: [  731.049097] 021.969009 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:21 mchp03 kernel: [  731.058081] 021.978002 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:21 mchp03 kernel: [  731.066999] 021.986927 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:21 mchp03 kernel: [  731.075948] 021.995884 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.084569] 022.004511 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.092824] 022.012772 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.100941] 022.020895 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.108622] 022.028582 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.116022] 022.035988 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.123143] 022.043114 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.129898] 022.049875 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.136448] 022.056430 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.142602] 022.062588 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.148683] 022.068674 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.154288] 022.074283 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.159593] 022.079592 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.164592] 022.084595 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.169228] 022.089235 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.173844] 022.093855 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.178456] 022.098470 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.183008] 022.103026 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.187625] 022.107646 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.192258] 022.112283 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.196793] 022.116821 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.201399] 022.121430 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.206008] 022.126044 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.210514] 022.130552 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:22 mchp03 kernel: [  731.215089] 022.135131 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:23 mchp03 kernel: [  732.219035] BUG: unable to handle kernel NULL pointer dereference at           (null)
Dec 21 09:30:23 mchp03 kernel: [  732.223845] IP: [<ffffffffc05aee4d>] generic_netmap_txsync+0x1dd/0x4c0 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.229019] PGD f2a964067 PUD f2a963067 PMD 0 
Dec 21 09:30:23 mchp03 kernel: [  732.234374] Oops: 0000 [#1] SMP 
Dec 21 09:30:23 mchp03 kernel: [  732.239681] Modules linked in: ixgbe(OE) netmap(OE) xt_CHECKSUM iptable_mangle ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT xt_tcpudp bridge stp llc openvswitch(OE) libcrc32c ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ip_tables x_tables ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi bnep rfcomm bluetooth 6lowpan_iphc intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp nfsd kvm_intel auth_rpcgss nfs_acl kvm nfs crct10dif_pclmul crc32_pclmul ghash_clmulni_intel lockd joydev sunrpc fscache aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd hpilo lpc_ich ipmi_si ipmi_msghandler nls_iso8859_1 wmi acpi_power_meter ioatdma shpchp mac_hid parport_pc ppdev lp parport hid_generic usbhid hid tg3 i40e dca vxlan ptp pps_core hpsa [last unloaded: ixgbe]
Dec 21 09:30:23 mchp03 kernel: [  732.307026] CPU: 1 PID: 13081 Comm: pktio_main Tainted: G           OE 3.16.0-53-generic #72~14.04.1-Ubuntu
Dec 21 09:30:23 mchp03 kernel: [  732.317786] Hardware name: HP ProLiant DL360 Gen9, BIOS P89 07/20/2015
Dec 21 09:30:23 mchp03 kernel: [  732.328831] task: ffff880f4845c750 ti: ffff880f225f8000 task.ti: ffff880f225f8000
Dec 21 09:30:23 mchp03 kernel: [  732.340251] RIP: 0010:[<ffffffffc05aee4d>]  [<ffffffffc05aee4d>] generic_netmap_txsync+0x1dd/0x4c0 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.352179] RSP: 0018:ffff880f225fb9a8  EFLAGS: 00010283
Dec 21 09:30:23 mchp03 kernel: [  732.363878] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000200
Dec 21 09:30:23 mchp03 kernel: [  732.375774] RDX: ffffc90019a01000 RSI: 0000000000000001 RDI: ffff880f2a978000
Dec 21 09:30:23 mchp03 kernel: [  732.387395] RBP: ffff880f225fba60 R08: ffff880f2a978068 R09: 0000000000000001
Dec 21 09:30:23 mchp03 kernel: [  732.399009] R10: ffff880f2d7e0b40 R11: ffff880f1d49a800 R12: ffff880f1fc90100
Dec 21 09:30:23 mchp03 kernel: [  732.410665] R13: 0000000000000040 R14: ffff880f56b51000 R15: 0000000000000000
Dec 21 09:30:23 mchp03 kernel: [  732.422469] FS:  00007ffff7fd77c0(0000) GS:ffff88103f220000(0000) knlGS:0000000000000000
Dec 21 09:30:23 mchp03 kernel: [  732.435865] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Dec 21 09:30:23 mchp03 kernel: [  732.448689] CR2: 0000000000000000 CR3: 0000000f2a977000 CR4: 00000000001407e0
Dec 21 09:30:23 mchp03 kernel: [  732.461300] Stack:
Dec 21 09:30:23 mchp03 kernel: [  732.474064]  0000008000000000 ffff8810237ab000 ffff88103ec10000 000001ff00000000
Dec 21 09:30:23 mchp03 kernel: [  732.487335]  ffff880f1fc90000 00000001ffffffff 0000000000000001 ffff880f225fba50
Dec 21 09:30:23 mchp03 kernel: [  732.500821]  ffff880f2a978000 000000000000ffff 0000000000000000 ffff880f54d63000
Dec 21 09:30:23 mchp03 kernel: [  732.514373] Call Trace:
Dec 21 09:30:23 mchp03 kernel: [  732.528177]  [<ffffffffc05b32d1>] netmap_poll+0x531/0x880 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.542205]  [<ffffffffc05b5850>] linux_netmap_poll+0x30/0x40 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.556461]  [<ffffffff811e96c8>] do_sys_poll+0x2f8/0x540
Dec 21 09:30:23 mchp03 kernel: [  732.570841]  [<ffffffff8116bc4a>] ? __alloc_pages_nodemask+0x15a/0x2a0
Dec 21 09:30:23 mchp03 kernel: [  732.585525]  [<ffffffff8176dd22>] ? mutex_lock+0x12/0x2f
Dec 21 09:30:23 mchp03 kernel: [  732.600274]  [<ffffffffc05a467c>] ? netmap_mem2_ofstophys+0xfc/0x110 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.615387]  [<ffffffff811eefc1>] ? update_time+0x81/0xd0
Dec 21 09:30:23 mchp03 kernel: [  732.630640]  [<ffffffff8119930f>] ? page_add_file_rmap+0x6f/0xa0
Dec 21 09:30:23 mchp03 kernel: [  732.646202]  [<ffffffff811ef1da>] ? file_update_time+0x8a/0xd0
Dec 21 09:30:23 mchp03 kernel: [  732.661687]  [<ffffffff8118d885>] ? do_shared_fault.isra.57+0x185/0x1c0
Dec 21 09:30:23 mchp03 kernel: [  732.677459]  [<ffffffff8118ef4e>] ? handle_mm_fault+0x5de/0x10b0
Dec 21 09:30:23 mchp03 kernel: [  732.693705]  [<ffffffff8105afcc>] ? __do_page_fault+0x20c/0x560
Dec 21 09:30:23 mchp03 kernel: [  732.709668]  [<ffffffff810949f8>] ? hrtimer_try_to_cancel+0x48/0xe0
Dec 21 09:30:23 mchp03 kernel: [  732.725844]  [<ffffffff8176ae12>] ? do_nanosleep+0x92/0x130
Dec 21 09:30:23 mchp03 kernel: [  732.742117]  [<ffffffff8109561b>] ? hrtimer_nanosleep+0xbb/0x180
Dec 21 09:30:23 mchp03 kernel: [  732.758545]  [<ffffffff810944b0>] ? hrtimer_get_res+0x50/0x50
Dec 21 09:30:23 mchp03 kernel: [  732.775503]  [<ffffffff811e99e5>] SyS_poll+0x65/0x100
Dec 21 09:30:23 mchp03 kernel: [  732.792190]  [<ffffffff8176f94d>] system_call_fastpath+0x1a/0x1f
Dec 21 09:30:23 mchp03 kernel: [  732.809871] Code: 4c 8b 5d 80 66 2e 0f 1f 84 00 00 00 00 00 41 8b 86 14 01 00 00 41 39 c5 44 0f 47 e8 48 8b 45 88 48 8b 80 98 00 00 00 4e 8d 3c f8 <49> 8b 07 48 85 c0 0f 84 f9 01 00 00 48 89 45 a8 31 c0 3b 9d 70 
Dec 21 09:30:23 mchp03 kernel: [  732.845067] RIP  [<ffffffffc05aee4d>] generic_netmap_txsync+0x1dd/0x4c0 [netmap]
Dec 21 09:30:23 mchp03 kernel: [  732.862106]  RSP <ffff880f225fb9a8>
Dec 21 09:30:23 mchp03 kernel: [  732.878693] CR2: 0000000000000000
Dec 21 09:30:23 mchp03 kernel: [  732.928289] ---[ end trace 9511c1617138e8a3 ]---
Dec 21 09:30:23 mchp03 kernel: [  732.948340] 023.869718 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:23 mchp03 kernel: [  732.964611] 023.886001 [1047] generic_netmap_dtor       Restored native NA           (null)
Dec 21 09:30:23 mchp03 kernel: [  732.980392] 023.901795 [ 333] generic_netmap_register   nm_os_catch_rx(1) failed (16)
Dec 21 09:30:23 mchp03 kernel: [  732.995573] 023.916988 [1047] generic_netmap_dtor       Restored native NA           (null)
Dec 21 09:31:49 mchp03 kernel: [  817.936381] general protection fault: 0000 [#2] SMP 
Dec 21 09:31:49 mchp03 kernel: [  817.948382] Modules linked in: ixgbe(OE) netmap(OE) xt_CHECKSUM iptable_mangle ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT xt_tcpudp bridge stp llc openvswitch(OE) libcrc32c ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ip_tables x_tables ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi bnep rfcomm bluetooth 6lowpan_iphc intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp nfsd kvm_intel auth_rpcgss nfs_acl kvm nfs crct10dif_pclmul crc32_pclmul ghash_clmulni_intel lockd joydev sunrpc fscache aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd hpilo lpc_ich ipmi_si ipmi_msghandler nls_iso8859_1 wmi acpi_power_meter ioatdma shpchp mac_hid parport_pc ppdev lp parport hid_generic usbhid hid tg3 i40e dca vxlan ptp pps_core hpsa [last unloaded: ixgbe]
Dec 21 09:31:49 mchp03 kernel: [  818.060562] CPU: 0 PID: 13094 Comm: sudo Tainted: G      D    OE 3.16.0-53-generic #72~14.04.1-Ubuntu
Dec 21 09:31:49 mchp03 kernel: [  818.075875] Hardware name: HP ProLiant DL360 Gen9, BIOS P89 07/20/2015
Dec 21 09:31:49 mchp03 kernel: [  818.091666] task: ffff881025f08a30 ti: ffff880f2a95c000 task.ti: ffff880f2a95c000
Dec 21 09:31:49 mchp03 kernel: [  818.108386] RIP: 0010:[<ffffffff8165e9ec>]  [<ffffffff8165e9ec>] dev_get_phys_port_id+0x1c/0x30
Dec 21 09:31:49 mchp03 kernel: [  818.124616] RSP: 0018:ffff880f2a95f828  EFLAGS: 00010286
´´´

**Comment by vmaffione** [comment]
Hi,
  Unfortunately we've had problems during the merge of a Pull Request, and we are working on that.
Please use commit 791d1c88c173a5ac4413b3e447fe0c1feab224fc for the moment.

I will comment in this thread once we push the fix.

**Comment by matiaselo** [comment]
OK, thanks for the quick reply.

**Comment by vmaffione** [comment]
The fix has been pushed. Could you please check if you are ok with the current master?

**Comment by matiaselo** [comment]
I'm already out of office for the holidays but I'll test the code next week. Happy holidays!

**Comment by vmaffione** [comment]
Thanks!
No problems, you can update on this thread when you have the chance.

**Comment by matiaselo** [comment]
The problem seems to be fixed now, thanks!
