### ISSUE TITLE
Poor performance and corrupted module building in Ubuntu 14.04

### ISSUE THREAD

**Issue by muradkablan** [luigirizzo/netmap#124]
Hi,
I'm using Ubuntu 14.04 with kernel 3.19.0-42-generic and the following NIC
82599ES 10-Gigabit SFI/SFP+ Network Connection' if=p5p1 drv=ixgbe unused=vfio-pci

I downloaded the latest netmap version today and I'm having problems with it.
First of all, following the instructions in LINUX/README, it seems that the ixgbe kernel built by netmap is corrupted. After doing:
sudo rmmod ixgbe
sudo insmod ./netmap_lin.ko
sudo insmod ./ixgbe/ixgbe.ko

I ran pkt-gen and kept getting the following error:
murad@client-1:~/netmap/LINUX$ sudo ./build-apps/pkt-gen -i p5p1 -f tx -l 64 -w 5 
289.541834 main [1930] interface is p5p1
289.541918 main [2050] running on 1 cpus (have 12)
289.542498 extract_ip_range [367] range is 10.0.0.1:0 to 10.0.0.1:0
289.542509 extract_ip_range [367] range is 10.1.0.1:0 to 10.1.0.1:0
290.009691 main [2148] mapped 334980KB at 0x7f7351e37000
Sending on netmap:p5p1: 12 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
290.009777 main [2233] Sending 512 packets every  0.000000000 s
290.009790 main [2235] Wait 5 secs for phy reset
295.009883 main [2237] Ready...
295.010014 sender_body [1211] start, fd 3 main_fd 3
296.010919 main_thread [1720] 6.126 Kpps (6.132 Kpkts 3.140 Mbps in 1000953 usec) 511.00 avg_batch 0 min_space
297.011558 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1000639 usec) 0.00 avg_batch 99999 min_space
297.016236 sender_body [1280] poll error/timeout on queue 0: Success
298.012540 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1000981 usec) 0.00 avg_batch 99999 min_space
299.013429 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1000890 usec) 0.00 avg_batch 99999 min_space
299.018309 sender_body [1280] poll error/timeout on queue 0: Success
300.014413 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1000983 usec) 0.00 avg_batch 99999 min_space
301.015083 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1000670 usec) 0.00 avg_batch 99999 min_space
301.019897 sender_body [1280] poll error/timeout on queue 0: Success
^C301.158648 sigint_h [404] received control-C on thread 0x7f7366f56740
301.158679 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 143597 usec) 0.00 avg_batch 99999 min_space

If I just use the kernel default ixgb module, I no longer get the above error. However, the performance is not as good as it should be. The max I got is  969.260 Kpps

Below are the actual steps/commands I made before running pkt-gen:

$ uname -r
3.19.0-42-generic

$ ./configure --kernel-dir=/usr/src/linux-headers-3.19.0-42-generic --kernel-sources=/usr/src/linux-lts-vivid-3.19.0

$ make && make apps

$ ifconfig p5p1 down && ifconfig p5p1 up

$ sudo ethtool --pause p5p1 tx off

Please advice what I should do.

Thanks,
Murad

**Comment by vmaffione** [comment]
You may try to compile netmap against an official kernel release (kernel.org), e.g. 3.19, 4.2, instead of the one patched by Ubuntu.

Moreover, are you sure that the vfio does not get in the way?

On my machine, using the unpatched ixgbe driver, I get about 3.9 Mpps.
But yes, you have to get 14.8 Mpps with the patched driver.

Finally, you should run

$ sudo ethtool --pause p5p1 tx off rx off autoneg off

on both transmitter and receiver.

**Comment by muradkablan** [comment]
Thanks for the feedback,
I'm afraid it didn't work.

# After downloading and untarring the kernel source. 
cd linux-3.19.8
make-kpkg clean
fakeroot make-kpkg --initrd --append-to-version=-custom kernel_image kernel_headers

sudo dpkg -i linux-custom-image
sudo dpkg -i linux-custom-header

update-grub
reboot now

then I ran this from netmap/LINUX
sudo ./configure --kernel-dir=/usr/src/linux-headers-3.19.8-custom-1.19.8-kernel --kernel-sources=/usr/src/linux-3.19.8

I'm still getting the same issues above
I also removed vfio module.

I get this error when I run the ./configure

*** The virtio_net.c driver is not compiled as a module:
*** you will not be able to load the netmap enabled driver on this kernel.
*** Please consider setting


I am not doing nor planning to do any virtualization on my machine. Do I need virtio even so??

Thanks again

**Comment by vmaffione** [comment]
Hi,
  I don't use Debian-based systems, so I don't know what make-kpkg/dpkg is doing. But what I see is that you're still using the "3.19.8" kernel, which could be different from the "3.19" (see https://www.kernel.org/pub/linux/kernel/v3.x/).

Instead, try using https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.19.tar.xz

For some reason in Ubuntu virtio-net driver is compiled in statically. You can just tell netmap that you don't care about patching virtio-net

./configure --no-drivers=virtio_net.c

**Comment by muradkablan** [comment]
Thank you, Vincenzo.
The 3.19.8 I got from kerenl.org as well https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.19.8.tar.xz

But I'll try the version you pointed out anyway. 

The reason I used dpkg and generate debian based kernel is that I couldn't find the header files of 3.19.8 downloaded and installed from kernel.org

This might not be related to netmap but I really appreciate your help. After compiling and installing kernel 3.19, there will be, in usr/src, the source file linux-3.19.8. Where can I get the header files directory so I point netmap configure file to them?

Murad

**Comment by vmaffione** [comment]
Yes, but point is that we are trying to maintain all major versions from 2.6.32 to 4.3, so the patches are for 3.19, not for 3.19.8.

This Debian headers thing is not related to netmap. From the README:
````
  + make sure you have kernel sources matching your installed kernel
    (headers only suffice, if you want NETMAP/VALE but no drivers)

  + Enter LINUX directory and configure netmap.
    To compile only NETMAP/VALE (using unmodified drivers):

        ./configure --no-drivers # only netmap

    If kernel sources (prepared for out-of-tree compilation) are in
    /a/b/c/linux-A.B.C/, and you want to compile netmap-enabled (patched)
    drivers, then you should do

        ./configure --kernel-dir=/a/b/c/linux-A.B.C/ # netmap+device drivers

    You can omit --kernel-dir if your kernel sources are in a standard place.

    If you use distribution packages, full sources and headers  may be in
    different places contain headers (e.g., on debian systems). Use

        ./configure --kernel-sources=/a/b/c/linux-sources-A.B/ \
                    --kernel-dir=/a/b/c/linux-headers-A.B/

  + build kernel modules and sample applications:
        # build kernel modules
        make
        # build sample applications
        make apps
````

Anyway, if you use manually downloaded sources (in place of sources packaged by the distribution), headers will be there. Just put a .config in the root directory, and make module_prepare. Also see #125. Then you can point --kernel-dir and --kernel-sources to the root directory.

**Comment by muradkablan** [comment]
I followed your instructions but unfortunately it didn't work.
$ uname -r
3.19.0

$ cd /usr/src/linux-3.9/
$ make module_preparemake module_prepare
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CALL    scripts/checksyscalls.sh

$ cd ~/netmap/LINUX
$ make clean
$ ./configure  // showing the following print out

** Disabling driver.
*****************************************************************************
kernel directory            /lib/modules/3.19.0/build
linux version               31300  [3.19]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /lib/modules/3.19.0/build
requested drivers           i40e ixgbe igb e1000e e1000 veth.c forcedeth.c virtio_net.c

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using..."

$ make
$ make apps
$ rmmod ixgbe 
$ rmmod netmap 
$ insmod ./netmap.ko 
$ insmod ./ixgbe/ixgbe.ko 
$ ifconfig p5p1 down
$ ifconfig p5p1 up
$ ./build-apps/pkt-gen -i p5p1 -f tx -l 64 -w 5./build-apps/pkt-gen -i p5p1 -f tx -l 64 -w 5

660.403562 main [1930] interface is p5p1
660.403647 main [2050] running on 1 cpus (have 12)
660.404151 extract_ip_range [367] range is 10.0.0.1:0 to 10.0.0.1:0
660.404161 extract_ip_range [367] range is 10.1.0.1:0 to 10.1.0.1:0
661.665416 main [2148] mapped 334980KB at 0x7fac30411000
Sending on netmap:p5p1: 12 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
661.665475 main [2233] Sending 512 packets every  0.000000000 s
661.665482 main [2235] Wait 5 secs for phy reset
666.665553 main [2237] Ready...
666.665682 sender_body [1211] start, fd 3 main_fd 3
667.666658 main_thread [1720] 6.126 Kpps (6.132 Kpkts 3.140 Mbps in 1001020 usec) 511.00 avg_batch 0 min_space
668.667715 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001057 usec) 0.00 avg_batch 99999 min_space
668.671952 sender_body [1280] poll error/timeout on queue 0: Success
669.668768 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001052 usec) 0.00 avg_batch 99999 min_space
670.669815 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001048 usec) 0.00 avg_batch 99999 min_space
670.673976 sender_body [1280] poll error/timeout on queue 0: Success
671.670850 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001035 usec) 0.00 avg_batch 99999 min_space
672.671897 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001047 usec) 0.00 avg_batch 99999 min_space
672.676018 sender_body [1280] poll error/timeout on queue 0: Success
673.672932 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 1001034 usec) 0.00 avg_batch 99999 min_space
^C673.913959 sigint_h [404] received control-C on thread 0x7fac45530740
673.913990 main_thread [1720] 0.000 pps (0.000 pkts 0.000 bps in 241059 usec) 0.00 avg_batch 99999 min_space

**Comment by muradkablan** [comment]
Update,
pkt-gen can run 
I'm not sure if this is useful, but when I get "poll error/timeout" message, I looked at dmesg and saw this

[ 5627.158411] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 0 not cleared within the polling period
[ 5627.189277] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 1 not cleared within the polling period
[ 5627.220233] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 2 not cleared within the polling period
[ 5627.250437] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 3 not cleared within the polling period
[ 5627.281233] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 4 not cleared within the polling period
[ 5627.312085] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 5 not cleared within the polling period
[ 5627.342478] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 6 not cleared within the polling period
[ 5627.373622] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 7 not cleared within the polling period
[ 5627.404797] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 8 not cleared within the polling period
[ 5627.435921] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 9 not cleared within the polling period
[ 5627.466589] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 10 not cleared within the polling period
[ 5627.497597] ixgbe 0000:04:00.0 p5p1: RXDCTL.ENABLE on Rx queue 11 not cleared within the polling period
[ 5627.710996] ixgbe 0000:04:00.0 p5p1: detected SFP+: 3

**Comment by vmaffione** [comment]
So apparently the model you have (82599ES) does not work properly with our native adapter.
It seems like TX interrupts are disabled.

Can you try to add "-R 100", argument to see if you are able to transmit 100pps?

**Comment by muradkablan** [comment]
Yes, I can transmit 100pps

**Comment by vmaffione** [comment]
Ok, so if you limit a 100pps pkt-gen keeps going forever.
Probably, at low rates it works because you don't need TX interrupts.

You can debug  LINUX/ixgbe_netmap_linux.h to see what's going on.
You could try to put print statements in ixgbe_netmap_txsync to see how the ring status evolves (TX descriptors reclaimed and TX descriptor submitted).

As a first step, however, you could try to disable the NS_REPORT optimization, to see if the TX machinery gets stuck because of that
````
diff --git a/examples/pkt-gen.c b/examples/pkt-gen.c
index a4d7dd4..c327f56 100644
--- a/examples/pkt-gen.c
+++ b/examples/pkt-gen.c
@@ -865,8 +865,8 @@ send_packets(struct netmap_ring *ring, struct pkt *pkt, void *frame,
                        fcnt = nfrags;
                if (sent == count - 1) {
                        slot->flags &= ~NS_MOREFRAG;
-                       slot->flags |= NS_REPORT;
                }
+               slot->flags |= NS_REPORT;
                cur = nm_ring_next(ring, cur);
        }
        ring->head = ring->cur = cur;
````

**Comment by vmaffione** [comment]
You should also check somehow that you are receiving TX interrupts from the NIC (e.g. /proc/interrupts)

**Comment by muradkablan** [comment]
Hi,
I'm still struggling on this and couldn't figure out how to solve it. I tried to disable the NS_REPORT optimization as suggested above but that didn't help.

Anything else I can do? If not, what models, beside what I have (82599ES) I can try and use?

Thanks,

**Comment by tbarbette** [comment]
With the last versions of pkt-gen, I need to set the burst size properly to achieve full speed, something like "-b 32" or "-b 64" should do it.

This driver should definitely go faster, are these NICs the Intel X520 card? Can you use "perf top -a -g" to find what's so slow?

Looking at the first line of your post, it looks like this line comes frome DPDK? I suggest a reboot before going from Netmap to DPDK and vice-versa, that always messed performances on my testbench (memory layout), but not that much...

**Comment by muradkablan** [comment]
Thanks, Tom.
burst option didn't help.

The card I'm using is 
Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection

I tried the same card with no DPDK on it and I still get the poor performance. I also tested Linux Pktgen tool on the same card and it gave me the same performance (955.810Mpps). It seems that this card model has a problem but I'm not sure.

**Comment by vmaffione** [comment]
It seems an hw problem, not related to netmap.
