### ISSUE TITLE
Issues with cross-compilation with override facility

### ISSUE THREAD

**Issue by pavel-odintsov** [luigirizzo/netmap#131]
Hello!

I'm trying to build DKMS packages for Netmap and hit very specific issue. I need some way to specify override path's without using absolute paths because I could not predict paths used by customer.

But right now it's impossible because you are using <driver_name>-src variables on different levels:
1) Inside configure script ([ -z "$(e1000e-src)" ] || cp -Rp $(e1000e-src) $(if $(e1000e-dst),$(e1000e-dst),.))
2) Inside make script in folder netmap-tmpdir: [ -z "$(e1000e-src)" ] || cp -Rp $(e1000e-src) $(if $(e1000e-dst),$(e1000e-dst),.)

And I could not use some path for upper folder with drivers:

``` bash
igb-dst := igb
igb-patch := #(leave empty) 
igb-src := ../../igb-linux-netmap/igb-5.3.3.5/src/
```

Do you have any ideas how we could improve this behavour?

**Comment by vmaffione** [comment]
isn't this provided by `LINUX/dkms` ?
