### ISSUE TITLE
Builidng for Windows 

### ISSUE THREAD

**Issue by datkins47** [luigirizzo/netmap#132]
Hi,

Trying to build netmap as per build instructions for windows on a windows 10 machine with Visual Studio 2013 express as indicated but it reports the following, any ideas?

Project 'netmap-pkg' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
D:\CCSTV\STVModules\NetMap\WINDOWS\netmap-pkg.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'loader' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
D:\CCSTV\STVModules\NetMap\WINDOWS\Loader\loader.vcxproj : error  : Exception from HRESULT: 0x80042003

Project 'netmap' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
D:\CCSTV\STVModules\NetMap\WINDOWS\netmap.vcxproj : error  : Could not recognize the MSBuild value 'Driver' for property 'ConfigurationType' when converting to a VCProjectEngine legacy enumeration.

Project 'nm-ndis' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
D:\CCSTV\STVModules\NetMap\WINDOWS\nm-ndis\nm-ndis.vcxproj : error  : Could not recognize the MSBuild value 'Driver' for property 'ConfigurationType' when converting to a VCProjectEngine legacy enumeration.

Project 'nm-ndis-pkg' could not be loaded because this edition of Visual C++ does not support classic style native application or managed projects.
D:\CCSTV\STVModules\NetMap\WINDOWS\nm-ndis\nm-ndis-pkg.vcxproj : error  : Exception from HRESULT: 0x80042003

**Comment by xuxiaochun1972** [comment]
Dear datkins47,

When I try to open the .sln, Visual Studio 2013 complaints file sysctl.vcxproj is missing. There is no sysctl.vcxproj file existed on the github.

Where do you find the sysctl.vcxproj file? And may you send one copy to me?

xu xiaochun

**Comment by datkins47** [comment]
Just checked and I do not have that file either, does not seem to be in the repo at all, anyone else able to build for windows?

**Comment by deemru** [comment]
Windows branch seems outdated (https://github.com/luigirizzo/netmap/commits/master?author=Alessio-Faina)

Try get old revisions when the author maintained his code.

**Comment by jcavera** [comment]
I'm able to get a clean compile (not a clean link, but that's a separate issue), by creating a new project from scratch in VisualStudio, and adding the needed components by hand.  Seems to be the best way around this particular issue.

**Comment by datkins47** [comment]
is the link due ti missing files or is that something your working on?

**Comment by jcavera** [comment]
datkins47: My lack of link-ability is due to the fact that there are a number of functions that are defined for BSD, but not Windows.  They are declared and used, just never defined.  The functions in question are:

nm_os_kthread_start
nm_os_kthread_stop
nm_os_kthread_create
nm_os_kthread_delete
nm_os_kthread_set_affinity

**Comment by vmaffione** [comment]
Fixed, see #234
