### ISSUE TITLE
I need netmap for ARM platform 

### ISSUE THREAD

**Issue by punkofnewsociety** [luigirizzo/netmap#137]
Hello , I`m trying to run make, having this output.
I need netmap for ARM platform 

```
> make -C /home/vladislav/Fobos-Plug-HSD/linux-3.1.1 M=/home/vladislav/Fobos-Plug-HSD/netmap/LINUX EXTRA_CFLAGS='-I/home/vladislav/Fobos-Plug-HSD/netmap/LINUX -I/home/vladislav/Fobos-Plug-HSD/netmap/LINUX -I/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys -I/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE' ARCH=arm CROSS_COMPILE=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-  modules CONFIG_NETMAP=m  O_DRIVERS="" \
>       NETMAP_DRIVER_SUFFIX=
> make[1]: Entering directory `/home/vladislav/Fobos-Plug-HSD/linux-3.1.1'
>   CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap_mem2.o
> In file included from /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev/netmap/netmap_mem2.c:67:
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:146: error: expected specifier-qualifier-list before 'uint32_t'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:265: error: expected ':', ',', ';', '}' or '__attribute__' before 'buf_ofs'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:319: error: 'IFNAMSIZ' undeclared here (not in a function)
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:320: error: expected ':', ',', ';', '}' or '__attribute__' before 'ni_version'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:476: error: expected specifier-qualifier-list before 'uint32_t'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h: In function 'nm_ring_empty':
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:605: error: 'struct netmap_ring' has no member named 'cur'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:605: error: 'struct netmap_ring' has no member named 'tail'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h: At top level:
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:624: error: expected specifier-qualifier-list before 'uint64_t'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:630: error: expected specifier-qualifier-list before 'u_long'
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/net/netmap.h:638: error: expected specifier-qualifier-list before 'uint64_t'
> In file included from /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev/netmap/netmap_mem2.c:68:
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev/netmap/netmap_kern.h:226: error: #error unsupported platform
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev/netmap/netmap_kern.h:273: error: expected ')' before '*' token
> /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/../sys/dev/netmap/netmap_kern.h:274: error: expected ')' before '*' token
```

so # error unsupported platform stabbed me, 
Im running ubuntu 14.04 
Anyone can help ?

**Comment by stefano-garzarella** [comment]
Hi,
you can try these step:

cd where/is/netmap/LINUX
make distclean
./configure --kernel-dir=/home/vladislav/Fobos-Plug-HSD/linux-3.1.1 --kernel-opts="ARCH=arm CROSS_COMPILE=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-" --cc=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-cc --ld=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-ld
make
make apps

Cheers,
Stefano

**Comment by punkofnewsociety** [comment]
Well the problem is that my pre-built kernel seems to be compiled correctly 
`  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  LD      .tmp_vmlinux1
  KSYM    .tmp_kallsyms1.S
  AS      .tmp_kallsyms1.o
  LD      .tmp_vmlinux2
  KSYM    .tmp_kallsyms2.S
  AS      .tmp_kallsyms2.o
  LD      vmlinux
  SYSMAP  System.map
  SYSMAP  .tmp_System.map
  OBJCOPY arch/arm/boot/Image
  Kernel: arch/arm/boot/Image is ready
  AS      arch/arm/boot/compressed/head.o
  GZIP    arch/arm/boot/compressed/piggy.gzip
  AS      arch/arm/boot/compressed/piggy.gzip.o
  CC      arch/arm/boot/compressed/misc.o
  CC      arch/arm/boot/compressed/decompress.o
  SHIPPED arch/arm/boot/compressed/lib1funcs.S
  AS      arch/arm/boot/compressed/lib1funcs.o
  LD      arch/arm/boot/compressed/vmlinux
  OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
  Building modules, stage 2.
  MODPOST 57 modules
`
and after make distclean i add my kopts in     configure file and running script 

vladislav@evgenykrivosheev-H61M-DS2:~/Fobos-Plug-HSD/netmap/LINUX$ ./configure --kernel-dir=/home/vladislav/Fobos-Plug-HSD/linux-3.1.1/ --no-drivers
kernel directory            /home/vladislav/Fobos-Plug-HSD/linux-3.1.1
linux version               30101  [3.1.1]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
no-drivers

but when im cat config.log i see some tests are not passed. 

`
all: $(S_DRIVERS:%=get-%)
	$(MAKE) -C /home/vladislav/Fobos-Plug-HSD/linux-3.1.1 M=$$PWD ARCH=arm CROSS_COMPILE=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-

-include /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/drivers.mak
endif
##############################################################################
make -C /home/vladislav/Fobos-Plug-HSD/linux-3.1.1 M=$PWD ARCH=arm CROSS_COMPILE=/home/vladislav/Fobos-Plug-HSD/arm-2009q3/bin/arm-none-eabi-
make[1]: Entering directory `/home/vladislav/Fobos-Plug-HSD/linux-3.1.1'
  LD      /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/built-in.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__32.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__31.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__29.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.c: In function 'dummy':/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__31.c: In function 'dummy':

/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.c:12: error: macro "alloc_netdev" passed 4 arguments, but takes just 3/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__31.c:9: error: implicit declaration of function 'netdev_notifier_info_to_dev'

/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.c:11: error: 'alloc_netdev' undeclared (first use in this function)
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__31.c:9: warning: return makes pointer from integer without a cast
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.c:11: error: (Each undeclared identifier is reported only once
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.c:11: error: for each function it appears in.)
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__31.o] Error 1
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__30.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__28.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__27.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__29.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__29.c:7: error: implicit declaration of function 'eth_hw_addr_random'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__29.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__26.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__25.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__28.c:7: error: expected identifier or '(' before 'void'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__28.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__24.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__23.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__25.c:6: error: 'IFF_LIVE_ADDR_CHANGE' undeclared here (not in a function)
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__22.o
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__25.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__21.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__20.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__19.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__18.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__17.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__16.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__15.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__14.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__13.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__12.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__11.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__10.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__9.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__12.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__12.c:9: error: 'struct poll_table_struct' has no member named '_key'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__12.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__8.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__11.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__11.c:10: error: 'struct net_device' has no member named 'real_num_rx_queues'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__11.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__7.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__6.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__5.o
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__4.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__7.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__7.c:8: error: too many arguments to function 'ndo->ndo_select_queue'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__7.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__3.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__6.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__6.c:8: error: too many arguments to function 'ndo->ndo_select_queue'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__6.o] Error 1
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__2.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__4.c:7: warning: 'struct sk_buf' declared inside parameter list
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__4.c:7: warning: its scope is only this definition or declaration, which is probably not what you want
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__4.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__4.c:15: warning: passing argument 2 of 'netdev_rx_handler_register' from incompatible pointer type
include/linux/netdevice.h:2074: note: expected 'enum rx_handler_result_t (*)(struct sk_buff **)' but argument is of type 'enum rx_handler_result_t (*)(struct sk_buf **)'
  CC [M]  /home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.o
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.c: In function 'dummy':
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.c:8: error: implicit declaration of function 'iommu_group_get'
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.c:8: warning: initialization makes pointer from integer without a cast
/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.c:9: error: implicit declaration of function 'iommu_group_id'
make[2]: *** [/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir/__test__1.o] Error 1
make[2]: Target `__build' not remade because of errors.
make[1]: *** [_module_/home/vladislav/Fobos-Plug-HSD/netmap/LINUX/netmap-tmpdir] Error 2
make[1]: Target `_all' not remade because of errors.
make[1]: Leaving directory `/home/vladislav/Fobos-Plug-HSD/linux-3.1.1'
make: *** [all] Error 2
##############################################################################
## END RUNNING TESTS: Fri Feb  5 14:09:17 FET 2016
##############################################################################
`
and finally i recieve those errors which i meentioned in my prev message. 
probably when errors such as 
function takes 4 arguments instead of 3 
may occur when during configuring netmap do not changes these functions with suitable direclty from the library , and using standart functions from my pre-built kernel . 
i think probably of that error unsupported platform may occur 

maybe you know what can help in this situation ?

**Comment by punkofnewsociety** [comment]
Where can i figure out which version of kernel was used to build netmap , cause in my device there is 3,1,1 version and my head-chief says that this is very old version and probably i need to rewrite sources of netmap-library according to the version of kerlnel 3.1.1 .  
Any feedback will be useful

**Comment by vmaffione** [comment]
@punkofnewsociety could you try again with the latest code? The build system has changed.

**Comment by punkofnewsociety** [comment]
not think it will be soon, but i will try to check it.

**Comment by ykondrashyn** [comment]
@punkofnewsociety have you managed resolve this issue?

**Comment by punkofnewsociety** [comment]
hi. @ykondrashyn it was very long time ago. It seems to me that i have managed that by testing some ifdef/ifndef macroses. Just is one macros cannot be included by mistake, so then some errors like undefined reference might occur later.  Excuse me if im mistaken , was too much time ago ^_^

**Comment by ykondrashyn** [comment]
Thank you, the issue was revealed during building of netxtreme2-7.12.10 drivers, namely while building bnx2 driver. 
So, I've taken bnx2x, which builds correctly, from 7.12.10 and used old bnx2 from 7.10.14.
Hope it will help someone

**Comment by murali-rd** [comment]
hi. trying to build netmap module for android. compile is ok but during linking i m getting following error.
prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld: no input files
make[2]: *** [/home/netmap/netmap-master/netmap.o] Error 1
make[1]: *** [_module_/home/netmap/netmap-master] Error 2
make[1]: Leaving directory `/home/kernel/linux-4.1'
make: *** [netmap.ko] Error 2

the CROSS_COMPILE and other paths are set properly.  the .o generated properly for arm architecture.
for ex:
netmap_mem2.o: ELF 64-bit LSB  relocatable, ARM aarch64, version 1 (SYSV), not stripped

any idea what might be the issue. 

thanks.

**Comment by murali-rd** [comment]
hi,

was able to solve this by manually executing the linking steps. (after make has compiled individual files)

cd /kernel/linux-4.1

/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld -EL -r -o /home/netmap/netmap-master/netmap.o /home/netmap/netmap-master/netmap_mem2.o /home/netmap/netmap-master/netmap_mbq.o /home/netmap/netmap-master/netmap_vale.o /home/netmap/netmap-master/netmap_offloadings.o /home/netmap/netmap-master/netmap_pipe.o /home/netmap/netmap-master/netmap_monitor.o /home/netmap/netmap-master/netmap_generic.o /home/netmap/netmap-master/netmap_common.o /home/netmap/netmap-master/netmap_linux.o 

make -f /kernel/linux-4.1/scripts/Makefile.modpost

find /home/netmap/netmap-master/.tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | ./scripts/mod/modpost -m -a -i /kernel/linux-4.1/Module.symvers -I /home/netmap/netmap-master/Module.symvers  -o /home/netmap/netmap-master/Module.symvers -S -w  -s -T -

/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,/home/netmap/netmap-master/.netmap.mod.o.d  -nostdinc -isystem /prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h  -I./mm -I./include -I./include/linux/hisi -I./drivers -I./drivers/huawei_platform -I./drivers/hisi/ap/platform/ -I./fs/proc  -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -I/home/netmap/netmap-master -I/home/netmap/netmap-master/LINUX -I/home/netmap/netmap-master/LINUX/../sys -I/home/netmap/netmap-master/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -mcmodel=large -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(netmap.mod)"  -D"KBUILD_MODNAME=KBUILD_STR(netmap)" -DMODULE  -c -o /home/netmap/netmap-master/netmap.mod.o /home/netmap/netmap-master/netmap.mod.c


/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld -r -m aarch64linux --build-id  -o /home/netmap/netmap-master/netmap.ko /home/netmap/netmap-master/netmap.o /home/netmap/netmap-master/netmap.mod.o

cd -

**Comment by vmaffione** [comment]
Example of how to cross-compile netmap for ARM
````
$ ./configure --drivers=e1000e --no-ext-drivers --kernel-sources=/path/to/kernel/sources --kernel-dir=/path/to/kernel/sources --kernel-opts="ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-" --cc=/usr/bin/aarch64-linux-gnu-gcc --ld=/usr/bin/aarch64-linux-gnu-ld --driver-suffix=-netmap
````
