### ISSUE TITLE
pkt-gen multi-thread sending/receving

### ISSUE THREAD

**Issue by FuZhang** [luigirizzo/netmap#141]
Hi,

I'm trying achieve multi-thread sending/receving packets using netmap. 
I'm wondering how does pkt-gen code achieve mutual-exclusion when multiple thread access the same 
tx_ring or rx_ring, since they will change the cur of the ring concurrently.
I have read through the code, but didn't find any thing about mutual-exclusion. 
I also found that, each thread actually re-open the /dev/netmap file, what is the reason for that? 
Can anyone help me here?

**Comment by vmaffione** [comment]
Mutual exclusion among different threads working on the same netmap ring is demanded to the application. In pkt-gen it never happens that two threads access the same ring. Depending on the command-line options, pkt-gen can use one thread per ring or a single thread servicing all the rings.

The reason for reopening the file multiple times is to have different thread polling different rings. In fact, when multiple threads are used, the file descriptor associated to each thread is bound on a different ring of the interface.

**Comment by deemru** [comment]
- Read `SYNCHRONIZATION (USER)` at [netmap.c](https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap.c)

- pkt-gen threads do not access the same rings, look closely at `nr_ringid`

- Multi-threading pkt-gen for me works much slower or does not work at all, so it seems pkt-gen approach is not effective or broken

- In common, single producer single consumer (SPSC) is the most efficient way to proccess queues. Consider section `5.3 Performance Evaluation on Real Testbed` approach from [B-Queue: Efficient and Practical Queuing for Fast Core-to-Core Communication](http://staff.ustc.edu.cn/~bhua/publications/IJPP_draft.pdf)
