### ISSUE TITLE
have trouble to use netmap 

### ISSUE THREAD

**Issue by maishi** [luigirizzo/netmap#143]
here are the result
step 1:
./configure --kernel-sources=/usr/src/kernels/2.6.32-573.18.1.el6.x86_64 --kernel-dir=/usr/include/linux/
**********************************  ERROR  **********************************
*** kernel not configured.
*** 
*** The kernel directory must be ready for external module compilation.
*** You may need to issue the following or equivalent commands:
*** 
***     cd /usr/include/linux
***     make oldconfig
***     make modules_prepare
***
***
***     Current configuration values:
***
*** kernel directory            /usr/include/linux
*** linux version               - 
*** module file                 netmap.ko
*** subsystems                  generic monitor pipe vale
*** kernel sources              /usr/src/kernels/2.6.32-573.18.1.el6.x86_64
*** requested drivers           i40e ixgbe igb e1000e e1000 veth.c forcedeth.c virtio_net.c r8169.c
*** 
*** Contents of the drivers.mak file:
*** 
***   Note: only drivers for which both the <driver>-src and the
***   <driver>-patch variable are set may be used in native mode (assuming
***   we can actually patch the sources). Other NICs will be accessed using
***   the generic driver, at reduced performance.
*** 
*** ########################################
*** #  configure generated values          #
*** ########################################
*** e1000-src := /home/git_hub/linux-2.6.3/drivers/net/e1000
*** e1000-patch := patches/diff--e1000--20620--31200
*** e1000-dst := e1000
*** r8169.c-src := /home/git_hub/linux-2.6.3/drivers/net/r8169.c
*** r8169.c-patch := patches/diff--r8169.c--20620--20625
*** r8169.c-dst := r8169.c

step 2:
[root@localhost LINUX]# make
cp -Rp /home/git_hub/linux-2.6.3/drivers/net/e1000 e1000
patch --posix --quiet --force -p1 < patches/diff--e1000--20620--31200;
3 out of 6 hunks FAILED -- saving rejects to file e1000/e1000_main.c.rej
make: *** [get-e1000] Error 1

**Comment by vmaffione** [comment]
Your --kernel-dir seems wrong.
Here is my configuration, as an example

'./configure' '--kernel-dir=/lib/modules/4.4.1-2-ARCH/build/' '--kernel-sources=/home/vmaffione/abs/core/linux/src/linux-4.4/' '--drivers=i40e' '--enable-ptnetmap'
