### ISSUE TITLE
A Question on pkt-gen

### ISSUE THREAD

**Issue by kaiaixi** [luigirizzo/netmap#146]
Dear all,
I want to test pkt-gen of netmap on eth3. 
The eth3 is 82599 and using patched ixgbe driver.
But it always fails. Could you please help me figure out where I am wrong? Thanks!
Ubuntu 14.04 / kernel 3.13

sudo pkt-gen -f tx -i eth3 

176.425746 main [1624] interface is eth3
176.426661 extract_ip_range [275] range is 10.0.0.1:0 to 10.0.0.1:0
176.426713 extract_ip_range [275] range is 10.1.0.1:0 to 10.1.0.1:0
176.576644 nm_open [542] NIOCREGIF failed eth3
176.576700 main [1803] Unable to open netmap:eth3: Invalid argument
176.576770 main [1851] aborting

However, use sudo  pkt-gen -f rx -i vale0:rxp is fine.
And bridge vale0 and eth3 and use sudo  pkt-gen -f rx -i vale0:rxp is also fine.

**Comment by vmaffione** [comment]
could you paste the kernel log (just the last part)?

**Comment by kaiaixi** [comment]
Hi,
So sorry for the problem. I just done by change another version of netmap and stock kernel.
