### ISSUE TITLE
Building netmap on CentOS 7

### ISSUE THREAD

**Issue by dcassell** [luigirizzo/netmap#149]
Can anyone share a recipe for successfully building netmap on CentOS 7. I cannot get this to work for love or money. Patching ixgbe against the CentOS source fails, and if I use virgin source from kernel.org I can get the ixgbe.ko and netmap.ko modules to compile but they will not load (incorrect module version error).

**Comment by morphyno** [comment]
The trick comes down to the environment, "make prepare" and "make prepare
scripts" would solve those version problems.

 cd ~/rpmbuild/BUILD

 cd kernel-3.10.0-123.4.2.el7/

 cd linux-3.10.0-123.4.2.el7.x86_64/

make clean

sudo cp /usr/src/kernels/3.10.0-123.8.1.el7.x86_64/Module.symvers .

sudo make oldconfig

sudo make prepare

sudo make prepare scripts

On Mon, Feb 29, 2016 at 10:27 AM, Damon Cassell <notifications@github.com>
wrote:

> Can anyone share a recipe for successfully building netmap on CentOS 7. I
> cannot get this to work for love or money. Patching ixgbe against the
> CentOS source fails, and if I use virgin source from kernel.org I can get
> the ixgbe.ko and netmap.ko modules to compile but they will not load
> (incorrect module version error).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/149>.
>



-- 
All in a can, just add water and stir goodness

**Comment by dcassell** [comment]
Thank you, this is a helpful start but can you tell me what the subsequent correct ./configure syntax should be for netmap?

**Comment by morphyno** [comment]
It sounded like you were able to get both ixgbe.ko and netmap.ko compiled
already, so it doesn't sound like you have a problem with configure script

On Mon, Feb 29, 2016 at 10:55 AM, Damon Cassell <notifications@github.com>
wrote:

> Thank you, this is a helpful start but can you tell me what the subsequent
> correct ./configure syntax should be for netmap?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/149#issuecomment-190331722>.
>



-- 
All in a can, just add water and stir goodness

**Comment by dcassell** [comment]
I am confused if I am supposed to be supplying a --kernel-dir or --kernel-source pointing to vanilla Torvalds linux source, if I can get this built against the CentOS stuff. I was only able to get netmap and ixgbe to compile when using Torvalds source, but then run into the module version problem.

I will keep at it and see what I can come up with.

**Comment by morphyno** [comment]
Are you trying to run kernel from kernel.org ontop of centos7? Redhat makes
alot of kernel changes, unless you absolutely need it, you are better off
getting the kernel source RPM from redhat and compile netmap against that.

On Mon, Feb 29, 2016 at 11:01 AM, Damon Cassell <notifications@github.com>
wrote:

> I am confused if I am supposed to be supplying a --kernel-dir or
> --kernel-source pointing to vanilla Torvalds linux source, if I can get
> this built against the CentOS stuff. I was only able to get netmap and
> ixgbe to compile when using Torvalds source, but then run into the module
> version problem.
>
> I will keep at it and see what I can come up with.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/149#issuecomment-190334429>.
>



-- 
All in a can, just add water and stir goodness

**Comment by dcassell** [comment]
No, this is a stock CentOS 7 kernel. Currently 3.10.0-327.10.1.el7.x86_64. I'm not sure what the ./configure syntax should be after performing the steps you mentioned.

**Comment by morphyno** [comment]
For me, its --kernel-source=
/home/user/rpmbuild/BUILD/kernel-3.10.0-123.4.2.el7/linux-3.10.0-123.4.2.el7.x86_64/

That's setting up RPMBuild in my home directory
https://wiki.centos.org/HowTos/I_need_the_Kernel_Source




On Mon, Feb 29, 2016 at 11:21 AM, Damon Cassell <notifications@github.com>
wrote:

> No, this is a stock CentOS 7 kernel. Currently 3.10.0-327.10.1.el7.x86_64.
> I'm not sure what the ./configure syntax should be after performing the
> steps you mentioned.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/149#issuecomment-190343499>.
>



-- 
All in a can, just add water and stir goodness

**Comment by dcassell** [comment]
Do you also specify a --kernel-dir and if so, which?

**Comment by dcassell** [comment]
Here is what I get after following your original steps inside of rpmbuild/BUILD and then going back to the netmap/LINUX dir:

`[root@server LINUX]# ./configure --kernel-sources=/home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64 --drivers=ixgbe
kernel directory            /lib/modules/3.10.0-327.10.1.el7.x86_64/build
                            [/usr/src/kernels/3.10.0-327.10.1.el7.x86_64]
linux version               30a00  [3.10]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64
requested drivers           ixgbe

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using
  the generic driver, at reduced performance.

########################################
#  configure generated values          #
########################################
ixgbe-src := /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe
ixgbe-patch := patches/diff--ixgbe--30a00--30d00
ixgbe-dst := ixgbe
[root@server LINUX]# make
cp -Rp /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe ixgbe
patch --posix --quiet --force -p1 < patches/diff--ixgbe--30a00--30d00;
1 out of 8 hunks FAILED -- saving rejects to file ixgbe/ixgbe_main.c.rej
make: *** [get-ixgbe] Error 1
[root@server LINUX]#
`

**Comment by morphyno** [comment]
That is expected as well because Redhat changes ixgbe source, so the patch
(which was written for ixgbe source from kernel.org), won't apply.
The patching failed here, you can do the following:

(1) Diff the files and see which lines failed, probably a small change due
to version # and so forth
(2) Just go with pavel's patch agasint official intel released (which is
different from kernel.org).
(3) Wait for the netmap guys to update the patch
(4) Run an older kernel (kernel-3.10.0-123.4.2.el7), I have that running in
production right now

Overall, there are three ixgbe sources, intel's, kernel.org, and Redhat's,
they are always different from each other


On Mon, Feb 29, 2016 at 11:33 AM, Damon Cassell <notifications@github.com>
wrote:

> Here is what I get after following your original steps inside of
> rpmbuild/BUILD and then going back to the netmap/LINUX dir:
>
> `[root@server LINUX]# ./configure
> --kernel-sources=/home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64
> --drivers=ixgbe
> kernel directory /lib/modules/3.10.0-327.10.1.el7.x86_64/build
> [/usr/src/kernels/3.10.0-327.10.1.el7.x86_64]
> linux version 30a00 [3.10]
> module file netmap.ko
> subsystems generic monitor pipe vale
> kernel sources
> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64
> requested drivers ixgbe
>
> Contents of the drivers.mak file:
>
> Note: only drivers for which both the -src and the
> -patch variable are set may be used in native mode (assuming
> we can actually patch the sources). Other NICs will be accessed using
> the generic driver, at reduced performance.
>
> ########################################
> configure generated values
>
> ########################################
> ixgbe-src :=
> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe
> ixgbe-patch := patches/diff--ixgbe--30a00--30d00
> ixgbe-dst := ixgbe
> [root@server LINUX]# make
> cp -Rp
> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe
> ixgbe
> patch --posix --quiet --force -p1 < patches/diff--ixgbe--30a00--30d00;
> 1 out of 8 hunks FAILED -- saving rejects to file ixgbe/ixgbe_main.c.rej
> make: *** [get-ixgbe] Error 1
> [root@server LINUX]#
> `
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/149#issuecomment-190348556>.
>



-- 
All in a can, just add water and stir goodness

**Comment by morphyno** [comment]
Here is pavel's link

https://github.com/pavel-odintsov/ixgbe-linux-netmap


On Mon, Feb 29, 2016 at 11:41 AM, Morgan Yang <morphyno@gmail.com> wrote:

> That is expected as well because Redhat changes ixgbe source, so the patch
> (which was written for ixgbe source from kernel.org), won't apply.
> The patching failed here, you can do the following:
>
> (1) Diff the files and see which lines failed, probably a small change due
> to version # and so forth
> (2) Just go with pavel's patch agasint official intel released (which is
> different from kernel.org).
> (3) Wait for the netmap guys to update the patch
> (4) Run an older kernel (kernel-3.10.0-123.4.2.el7), I have that running
> in production right now
>
> Overall, there are three ixgbe sources, intel's, kernel.org, and
> Redhat's, they are always different from each other
>
>
> On Mon, Feb 29, 2016 at 11:33 AM, Damon Cassell <notifications@github.com>
> wrote:
>
>> Here is what I get after following your original steps inside of
>> rpmbuild/BUILD and then going back to the netmap/LINUX dir:
>>
>> `[root@server LINUX]# ./configure
>> --kernel-sources=/home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64
>> --drivers=ixgbe
>> kernel directory /lib/modules/3.10.0-327.10.1.el7.x86_64/build
>> [/usr/src/kernels/3.10.0-327.10.1.el7.x86_64]
>> linux version 30a00 [3.10]
>> module file netmap.ko
>> subsystems generic monitor pipe vale
>> kernel sources
>> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64
>> requested drivers ixgbe
>>
>> Contents of the drivers.mak file:
>>
>> Note: only drivers for which both the -src and the
>> -patch variable are set may be used in native mode (assuming
>> we can actually patch the sources). Other NICs will be accessed using
>> the generic driver, at reduced performance.
>>
>> ########################################
>> configure generated values
>>
>> ########################################
>> ixgbe-src :=
>> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe
>> ixgbe-patch := patches/diff--ixgbe--30a00--30d00
>> ixgbe-dst := ixgbe
>> [root@server LINUX]# make
>> cp -Rp
>> /home/user/rpmbuild/BUILD/kernel-3.10.0-327.10.1.el7/linux-3.10.0-327.10.1.el7.x86_64/drivers/net/ethernet/intel/ixgbe
>> ixgbe
>> patch --posix --quiet --force -p1 < patches/diff--ixgbe--30a00--30d00;
>> 1 out of 8 hunks FAILED -- saving rejects to file ixgbe/ixgbe_main.c.rej
>> make: *** [get-ixgbe] Error 1
>> [root@server LINUX]#
>> `
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/luigirizzo/netmap/issues/149#issuecomment-190348556>.
>>
>
>
>
> --
> All in a can, just add water and stir goodness
>



-- 
All in a can, just add water and stir goodness

**Comment by dcassell** [comment]
OK, thank you. I will evaluate my options at this point.

**Comment by giuseppelettieri** [comment]
Hi dcassel, there is no problem in your configure. Unfortunately, the patch we distribute with netmap does not apply to your kernel sources since, as morphyno explained, Redhat kernel sources are significantly different from the Torvarld's sources with the same major.minor version number.

Also, using the sources from Torvalds while running the kernel from CentOS will not work. As you have already found out, the modules will not load.

We are trying to find a better way to handle these situations, but this will take some time. In the meantime I suggest you go with any of the options provided by morphyno, (4) being probably the easiest.

**Comment by dcassell** [comment]
Hi, thanks for the information. I installed the older 3.10.0-123.el7.x86_64 from RPM, along with the kernel-devel and headers, and rebooted after removing the newer kernel (this is a test system). I was then able to get netmap.ko and ixgbe.ko to compile and load. We will begin the testing we are interested in. 

I will say it will be very helpful if you could improve the installation process... CentOS 7 is very popular and we need to keep our kernel patch levels current. PF_RING is a lot easier for us to install, but we have some issues with it that we are hoping netmap might solve.

**Comment by morphyno** [comment]
@dcassell, I use both PF_RING and Netmap, and I must confess the main reason I prefer Netmap is because the zero copy drivers are free (PF_RING zc drivers are not). Netmap releases things in patches and PF_RING offers pre-compiled driver modules. I can also tell you that Netmap performance on CentOS7 is not as good as Ubuntu 14.04, it comes down to some kernel magic between 3.10 and 3.13. 
So I use CentOS 7 for customers, but Ubuntu 14.04 internally.

**Comment by dcassell** [comment]
Thanks for your comments, I am very interested in any other information you can provide. What application(s) are you running with netmap? I am mostly interested in improving the performance of Bro. As you may know Bro supports both PF_RING and netmap. We have been seeing some unacceptable packet loss with PF_RING that we cannot eliminate no matter how we tune it. We are using X520 cards (ixgbe) and we have very fast hardware and a lot of memory. Do you have any idea just how big of a difference the performance is between CentOS 7 and Ubuntu 14.04?

**Comment by morphyno** [comment]
The applications we bench-marked were homegrown, but there was a clear difference between running the same application with Netmap on CentOS7 and Ubuntu14.04. For small sized packets (64,128,256), Ubuntu setup was processing 40% faster.

**Comment by morphyno** [comment]
I believed the difference was to kernel and two ixgbe drivers were different. As I mentioned earlier, CentOS uses and modifies the driver, and Ubuntu uses driver almost identical to the code from ixgbe. The patches might be identical but the result might not. At the time, there was no patch for Intel's official release. I would recommend trying that as well as part of your benchmark

**Comment by dcassell** [comment]
Thanks for the tips on Ubuntu, I may check that out. I have the modules loaded but I am having problems building the apps (make apps):

make -C build-apps SRCDIR=/root/netmap/LINUX/.. CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/LINUX/build-apps'
make[1]: *** No rule to make target `lb', needed by `all'.  Stop.
make[1]: Leaving directory `/root/netmap/LINUX/build-apps'
make: *** [apps] Error 2

Any ideas here?

**Comment by vmaffione** [comment]
Make sure you don't issue make directly in examples/. Go to examples/, issue make clean and then try to make apps again (maybe re ./configure ing to be safe).

**Comment by dcassell** [comment]
OK, well thank you, I have everything running that I need. I appreciate everyone's help.. we are now testing Netmap with Bro and everything is running after having installed an older kernel from RPM.

**Comment by morphyno** [comment]
@dcassell, i'm curious of your findings in regard to netmap and bro, I'm looking at something similar at a customer's request.

**Comment by dcassell** [comment]
So, our goal has been to reduce the numbers reported in the capture_loss log. We know this may never be zero, but it is unacceptably high on our production systems. This is with PF_RING vanilla, the PF_RING ixgbe and X520 cards. This brought us to zero copy (ZC or netmap). For various reasons we steered towards netmap, which brought me here.

With your suggestion in mind, I built a test system using Ubuntu 15.10 and an X520 card. This system is receiving the same traffic our production ones do. Out of the box, there was an immediate difference vs. our systems with CentOS 7. Not huge, but a noticeable difference. With some very careful testing/tuning of sysctl.conf and interface options, we managed to get capture loss down to about 1/3rd of our production system with PF_RING. And that's with nothing but vanilla Ubuntu and the X520. We then added vanilla PF_RING and this brought capture loss down yet again. We tried some work with C-states and CPU pinning on the NUMA node the card is on, but didn't really see a difference there.

We will next test netmap again on this Ubuntu setup, but I haven't gotten there yet with everything else going on here. So to answer your question, I have not actually tested netmap and Bro, yet. To make things even more interesting, I ordered a Myricom card and a Sniffer10G license to test. Should be here today. The thinking being that these are cheap enough (way cheaper than Napatech for instance) that we would just use them instead of netmap. In light of the fact that documentation for netmap seems a little thin, and it initially failed my "ease of deployment" test, a more mature and vendor supported solution has become attractive. Netmap isn't out of the question, though.

I can provide updates or more information if you are interested.

Damon Cassell

**Comment by vkotovv** [comment]
If you have this error on Centos 7:
```
**********************************  ERROR  **********************************
*** Cannot find kernel directory.
*** 
*** We need at least the kernel headers to compile the netmap kernel module.
```
Please make sure your `kernel` and `kernel-devel` package versions match.
