### ISSUE TITLE
Netmap Add NIC to vale0 - Cannot allocate memory

### ISSUE THREAD

**Issue by kaiaixi** [luigirizzo/netmap#150]
When I testing netmap, I meet an issue called "vale0:eth4: Cannot allocate memory".

The CMD is "sudo vale-ctl -a vale0:eth4" and the result is "vale0:eth4: Cannot allocate memory". And the dmesg shows that

[  122.923184] netmap: loaded module
[  211.911963] 004.586828 [1456] netmap_set_ringid         deprecated API, old ringid 0x0 -> ringid 0 reg 1
[  211.922603] 004.597476 [1049] netmap_mem_global_config  reconfiguring
[  212.122870] 004.797936 [ 385] netmap_obj_malloc         netmap_if request size 1080 too large
[  212.132857] 004.807941 [ 753] generic_netmap_dtor       Restored native NA           (null)
[  259.431331] nr_pdflush_threads exported in /proc is scheduled for removal

I found an link "https://github.com/luigirizzo/netmap/issues/32". I am not sure whether it is related or not.  In the link you said we should increase the ring size and buffer size. But, how to do that?  

Thanks!

NIC: x520 / ixgbe
Linux: kernel 3.9.1

**Comment by vmaffione** [comment]
Load netmap, make sure there are no netmap applications running, and 

''''
# echo 2048 > /sys/module/netmap/parameters/if_size
''''

Then try to restart your applications (in this case vale-ctl).

**Comment by kaiaixi** [comment]
Thanks ! I also solved this problem by limit the number of CPU in grub

maxcpus = 16

**Comment by vmaffione** [comment]
Also consider that you can set the if_size parameter at module load time
````
# modprobe netmap if_size=2048
````
