### ISSUE TITLE
ovs with netmap

### ISSUE THREAD

**Issue by morphyno** [luigirizzo/netmap#151]
Based on a paper by Luigi from a few years ago, [https://www.usenix.org/system/files/conference/atc12/atc12-final186.pdf](url)
there was a test conducted on OVS with netmap, and the results were comparable to Click. I would like to ask how was OVS patched to support netmap, and can that patch be shared.

**Comment by vmaffione** [comment]
https://github.com/luigirizzo/netmap/blob/master/examples/switch-modules/ovs-datapath/0001-datapath-Add-support-for-netmap-VALE.patch

**Comment by morphyno** [comment]
Wow, super awesome! Thanks!
