### ISSUE TITLE
pkt-gen reports only one queue, but actually six in use

### ISSUE THREAD

**Issue by 67113513** [luigirizzo/netmap#152]
Dear all,
I installed netmap/ixgbe drivers on CentOS 6.5. And find error when I ran pkt-gen to verify the speed.
First, I have 6 rx queues receiving data, they are all active:
[root@localhost probe]# ethtool -S p1p2 | grep rx_queue_[0-5]_
     rx_queue_0_packets: 23617873817
     rx_queue_0_bytes: 4529618136885
     rx_queue_1_packets: 23770910647
     rx_queue_1_bytes: 4538948127234
     rx_queue_2_packets: 22599767943
     rx_queue_2_bytes: 4361369911174
     rx_queue_3_packets: 22667889770
     rx_queue_3_bytes: 4359932531220
     rx_queue_4_packets: 22655216992
     rx_queue_4_bytes: 4356683059286
     rx_queue_5_packets: 22673567992
     rx_queue_5_bytes: 4342627492210
[root@localhost probe]# ethtool -S p1p2 | grep rx_queue_[0-5]_
     rx_queue_0_packets: 23621771719
     rx_queue_0_bytes: 4530288320588
     rx_queue_1_packets: 23774774364
     rx_queue_1_bytes: 4539558204252
     rx_queue_2_packets: 22603466903
     rx_queue_2_bytes: 4361971492919
     rx_queue_3_packets: 22671651863
     rx_queue_3_bytes: 4360525185573
     rx_queue_4_packets: 22658953434
     rx_queue_4_bytes: 4357238888245
     rx_queue_5_packets: 22677364764
     rx_queue_5_bytes: 4343249630701
Second, I use "./pkt-gen -i p1p2 -f rx" to receive data. And find the bandwidth is very low(compared to real traffic).
Third, I tried to use more threads on receiving, but pkt-gen reports error, and only one thread was created:
[root@localhost examples]# ./pkt-gen -i p1p2 -f rx -p 6
395.126551 main [1932] interface is p1p2
395.126666 main [2052] running on 1 cpus (have 6)
395.128464 extract_ip_range [367] range is 10.0.0.1:0 to 10.0.0.1:0
395.128479 extract_ip_range [367] range is 10.1.0.1:0 to 10.1.0.1:0
395.568296 nm_open [777] overriding ifname p1p2 ringid 0x0 flags 0x4
395.800127 main [2150] mapped 334980KB at 0x7fc56f3ab000
395.800142 main [2160] bad nthreads 6, have 1 queues
Receiving from netmap:p1p2: 1 queues, 6 threads and 1 cpus.
395.800166 main [2237] Wait 2 secs for phy reset
397.800240 main [2239] Ready...
397.800438 nm_open [777] overriding ifname p1p2 ringid 0x1 flags 0x4
397.800434 receiver_body [1412] reading from netmap:p1p2 fd 3 main_fd 3
397.800488 nm_open [847] NIOCREGIF failed: Invalid argument p1p2
397.800493 start_threads [1643] Unable to open netmap:p1p2: Invalid argument
397.800506 nm_open [777] overriding ifname p1p2 ringid 0x2 flags 0x4
397.800522 nm_open [847] NIOCREGIF failed: Invalid argument p1p2
397.800525 start_threads [1643] Unable to open netmap:p1p2: Invalid argument
397.800537 nm_open [777] overriding ifname p1p2 ringid 0x3 flags 0x4
397.800545 nm_open [847] NIOCREGIF failed: Invalid argument p1p2
397.800552 start_threads [1643] Unable to open netmap:p1p2: Invalid argument
397.800560 nm_open [777] overriding ifname p1p2 ringid 0x4 flags 0x4
397.800578 nm_open [847] NIOCREGIF failed: Invalid argument p1p2
397.800588 start_threads [1643] Unable to open netmap:p1p2: Invalid argument
397.800596 nm_open [777] overriding ifname p1p2 ringid 0x5 flags 0x4
397.800615 nm_open [847] NIOCREGIF failed: Invalid argument p1p2
397.800618 start_threads [1643] Unable to open netmap:p1p2: Invalid argument
398.801637 main_thread [1722] 143.766 Kpps (143.911 Kpkts 171.549 Mbps in 1001010 usec) 15.02 avg_batch 0 min_space

I briefly go through the pkt-gen.c and find the number of RX queues is returned by nm_open:
g.nmd = nm_open(g.ifname, &base_nmd, NM_OPEN_IFNAME, &saved_desc);
...
..
devqueues = g.nmd->req.nr_rx_rings;

I'm not sure if it's a bug or just configuration. Could someone help me?
Thanks in advance.

**Comment by 67113513** [comment]
Find something more, during the pkt-gen is running, ethtool shows no more data on queue_0, but the other 4 queues do have data. Does this mean the data on other 4 queues are not received by netmap?

[root@localhost probe]# ethtool -S p1p2 | grep rx_queue_[0-5]_
     rx_queue_0_packets: 23992022222
     rx_queue_0_bytes: 4588599995380
     rx_queue_1_packets: 24159013575
     rx_queue_1_bytes: 4600110761637
     rx_queue_2_packets: 22977247856
     rx_queue_2_bytes: 4418541641220
     rx_queue_3_packets: 23040123631
     rx_queue_3_bytes: 4419106166490
     rx_queue_4_packets: 23028802739
     rx_queue_4_bytes: 4415585867543
     rx_queue_5_packets: 23048298157
     rx_queue_5_bytes: 4402049539077
[root@localhost probe]# ethtool -S p1p2 | grep rx_queue_[0-5]_
     rx_queue_0_packets: 23992022222
     rx_queue_0_bytes: 4588599995380
     rx_queue_1_packets: 24159312576
     rx_queue_1_bytes: 4600158517083
     rx_queue_2_packets: 22977527824
     rx_queue_2_bytes: 4418583592800
     rx_queue_3_packets: 23040403206
     rx_queue_3_bytes: 4419149287793
     rx_queue_4_packets: 23029092573
     rx_queue_4_bytes: 4415634160646
     rx_queue_5_packets: 23048589505
     rx_queue_5_bytes: 4402097059820

**Comment by vmaffione** [comment]
This seems to be related to #242, upgrading the kernel would probably solve it

**Comment by vmaffione** [comment]
Is this problem still valid?

**Comment by 67113513** [comment]
It works fine on centos7.2, 
closed issue
