### ISSUE TITLE
NR_REG_SW_NIC mode caused ubuntu hang

### ISSUE THREAD

**Issue by flybeyond** [luigirizzo/netmap#155]
My aim is get packets from eth0, then send them to linux stack. But after executing following code, whole system hangs. If use another mode, say NR_REG_ALL_NIC. It can capture packets and system will not hang.
This is my code:

struct nm_desc *host_stack_nm = nm_open("netmap:eth0^", NULL, 0, NULL);
struct	pollfd fds;
fds.fd = NETMAP_FD(host_stack_nm);
fds.events = POLLIN;
 for (;;) {
    poll(&fds,1, -1);
     buf = nm_nextpkt(host_stack_nm, &h);
    if (buf != NULL) {
	nm_inject(host_stack_nm, buf, h.len);
   }
}

**Comment by vmaffione** [comment]
You don't need netmap to do that. The host stack rings (eth0^) are used by netmap applications to exchange packets with the host stack (only the traffic associated to eth0). You won't get any packets from eth0 iwth eth0^.
