### ISSUE TITLE
netmap/pkt-gen causes 10g adapter to flap ?

### ISSUE THREAD

**Issue by Onepamopa** [luigirizzo/netmap#156]
Running freebsd 10.2-release (x64) for a few netmap tests.
I'm not sure if this is a hardware fault (faulty nic/sfp's/cable) or just some kind of incompatibility between netmap and this particular NIC.

Here are some details:

# pciconf -lv | grep -i device | grep -i network
    device     = '82599EB 10-Gigabit SFI/SFP+ Network Connection'
    device     = '82599EB 10-Gigabit SFI/SFP+ Network Connection'
# ifconfig ix0
ix0: flags=8843 UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST  metric 0 mtu 1500
options=8407bb RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO 
        ether MACADDR1
        inet IPADDR netmask 0xfffffff8 broadcast BCAST
        nd6 options=29 PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL 
        media: Ethernet 10Gbase-SR (10Gbase-SR  full-duplex,rxpause,txpause )
        status: active
# ifconfig ix1 (NOT USED @ netmap tests)
ix1: flags=8802 BROADCAST,SIMPLEX,MULTICAST  metric 0 mtu 1500
options=8407bb RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO 
        ether MACADDR2
        nd6 options=29 PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL 
        media: Ethernet autoselect
        status: no carrier

# On boot - Faults: 2/4 (before I even start pkt-gen)
# uptime
 9:39PM  up 2 mins, 2 users, load averages: 0.46, 0.46, 0.21
# sysctl -a | grep ix. | grep "fault"
dev.ix.1.mac_stats.remote_faults: 0
dev.ix.1.mac_stats.local_faults: 0
dev.ix.0.mac_stats.remote_faults: 2
dev.ix.0.mac_stats.local_faults: 4
#
# Faults increase each time pkt-gen is started:
# sysctl -a | grep ix. | grep "fault"
dev.ix.1.mac_stats.remote_faults: 0
dev.ix.1.mac_stats.local_faults: 0
dev.ix.0.mac_stats.remote_faults: 3
dev.ix.0.mac_stats.local_faults: 6
# sysctl -a | grep ix. | grep "fault"
dev.ix.1.mac_stats.remote_faults: 0
dev.ix.1.mac_stats.local_faults: 0
dev.ix.0.mac_stats.remote_faults: 6
dev.ix.0.mac_stats.local_faults: 15
# sysctl -a | grep ix. | grep "fault"
dev.ix.1.mac_stats.remote_faults: 0
dev.ix.1.mac_stats.local_faults: 0
dev.ix.0.mac_stats.remote_faults: 7
dev.ix.0.mac_stats.local_faults: 17
#
# pkt-gen started with:
# ./pkt-gen -i ix0 -f tx -l 64 -d dstip:port -s srcip:4000-srcip:5000 -D GWmac -S IXmac -c 16 -p 1 -v -R 900000

Each time pkt-gen starts, there are no packets for at least 5-6 seconds -> then I start to see the packets normally for about 10 seconds -> packets drop to 0 -> 5-6 more seconds -> again normal packets -> drop . . . .

Any ideas ?

**Comment by rbtcollins** [comment]
I'm going to guess at a fault somewhere outside of netmap. You might try the linux in-kernel pktgen (there's a script in the netmap tree under LINUX/scripts) that might serve to provoke similar symptoms.
