### ISSUE TITLE
Load packets from pcap files

### ISSUE THREAD

**Issue by muradkablan** [luigirizzo/netmap#157]
Hello,
I see in pkt-gen options "-P"
It is supposed to load packets from pcap file. I tried this option with pcap file, but pkt-gen seems to ignore it and nothing happen.

What is P option for and how can use it properly? 

Thanks,

**Comment by vmaffione** [comment]
Hi,
  when you compile pkt-gen, by default pcap support is not included (-DNO_PCAP is specified in the Makefile).

After pulling the latest master (updated right now), you can therefore try to modify the GNUMakefile to compile without the NO_PCAP macro.

As far as I understand, the -P option will cause pkt-gen to read the first packet from the provided pcap file, and use that packet as a prototype for sending.

**Comment by luongnv89** [comment]
In fact we do not need to modify the GNUMakefile. just need to compile `pkt-gen` with flag `WITH_PCAP=1`

```
cd netmap/apps/pkt-gen
make WITH_PCAP=1
```
Then try to generate the traffic from a pcap file

```
sudo ./pkt-gen -i eth3 -P PATH_TO_PCAP_FILE -f tx
```
