### ISSUE TITLE
kernel panic when trying bridge.c

### ISSUE THREAD

**Issue by flybeyond** [luigirizzo/netmap#160]
./bridge -i netmap:eth0^ -i netmap:eth0
Ctrl+C make my system hang, but
./bridge -i netmap:eth0 -i netmap:eth0^
works normal.

ubuntu, 14.04

**Comment by Fr3DBr** [comment]
Well, if you want to use the same interface, then you don't have to use ^, just do as :

./bridge -i netmap:eth0 -i netmap:eth0 since it adds the ^ automatically. (to the second interface).

**Comment by vmaffione** [comment]
This should be fixed right now.
