### ISSUE TITLE
python class doesn't support 'with' statement

### ISSUE THREAD

**Issue by abunimeh** [luigirizzo/netmap#163]
`netmap.NetmapDesc('netmap:em0*')` is very convenient, however, I cannot use it with the following
`with netmap.NetmapDesc('netmap:em0*') as d:`

I get this error:
AttributeError: __exit__

Please add __enter__ and __exit__ methods.

**Comment by vmaffione** [comment]
Can you try the attached patch ?

[with.txt](https://github.com/luigirizzo/netmap/files/222094/with.txt)

**Comment by vmaffione** [comment]
any news on this?

**Comment by abunimeh** [comment]
I have just quickly tested it works well. 

I think the memory is freed correctly as well. I just looked at 'top' to observe it not growing.

Thanks!

**Comment by vmaffione** [comment]
Thanks for testing, I will merge this internally. It will be published in the following days.
