### ISSUE TITLE
nmreplay sends data once at right speed, then again at full speed

### ISSUE THREAD

**Issue by bmerry** [luigirizzo/netmap#166]
It seems that, unlike tcpreplay, nmreplay can only operate in the mode of cycling through the packets, playing an infinite stream. That is very inconvenient on its own, but there is also a bug that prevents it from working correctly. After the first pass, q->cons_now never gets updated again. Every packet thus appears to be due for transmission in the past, causing packets to be sent at line rate rather than according to the schedule.

(above applies to git revision 77df06a)

**Comment by giuseppelettieri** [comment]
Should be fixed now, thanks.
