### ISSUE TITLE
nmreplay: incorrect behaviour on filling a burst

### ISSUE THREAD

**Issue by bmerry** [luigirizzo/netmap#167]
At [this line](https://github.com/luigirizzo/netmap/blob/77df06a/apps/nmreplay/nmreplay.c#L900), a packet send failure is treated the same as having reached the burst limit. This causes two issues:
- the packet is not consumed (due to the `continue` statement), so it will be sent again (I think - I haven't verified experimentally)
- a misleading message is produced

**Comment by giuseppelettieri** [comment]
I don'w know why this comment was ignored, since it is spot on. Fixed now.
