### ISSUE TITLE
linux configure cannot find headers on fedora 23

### ISSUE THREAD

**Issue by abunimeh** [luigirizzo/netmap#168]
I install headers/source using 
`sudo dnf install kernel-devel kernel-headers`
I tried all --kernel-sources and --kernel-dir possibilities and still the configure script couldn't find the sources. I think the method used to detect the headers is not correct.
`$ uname -a
Linux abunimeh 4.4.6-301.fc23.x86_64 #1 SMP Wed Mar 30 16:43:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

`$ ./configure
**********************************  ERROR  **********************************
*** Cannot find full kernel sources.
***
*** We need the full kernel sources to build the netmap-enabled drivers.
*** Please note that most distributions provide separate packages for kernel
*** headers and sources. Once you know the path to kernel sources, you can
*** rerun this script with the additional
***
***     --kernel-sources=/path/to/sources
***
*** option.
***
*** If you are only interested in VALE and pipes, you can rerun the script
*** now with the '--no-drivers' option. Hardware devices will then be accessed
*** via a generic adapter at reduced performance."
***
***
***     Current configuration values:
***
*** kernel directory            /lib/modules/4.4.6-301.fc23.x86_64/build
***                             [/usr/src/kernels/4.4.6-301.fc23.x86_64]
*** linux version               40406  [4.4.6]
*** module file                 netmap.ko
*** subsystems                  generic monitor pipe vale
*** no-drivers
*****************************************************************************`

**Comment by giuseppelettieri** [comment]
The headers have been found, the problem is the full sources. The ./configure script contains no method to find them if they are not in the same directory as the headers. You have to pass the path to the full sources with --kernel-sources=...

**Comment by abunimeh** [comment]
i did try
`./configure --kernel-sources=/usr/src/kernels/4.4.6-301.fc23.x86_64`

but I get the same thing. Cannot find full kernel sources.

I had to go to kernel.org and download linux-4.4.6.tar.gz to point to the extracted directory to get to work. I guess this is what you meant buy 'full' kernel.

Thanks!

**Comment by vkotovv** [comment]
I had the same issue with Centos 7. Please make sure your `kernel` and `kernel-devel` package versions match, otherwise there could be issues like this.
