### ISSUE TITLE
i40e on Linux: netmap_slot.len is 4 bytes too small

### ISSUE THREAD

**Issue by bmerry** [luigirizzo/netmap#169]
When I receive packets with netmap on Linux, I am having an issue where the `len` field of the `netmap_slot` is 4 smaller than the correct value, regardless of the packet size. If I remove the netmap-compiled i40e and insert the regular kernel-provided one (which I assume puts netmap into generic mode), the problem goes away.

I am using Ubuntu 14.04, with the linux-image-generic-lts-xenial kernel (4.4.0-18-generic).

**Comment by vmaffione** [comment]
Hi, this is due to the CRC, which can be subtracted in the native i40e rxsync(), depending on the value of the ix_crcstrip parameter (default 0, means don't stsrip).

You are correct, if you use the kernel-provided driver, the generic adapter is used and the driver does the default thing, which is stripping CRC.

You can set the ix_crcstrip ntemap module parameter to 1 to fix your problem.

**Comment by bmerry** [comment]
Thanks for the quick reply. Just to make sure that we're talking about the same thing. I have packets with, say:
- 14 bytes Ethernet header
- 20 bytes IP header
- 8 bytes UDP header
- 1472 bytes UDP payload
- 4 bytes Ethernet CRC
I expect that to give me a length of either 1514 or 1518, depending on whether the CRC has been stripped. Instead, I'm getting a length of 1510, meaning 4 bytes of my UDP payload has gone missing.

Setting ix_crcstrip=1 does seem to work around the bug though, thanks!

**Comment by vmaffione** [comment]
It should be the other way around. In fact I see logic inversion here:

https://github.com/luigirizzo/netmap/blob/master/LINUX/i40e_netmap_linux.h#L456

It should be:
````
int crclen = ix_crcstrip ? 4 : 0;
````

**Comment by bmerry** [comment]
Isn't switching that just going to make the ix_crcstrip=1 case broken (losing payload bytes)? It seems to me that the length before subtracting crclen doesn't include the CRC anyway, so subtracting 4 is never the right choice. Possibly it would be if ix_crcstrip actually poked the HW in any way, but currently set_crcstrip is `#if 0`ed out and not called.

**Comment by vmaffione** [comment]
You are right, i40e support is still experimental, so it's not well integrated yet with the CRC configuration. More work is needed on that.

**Comment by vmaffione** [comment]
For now I will just push a fix that correctly initializes ix_crcstrip=1 as default.
