### ISSUE TITLE
Unknown references

### ISSUE THREAD

**Issue by jcavera** [luigirizzo/netmap#170]
In the Windows build, there are several unknown functions.  These are declared but never defined.  They are as follows:

nm_os_kthread_create
nm_os_kthread_delete
nm_os_kthread_start
nm_os_kthread_stop
nm_os_kthread_set_affinity
nm_os_ncpus

The "nm_os_ncpus" function is trivial to implement and should work fine even when hard-coded to return "1".  The _kthread_ routines, not so much.  I cannot find any good implementation of them for Windows -- the BSD version does implement them, but does not work under Windows (of course).

**Comment by vmaffione** [comment]
Solved
