### ISSUE TITLE
python ring.space() values

### ISSUE THREAD

**Issue by abunimeh** [luigirizzo/netmap#172]
I am trying to detect when the rx circular buffer starts overwriting unread values i.e. when incoming data is faster than outgoing data.

ring.space() doesn't provide the correct value. Initially, it is zero than after a while it hovers around 1 and 2.

I thought .space should give me num_slots at start up not zero.

I tried to monitor head, cur, tail, however, tail never overlaps/bypasses head.
If .space() is the wrong way to detect overwrites what is the correct method?

Thanks!

**Comment by vmaffione** [comment]
tail cannot reach head.
Please read the netmap manual in share/man/man4 to understand the meaning of cur, tail and head for TX and RX ring.

ring.space is simply (tail-head) % num_slots.

**Comment by abunimeh** [comment]
I did read the man page but the following doesn't state what happens if the write is faster than read

> At	the next NIOCRXSYNC/select()/poll(), slots up to head-1	are returned
     to	the kernel for further receives, and tail may advance to report	new
     incoming packets.

I can confirm that tail stops advancing if I don't read/release.

Is it possible to detect slots being overwritten using netmap API?

**Comment by vmaffione** [comment]
Netmap rings are circular buffers, and therefore tail never reaches head, and a slot is always left unused - as stated by the manual - to distinguish the full queue state from the empty queue state.

**Comment by abunimeh** [comment]
'Circular buffer' is just a term but the implementation can be anything. I have created hardware circular buffers where a dirty flag is (un)set when the buffer write pointer surpasses my read pointer.

I am not getting a direct answer to my question. So I am assuming there is no way to know if the circular buffer started overwriting unread values.

**Comment by vmaffione** [comment]
That's right, but you got a direct answer: tail never reaches head.
So write pointer (tail) cannot pass read pointer (head). The implementation takes care of this.

**Comment by abunimeh** [comment]
Thanks for the informative discussion.

**Comment by vmaffione** [comment]
you're welcome!
