### ISSUE TITLE
Support for ixgbe 4.3.15

### ISSUE THREAD

**Issue by leleobhz** [luigirizzo/netmap#180]
Hello,

It's possible to support ixgbe module from upstream e1000?

```
# ▶ ./configure --kernel-sources=/root/rpmbuild/BUILD/kernel-ml-4.6.0/linux-4.6.0-1.el7.centos.x86_64 --override=OVERRIDE_FOR_IXGBE --drivers=ixgbe
kernel directory            /lib/modules/4.6.0-1.el7.elrepo.x86_64/build
                            [/usr/src/kernels/4.6.0-1.el7.elrepo.x86_64]
linux version               40600  [4.6]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /root/rpmbuild/BUILD/kernel-ml-4.6.0/linux-4.6.0-1.el7.centos.x86_64
requested drivers           ixgbe

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using
  the generic driver, at reduced performance.

########################################
#  configure generated values          #
########################################
ixgbe-src := /root/rpmbuild/BUILD/kernel-ml-4.6.0/linux-4.6.0-1.el7.centos.x86_64/drivers/net/ethernet/intel/ixgbe
ixgbe-patch := patches/diff--ixgbe--31300--99999
ixgbe-dst := ixgbe
########################################
# ovverride from
# OVERRIDE_FOR_IXGBE
########################################
ixgbe-src=/usr/src/ixgbe-4.3.15/src/
# ▶ make
cp -Rp /usr/src/ixgbe-4.3.15/src/ ixgbe
patch --posix --quiet --force -p1 < patches/diff--ixgbe--31300--99999;
5 out of 9 hunks FAILED -- saving rejects to file ixgbe/ixgbe_main.c.rej
make: ** [get-ixgbe] Erro 1
# ▶ wgetpaste ixgbe/ixgbe_main.c.rej 
Apparently nothing was received. Perhaps the connection failed. Enable --verbose or
--debug to get the output from wget that can help diagnose it correctly.
```

Thanks!

**Comment by vmaffione** [comment]
PLease download and use kernel.org sources. 4.3 drivers are supported.
Moreover, you shouldn't use 4.3 version for ixgbe sources and 4.6 for other linux sources. Just use the same version.

**Comment by leleobhz** [comment]
@vmaffione This is not a option for a lot of people (Me included) because the software I use requires options that only exists in 4.x version of ixgbe. Im trying to use https://github.com/pavel-odintsov/ixgbe-linux-netmap but a official support is wellcome.

And ixgbe version (Official from e1000.sf.net) is not related to kernel version.

**Comment by vmaffione** [comment]
Sorry, I don't think I follow your reasoning.
Each kernel version potentially changes the API used by drivers, and so in general there is a different ixgbe version for each kernel version. It may also happen that the API does not change too much across 4.1,4.2,... versions, so that the ixgbe driver code stays the same for those versions. But if this is true you can use the ixgbe driver with any 4.x kernel, up to 4.5 included.
The current version of netmap does not compile under linux 4.6 - not yet.

So what I was suggesting in the end is that as a temporary solution you could use 4.5 kernel (for instance) sources (including ixgbe) and headers. It is still a 4.x version, so you will get the options that you need.

**Comment by leleobhz** [comment]
The e1000.sf.net version (From Intel Developers) does not follow the kernel version. So the 4.3.15 Intel module version does not have any connection to kernel module. ixgbe module compiles in 4.6.0: http://pastebin.com/U3wEujb0 - and used @pavel-odintsov patch to compile this ixgbe version with netmap support. Strings from module (Grepped for "LINUX", /lib/modules/4.6.0-1.el7.elrepo.x86_64/extra/ixgbe/ixgbe.ko) here: http://dpaste.com/0PR9MFK

About netmap x 4.6: http://pastebin.com/j4efp7BC

Now, the issue I have (And I dont know if its my software bug or netmap issue) is use netmap just dont return any packet in sniffing and the issue I registered about number of threads of capture x netmap.

I think Kernel may be rolled back, but rollback ixgbe version is not a option, so I still needing pavel patch to compile ixgbe with netmap in version 4.x of ixgbe, so I don think it changes too much thing. But the issue of netmap not returning any packet concerns me.

**Comment by vmaffione** [comment]
Ok now I understand that this 4.3.15 e1000.sf.net ixgbe driver released from Intel has nothing to do with the ixgbe in the kernel sources. We have ixgbe netmap-patches for the ixgbe driver in the Linux vanilla sources (for the different versions). But we don't have netmap-patches for the e1000.sf.net ixgbe drivers. If you wish to develop/adapt a patch for those sources it would be great.

Regarding your problems with netmap applications, I would recommend you to start testing/developing the application using the emulated (aka generic) netmap adapter, i.e. using an unpatched ixgbe driver (either the one in the kernel sources or the one from e1000.sf.net). Performances won't be the best (up to 4 Mpps per-queue), but at least you are able to isolate the bug.

**Comment by leleobhz** [comment]
Hello @vmaffione 

About ixgbe/intel netmap-patches, @pavel-odintsov did it already: https://github.com/pavel-odintsov/ixgbe-linux-netmap

After Pavel helped-me to diagnose the issue, I'm convinced ixgbe patch works (See http://pastebin.com/hZMS253c ).

So now I assume the dev of my closed-source software is the responsable for the misuse of netmap. But I still affected by https://github.com/luigirizzo/netmap/issues/183 - since I need a lot of threads doing capture in same interface.

May the pavel patches be inserted in netmap-upstream?

Thanks!

**Comment by vmaffione** [comment]
Hi,
  We are planning to rework the ixgbe netmap support in the next month (using the official ixgbe sources you are talking about), to avoid compilation problems. So stay tuned :)

**Comment by pavel-odintsov** [comment]
That's really nice news! Awesome!

On Wed, Jun 1, 2016 at 12:20 PM, Vincenzo Maffione <notifications@github.com
> wrote:

> Hi,
> We are planning to rework the ixgbe netmap support in the next month
> (using the official ixgbe sources you are talking about), to avoid
> compilation problems. So stay tuned :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/180#issuecomment-222938615>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZhLsSLS330BGuut3mXJ2iqm0V4jgks5qHU7jgaJpZM4IjgtV>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by leleobhz** [comment]
Awesome @vmaffione !!! Im already following netmap and now, more than ever.

Thanks!
