### ISSUE TITLE
Is it possible to send&receive from the same interface at the same time? 

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#181]
I am trying to start from rewriting the pkt-gen.c, but not sure whether this is inherently impossible?

**Comment by vmaffione** [comment]
Yes, it is definitely possible. Receive and transmit rings are independent on each other.

**Comment by Linerd** [comment]
If I want to have two separate threads each handling receive and send, on the same interface, how should I modify the code? I am quite new to your code base, so I would really appreciate it if you could point me to the right direction.

Also, if I run the program in Docker containers, how is it gonna affect the performance of Netmap? I am a bit unclear about the path that packets traverse if the setting looks like this: phy_intf — software switch — container — software switch — another phy_intf. 

Thanks a lot


Best Regards,

Yikai Lin(Leonard)
PhD Student, Computer Science & Engineering
University of Michigan, Ann Arbor
--------------------------------
Phone: +1-734-2392189

**Comment by vmaffione** [comment]
pkt-gen is just a test application, there is nothing special in modifying the code to achieve what you want. You could add two command line options to specify the number of sender and number of receivers, and then run that number of thread, respectively.

Otherwise you could just avoid modifying pkt-gen and run two pkt-gen instances to the same interfaces.

If you are using netmap to access a phisical NIC, then there is no performance difference between doing it inside or outside the container.
If you are using regular software switches (linux bridges, openvswitch), your inter-container throughput will be limited. You may want to use a VALE switch to connect your container.

**Comment by Linerd** [comment]
> On May 21, 2016, at 00:17, Vincenzo Maffione <notifications@github.com> wrote:
> 
> pkt-gen is just a test application, there is nothing special in modifying the code to achieve what you want. You could add two command line options to specify the number of sender and number of receivers, and then run that number of thread, respectively.
> 
> Otherwise you could just avoid modifying pkt-gen and run two pkt-gen instances to the same interfaces.
> 
> If you are using netmap to access a phisical NIC, then there is no performance difference between doing it inside or outside the container.
> If you are using regular software switches (linux bridges, openvswitch), your inter-container throughput will be limited. You may want to use a VALE switch to connect your container.
> 
Is this throughput degradation inherent with software switches? Does the traffic go a stretched path if I use netmap for the purpose?

**Comment by Linerd** [comment]
Also, when I was trying to have two threads accessing the same interface, I was told that the # of devqueues is just 1, which is smaller than the # of threads. What is this devqueue used for? I also encountered Unable to open <itf_name> error.

207.013024 main [2271] interface is eth0
207.013114 main [2391] running on 1 cpus (have 2)
207.013269 extract_ip_range [379] range is 10.0.0.2:0 to 10.0.0.2:0
207.013288 extract_ip_range [379] range is 10.0.0.3:0 to 10.0.0.3:0
207.013974 nm_open [777] overriding ifname eth0 ringid 0x0 flags 0x8004
207.014082 main [2492] mapped 334980KB at 0x7f3731baf000
207.014102 main [2512] bad nthreads 2, have 1 queues
Sending on netmap:eth0: 1 queues, 2 threads and 1 cpus.
10.0.0.2 -> 10.0.0.3 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
207.014121 main [2589] Sending 512 packets every  0.000000000 s
207.014146 main [2591] Wait 2 secs for phy reset
209.014540 main [2593] Ready...
209.014721 nm_open [777] overriding ifname eth0 ringid 0x1 flags 0x8004
209.014782 nm_open [847] NIOCREGIF failed: Invalid argument eth0
209.014792 start_threads [1979] Unable to open netmap:eth0: Invalid argument i:1

These are the debug messages. 


Best Regards,

Yikai Lin(Leonard)
PhD Student, Computer Science & Engineering
University of Michigan, Ann Arbor
--------------------------------
Phone: +1-734-2392189

**Comment by vmaffione** [comment]
pkt-gen is just an example application that uses the netmap API. The application itself is somehow cahotic, supporting lots of features we need to do our tests.

In this case pkt-gen refuses to run more than one thread if the interface does not support multi-queue. But this is just a straightforward policy of a tool that we use for testing.

I think it may be simpler for you if you write a simple application from scratch using the C netmap API (sys/net/netmap.h is the lower level API, sys/net/netmap_user.h is the higher level API).
The netmap API is also available in python (see extra/python, there is code and some examples), which is probably easier to start with.

Then you can create as many threads as you wish and access

**Comment by Linerd** [comment]
Hi, I was able to create this program from scratch as suggested. I do have a couple questions though. 

First is whether to set "ring->head = ring->cur = cur" every packet or every batch? I can see this is different between the pinger and the sender. 

Second is why do I see missing packets when using two pkt-gen to send packets to the other? I sent say 500,000 pkts using tx and saw just about 350,000 at the receiver.

**Comment by vmaffione** [comment]
The only important thing is that you update ring->head and ring->cur before calling ioctl(TXSYNC), ioctl(RXSYNC) or poll(), otherwise the kernel won't see your new work.

For the second question, you didn't say what kind of netmap ports each pkg-gen instance is sending/receiving on.

**Comment by Linerd** [comment]
The two ports are virtual ports in OVS, connected to two Docker containers. The topology looks like this

Container1 ---- OVS ---- Container2

**Comment by vmaffione** [comment]
Virtual ports can be TAP interfaces, veth interfaces, etc. If they are TAP interfaces, packets may be dropped by the TAP driver, since they have an internal sk_buff queue with limited size.

**Comment by Linerd** [comment]
I believe they are veth interfaces. Is there anything special I should do?

**Comment by vmaffione** [comment]
You could try to use a VALE switch in place of the OVS. Than you can attach the host-side of each veth pair to the VALE switch using the vale-ctl -a command.

**Comment by Linerd** [comment]
But I do need to use OVS for the traffic engineering, should I use vale as the OVS datapath?

**Comment by vmaffione** [comment]
You could try to use VALE with "patched OVS", so that you should be able to use OpenFlow:

https://github.com/luigirizzo/netmap/blob/master/examples/switch-modules/ovs-datapath/0001-datapath-Add-support-for-netmap-VALE.patch

but I've never tried this personally.
