### ISSUE TITLE
how to create more than 16 pipes 

### ISSUE THREAD

**Issue by zhangwei1984** [luigirizzo/netmap#185]
Hi,

I want to create more than 18 pipes when using lb application.  After 18 (for example lb -i p2p2 -p 20), I got this error:261.135269 nm_open [847] NIOCREGIF failed: Cannot allocate memory p2p2{18
261.135276 main [456] cannot open netmap:p2p2{18
It seems that there is some limitation. There is a macro NM_MAXPIPES 64, but I can't make more than 18. It seems here is not the limitation. My question is that if I want to create more than 18 pipes, eg 100 pipes, where should I change to make it work?

From the error "Cannot allocate memory", inside function netmap_get_pipe_na()
here will allocate memory which is related to the number of pipes
https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap_pipe.c#L102. 
But I do not think it was caused by here.  

Dmesg shows the error:
[88943.459956] 112.380834 [ 840] netmap_obj_malloc         no more netmap_ring objects
[88943.471745] ixgbe 0000:07:00.1 p2p2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
[88943.481829] 112.402705 [1736] netmap_mem2_rings_create  Cannot allocate TX_ring
[88943.852137] ixgbe 0000:07:00.1 p2p2: detected SFP+: 4
[88944.091797] ixgbe 0000:07:00.1 p2p2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
Thanks

**Comment by leleobhz** [comment]
@zhangwei1984 - may you report be related with my issue https://github.com/luigirizzo/netmap/issues/183 ?

Im also limited to <20 process ( But i did not measured it) and i only have access to dmesg, since my app is a closed-source app.

**Comment by zhangwei1984** [comment]
OK, I also put the problem into your issue.

**Comment by vmaffione** [comment]
you need to increase the value of the num_ring module parameter
