### ISSUE TITLE
interaction with checksum offload etc not documented

### ISSUE THREAD

**Issue by rbtcollins** [luigirizzo/netmap#194]
I mean, it is in various random places on the net, but its not in README.md, nor in netmap.h or netmap_user.h

See #195 about improving the situation other than docs.

**Comment by vmaffione** [comment]
please check
https://github.com/luigirizzo/netmap/commit/eb7400713b024f470958575cb151def348f89681

**Comment by rbtcollins** [comment]
That commit looks nice and clear.
