### ISSUE TITLE
generic adapters forward all received traffic to host

### ISSUE THREAD

**Issue by rbtcollins** [luigirizzo/netmap#196]
I have a small test program which forwards all frames except gre frames from eth0 to eth0^, but when its running I still see gre packets in tcpdump; if I disable the filtering, I see each incoming gre packet twice.

**Comment by rbtcollins** [comment]
trivially reproduced with bridge.c
```
bridge netmap:eth0
run tcpdump -nei eth0 proto gre
```
on a remote machine send a single gre packet - tcpdump sees 2.

**Comment by vmaffione** [comment]
That's an artifact of the generic adapter. A packet received from the unmodified driver is passed to taps (e.g. tcpdump) before it can be intercepted by netmap to end up in a RX ring (e.g. RX ring 0). Then, when the bridge program pushes the packet to the host TX ring, netmap pushes the packet back to host stack (using nm_os_send_up), where it will pop out as it was received by eth0. That's why you see the packet the second time.

**Comment by rbtcollins** [comment]
Will the host stack receive packets twice, or just things like tcpdump? If its just tcpdump, I think this is just a docs bug (assuming i didn't manage to miss reading about it).

**Comment by vmaffione** [comment]
No, just tcpdump (or any other tap listener) will see the packet twice.
It's just a difference between native netmap adapters and generic netmap adapters.
When using tcpdump on eth0, you will packets coming from the wire if you are using a generic adapter, you will see nothing if you are using a native netmap adapter.

**Comment by rbtcollins** [comment]
Where would be the right place to document this? There's no mention of generic adapters in netmap.h or /README.md.

**Comment by vmaffione** [comment]
It's in the man, it is called "emulated netmap" or "emulated adapter".

**Comment by rbtcollins** [comment]
Does this generic behaviour apply to all OS's / all unix-like OS's / just linux ?

**Comment by rbtcollins** [comment]
I've taken a stab at documenting this.

**Comment by vmaffione** [comment]
It's not a rule, it is an implementation artifact.

2016-06-09 12:36 GMT+02:00 rbtcollins <notifications@github.com>:

> I've taken a stab at documenting this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/196#issuecomment-224858947>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEsSwa0JDxLZ9wVninrb20VUxx17qYZcks5qJ-zFgaJpZM4IviwV>
> .
>



-- 
Vincenzo Maffione

**Comment by rbtcollins** [comment]
I'm happy to change my patch if you've got some feedback on it :) - I realise its an implementation artifact, but it is such a thing today, so we should document that it is. Perhaps you mean that my patch should note that this isn't desired, its just the best we deliver today?

**Comment by vmaffione** [comment]
yes, indeed, just commented on your PR
