### ISSUE TITLE
Netmap multi progress simultaneous access

### ISSUE THREAD

**Issue by leleobhz** [luigirizzo/netmap#200]
Hello!

In a closed-source software that uses netmap, I got the following awnser about opening multiples analysers at same time:

> Hello,
> It's a netmap architectural limitation. Access is exclusive. Two netmap programs cannot listen at the same time to the same physical interface. You can try running 2 pkt_gen programs at the same time in listening mode, and they will fail.
> Regards,
> Support Team 

Is that true? There is some way to handle this?

Thanks!

**Comment by giuseppelettieri** [comment]
If you only need to capture packets (as opposed to injecting them) you can open a netmap monitor on the port: just add '/r' after the name the port in the string that you pass to nm_open(). Note that for the monitor to work, the port must already be in netmap mode. So, assume for example that the closed source software is capturing from eth0. While the software is running, you can run

pkt-gen -i netmap:eth0/r

and pkt-gen will start receiving a copy of all the packets received by the other application. You can also capture the packets that the other application is injecting into eth0, if any, by adding the 't' flag, e.g:

pkt-gen -i netmap:eth0/rt

Cheers,
Giuseppe

**Comment by leleobhz** [comment]
Thanks for you awnser @giuseppelettieri ! Just one question: It's possible to be entirelly based on netmap? I have a dedicated interface connected to my portmirror, so this interface only listens, does not have in or out or forward. Also we today, using standard libpcap, have a considerable drop rate, what I think netmap will help us to avoid, so I dont need notthing else being done in this interface.

That said, what you can recommend or tell-me more about this? Also, I notified upstream about this issue, so they are reading here too.

Thanks for all yoou help.

**Comment by leleobhz** [comment]
@giuseppelettieri The proprietary software awnsered today about you suggestion as following:

> The error is gone if a first Sensor starts listening using Netmap to p2p1, after which the second Sensor starts listening using Netmap to p2p1/r. But when both Sensors start, packet rate drops to zero. So the proposed solution is not working.

Do you have an idea about what is wrong? Also, there is some documentation that me, as non-dev, can help to find why this do not work well?

Thanks!

**Comment by giuseppelettieri** [comment]
I am sorry, but I miss too much context and I am not able to understand their reply. The first period says that, by using a monitor on the second "Sensor" (whatever that is), "the error is gone". Then, the second period mentions a (different?) scenario in which "both Sensors start" (start again? on which netmap ports?).

One limitations of monitors is that they are attached to an instance of an open netmap port: if you restart the port you also have to restart the monitor. Again, however, I don't know whether this is relevant or not to your case, since I am confused by what they say.

**Comment by leleobhz** [comment]
@giuseppelettieri I can send you in private the entire context (Since the code is closed source, I fear publish the ticket token can bring-me some problems)?

P.s: I do not like the "argumentative bridge" I'm doing, but our vendor want to "blame" netmap where I think its not netmap fault, but since Im not a developer, I cant question him more than I did.

Thanks!
