### ISSUE TITLE
pkt_gen not receive UDP packets 

### ISSUE THREAD

**Issue by huangh901218** [luigirizzo/netmap#205]
hello netmap team:
        when run ./pkt_gen -i enp1s0f0 -v -f rx -s 192.191.10.113 -d 192.191.10.154 , The result:

![3](https://cloud.githubusercontent.com/assets/20471137/17589179/c3214bb4-6005-11e6-9f31-c704715eaa7d.gif)

![2](https://cloud.githubusercontent.com/assets/20471137/17590582/d528e658-600c-11e6-9bb2-91cd68425de0.gif)

**Comment by huangh901218** [comment]
![Image of IMG_7165](https://octodex.github.com/images/yaktocat.png)

**Comment by huangh901218** [comment]
![Image of IMG_7165](https://octodex.github.com/images/yaktocat.png)

**Comment by huangh901218** [comment]
![4](https://cloud.githubusercontent.com/assets/20471137/17590593/ddf39cec-600c-11e6-817d-24bf1d88b17e.gif)
![1](https://cloud.githubusercontent.com/assets/20471137/17590634/0b1da028-600d-11e6-868a-5dfcb88632b1.gif)

**Comment by deemru** [comment]
`ip link set enp1s0f0 promisc on`

**Comment by huangh901218** [comment]
ifconfig  enp1s0f0 promisc?????

**Comment by huangh901218** [comment]
![img_7169](https://cloud.githubusercontent.com/assets/20471137/17609808/db076faa-606a-11e6-8d85-e17846bcc3fa.gif)
![img_7170](https://cloud.githubusercontent.com/assets/20471137/17609870/5e6ae5fc-606b-11e6-93cd-e666fd67716c.JPG)

**Comment by huangh901218** [comment]
![Uploading IMG_7171.gif…]()

**Comment by huangh901218** [comment]
![img_7171](https://cloud.githubusercontent.com/assets/20471137/17610134/9016c024-606d-11e6-81ba-accc0b0e93bb.gif)

The result is same!!!

**Comment by deemru** [comment]
add static arp entry of the server to the client:
`arp -s 192.191.10.113 00:15:1a:6e:08:f4`

**Comment by huangh901218** [comment]
hello，thank you for your help！can you tell me why？

**Comment by deemru** [comment]
> why?

because the most protocols (including [ARP](https://en.wikipedia.org/wiki/Address_Resolution_Protocol)) do not work by default on a netmapped interfaces so your client do not know where to send his packets

**Comment by huangh901218** [comment]
thank you very much！
