### ISSUE TITLE
Interface is not accessible On which Netmap (--Suricata) is running

### ISSUE THREAD

**Issue by admin2020** [luigirizzo/netmap#206]
I am using Suricata with Netmap on, say eth0 interface (on device-1). Before that other device (say device-2) is connected to eth0 and got reply from device-1 of ping request from device-2 while only suricata engine is running on device-1, but not be able to get reply of even ping request if execute suricata engine with netmap.

Do anyone have idea how can i capture packets when netmap (zero copy interface) is running?

**Comment by vmaffione** [comment]
If you have an interface eth0 being used by a netmap application, you can sniff the packets passing through that interface by using netmap monitors (lookup "monitor" and "MONITOR" in sys/net/netmap.h). This would be similar to tcpdump.
