### ISSUE TITLE
To increase number of slots or rings when using virtio_net driver in KVM Guest

### ISSUE THREAD

**Issue by rahulshcse** [luigirizzo/netmap#207]
Hello.

I am using **netmap** inside multiple virtual machines in **KVM** based virtualization environment, connected via **VALE switch** and **passthrough** enabled.   Is there a way to increase **number of rings/ netmap slots per rin**g when using **virtio_net** driver.

Thanks

**Comment by admin2020** [comment]
Hi Rahul,
I have posted below question regarding netmap. Do you have any idea ?
https://github.com/luigirizzo/netmap/issues/206

**Comment by vmaffione** [comment]
Hi,
  In order to use netmap passthrough with KVM you have to use a slightly modified version of qemu, available here

https://github.com/vmaffione/qemu/tree/ptnet

You have to enable netmap (and netmap passthrough) with ./configure options. To give you an idea, this is my config.status (from which you can extract the options you need):
````
#!/bin/sh
# Generated by configure.
# Run this file to recreate the current configuration.
# Compiler output produced by configure, useful for debugging
# configure, is in config.log if it exists.
exec '/home/vmaffione/git/qemu/configure' '--target-list=x86_64-softmmu' '--enable-kvm' '--enable-vhost-net' '--python=python2' '--disable-werror' '--enable-debug' '--enable-netmap' '--extra-cflags=-I/home/vmaffione/git/netmap/sys' '--enable-ptnetmap' "$@"
````

When invoking qemu, you have to use "ptnet-pci" in place of "virtio-net-pci" as a device model. In other words, you don't have to use virtio_net, but ptnet.
More info here http://info.iet.unipi.it/~luigi/papers/20160613-ptnet.pdf

**Comment by rahulshcse** [comment]
Thanks a lot vmaffione. I shall try it.

**Comment by vmaffione** [comment]
No unfortunately the "rings" option is still not there, but:

- Netmap passthrough supports multi-ring, that is if you specify ifname=netmap:eth3, and eth3 happens to be multiqueue device (e.g. an 8-queues ixgbe device), you will see all its queues in the guest. No "rings" option needs to be specified.
- We can easily add "rings" option for VALE ports (and probably netmap pipes): this is something that I plan to do in the future and propose to upstream QEMU. In the meanwhile you could try to do it yourself, using the attached patch as a starting point, to be applied to my QEMU ptnet branch. In particular take a look at the "struct nmreq" definition to see all the things that you may want to configure for the VALE port.

[mq-vale.patch.txt](https://github.com/luigirizzo/netmap/files/422708/mq-vale.patch.txt)

**Comment by rahulshcse** [comment]
Ok. Thanks @vmaffione

**Comment by vmaffione** [comment]
Ok, to check that the whole setup is working you should be able to get ~20 Mpps, using the pkt-gen program between two VMs connected by a  VALE switch (on the same physical machine).
