### ISSUE TITLE
Mellanox ConnectX-4 support

### ISSUE THREAD

**Issue by gkatsikas** [luigirizzo/netmap#210]
Hi,

I am wondering whether there is any netmap effort being put for Mellanox drivers.
I have a single port ConnectX4 100GbE card which uses mlx4-en and mlx4-core modules and I want to test how far I can go, in terms of Tx and Rx capabilities, with netmap.

Thanks in advance,
Georgios

**Comment by vmaffione** [comment]
Hi,
  There is nobody working on it at the moment, but we would really like to see netmap support for Mellanox.
We can guide you through the process of writing the adapter. Have you had a look at existing adapters like LINUX/ixgbe_netmap_linux.h and LINUX/if_e1000_netmap.h?

**Comment by gkatsikas** [comment]
Hi,

I am afraid I have no cycles to start such a demanding task at the moment.
I will come back once I find some time.

Thanks!
