### ISSUE TITLE
Receiver always misses a few packets?

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#212]
I have established a topology like this:

pkt-gen ----- app ------ pkt-gen

app is my own application built upon netmap, basically rewritten from pkt-gen

when I sent packets from the left hand side, the total number of packets received at the right hand side(and at the app side as I confirmed) is always smaller (5000000 vs. 4900000) than the sent number of packets. I tried sending at a little lower packet rate, didn't help (if set to very low, it helps though), reducing the sending burst size didn't help either... 

Is there anyway to increase the receiving capacity of my app? the app basically has two threads, one receiving packets and store in a buffer, the other thread emptying the buffer.

Thanks

**Comment by vmaffione** [comment]
This is not weird, packets are dropped if rings are found full. You did not specify what kind of netmap ports you are using, but if you are using VALE ports this happens very easily (the transmitter is not blocking, so if there is no space in the receiver ring then packets are dropped).

You could use netmap pipes in place of VALE ports. They are blocking IIRC.

**Comment by Linerd** [comment]
I am using ovs internal ports. I do not expect very high packet rate though, I was just testing with 300kpps, as long as my app does not slow it down, I will be satisfied. Now the receiver packet rate can be around 299kpps-301kpps, so I am really concerned with the loss

**Comment by Linerd** [comment]
Is there any way to increase the number of slots available? Given 1024 slots, seems that the best burst size for my app is 1024.

**Comment by vmaffione** [comment]
It's not tunable for now, you have to modify the code. Just replace the 1024 at line 920.

**Comment by Linerd** [comment]
Cool, it does reduce the drop rate. What is the maximum number for the slot number? Is there any concern behind how large it should be set?

**Comment by vmaffione** [comment]
the number of slots in the netmap ring depends on the interface hardware
