### ISSUE TITLE
Proper way to drop a packet (Bridge.c)

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#215]
Hi,

Sorry to be bothering you with this question, but lets say we want to drop a packet, in bridge.c example, what is the correct way to do it ?

I've tried commenting this:

                        uint32_t pkt = ts->buf_idx;
                        ts->buf_idx = rs->buf_idx;
                        rs->buf_idx = pkt;
                        /* report the buffer change. */
                        ts->flags |= NS_BUF_CHANGED;
                        rs->flags |= NS_BUF_CHANGED;

Expecting it would do the trick, but it seems something else is missing to be done ! Any light ? :)

**Comment by vmaffione** [comment]
To drop a packet you should not advance k (but only j). You should also not to execute "ts->len = rs->len", at least in principle.

**Comment by Fr3DBr** [comment]
Yes, it worked 100%, thank you very much. :)
