### ISSUE TITLE
netmap hook behavior - link down on register/unregister

### ISSUE THREAD

**Issue by kdzadza** [luigirizzo/netmap#217]
Hi,

I am working on a project, which uses netmap to interact with an Intel 10G based card.

The issue I am currently trying to overcome is that whenever an user-space application registers(or deregister) via netmap to the card, the card link flaps.
I saw that this behaviour is basically implemented on all supported card, and wanted to understand the motivation behind it.
I see that whenever per card registration hook is called, it first shuts down the card, for example in case of IXGBE:

```
static int
ixgbe_netmap_reg(struct netmap_adapter *na, int onoff)
{
    struct ifnet *ifp = na->ifp;
    struct SOFTC_T *adapter = netdev_priv(ifp);

    // adapter->netdev->trans_start = jiffies; // disable watchdog ?
    /* protect against other reinit */
    while (test_and_set_bit(__IXGBE_RESETTING, &adapter->state))
        usleep_range(1000, 2000);

    if (netif_running(adapter->netdev))
        ixgbe_down(adapter); // <--- power down
    /* enable or disable flags and callbacks in na and ifp */
    if (onoff) {
        nm_set_native_flags(na);
    } else {
        nm_clear_native_flags(na);
    }
    /* XXX SRIOV migth need another 2sec wait */
    if (netif_running(adapter->netdev))
        ixgbe_up(adapter);  /* also enables intr */ // <--- power up

    clear_bit(__IXGBE_RESETTING, &adapter->state);
    return (0);
}
```

So the `ixgbe_down` and `ixgbe_up` functions will do major reinit of the card and also shut down and bring up the link on the card.

I was wondering if this is done on purpose, including the power flapping and of the carrier, or it is the done for staying on the safe side, and keeping minimal changes to the original driver?

My theory is that during registration, should be enough to stop RX and TX operations, and as well as stop processing IRQs etc.
I would like to start working on such a solution and want to get initial feedback from you guys:
- If that should be possible from your perspective, or Power Donw/Up is mandatory
- If it is possible from theoretical point of view, I would appreciate some pointers on,
  what should be for sure blocked or reinitialized during registration/deregistration of the netmap process.

**Comment by vmaffione** [comment]
Hi, you are hitting one of the long standing issues.
Yes, reinit is done for staying on the safe side and keep the changes minimal. From a discussion with the Intel guys it came out that this is the simplest solution to be sure about the internal state of the card.

I would say that power down/up is not mandatory for netmap. Once you stop tx/rx operations (including interrupts) you should be safe, in theory. From netmap point of view, in the netmap register routine you would need to call ixgbe_netmap_configure_rx_ring() and ixgbe_netmap_configure_tx_ring(), as you can see in LINUX/final-patches/diff--ixgbe--*, which would be part of the TX/RX initialization.

But we are not aware of other NIC specific things (netmap unrelated) that may be necessary: e.g. register accesses.

(Maybe also @giuseppelettieri wants to comment on it)
