### ISSUE TITLE
FD Error (Bridge.c)

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#219]
Hi,

The error:

error on fd1, rx [373,373,373)

Means that the number of packets being received on the NIC/Queue is above the current processing capacity right ?

**Comment by vmaffione** [comment]
No, there are no packets available, actually (head = 373, tail = 373). POLLERR is cause by multiple reasons, check the kernel log

**Comment by Fr3DBr** [comment]
This is what I see there:

```
Sep  3 07:22:03 localhost kernel: 723.452936 [1604] nm_rxsync_prologue        ens1f0 RX3: fail 'head < kring->nr_hwcur || head > kring->nr_hwtail' h 922 c 922 t 1948 rh 922 rc 922 rt 1948 hc 923 ht 1948
Sep  3 07:22:03 localhost kernel: 723.453532 [1648] netmap_ring_reinit        called for ens1f0 RX3
Sep  3 07:22:04 localhost kernel: 724.591611 [1604] nm_rxsync_prologue        ens1f0 RX3: fail 'head < kring->nr_hwcur || head > kring->nr_hwtail' h 564 c 564 t 1590 rh 564 rc 564 rt 1590 hc 565 ht 1590
Sep  3 07:22:04 localhost kernel: 724.592068 [1648] netmap_ring_reinit        called for ens1f0 RX3
```

**Comment by Fr3DBr** [comment]
I think this is because I'm not able to read all packets at once, which may be fine, considering this machine even on packet-gen wasn't capable of handling 14 Mpps, but around 11~12 ? :)

**Comment by vmaffione** [comment]
Nope, the log shows that for some reason the kernel sees ring->head going backward (for each receive ring). In the first line, for instance, you see that h (head) is at 793, while hwcur (hc) is at 794. This should never happen, because hwcur (visible only in kernel-space) follows head and head is expected to only go onwards (like all the other index fields).

It could be a bug in the netmap implementation, but maybe it is more likely to be a bug in your application.

**Comment by Fr3DBr** [comment]
You are correct, it was a bug in my end, because I wasn't properly opening the queues, after reviewing my code and re-writing it the same way pkt-gen does, no more errors have showed, so sorry for wasting your time on this, have a nice weekend. :)

**Comment by vmaffione** [comment]
Consider that netmap supports full synchronization: if your application is slower than the NIC (to transmit or receive), the NIC will drop received packets or transmit without filling its rings; if your application is faster than the NIC, then poll/select will block and wait for some packets to arrive in the RX rings or for some free room for TX ring. No POLLERR can come from synchronization, idependently of who is faster.

No worries, have a nice week end too :)
