### ISSUE TITLE
zero copy 

### ISSUE THREAD

**Issue by alexhebra** [luigirizzo/netmap#222]
Hi,

I've merged last netmap github to FreeBSD 10.3-STABLE r305972M. After that zero copy is not working anymore:

server# tcpdump -i netmap:ix0 &
server# tcpdump -i netmap:ix0/rtz
866.916992 nm_open [859] NIOCREGIF failed: Invalid argument ix0/rtz
tcpdump: netmap open: cannot access netmap:ix0/rtz: Invalid argument

Is this a issue? Am i missing something? it used to work with July github netmap code.

Thanks.

**Comment by vmaffione** [comment]
Can you provide the SHA of the last working commit that you tried?

**Comment by alexhebra** [comment]
Hi,

Yes, the version that was working is eb74007.

I use this version on my FreeBSD port variable GIT_VERSION to download it.

Let me know if you need any other info.

Thanks

**Comment by vmaffione** [comment]
No, there was a bug indeed (triggered by a sanity check, sometimes happens). I pushed a fix, does it work now?

**Comment by alexhebra** [comment]
Yes, good job, it worked. Thanks.

You can close this issue. I'll open another one with if_ptnet on FreeBSD 11-RC3.
