### ISSUE TITLE
dmesg is full of netmap_transmit for non existing interface

### ISSUE THREAD

**Issue by potakhov** [luigirizzo/netmap#223]
I'm using netmap with ixgbe NIC on CentOS 7 to filter incoming traffic to match some specific rules and then inject it back to the host stack. All the host stack traffic is injected back to NIC. I know this is not recommended however the volume for the valid traffic is not high so in overall it works well.
The question is - from time to time system log gets flooded with messages like those:

[1216052.820858] 929.361557 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 130 m ffff8807ba828af8
[1216052.821552] 929.362251 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 564 m ffff88083151b4f8
[1216052.822513] 929.363213 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 292 m ffff8808202b8af8
[1216052.823279] 929.363979 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 60 m ffff88084f9a1ef8
[1216052.823894] 929.364592 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 130 m ffff880821dcf2f8
[1216052.824520] 929.365219 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 130 m ffff8800368234f8
[1216052.825393] 929.366091 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 130 m ffff88082182f8f8
[1216052.825901] 929.366598 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 564 m ffff880822d470f8
[1216052.826657] 929.367354 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 292 m ffff880035d332f8
[1216052.827160] 929.367857 [3010] netmap_transmit           eth0 full hwcur 51 hwtail 198 qlen 364 len 292 m ffff88084a3242f8

The issue is that eth0 device does not exist on any of target machines. Netmap is listening on ens1f0 and eth0 is not even registered to any of the NICs.
It is not seem related with inbound or outbound traffic levels nor with CPU load on particular boxes. Could you please give me a hint where to look further.

**Comment by vmaffione** [comment]
Can you dump "ifconfig" output on the machine where you get this log?

**Comment by potakhov** [comment]
eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:ac:37:8a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc7120000-c713ffff

eno2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:ac:37:8b  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc7100000-c711ffff

ens1f0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 90:e2:ba:b8:50:a8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens1f1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx  netmask 255.255.255.0  broadcast xx.xx.xx.xx
        ether 90:e2:ba:b8:50:a9  txqueuelen 16000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens1f1:0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx netmask 255.255.255.240  broadcast xx.xx.xx.xx
        ether 90:e2:ba:b8:50:a9  txqueuelen 16000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 11929  bytes 909113 (887.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11929  bytes 909113 (887.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

or another machine

eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:78:80:b6  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc7200000-c727ffff

eno2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0c:c4:7a:78:80:b7  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xc7100000-c717ffff

ens15: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx netmask 255.255.255.224  broadcast xx.xx.xx.xx
        ether 90:e2:ba:78:06:8c  txqueuelen 16000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens15:0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet xx.xx.xx.xx  netmask 255.255.255.224  broadcast xx.xx.xx.xx
        ether 90:e2:ba:78:06:8c  txqueuelen 16000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 27476  bytes 2645174 (2.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 27476  bytes 2645174 (2.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by vmaffione** [comment]
Well, the fact that netmap prints "eth0" means that it read that string from the kernel at some point, it cannot just make it up. Maybe you have some udev rules that change the interface names, so that netmap holds the old name of one of these interfaces? I don't see other possible solutions.

**Comment by potakhov** [comment]
yes and that is why I'm asking, I checked the source myself and understand that it can't just make it up however I don't have any udev rules on renaming and those names are how CentOS 7 actually calls the interfaces itself
it seems that it happens more often under a bigger load (passing ~250mbps in/out to/from the kernel stack ring) - could it be caused by operations on a host stack ring somehow maybe? 
On a side note - if I increase the ring size - would that increase size for a host ring as well? Is that a /sys/module/netmap/parameters/ring_size parameter which controls that?

**Comment by vmaffione** [comment]
If ens1f0 is the only interface in netmap mode, it must be that it was called eth0 at some points. To verify that, you can print the "ifp" pointer in netmap_transmit (where the logging happens) rather than printing the ifname. Then you can print the ifp pointer somewhere else (e.g. in the netmap_to_regif), which is called when you NIOCREGIF ens1f0 in your application. Comparing the pointers will unveil the thruth.

This said, the log message is just saying that the netmap application draining the host rx ring is for some reason too slow to drain all the packets that the host stack is trying to transmit through eth0/ens1f0. Or maybe nobody is draining the host rx ring.

No, the number of descriptors depends on the hardware, so you cannot change it (afaik), at least for native netmap drivers.
