### ISSUE TITLE
Netmap performance issue

### ISSUE THREAD

**Issue by alexhebra** [luigirizzo/netmap#227]
Hi @vmaffione ,

I did some performance tests today and last commit broke netmap performance on FreeBSD. I don't know what has been touched but before last commit i had 10Mpps with netmap bridge, and now i got 5Mpps.

I did a rollback to commit 4492bc2 and everything worked as expected again.

**Comment by vmaffione** [comment]
If you mean examples/bridge, what interfaces have you attached to the bridge?

**Comment by alexhebra** [comment]
Yes examples/bridge. I was using intel ix driver (ix0 and ix1)

**Comment by vmaffione** [comment]
Are you using the native ixgbe support or the generic/emulated adapter? You can check this from the log when you run netmap.

**Comment by alexhebra** [comment]
@vmaffione you are right. It's was running using generic adapter. I've changed to use native support and worked again.

Thank you for your help.
