### ISSUE TITLE
how to use the patched ovs with netmap?

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#230]
I have the patched OVS installed, what kind of port should I use to see the performance improvement? I am thinking of using OVS internal ports with Docker containers, and run netmap applications within the container. Any suggestions?

**Comment by Linerd** [comment]
I noticed that using vale-ctl will create and destroy bridges and ports on the fly, but when ovs runs with vale, what is the bridge name? I can't use pkt-gen with ovs to test the performance...

**Comment by vmaffione** [comment]
@micchie do you have some suggestions here?

**Comment by micchie** [comment]
Basically, in use of OVS, please don't use vale-ctl command except for with "-n" or "-r" options which create or destroy a system-visible (i.e., you can see them with ip link commands) virtual port which can be accessed via netmap API.
In order to quickly test performance with OVS+VALE, I suggest following steps:
vale-ctl -n vi0
vale-ctl -n vi1
ovs-vsctl add bridge vale0
ovs-vsctl add port vale0 vi0
ovs-vsctl add port vale0 vi1
(insert a rule to forward packets from vi0 to vi1 using ovs-ofctl or something)
pkt-gen -i vi0 -f rx
(in a different terminal) pkt-gen -i vi1 -f tx

**Comment by Linerd** [comment]
@micchie I tried, but the flow rule isn't matched. ovs internal port works, but performance is not good. Any thoughts?

**Comment by Linerd** [comment]
@micchie the receiving pkt-gen didn't see any packets, ovs-ofctl dump-flows gives no matched packets, the sender is sending at ridiculously high speed of 200+Mpps(Tbps throughput).

**Comment by Linerd** [comment]
@micchie I have been able to detect the traffic when I added this command: vale-ctl -a vale:vi0

But when I try to detach and delete the interface, the command froze
vale-ctl -d vale:vi0 runs without problem, but vale-ctl -r vi0 froze

@vmaffione any ideas?

**Comment by micchie** [comment]
Please don't detach (-d) using vale-cal for ovs-vale. Please try to use ovs-vsctl...

cheers,
- Michio

		_____________________________

**Comment by Linerd** [comment]
@micchie But if I don't detach, when I try to delete it, it tells me the device or resource is busy

**Comment by micchie** [comment]
yes, vi0 is a kind of NIC, so cannot be deleted by vale-ctl -r until it has been detached by ovs-vsctl

cheers,
- Michio




On Fri, Sep 30, 2016 at 4:56 PM +0200, "Yikai" <notifications@github.com> wrote:












@micchie But if I don't detach, when I try to delete it, it tells me the device or resource is busy

**Comment by Linerd** [comment]
@micchie I first use ovs-vsctl del-port to detach, then I try to delete it, didn't work.

Let me reorganize the problem:

If I just use vale-ctl -n to create, then ovs-vsctl add-port to attach, I don't see any packets

I have to use vale-ctl -a/-h vale:[xx] to attach, then I can see the packets

But when I attach using vale-ctl, I can't delete them, no matter what I do with ovs-vsctl

**Comment by Linerd** [comment]
@micchie In other words, I can't get it to work without using vale-ctl -a to attach, and when I use this command to attach, I have to use this command(-d) to detach, otherwise it is always busy(no matter what I do with ovs-vsctl), and that's when it freezes. I hope it is clear by now...

**Comment by vmaffione** [comment]
A short tutorial on how to use the OVS patched for netmap is available in the OVS patches (e.g. https://github.com/luigirizzo/netmap/blob/master/utils/switch-modules/ovs-2.6.1/0001-datapath-netmap-VALE-support.patch)
