### ISSUE TITLE
Cannot build for windows

### ISSUE THREAD

**Issue by olproff** [luigirizzo/netmap#234]
Hello all.
When I've started build for windows i got the following errors:
i've added in win_glue.h

typedef int bool;
#define true 1
#define false 0

and the number of errors was reduced to 2, there are:
VS log:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4013	'MBUF_TRANSMIT' undefined; assuming extern returning int	netmap	E:\Programming\netmap2\sys\dev\netmap\netmap.c	3029	
Error	C4013	'MBUF_TXQ' undefined; assuming extern returning int	netmap	E:\Programming\netmap2\sys\dev\netmap\netmap.c	3022	

Steps:
1) git clone https://github.com/luigirizzo/netmap.git
2) The build was made by VS2013/2015. 

Please take this into account.

**Comment by olproff** [comment]
How can I  replace those macros in  Windows ?

**Comment by vmaffione** [comment]
Unfortunately we don't have expertise on Windows. However, I prepared and attached a patch, following your suggestions. Can you try it to see if it fixes the compilation?

[fix.patch.txt](https://github.com/luigirizzo/netmap/files/528130/fix.patch.txt)

**Comment by olproff** [comment]
Yes of course, i have all environment and i wiil try.

**Comment by olproff** [comment]
fix applied, but i got linker errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol nm_os_mbuf_has_offld	netmap	E:\Programming\netmap2\WINDOWS\netmap.obj	1	
Error	LNK1120	7 unresolved externals	netmap	E:\Programming\netmap2\WINDOWS\Output-Win8.1Release\tmp\netmap-unsigned\netmap.sys	1	
Error	LNK2001	unresolved external symbol nm_os_kthread_start	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1	
Error	LNK2001	unresolved external symbol nm_os_kthread_create	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1	
Error	LNK2001	unresolved external symbol nm_os_kthread_delete	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1	
Error	LNK2001	unresolved external symbol nm_os_kthread_set_affinity	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1	
Error	LNK2001	unresolved external symbol nm_os_ncpus	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1	
Error	LNK2001	unresolved external symbol nm_os_kthread_stop	netmap	E:\Programming\netmap2\WINDOWS\netmap_vale.obj	1

**Comment by deemru** [comment]
See #132 

Specially: https://github.com/luigirizzo/netmap/issues/132#issuecomment-182891021

**Comment by vmaffione** [comment]
Ok, this is related to kthread support, which is cleary missing on windows. Can you try with this new patch?

[fix.patch.txt](https://github.com/luigirizzo/netmap/files/529210/fix.patch.txt)

**Comment by olproff** [comment]
fix was applied, after build i've got netmap.sys driver.
win-ps MINGW64 /e/Programming/netmap2/WINDOWS/Output-Win7Release/tmp/netmap-unsigned (master)
$ ls
netmap.cer  netmap.inf  netmap.pdb  netmap.sys.

Will see how it works. thank you .

**Comment by vmaffione** [comment]
ok, closing this since it was about the build

**Comment by vmaffione** [comment]
Hi,
  The previous patches have been integrated in the mainstream, but I am afraid some other modifications may have broken the compilation. Could someone check the compilation of the current state of master and report problems to me?

**Comment by psechenov** [comment]
Hi @vmaffione 
  netmap_mem2.c
..\sys\dev\netmap\netmap_mem2.c(1914): error C4013: 'copyout' undefined; assuming extern returning int [C:\code\netmap_master\WINDOWS\netmap.vcxproj]
  netmap_monitor.c
  netmap_pipe.c
  netmap_vale.c
  netmap_windows.c
netmap_windows.c(976): error C2016: C requires that a struct or union has at least one member [C:\code\netmap_master\WINDOWS\netmap.vcxproj]

Please fix the errors and I'll check the master on Hyper-V

**Comment by vmaffione** [comment]
Hi, please let me know if the attached patch fixes the compilation, or if more fixes are necessary.

Thanks
[fix.patch.txt](https://github.com/luigirizzo/netmap/files/600266/fix.patch.txt)

**Comment by psechenov** [comment]
@vmaffione ,
Compilation errors disappeared. Linking errors:

"C:\code\netmap_master\WINDOWS\netmap.sln" (Build target) (1) ->
"C:\code\netmap_master\WINDOWS\netmap.vcxproj" (default target) (2) ->
(Link target) ->
  netmap.obj : error LNK2001: unresolved external symbol nm_os_free [C:\code\netmap_master\WINDOWS\netmap.vcxproj]
  netmap.obj : error LNK2001: unresolved external symbol nm_os_malloc [C:\code\netmap_master\WINDOWS\netmap.vcxproj]
  netmap_monitor.obj : error LNK2001: unresolved external symbol nm_os_realloc
[C:\code\netmap_master\WINDOWS\netmap.vcxproj]
  C:\code\netmap_master\WINDOWS\\Output-Win8.1Release\tmp\netmap-unsigned\netmap.sys : fatal error LNK1120: 3 unresolved externals [C:\code\netmap_master\WIND
OWS\netmap.vcxproj]

**Comment by vmaffione** [comment]
Can you try again with the following patch?
[fix.patch.txt](https://github.com/luigirizzo/netmap/files/600504/fix.patch.txt)

**Comment by psechenov** [comment]
win_glue.c(182): error C4013: 'nm_os_malloc' undefined; assuming extern returning int 
  win_glue.c(237): error C4013: 'nm_os_free' undefined; assuming extern returning int

**Comment by vmaffione** [comment]
Ok, please try with the next version.
[fix.patch.txt](https://github.com/luigirizzo/netmap/files/600699/fix.patch.txt)

**Comment by psechenov** [comment]
c:\code\netmap_master\sys\dev\netmap\netmap_vale.c(2237): warning C4701: pote
ntially uninitialized local variable 'error' used [C:\code\netmap_master\WINDOWS\netmap.vcxproj]

(Link target) ->
  c:\code\netmap_master\sys\dev\netmap\netmap_vale.c(2237): error C2220: warnin
g treated as error - no 'executable' file generated [C:\code\netmap_master\WINDOWS\netmap.vcxproj]
  LINK : fatal error LNK1257: code generation failed [C:\code\netmap_master\WINDOWS\netmap.vcxproj]

**Comment by psechenov** [comment]
Ok, netmap is compilable.
Examples with this patch:
[fix.patch.txt](https://github.com/luigirizzo/netmap/files/603405/fix.patch.txt)

gcc -I../sys -Iincludes -DNO_PCAP -g -O2 -Wall -Werror ../apps/pkt-gen/pkt-gen.c
  -o ../examples/pkt-gen.exe
../apps/pkt-gen/pkt-gen.c:67:18: fatal error: ctrs.h: No such file or directory
 #include "ctrs.h"

**Comment by vmaffione** [comment]
what build command are you running, and in which directory?
You should run 'make apps' in the directory where you run ./configure

**Comment by psechenov** [comment]
I  run make in WINDOWS directory. It contains makefile and builds netmap + examples

**Comment by vmaffione** [comment]
Right, can you please with this one?
[fix.patch.txt](https://github.com/luigirizzo/netmap/files/603697/fix.patch.txt)

**Comment by vmaffione** [comment]
any news on that? does it work?

**Comment by psechenov** [comment]
Hi @vmaffione ,
Sorry for delays. Everything compiles fine now!

**Comment by vmaffione** [comment]
No problems, thanks!

**Comment by psechenov** [comment]
![vale](https://cloud.githubusercontent.com/assets/17339835/20558647/fa889000-b125-11e6-8916-e2ef84ed77db.png)
That's how vale works with the last patch

**Comment by vmaffione** [comment]
can you open another issue?

**Comment by vmaffione** [comment]
btw, the windows fixes are now upstream

**Comment by psechenov** [comment]
> can you open another issue?
The problem should be tested more thoroughly before. May be later when I have more time
