### ISSUE TITLE
netmap windows issue

### ISSUE THREAD

**Issue by olproff** [luigirizzo/netmap#237]
Hello all.
I've installed netmap on Windows:
driverquery utility show:
NdisWan      NDIS-драйвер WAN удале Kernel        20.11.2010 13:52:32
NDProxy      NDIS Proxy             Kernel        20.11.2010 13:52:20
NetBIOS      NetBIOS Interface      File System   14.07.2009 3:09:26
NetBT        NetBT                  Kernel        11.05.2016 17:58:22
netmap       Universita` di Pisa ne Kernel        14.10.2016 15:13:22
netr28ux     RT2870 USB Extensible  Kernel        30.04.2015 7:06:44
IOMap        IOMap                  Kernel        23.10.2014 3:52:12
NAL          Nal Service            Kernel        14.11.2013 18:22:43
NetmapNdis   Netmap NDIS LightWeigh Kernel        14.10.2016 16:59:56

$ ../../nm-loader.exe l
load driver for netmap
file E:\Programming\netmap2\WINDOWS\Output-Win7Release\tmp\netmap-unsigned/netmap.sys found.
CreateService netmap success
StartService failure! Error = 1275
ControlService failed!  Error = 1062
RemoveDriver netmap success
ManageDriver returns TRUE
Driver netmap correctly loaded

when i've started pkt-get:
$ ./pkt-gen-b.exe -i vale0:a -f tx
356.843334 main [2274] interface is vale0:a
356.843334 main [2397] running on 1 cpus (have 12)
356.863334 extract_ip_range [369] range is 10.0.0.1:0 to 10.0.0.1:0
356.863334 extract_ip_range [369] range is 10.1.0.1:0 to 10.1.0.1:0
356.863334 nm_open [859] cannot open /dev/netmap: No such file or directory vale0:a
356.873334 main [2479] Unable to open vale0:a : No such file or directory
356.873334 main [2560] aborting

$ ./pkt-gen-b.exe -i netmap:eth17 -f tx
938.242627 main [2274] interface is netmap:eth17
938.242627 main [2397] running on 1 cpus (have 12)
938.252627 extract_ip_range [369] range is 10.0.0.1:0 to 10.0.0.1:0
938.262627 extract_ip_range [369] range is 10.1.0.1:0 to 10.1.0.1:0
938.262627 nm_open [859] cannot open /dev/netmap: No such file or directory eth17
938.262627 main [2479] Unable to open netmap:eth17: No such file or directory
938.262627 main [2560] aborting

I have the follwing issues: 
356.863334 nm_open [859] cannot open /dev/netmap: No such file or directory vale0:a
356.873334 main [2479] Unable to open vale0:a : No such file or directory
938.262627 nm_open [859] cannot open /dev/netmap: No such file or directory eth17
938.262627 main [2479] Unable to open netmap:eth17: No such file or directory

Next i've tried to create device through vale-ctl utility:
$ ./vale-ctl.exe -n a
547.639276 bdg_ctl [92] Unable to open /dev/netmap

All netmap examples under directory [root netmap]/examples( in my case E:\Programming\netmap2\examples)  i've built under cygwin environment: copy two files from E:\Programming\netmap2\WINDOWS\includes\net[ethernet.h, if_dl.h] to E:\Programming\cygwin64\usr\include\net.
in GNUMakefile disable -Werror and -Wunused-function
trace:
win-ps /cygdrive/e/Programming/netmap2/examples
$ ls -1
bridge.c
click-test.cfg
ctrs.h
GNUmakefile
Makefile
pkt-gen.c
README
switch-modules
test_nm.c
test_select.c
testcsum.c
testlock.c
testmmap.c
testmod
vale-ctl.c

$ make
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP   -c -o pkt-gen.o pkt-gen.c
cc   pkt-gen.o  -lpthread -o pkt-gen
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP -DBUSYWAIT -c pkt-gen.c -o pkt-gen-b.o
cc   pkt-gen-b.o  -lpthread -o pkt-gen-b
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP   -c -o bridge.o bridge.c
In file included from bridge.c:14:0:
../sys/net/netmap_user.h:545:1: warning: «win_nm_poll» defined but not used [-Wunused-function]
 win_nm_poll(struct pollfd *fds, int nfds, int timeout)
 ^
cc   bridge.o  -lpthread -o bridge
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP -DBUSYWAIT -c bridge.c -o bridge-b.o
In file included from bridge.c:14:0:
../sys/net/netmap_user.h:545:1: warning: «win_nm_poll» defined but not used [-Wunused-function]
 win_nm_poll(struct pollfd *fds, int nfds, int timeout)
 ^
cc   bridge-b.o  -lpthread -o bridge-b
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP   -c -o vale-ctl.o vale-ctl.c
In file included from vale-ctl.c:29:0:
../sys/net/netmap_user.h:545:1: warning: «win_nm_poll» defined but not used [-Wunused-function]
 win_nm_poll(struct pollfd *fds, int nfds, int timeout)
 ^
cc   vale-ctl.o  -lpthread -o vale-ctl
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP    test_select.c  -lpthread -o test_select
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP    testmmap.c  -lpthread -o testmmap
cc -O2 -pipe -Wall -I ../sys  -Wextra -DNO_PCAP   -c -o test_nm.o test_nm.c
cc   test_nm.o  -lpthread -o test_nm

**Comment by vmaffione** [comment]
I see the nm_open() calls open("/proc/sys/DosDevices/Global/netmap", O_RDWR), so the problem could be that this path does not exist or is in another place.

Maybe @Alessio-Faina can help?

**Comment by psechenov** [comment]
Hi,

StartService failure! Error = 1275
ControlService failed! Error = 1062
as i understand you didn't manage to load netmap. Are you sure you  run cmd as admin ?
After loading netmap you should install nm-ndis as described in corresponding section in WINDOWS/README.txt. It gives you ability to address your ethernet adapters as netmap:ethXX. After that you can run pkg-gen.

Please correct me if i'm wrong.

**Comment by olproff** [comment]
Hi,
@psechenov , netmap driver is loaded as service.

**Comment by Alessio-Faina** [comment]
Hi,

this part
>>StartService failure! Error = 1275
>>ControlService failed! Error = 1062
means that the driver hasn't been correctly loaded: this is why"/proc/sys/DosDevices/Global/netmap" doesn't exists.
On top of my head one of the problems may be that the system you are running netmap on is not put in test mode or you haven't installed the test certificate in the right store. Another thing may be the driver signature enforcement enabled.

On what OS are you working on? Just to have an idea.

Anyway I haven't worked with netmap for a long time so if this doesn't solve your problem I'll try to recover my old knowledge and we can try to make it work.

Cheers,

    -Alessio

**Comment by vmaffione** [comment]
Is the problem still there?

**Comment by sgeto** [comment]
Your OS is refusing to load the module because it's untrusted.
You must (self) sign them and enable test mode.
