### ISSUE TITLE
netmap bridge app in sw mode( linux host mode)

### ISSUE THREAD

**Issue by olproff** [luigirizzo/netmap#241]
Hello all,
I run bridge app  example from remote ssh client:
./build-apps/bridge -i netmap:enp2s0f1
./build-apps/bridge built Oct 19 2016 18:31:49
957.959546 main [225] same interface, endpoint 0 goes to host
and connection is lost.

from other machine:
ping 192.168.0.99
Response from 192.168.0.99: bytes = 32 time = 463ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 2427ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 1582ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 2036ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 1009ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 2399ms TTL = 64
Response from 192.168.0.99: bytes = 32 time = 811ms TTL = 64

Is it normal timeline for the  netmap sw mode?

**Comment by vmaffione** [comment]
If you don't see that large latency without ./bridge running --> there is something wrong. Have you disabled TSO/GRO/checksum offloadings on enp2s0f1?

**Comment by olproff** [comment]
no, i haven't disabled, will try.

**Comment by olproff** [comment]
ethtool -K enp2s0f1 rx off tx off
ethtool -K enp2s0f1 gro off
ethtool -K enp2s0f1 tso off.

Now very good. Thank you.
