### ISSUE TITLE
Support for BPF?

### ISSUE THREAD

**Issue by leleobhz** [luigirizzo/netmap#244]
Hello Developers,

Asking my netmap-enabled application vendor for capture support inside their app, they awnsered to me the following issue:

> Me 2016-10-21 19:31
> Hello support,
> Im trying to do a Packet Tracer capture but status revert from green to red w/o any capture or any logging in WANConsole or system log.
> Can you please check and fix this?
> Thanks! 
> 
> > SoftwareSupport 2016-10-21 21:35
> > Hello,
> > Packet trances are not possible when using Netmap.
> > Regards,
> > Support Team 
> 
> 
> Me 2016-10-25 12:45
> Hello,
> Can you explain why its not possible? Its a netmap limitation?
> Thanks 
> 
>> SoftwareSupport 2016-10-25 15:21
>> Netmap does not have a native BPF function which is necessary for the Packet Tracer to function.
>> Regards,
>> Support Team 
> 
> Me 2016-10-25 16:54
> Well, Ill try to ask to netmap upstream for this information. 

So does make some sense to you what support team told me? And there is something I can tell to the support team aiming help this feature to be implemented?

Thanks!

**Comment by vmaffione** [comment]
Netmap is a general purpose high performance network I/O tool, not a packet filter. You can use an external BPF library/implementation to filter packets in your userspace netmap application.
