### ISSUE TITLE
patched OVS with bridge.c throughput and packet drop tests

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#246]
Hi,

I have been performing some experiments with patched OVS and the provided bridge.c example.

Here is three of the test setup:
1. vp1 ---- OVS ---- vp2
2. vp1 ---- OVS ---- vp4
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;/&nbsp; &nbsp; \
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; /&nbsp; &nbsp; &nbsp; \
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;vp2&nbsp; vp3
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bridge.c
3. vp1 ---- OVS ---- vp4 ---- OVS ---- vp7
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;/&nbsp; &nbsp; \ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; / &nbsp; &nbsp; \
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; /&nbsp; &nbsp; &nbsp; \ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  / &nbsp; &nbsp; &nbsp; \
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;vp2&nbsp; vp3 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp;  &nbsp; vp5 &nbsp; vp6
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  | &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|
   &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bridge.c &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  &nbsp; bridge.c

pkt-gen is placed at both ends to test the throughput of the setup, and the results are as follows(for default packet size, no rate limit set):
1. 3.453 Mpps (with packet drops)
2. 2.875 Mpps (sending at 3.274 Mpps, lots of packet drops)
3. 2.521 Mpps (sending at 3.057 Mpps, lots of packet drops)

Based on the results above, I have a few questions:
1. What caused the constant overhead when switching from exp. 1 to exp. 2? Is it the two extra copies? Is it the kernel to userspace overhead?
2. Based on the result of exp. 2 and exp.3, it seems that adding extra copies shouldn't incur that much overhead.
3. Even if I limit the sending rate to 1 Mpps, there is still packet drop(being the receiving throughput always slightly less than the sending throughput), probably dues to the fact that VALE ports do not block. @micchie , did you come up with a way to mitigate this in your paper? Otherwise it is hard to claim that the throughput actually reaches that.

I am new to netmap, so please forgive me if I missed some obvious issues or tweaks.

**Comment by vmaffione** [comment]
Patched kernel OVS is not maintained. We are working to add netmap backend to userspace OVS.
