### ISSUE TITLE
Which generally recommended, please run a Linux kernel version netmap and ixgbe network card thanks

### ISSUE THREAD

**Issue by wtyvvv** [luigirizzo/netmap#249]
Which generally recommended, please run a Linux kernel version netmap and ixgbe network card

Linux2.62 compilation errors, Linux 3.19 appeared caught very slowly, when I kill off PKT - getn kernel collapses, thanks everybody

**Comment by vmaffione** [comment]
2.62 is not an existing version

Linux 3.19 it's supposed to work fine. Are you using the ixgbe patched drivers? What are the steps to reproduce the crash on 3.19?

**Comment by wtyvvv** [comment]
sorry,i type wrong, this is full version  2.6.32-573.22.1.el6.x86_64,
i'm follow readme file, first i'm upgrage linux kernel linux-3.0.80.tar.gz
./configure --kernel-sources=/root/tmplinuxupgrage/linux-3.1.9/ --drivers=ixgbe
make
make install

rmmod ixgbe
insmod netmap.ko
insmod ixgbe.ko

/sbin/ifconfig eth2 promisc

and i'm running command
./pkt-getn -i eth2 -t rx 
when i switch another tty  ,and i'm kill pkt-gen this program,the kernel crash,but now laptop is not around my side,so now i can't find kernel log,sorry ,but tomorrow i will find log post it,thanks verymuch.

**Comment by wtyvvv** [comment]
@vmaffione
hello,here is kernel log,thanks

Nov 14 15:51:02 TE kernel: device eth2 entered promiscuous mode
Nov 14 15:51:02 TE kernel: 862.174700 [1208] netmap_mem_global_config  reconfiguring
Nov 14 15:51:02 TE kernel: 862.849636 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.851720 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.853822 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.855932 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.858013 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.860114 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.862218 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.864323 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.866456 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.868529 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.870630 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.872740 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.874854 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.876963 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.879067 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE kernel: 862.881172 [ 460] ixgbe_netmap_configure_srrctl bufsz: 2048 srrctl: 2
Nov 14 15:51:02 TE NetworkManager[2109]: <info> (eth2): carrier now OFF (device state 3)
Nov 14 15:51:02 TE NetworkManager[2109]: <info> (eth2): device state change: 3 -> 2 (reason 40)
Nov 14 15:51:02 TE NetworkManager[2109]: <info> (eth2): deactivating device (reason: 40).
Nov 14 15:51:03 TE NetworkManager[2109]: <info> Policy set 'System eth1' (eth1) as default for IPv4 routing and DNS.
Nov 14 15:51:03 TE NetworkManager[2109]: <info> Policy set 'System eth1' (eth1) as default for IPv4 routing and DNS.
Nov 14 15:51:03 TE kernel: ixgbe 0000:07:00.0: eth2: detected SFP+: 5
Nov 14 15:51:03 TE kernel: ixgbe 0000:07:00.0: eth2: NIC Link is Up 10 Gbps, Flow Control: RX/TX
Nov 14 15:51:03 TE NetworkManager[2109]: <info> (eth2): carrier now ON (device state 2)
Nov 14 15:51:03 TE NetworkManager[2109]: <info> (eth2): device state change: 2 -> 3 (reason 40)
Nov 14 15:51:21 TE kernel: 881.838484 [1619] nm_rxsync_prologue        kring error: hwcur 321 rcur 318 hwtail 321 head 318 cur 318 tail 321
Nov 14 15:51:21 TE kernel: 881.838494 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838497 [1660] netmap_ring_reinit        bad index at slot 0 idx 15362 len 106 
Nov 14 15:51:21 TE kernel: 881.838499 [1660] netmap_ring_reinit        bad index at slot 1 idx 15363 len 90 
Nov 14 15:51:21 TE kernel: 881.838502 [1660] netmap_ring_reinit        bad index at slot 2 idx 15364 len 102 
Nov 14 15:51:21 TE kernel: 881.838504 [1660] netmap_ring_reinit        bad index at slot 3 idx 15365 len 174 
Nov 14 15:51:21 TE kernel: 881.838507 [1660] netmap_ring_reinit        bad index at slot 4 idx 15366 len 102 
Nov 14 15:51:21 TE kernel: 881.838550 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838565 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838578 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838603 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838629 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838649 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838661 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838682 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.838705 [1644] netmap_ring_reinit        called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.839553 [1619] nm_rxsync_prologue        kring error: hwcur 360 rcur 359 hwtail 360 head 359 cur 359 tail 360
Nov 14 15:51:22 TE kernel: 882.851007 [1644] netmap_ring_reinit        called for eth2 RX12
Nov 14 15:51:22 TE kernel: 882.851012 [1660] netmap_ring_reinit        bad index at slot 0 idx 0 len 0 
Nov 14 15:51:22 TE kernel: 882.851016 [1660] netmap_ring_reinit        bad index at slot 1 idx 0 len 0 
Nov 14 15:51:22 TE kernel: 882.851020 [1660] netmap_ring_reinit        bad index at slot 2 idx 0 len 0 
Nov 14 15:51:22 TE kernel: 882.851024 [1660] netmap_ring_reinit        bad index at slot 3 idx 0 len 0 
Nov 14 15:51:22 TE kernel: 882.851027 [1660] netmap_ring_reinit        bad index at slot 4 idx 0 len 0

**Comment by wtyvvv** [comment]
when i use ctrl+c  kill program,but kill is crash.


77.000404 main_thread [1446] 819450 pps (820372 pkts in 1001125 usec)
078.001655 main_thread [1446] 815382 pps (816401 pkts in 1001250 usec)
079.002773 main_thread [1446] 819013 pps (819929 pkts in 1001119 usec)
080.004769 main_thread [1446] 821405 pps (823044 pkts in 1001995 usec)
081.005993 main_thread [1446] 819706 pps (820709 pkts in 1001224 usec)
082.007065 main_thread [1446] 805191 pps (806054 pkts in 1001072 usec)
083.008201 main_thread [1446] 818713 pps (819643 pkts in 1001136 usec)
084.008868 main_thread [1446] 812015 pps (812557 pkts in 1000667 usec)
085.010119 main_thread [1446] 791255 pps (792246 pkts in 1001252 usec)
086.011190 main_thread [1446] 798233 pps (799088 pkts in 1001071 usec)
^C086.036785 main_thread [1446] 785028 pps (20092 pkts in 25594 usec)
087.038069 main_thread [1446] 48 pps (48 pkts in 1001284 usec)
Received 24192138 packets, in 29.72 seconds.
Speed: 813.93 Kpps
Killed
[root@TE examples]# 
Message from syslogd@TE at Nov 14 16:28:07 ...
 kernel:Oops: 0000 [#1] SMP 

Message from syslogd@TE at Nov 14 16:28:07 ...
 kernel:Stack:

Message from syslogd@TE at Nov 14 16:28:07 ...
 kernel:Call Trace:

Message from syslogd@TE at Nov 14 16:28:07 ...
 kernel:Code: ff ff 48 8b 75 d0 48 89 df e8 8d fd ff ff eb ba 66 66 2e 0f 1f 84 00 00 00 00 00 55 48 89 e5 41 54 49 89 d4 53 48 89 f3 eb 3a 90 

Message from syslogd@TE at Nov 14 16:28:07 ...
 kernel:CR2: 0000000000000010

**Comment by vmaffione** [comment]
There is no kernel crash here, and the options for pkt-gen are wrong. It should be

````
$ ./pkt-gen -i eth2 -f rx
````

**Comment by wtyvvv** [comment]
@vmaffione  
yes, i use ./pkt-gen -i eth2 -f rx,sorry i always type wrong.

`Nov 14 15:51:21 TE kernel: 881.838705 [1644] netmap_ring_reinit called for eth2 RX13
Nov 14 15:51:21 TE kernel: 881.839553 [1619] nm_rxsync_prologue kring error: hwcur 360 rcur 359 hwtail 360 head 359 cur 359 tail 360
Nov 14 15:51:22 TE kernel: 882.851007 [1644] netmap_ring_reinit called for eth2 RX12
Nov 14 15:51:22 TE kernel: 882.851012 [1660] netmap_ring_reinit bad index at slot 0 idx 0 len 0
Nov 14 15:51:22 TE kernel: 882.851016 [1660] netmap_ring_reinit bad index at slot 1 idx 0 len 0
Nov 14 15:51:22 TE kernel: 882.851020 [1660] netmap_ring_reinit bad index at slot 2 idx 0 len 0
Nov 14 15:51:22 TE kernel: 882.851024 [1660] netmap_ring_reinit bad index at slot 3 idx 0 len 0
Nov 14 15:51:22 TE kernel: 882.851027 [1660] netmap_ring_reinit bad index at slot 4 idx 0 len 0 `

here is kernel error log

**Comment by wtyvvv** [comment]
and here  kernel crash when i killed pkt-gen

> 086.011190 main_thread [1446] 798233 pps (799088 pkts in 1001071 usec)
^C086.036785 main_thread [1446] 785028 pps (20092 pkts in 25594 usec)
087.038069 main_thread [1446] 48 pps (48 pkts in 1001284 usec)
Received 24192138 packets, in 29.72 seconds.
Speed: 813.93 Kpps
Killed
[root@TE examples]#
Message from syslogd@TE at Nov 14 16:28:07 ...
kernel:Oops: 0000 [#1] SMP

Message from syslogd@TE at Nov 14 16:28:07 ...
kernel:Stack:

Message from syslogd@TE at Nov 14 16:28:07 ...
kernel:Call Trace:

Message from syslogd@TE at Nov 14 16:28:07 ...
kernel:Code: ff ff 48 8b 75 d0 48 89 df e8 8d fd ff ff eb ba 66 66 2e 0f 1f 84 00 00 00 00 00 55 48 89 e5 41 54 49 89 d4 53 48 89 f3 eb 3a 90

Message from syslogd@TE at Nov 14 16:28:07 ...
kernel:CR2: 0000000000000010

**Comment by vmaffione** [comment]
I don't see the kernel stack dump.
In any case, please try to add `-w 10` option to pkt-gen, to wait for the link to come up.

**Comment by wtyvvv** [comment]
I forgot to say that I used the version is netmap v11.1,

Because I use the master version of the Linux 3.19 in the following compile but I would like to ask what is wrong? 

**WARNING: "split_page" [/root/netmap-master/netmap.ko] undefined!**
 
netmap: Unknown symbol split_page (err 0)
Thanks very much

**Comment by vmaffione** [comment]
That problem should be solved now. Try to use the current netmap master, do a
````
$./configure
$ make
````
in the root directory (and not in the LINUX directory).

**Comment by wtyvvv** [comment]
sorry ,also this error.
  Building modules, stage 2.
  MODPOST 2 modules
WARNING: "split_page" [/root/netmap-master/netmap.ko] undefined!

yes in the netmap-master directory,and not in the LINUX directory

**Comment by vmaffione** [comment]
Can you try out the old build system? Run ./configure --kernel-sources=/path/to/sources/of/running/kernel and make inside LINUX/.
It may be that the official intel drivers do not support your kernel.

**Comment by vmaffione** [comment]
Can you please try with the updated code?
