### ISSUE TITLE
Cannot allocate RX_ring

### ISSUE THREAD

**Issue by alandtsang** [luigirizzo/netmap#251]
Hello all,
I use netmap with my program, but failed today.

$ tail -f /var/log/message
Nov 17 14:28:00 data2 kernel: 080.734809 [ 840]  netmap_obj_malloc         no more netmap_ring objects
Nov 17 14:28:00 data2 kernel: 080.734815 [1741] netmap_mem2_rings_create  Cannot allocate RX_ring

$ free -g
             total       used       free     shared    buffers     cached
Mem:           252        239         12          0          1        200
-/+ buffers/cache:         37        214
Swap:            3          0          3

**Comment by vmaffione** [comment]
You ran out of rings. You should be able to increase the number of rings by increasing the "ring_num" netmap module parameter (e.g. when you load the module).

netmap memory is preallocated, so the information shown by "free -g" is not useful here. You can have plenty of free memory, but if you don't tell netmap to use it, it won't.

**Comment by alandtsang** [comment]
My environment:

- RHEL 6.5 x86_64 
- kernel 2.6.32-437

It doesn't support ethtool to set the number of rings.
Is there other solutions ?

**Comment by vmaffione** [comment]
Maybe there is a misunderstanding, I was not talking about the physical rings in the card, but the netmap rings, which are data structures only used by the software. You can increase the number of netmap rings (default 200) using:
````
  # modprobe netmap ring_num=1000
````

**Comment by alandtsang** [comment]
OK. Thank you very much
