### ISSUE TITLE
netmap with ESXI 6.x 

### ISSUE THREAD

**Issue by ameagle** [luigirizzo/netmap#253]
Is it possible to increase RX and TX queues in VM (Frebsd 10.3) on HyperV ESXI 6.x?

I enabled PCI-Passthrough Intel 82599 10Gigabit NIC on ESXI 6.0. 
But netmap uses just 1 TX and 1 RX 
root@freebsd10.3:/usr/home/ # dmesg |grep ix1
ix1: <Intel(R) PRO/10GbE PCI-Express Network Driver, Version - 3.1.13-k> port 0x4020-0x403f mem 0xeb980000-0xeb9fffff,0xebaf8000-0xebafbfff irq 19 at device 0.1 on pci3
ix1: Using an MSI interrupt
ix1: Ethernet address: 91:e2:b9:92:5e:9
ix1: PCI Express Bus: Speed 5.0GT/s Unknown
**ix1: netmap queues/slots: TX 1/2048, RX 1/2048**
ix1: link state changed to UP

Used this article, but it doesn't help. https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1004278

Is there any another HyperV, working with netmap well?

**Comment by vmaffione** [comment]
Question is, how many RX/TX queues does FreeBSD guest see, using standard tools (i.e. ignoring netmap)? If PCI-passthrough is working correctly, there should not be any difference between a VM and a physical machine, in theory.

We usually use QEMU on Linux as an hypervisor (). bhyve support is coming, but it is yet to be merged upstream in FreeBSD.

**Comment by vmaffione** [comment]
You can use the netmap_generic_rings sysctl on freebsd to change the number of queues
