### ISSUE TITLE
Failed build in LEDE/OpenWrt

### ISSUE THREAD

**Issue by davidzodelin** [luigirizzo/netmap#260]
I'm trying to compile Netmap for LEDE / OpenWrt. The kernel I am using is version 4.4.38, but at the time of compiling the netmap.ko module and the utilities, the compilation of the same fails. I have noticed that the Makefile file for OpenWrt takes about 2 years without being modified. Someone could guide me. Please.

  Thanks in advance, David Fernandez.

**Comment by vmaffione** [comment]
Hi, have you tried this patch https://github.com/luigirizzo/netmap/issues/36 ?

**Comment by davidzodelin** [comment]
Hi vmaffio, for my is impossible download and apply this patch, storage.googleapis.com not avaible for Cuba. I will try to use a vpn and apply the patch to see the result. 

 Even manage to touch the Makefile for OpenWrt a little and at least download the sources of the repository, but when it starts to compile it fails. I will try this patch and upload the results. 

 Thanks for the reply.

**Comment by vmaffione** [comment]
Here you are:
````
diff --git a/LINUX/openwrt/netmap/Makefile b/LINUX/openwrt/netmap/Makefile
index af445e4..c95d3ea 100644
--- a/LINUX/openwrt/netmap/Makefile
+++ b/LINUX/openwrt/netmap/Makefile
@@ -9,14 +9,14 @@ include $(TOPDIR)/rules.mk
 include $(INCLUDE_DIR)/kernel.mk
 
 PKG_NAME:=netmap
-PKG_VERSION:=1
+PKG_VERSION:=HEAD
 PKG_RELEASE:=$(PKG_SOURCE_VERSION)
 
-PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.xz
+PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
-PKG_SOURCE_URL:=/home/giuseppe/Compile/netmap-git
+PKG_SOURCE_URL:=https://code.google.com/p/netmap/
 PKG_SOURCE_PROTO:=git
-PKG_SOURCE_VERSION:=1ac2b984c13489c893ca7448d1e024b67526afbf
+PKG_SOURCE_VERSION:=HEAD
 PKG_MAINTAINER:=Giuseppe Lettieri <g.lettieri@iet.unipi.it>
 
 include $(INCLUDE_DIR)/package.mk
@@ -25,8 +25,8 @@ define KernelPackage/netmap
   TITLE:=Netmap
   SECTION:=kernel
   SUBMENU:=Other modules
-  FILES:=$(PKG_BUILD_DIR)/LINUX/netmap_lin.ko
-  AUTOLOAD:=$(call AutoLoad,80,netmap_lin)
+  FILES:=$(PKG_BUILD_DIR)/LINUX/netmap.ko
+  AUTOLOAD:=$(call AutoLoad,80,netmap)
 endef
 
 define KernelPackage/r8169-netmap
````

Can you also point at the instructions for compiling OpenWRT?

**Comment by vmaffione** [comment]
Obviously, you need to replace PKG_SOURCE_URL with the github url

**Comment by davidzodelin** [comment]
Hello, I have tried again with the Makefile you published and the same result, I failed to compile all the modules I selected from Netmap. The steps I follow are to select the Netmap modules and start compiling the LEDE Firmware. I do not know if it will have to patch before the kernel? Any ideas?

**Comment by vmaffione** [comment]
I've never worked with OpenWrt or LEDE, so the first step is to understand how the whole build system works. Integrating netmap correctly would be a later step.
What instructions are you following? Maybe these ones https://wiki.openwrt.org/doc/howto/build ?

**Comment by davidzodelin** [comment]
Hi, I will try to patch the kernel before starting to compile the firmware. I will comment on the result, but I think maybe the compilation error is due to the lack of any steps.

**Comment by davidzodelin** [comment]
Ok, the problem is with apps of Netmap. I upload the log compile. Thanks.
