### ISSUE TITLE
Netmap is not respecting /sys/module/netmap/parameters/ring_size parameter anymore

### ISSUE THREAD

**Issue by potakhov** [luigirizzo/netmap#267]
I have established app that is running with Netmap from 09/22/2016 (commit 6b1a95ed7b202f22bf4ee518ea494286601ae258). Part of the initialization for the app includes setting NIC ring buffer sizes to `ethtool -G eth0 rx 4096 tx 4096` and setting `/sys/module/netmap/parameters/ring_size` parameter to `70000` in order to be able to allocate requested buffers.
However after updating with the recent code from 01/09/2017 (commit 6d6c59f68bc90cae498d6a9b3686b24292994e30) Netmap now fails on initialization producing following error
```
Jan 10 15:32:41 sr-3 kernel: 361.523062 [ 756] netmap_update_config      configuration changed (but fine)
Jan 10 15:32:41 sr-3 kernel: 361.641297 [ 847] netmap_obj_malloc         netmap_ring request size 65792 too large
Jan 10 15:32:41 sr-3 kernel: 361.641788 [1705] netmap_mem2_rings_create  Cannot allocate RX_ring
```
even when ring_size is set to 70000 before Netmap device initialization. I was able to patch that changing default values for the ring size at sys/dev/netmap/netmap_mem2.c however would like to understand what was changed and how do I configure it without changing the source.

Another part of the issue is that when nm_open(netmap:eth0) fails and returns nullptr (because of being unable to allocate the ring) it doesn't free the device and it becomes impossible to remove the ixgbe module as it is indicating usage count 1 and kernel keeps waiting on it indefinitely.

OS: CentOS 7.3; kernel 3.10.0-514.2.2.el7.x86_64; ixgbe 4.5.4

**Comment by giuseppelettieri** [comment]
Yes, there was a regression introduced by a partial merge. May you please try with the latest commit?

**Comment by potakhov** [comment]
Yes, this fixed the issue. Thank you!
