### ISSUE TITLE
Linux ethtool disable offloading recommendation

### ISSUE THREAD

**Issue by john-gress** [luigirizzo/netmap#268]
Looking at the LINUX/README, I noticed this new section:

```
* netmap does not program the NICs to perform offloadings such as TSO,
  UFO, RX/TX checksum offloadings, etc. As a result, in order to let
  netmap applications correctly interact with the host rings, you need
  to disable these offloadings

      # ethtool -K eth0 tx off rx off gso off tso off gro off lro off
```

If I am using the NS_MOREFRAG flag as discussed here, https://github.com/luigirizzo/netmap/issues/110, do I still need to disable the offloadings?

**Comment by vmaffione** [comment]
Yes, it's unrelated. Disabling the offloading affects the interaction between netmap and the host stack. If you don't disable those, the host stack will give netmap unchecksummed (and possibly > 2KB) packets, and so netmap would drop those, because it does not know how to handle them.

**Comment by john-gress** [comment]
Thanks. Appreciate the support.

**Comment by vmaffione** [comment]
Yeah, in particular disabling the offloadings is not related to the fact that you may use the NS_MOREFRAG flag with your hardware rings or the rings of a VALE port.
