### ISSUE TITLE
crash upon packet arrival at a netmap mode ovs internal port

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#270]
This test was done on a ubuntu server. I used ovs-vsctl to create a simple bridge, and ovs-vsctl add-port to add an internal port to the bridge. I launched an application to listen on the internal port, and immediately I lost connection to the server.

I did another test prior to this one, on a ubuntu desktop, I created a simple multi switch topology(with two hosts h1 and h2). And by bring an internal port of one of the switches into netmap mode, h1 can ping h2, but TCP connections such as iperf does not work. Using tcpdump, I observed that the packet from h1 reached h2, but was never delivered to the TCP state machine(because there was no handshake response). It seems that netmap module was somehow interfering with the network stack.

It is the latest netmap build, I tried both with kernel source and without kernel source(--no-drivers). Also tried setting generic_txqdisc and admode. Neither solved the problem.

**Comment by vmaffione** [comment]
For the first problem: the OVS patch it's experimental, and may be the root of the problem. In any case, if you think your server crashed, you should redo the same experiment on a local machine, so that you can get the crash stack strace at least.

For the second problem: it seems that you didn't disable the offloadings, as described in LINUX/README.

**Comment by Linerd** [comment]
@vmaffione I didn't apply the OVS patch in this set up, because last time I tested the patch doesn't work with mininet. I was trying to involve any few experimental code as possible.

The second problem I think is similar to the first problem. I think the connection was dropped because of the same issue. I tried the following on the server and it failed:
1. ovs-vsctl add-br br0
2. ovs-vsctl add-port br0 vp -- set Interface vp type=internal
3. pkt-gen -i vp

and it crashed

**Comment by vmaffione** [comment]
So you are saying that in your setup you are using the regular unpatched OVS, and launching pkt-gen on an internal port make the host crash?

**Comment by Linerd** [comment]
@vmaffione exactly. Or maybe not a crash, just that packets destined for the network stack were somehow "sucked" away, that is my suspicion. I am now doing it in a VM to see if it is a crash or network problem

**Comment by vmaffione** [comment]
You wrote "crash", I assumed it was kernel crash. Am I wrong? What crashed exactly?
Did you disable the offloadings on vp?

**Comment by Linerd** [comment]
@vmaffione I repeated the same experiment in a VM, this time without problem(even without disabling the offloaings). The server has linux 3.13 kernel, the VM has 4.x. 

The server crashed, the kernel log shows
device br0 entered promiscuous mode
device vp entered promiscuous mode
and then a lot of error codes unreadable

**Comment by vmaffione** [comment]
On my machine with Linux 4.8 the thing is working correctly. What is the kernel log of the crashing 3.13?

**Comment by Linerd** [comment]
@vmaffione as shown above, after the sentence 'device vp entered promiscuous mode', the log cuts off, the next entry is after the restart of the machine...

**Comment by vmaffione** [comment]
From your description it seems a 3.13-specific problem. One thing we may do is to compare the netmap_linux_config.h file generated by the netmap build in the two cases: 3.13 (crashing) and 4.X (working ok). Of course the same ./configure command line must be used.

Can you generate these files and attach the output of
````
$ diff -pu netmap-3.13/netmap_linux_config.h netmap-4.X/netmap_linux_config.h
````
?

**Comment by Linerd** [comment]
@vmaffione 
--- netmap_linux_config.h	2017-01-18 00:50:26.371039065 -0500 (3.13)
+++ ../netmap_linux_config.h	2017-01-19 10:53:04.939893368 -0500 (4.x)
@@ -1,6 +1,28 @@
   	#ifndef NETMAP_LINUX_CONFIG_H
   	#define NETMAP_LINUX_CONFIG_H

+		#define NETMAP_LINUX_I40E_PTR_ARRAY
+
+		#define NETMAP_LINUX_VIRTIO_NOTIFY
+
+		#define NETMAP_LINUX_VIRTIO_MULTI_QUEUE
+
+		#define NETMAP_LINUX_VIRTIO_FUNCTIONS
+
+		#define NETMAP_LINUX_VIRTIO_FREE_PAGES
+
+		#define NETMAP_LINUX_VIRTIO_GET_VRSIZE
+
+		#define NETMAP_LINUX_VIRTIO_CB_DELAYED
+
+		#define NETMAP_LINUX_IXGBE_PTR_ARRAY
+
+		#define NETMAP_LINUX_IXGBE_DESC 3
+
+		#define NETMAP_LINUX_HAVE_E1000E_EXT_RXDESC
+
+		#define NETMAP_LINUX_HAVE_E1000E_DOWN2
+
 		#define NETMAP_LINUX_PAGE_COUNT _count

 		#define NETMAP_LINUX_HAVE_SKB_CHECKSUM_START_OFFSET
@@ -11,12 +33,20 @@

 		#define NETMAP_LINUX_SKB_ADD_RX_FRAG_6ARGS

+		#define NETMAP_LINUX_HAVE_XMIT_MORE
+
 		#define NETMAP_LINUX_HAVE_ALLOC_SKB_IP_ALIGN

+		#define NETMAP_LINUX_HAVE_NAPI_ALLOC_SKB
+
+		#define NETMAP_LINUX_HAVE_NAPI_COMPLETE_DONE
+
 		#define NETMAP_LINUX_QDISC_CREATE_DFLT_3ARGS

 		#define NETMAP_LINUX_HAVE_NNITD

+		#define NETMAP_LINUX_ALLOC_NETDEV_4ARGS
+
 		#define NETMAP_LINUX_HAVE_ADDR_RANDOM

 		#define NETMAP_LINUX_HAVE_HW_FEATURES

It could also be an OVS problem, since the server is running ovs 2.0.2, which is pretty old. Let me upgrade the ovs and report back.

**Comment by Linerd** [comment]
@vmaffione I tried installing OVS 2.6.1, the pkt-gen still crashes at "wait 2 secs for phy reset."

**Comment by Linerd** [comment]
@vmaffione now I can reproduce this problem in a VM with kernel 4.4.0-59. 
create a bridge
create an internal port
listen on that port via netmap
when packet arrives at the port, the vm crashes
(latest netmap commit)
