### ISSUE TITLE
Multithread app with no performance gain

### ISSUE THREAD

**Issue by alexhebra** [luigirizzo/netmap#271]
Hi,

I need some help and a piece of advice. I spent last months developing a route multithread app to have a better performance.

I'm using NR_REG_ONE_NIC and mapping each ring to a thread and each thread to a CPU using setaffinity().

I also mapped for instance, if incoming ring is 0 outgoing ring will be ring 0 as well.

My router test server has: 8 cores and Intel 10G 2 ports with 8 queues, but i configured on FreeBSD to use only 4 queues (hw.ix.num_queues=4), because i achieved a better performance using 4. 

When i start the application i can see it's working as multithread. Started 8 threads, 4 for each NIC. :

4057 root          23    0   700M  3636K kqread  1   0:00   0.59% netmap-rt{netmap-rt}
 4057 root          20    0   700M  3636K select  3   0:00   0.59% netmap-rt{ix0-3}
 4057 root          21    0   700M  3636K select  7   0:00   0.59% netmap-rt{ix1-3}
 4057 root          23    0   700M  3636K select  0   0:00   0.59% netmap-rt{ix0-0}
 4057 root          23    0   700M  3636K select  2   0:00   0.59% netmap-rt{ix0-2}
 4057 root          23    0   700M  3636K select  4   0:00   0.59% netmap-rt{ix1-0}
 4057 root          23    0   700M  3636K select  6   0:00   0.59% netmap-rt{ix1-2}
 4057 root          23    0   700M  3636K select  1   0:00   0.59% netmap-rt{ix0-1}
 4057 root          23    0   700M  3636K select  5   0:00   0.59% netmap-rt{ix1-1}

I have this scenario:

Server1 <--->  Netmap router <---> Server2 

When i run pkt-gen on Server1 (tx) and Server2 (rx) i got only 1.5Mpps. It is as same as result when i was using monothread app. Looks like i didn't reach full NIC throughput. 

Any help is welcome. Thanks.

**Comment by vmaffione** [comment]
1.5Mpps at what packet size? Minimum?
If yes, is  server1 able to transmit at ~14 Mpps with pkt-gen?
If yes, if you use pkt-gen in receive mode on "Netmap router" (e.g. pkt-gen -i ix0 -f rx) are you able to receive ~14 Mpps?

**Comment by alexhebra** [comment]
Hi @vmaffione 

Yes, minimum.

Yes, Server1 is able to transmit at 14Mpps and router is able to receive at 14Mpps with pkt-gen.

Look:

router# /usr/local/proapps/bin/pkt-gen -i ix1 -f rx
451.905166 main [2274] interface is ix1
451.905206 main [2397] running on 1 cpus (have 8)
451.905303 extract_ip_range [369] range is 10.0.0.1:0 to 10.0.0.1:0
451.905318 extract_ip_range [369] range is 10.1.0.1:0 to 10.1.0.1:0
452.019232 main [2498] mapped 334980KB at 0x801c00000
Receiving from netmap:ix1: 4 queues, 1 threads and 1 cpus.
452.019311 main [2597] Wait 2 secs for phy reset
454.118114 main [2599] Ready...
454.118348 receiver_body [1383] reading from netmap:ix1 fd 3 main_fd 3
455.181619 receiver_body [1390] waiting for initial packets, poll returns 0 0
455.181619 main_thread [2056] 0.000 pps (0.000 pkts 0.000 bps in 1063289 usec) 0.00 avg_batch 0 min_space
456.194732 receiver_body [1390] waiting for initial packets, poll returns 0 0
456.194828 main_thread [2056] 0.000 pps (0.000 pkts 0.000 bps in 1013209 usec) 0.00 avg_batch 99999 min_space
457.211126 receiver_body [1390] waiting for initial packets, poll returns 0 0
457.211125 main_thread [2056] 0.000 pps (0.000 pkts 0.000 bps in 1016297 usec) 0.00 avg_batch 99999 min_space
458.274617 receiver_body [1390] waiting for initial packets, poll returns 0 0
458.274616 main_thread [2056] 0.000 pps (0.000 pkts 0.000 bps in 1063491 usec) 0.00 avg_batch 99999 min_space
459.281197 receiver_body [1390] waiting for initial packets, poll returns 0 0
459.281358 main_thread [2056] 0.000 pps (0.000 pkts 0.000 bps in 1006743 usec) 0.00 avg_batch 99999 min_space
460.283116 main_thread [2056] 1.824 Mpps (1.827 Mpkts 877.092 Mbps in 1001757 usec) 71.73 avg_batch 513 min_space
461.345377 main_thread [2056] 14.882 Mpps (15.808 Mpkts 7.588 Gbps in 1062261 usec) 70.48 avg_batch 1564 min_space
462.376616 main_thread [2056] 14.882 Mpps (15.347 Mpkts 7.366 Gbps in 1031239 usec) 70.49 avg_batch 744 min_space
463.412675 main_thread [2056] 14.882 Mpps (15.418 Mpkts 7.401 Gbps in 1036060 usec) 70.58 avg_batch 1676 min_space
464.475606 main_thread [2056] 14.882 Mpps (15.818 Mpkts 7.593 Gbps in 1062931 usec) 70.57 avg_batch 1800 min_space
465.538607 main_thread [2056] 14.882 Mpps (15.819 Mpkts 7.593 Gbps in 1063001 usec) 70.39 avg_batch 1616 min_space

server1# /usr/local/proapps/bin/pkt-gen -i ix0 -f tx 
485.243706 main [2568] interface is ix0
485.243745 main [2691] running on 1 cpus (have 8)
485.243868 extract_ip_range [465] range is 10.0.0.1:1234 to 10.0.0.1:1234
485.243888 extract_ip_range [465] range is 10.1.0.1:1234 to 10.1.0.1:1234
485.360802 main [2786] mapped 334980KB at 0x801c00000
Sending on netmap:ix0: 8 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
485.360867 main [2883] Sending 512 packets every  0.000000000 s
485.360910 start_threads [2251] Wait 2 secs for phy reset
487.416140 start_threads [2253] Ready...
487.416354 sender_body [1444] start, fd 3 main_fd 3
487.454066 sender_body [1526] drop copy
488.426142 main_thread [2341] 14.437 Mpps (14.579 Mpkts 6.998 Gbps in 1009800 usec) 432.24 avg_batch 0 min_space
489.428016 main_thread [2341] 14.875 Mpps (14.903 Mpkts 7.153 Gbps in 1001879 usec) 430.24 avg_batch 99999 min_space
490.428137 main_thread [2341] 14.886 Mpps (14.888 Mpkts 7.146 Gbps in 1000122 usec) 429.61 avg_batch 99999 min_space
491.429137 main_thread [2341] 14.881 Mpps (14.896 Mpkts 7.150 Gbps in 1001000 usec) 430.61 avg_batch 99999 min_space
492.430137 main_thread [2341] 14.878 Mpps (14.893 Mpkts 7.149 Gbps in 1000999 usec) 430.64 avg_batch 99999 min_space

**Comment by vmaffione** [comment]
Ok, so netmap support on NICs is ok.
Have you checked that traffic is equally distributed on the RX rings of "Netmap Router"?
If you use that pkt-gen command "pkt-gen -i ix0 -f tx", pkt-gen is going to generate UDP packets that are all the same. As a consequence, it's easy that they end up in the same RX ring on the router, so only one thread is actually used. This would explain why you don't see performance improvement.

**Comment by alexhebra** [comment]
@vmaffione 

Checking using top command it's always on same ring. It only change when i reboot the route server.

If all packets are the same and i didn't realize any improvement, how can i test if performance has improved? 

I tried to use pkt-gen with range src flag:

/usr/local/proapps/bin/pkt-gen-u -U -i ix0 -f tx -s 10.10.10.2-10.10.10.6 -d 192.168.0.2 -D 00:90:0b:4e:e0:5b

After this i can see more threads/ring consuming. But performance is still bad (about 1.5Mpps):

18170 root          52    0   720M 37100K select  4   0:20  63.28% netmap-rt{ix1-0}
18170 root          90    0   720M 37100K CPU6    6   0:18  58.15% netmap-rt{ix1-2}
18170 root          52    0   720M 37100K select  5   0:17  52.78% netmap-rt{ix1-1}
18170 root          52    0   720M 37100K select  7   0:14  43.16% netmap-rt{ix1-3}
18170 root         -92    0   720M 37100K CPU2    2   0:13  39.89% netmap-rt{ix0-2}
18170 root         -92    0   720M 37100K select  3   0:09  30.66% netmap-rt{ix0-3}
18170 root         -92    0   720M 37100K select  1   0:07  21.78% netmap-rt{ix0-1}

**Comment by vmaffione** [comment]
I'm not sure I got your question. You only can have performance improvement if you manage to someway distribute the work across different threads.in your case a prerequisite is that traffic arrives on different rx rings,which is reasonable for real world traffic. you can simulate that with pkt-gen and address/port ranges. This said, I don't know how your application is designed, in terms of shared data structures,locks and so on. Performance will heavily depend on those. If your custom processing has bottlenecks,you'll have to remove it. In the meanwhile I'll close this issue, it is not a netmap issue.
