### ISSUE TITLE
the OVS patch fails with vxlan ports

### ISSUE THREAD

**Issue by Linerd** [luigirizzo/netmap#272]
I used the v2.6.1 branch of OVS and the latest build of netmap.

Here is what I did:
sudo ovs-vsctl add-br br0
sudo ovs-vsctl add-port br0 vi0 -- set Interface vi0 type=vxlan options:remote_ip=10.0.0.11

Here is the error:
ovs-vsctl: Error detected while setting up 'vi0'.  See ovs-vswitchd log for details

vswitch.log shows: 
2017-01-28T22:30:51.170Z|00021|dpif|WARN|system@ovs-system: failed to add vi0 as port: Invalid argument
2017-01-28T22:30:51.171Z|00022|dpif|WARN|system@ovs-system: failed to add vi0 as port: File exists
...

kernel log shows:
[ 1965.136079] 985.056445 [ 114] ovs_netdev_link           vxlan_sys_4789: netmap generic adapter incompatible with OVS

**Comment by Linerd** [comment]
@vmaffione and building the same OVS v2.6.1 on the same kernel without the netmap patch doesn't lead to vxlan port errors.

**Comment by vmaffione** [comment]
I'm not the author of the patch,but this seems to mean that vxlan vale ports are not supported in netmap mode. The patch is experimental and incomplete, help is appreciated. In any case You may try to ask the author..

**Comment by Linerd** [comment]
@vmaffione could you please kindly point me to the author of patch? I only found the committer of the patch, didn't see any author information...

**Comment by Linerd** [comment]
@micchie the v2.6.1 patch seems to fail when adding a vxlan port to the ovs bridge. 

@vmaffione BTW, just to resolve a long lasting problem that I am facing: I am building a VM topology with VXLAN tunnel connections. In each VM there is an OVS bridge(patched or unpatched, I will discuss the difference later); on the bridge there are a few vxlan ports, and two internal ports for my Netmap application. The Netmap application has similar functionality as the bridge example, namely forwarding from one interface to another. The "physical interface" of the VM is not attached to the bridge.

Here is what I found:
1. When the bridge is not patched, I can create the vxlan ports without errors, and I can launch the netmap application to listen on the internal ports. When but traffic arrives at the "physical interface", the VM crashes. I repeated the same experiment without netmap, everything works fine.
2. When the bridge is patched, as shown in the very beginning, I can't even add the vxlan ports, so I haven't proceeded from that to see if the crashing problem still exists.

**Comment by micchie** [comment]
Current OVS patch doesn't support ports where packets travel to the host stack, including VXLAN. Sorry. But your patch is always welcome.

**Comment by greatbn** [comment]
Hi @micchie .How to patch openvswitch 2.6.1 with patch file. I have an error when run command: 
`./configure --with-netmap=/root/netmap-11.3` in openvswitch source

```
configure: WARNING: unrecognized options: --with-netmap
```

**Comment by micchie** [comment]
Are you sure that you have applied that patch to the entire OVS 2.6.1 source tree?
Then you must see lines with AC_ARG_WITH([netmap] and so on in acinclude.m4, for example.

**Comment by greatbn** [comment]
@micchie  I'm wrong. I have run boot.sh first. Thanks.

**Comment by greatbn** [comment]
Hi @micchie  I have a question. 
I want to use netmap/ovs to accelerated network communication between two physical host. 
I built netmap,  openvswitch with netmap module. 
I added two vale ports on two hosts with command 
```
vale-ctl -n vlan300
```
And then I added this port to bridge 
```
ovs-vsctl add-port br0 vlan300 tag=300
```
Then I set IP for `vlan300`  port
```
ip addr add 10.1.0.119/24 dev vlan300
ip link set dev vlan300 up
```
Same on second host. 

But I can't ping between them. Can you help me?
