### ISSUE TITLE
mismanging tx/rx queues?

### ISSUE THREAD

**Issue by kazdingo** [luigirizzo/netmap#273]
Using python netmap library, have total 3 queues, ixgbe driver
Running 3 processes:
* Process 1 is using TX only on ring 2 and is open as "netmap:eth0-2"
* Process 2 is using TX only on ring 1 and is open as "netmap:eth0-1"
* Process 3 is reading all data and sends data on TX ring 0. 
   * TX logic with open descriptor as "netmap:eth0-0" 
   * RX logic with descriptor that is open as "netmap:eth0" (Because it collects data from all 3 RX queues) and **netmap.NoTxPoll** flag so that polling won't trigger sending for other processes

What I see is that without process 3, process 1 and 2 outputs each 10 kpps (Limited purposefully). However, when code on process 3 runs, process 1 begins experiencing strange behavior: it still has enough buffer to output 10kpps (and thinks it does), but the receiving end sees only ~2.5kpps.  

Process 1 and Process 3  don't share any data except one of them is using **transmit_rings** and other one **receive_rings** of the same ring id

Why can this happen?

**Comment by vmaffione** [comment]
Are you using the emulated adapter or the native one? Is the problem showing up with both?
At least with the emulated adapter you can use something like `ethtool -S eth0 | grep tx_packets` to monitor what is the real traffic on each TX queue.

In any case, You should use the recent netmap features to open only what is really necessary.
From your description, process 1 should open "netmap:eth0-1/T", process 2 should open "netmap:eth0-2/T", process 3 should open "netmap:eth0-0/T" for TX logic and "netmap:eth0/R" for RX logic.

**Comment by kazdingo** [comment]
I added the /T and /R to the processes but the behavior still occurs.

How can I know what adapter I'm using? it's the ixgbe driver that was compiled together with netmap. The tx_packets counter hadn't increased by what I would expect it to (Few thousand of packets were sent, but it was increased by 4. )

**Comment by vmaffione** [comment]
If using the native adapter the counters are not updated.
To force the emulated adapter you can set the "admode" module parameter to 2 (see also netmap man page). Then you need to restart all your netmap applications.

**Comment by kazdingo** [comment]
It actually looks like the forcing /T and /R fixed the problem.

Thank you

**Comment by vmaffione** [comment]
I think the problem is still there, but maybe it's just an issue of your code or setup environment or an issue of the python library.
Let us know if you find more issues with python.
