### ISSUE TITLE
Traffic monitoring / counting for VALE ports.

### ISSUE THREAD

**Issue by ArchyCho** [luigirizzo/netmap#274]
Sorry for my question maybe stupid .

Is there any way to show the traffic of different VALE ports , 
whatever real time monitoring or counting ? (ie: MRTG / NLOAD ).

Thanks for advise.

**Comment by vmaffione** [comment]
There are currently no counters, but you can use monitors port and zerocopy monitor ports to transparently see what happens on a VALE port, e.g. like tcpdump.

For instance you can use `pkt-gen -i valeX:Y/t` to read what is being transmitted on valeX:Y. Check sys/net/netmap_user.h for the documentation of nm_open().

**Comment by ArchyCho** [comment]
I found the program ifstat , it shows traffic on FreeBSD but could not read the traffic on Linux when the interface at "netmap mode".

**Comment by vmaffione** [comment]
Yes, netmap does not take counters for performance reasons. Your netmap application is supposed to accomplish this task
