### ISSUE TITLE
RHEL 7 netmap issue for BRO 

### ISSUE THREAD

**Issue by ade5hmukh** [luigirizzo/netmap#275]
Hello guys, 

I am new to netmap and please excuse me and my ignorance. 
I am trying to configure netmap on two ixgbe interfaces on my RHEL 7 machines to load balance the traffic to BRO-workers.

However, when I am trying to load balance on the network interface I get the following error. It seems like kernel is not loading the netmap module. Please guide me if possible on this issue: 

[root@sec-bro04 deshmukh]# /usr/local/bin/lb -i em1 -B 1000 -p Bro:10
683.316970 main [637] interface is em1
683.317046 main [658] requested 1000 extra buffers
683.317281 nm_open [920] cannot open /dev/netmap: No such file or directory em1
683.317292 main [768] cannot open netmap:em1

Here's the process: 

./configure with no errors: 

[root@sec-bro04 netmap-corelight_updates]# ./configure --drivers=ixgbe
**********************************  NOTE   **********************************
*** We are trying to download the original sources for driver
*** ixgbe using the following command:
***
***   test -e /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/ixgbe-4.5.4.tar.gz || wget https://sourceforge.net/projects/e1000/files/ixgbe%20stable/4.5.4/ixgbe-4.5.4.tar.gz -P /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/
***
*** If this fails, please download the above file and put it
*** in /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/, then run configure again.
*****************************************************************************
**********************************  NOTE   **********************************
*** Now running compile tests to adapt the code to your
*** kernel version. Please wait.
*****************************************************************************
kernel directory            /lib/modules/3.10.0-514.6.1.el7.x86_64/build
                            [/usr/src/kernels/3.10.0-514.6.1.el7.x86_64]
kernel sources              /lib/modules/3.10.0-514.6.1.el7.x86_64/build
                            [/usr/src/kernels/3.10.0-514.6.1.el7.x86_64]
linux version               30a00  [3.10]
module file                 netmap.ko

subsystems                  generic monitor pipe vale
apps                        vale-ctl nmreplay tlem lb bridge pkt-gen
native drivers              ixgbe

Contents of the drivers.mak file:
ixgbe@conf := CONFIG_IXGBE
ixgbe@src := tar xf /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/ixgbe-4.5.4.tar.gz && ln -s ixgbe-4.5.4/src ixgbe
ixgbe@patch := patches/intel--ixgbe--4.5.4

[root@sec-bro04 netmap-corelight_updates]# make -j8
test -e /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/ixgbe-4.5.4.tar.gz || wget https://sourceforge.net/projects/e1000/files/ixgbe%20stable/4.5.4/ixgbe-4.5.4.tar.gz -P /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/
tar xf /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/ext-drivers/ixgbe-4.5.4.tar.gz && ln -s ixgbe-4.5.4/src ixgbe
make -C /lib/modules/3.10.0-514.6.1.el7.x86_64/build M=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates EXTRA_CFLAGS='-I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make -C build-apps/vale-ctl SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make -C build-apps/nmreplay SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make -C build-apps/tlem SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make -C build-apps/lb SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make -C build-apps/bridge SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make -C build-apps/pkt-gen SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. CC="cc" LD="ld"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/vale-ctl'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/nmreplay'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/lb'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/tlem'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/vale-ctl'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/nmreplay'
make[1]: Nothing to be done for `all'.
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/include -Wextra   -c -o lb.o /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/lb/lb.c
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/tlem'
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/pkt-gen'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/include -Wextra -DNO_PCAP    /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/pkt-gen/pkt-gen.c  -lpthread -lm -lrt     -o pkt-gen
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/bridge'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/include -Wextra    /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/bridge/bridge.c  -lpthread -lrt     -o bridge
patch --posix --quiet --force -p1 < patches/intel--ixgbe--4.5.4;
/bin/sh: patch: command not found
make: *** [get-ixgbe] Error 127
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/bridge'
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/include -Wextra   -c -o pkt_hash.o /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/lb/pkt_hash.c
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_mem2.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_mbq.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_vale.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_offloadings.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_pipe.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_monitor.o
cc   lb.o pkt_hash.o  -lpthread -lm -lrt         -o lb
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/lb'
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_generic.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_common.o
  CC [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap_linux.o
cc -O2 -pipe -Werror -Wall -Wunused-function -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/include -Wextra -DNO_PCAP -DBUSYWAIT -c /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/pkt-gen/pkt-gen.c -o pkt-gen-b.o
  LD [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap.mod.o
cc   pkt-gen-b.o  -lpthread -lm -lrt     -o pkt-gen-b
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/pkt-gen'
  LD [M]  /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap.ko
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'

[root@sec-bro04 netmap-corelight_updates]# sudo make install
make -C /lib/modules/3.10.0-514.6.1.el7.x86_64/build M=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates CONFIG_NETMAP=m  \
        O_DRIVERS="ixgbe" \
         \
        NETMAP_DRIVER_SUFFIX= \
         \
        modules_install
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
  INSTALL /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/netmap.ko
Can't read private key
  DEPMOD  3.10.0-514.6.1.el7.x86_64
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_unregister_client
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_register_client
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
make -C ixgbe install INSTALL_MOD_PATH= CFLAGS_EXTRA=" -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys -I/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE" NETMAP_DRIVER_SUFFIX= KSRC=/lib/modules/3.10.0-514.6.1.el7.x86_64/build
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/ixgbe-4.5.4/src'
make[2]: Entering directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
Copying manpages...
Installing modules...
make[2]: Entering directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
  INSTALL /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/ixgbe-4.5.4/src/ixgbe.ko
Can't read private key
  DEPMOD  3.10.0-514.6.1.el7.x86_64
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_unregister_client
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_register_client
make[2]: Leaving directory `/usr/src/kernels/3.10.0-514.6.1.el7.x86_64'
Running depmod...
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_unregister_client
depmod: WARNING: /lib/modules/3.10.0-514.6.1.el7.x86_64/kernel/drivers/infiniband/hw/i40iw/i40iw.ko needs unknown symbol i40e_register_client
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/ixgbe-4.5.4/src'
make -C build-apps/vale-ctl install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/vale-ctl'
install -D vale-ctl //usr/local/bin/vale-ctl
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/vale-ctl'
make -C build-apps/nmreplay install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/nmreplay'
install -D nmreplay //usr/local/bin/nmreplay
install -D -m 644 /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/nmreplay/nmreplay.8 //usr/local/share/man/man8/nmreplay.8
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/nmreplay'
make -C build-apps/tlem install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/tlem'
install -D tlem //usr/local/bin/tlem
install -D -m 644 /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/tlem/tlem.8 //usr/local/share/man/man8/tlem.8
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/tlem'
make -C build-apps/lb install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/lb'
install -D lb //usr/local/bin/lb
install -D -m 644 /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../apps/lb/lb.8 //usr/local/share/man/man8/lb.8
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/lb'
make -C build-apps/bridge install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/bridge'
install -D bridge //usr/local/bin/bridge
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/bridge'
make -C build-apps/pkt-gen install SRCDIR=/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/.. DESTDIR="" PREFIX="/usr/local"
make[1]: Entering directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/pkt-gen'
install -D pkt-gen //usr/local/bin/pkt-gen
install -D pkt-gen-b //usr/local/bin/pkt-gen-b
make[1]: Leaving directory `/home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/build-apps/pkt-gen'
install -m 0644 -D /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys/net/netmap.h //usr/local/include/net/netmap.h
install -m 0644 -D /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys/net/netmap_user.h //usr/local/include/net/netmap_user.h
install -m 0644 -D /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../sys/net/netmap_virt.h //usr/local/include/net/netmap_virt.h
install -D -m 644 /home/deshmukh/netmap-corelight_updates/netmap-corelight_updates/LINUX/../share/man/man4/netmap.4 //usr/local/share/man/man4/netmap.4

**Comment by vmaffione** [comment]
Hi,
  You need to load the modules manually:

````
# rmmod ixgbe # remove the unpatched driver
# cd /path/to/netmap/source
# modprobe netmap # or insmod ./netmap.ko if you didnt' install them
# insmod ixgbe/ixgbe.ko # load the patched driver
````

**Comment by ArchyCho** [comment]
My experience for netmap , never use patched kernel (ie: CentOS kernel source are huge modified  ).
You may download the linux kernel from http://www.kernel.org and just recompile the kernel with default settings , after reboot to the new kernel you may try to compile netmap driver and get it works.

I have tried many many modified kernel sources whatever RedHat or Debian , 
none of them will work with netmap.

**Comment by vmaffione** [comment]
The problem here is different, @ade5hmukh simply forgot to load netmap.ko and ixgbe.ko.
In any case, netmap should compile correctly even on CentOS patched kernel, because Intel NIC drivers are downloaded from the vendor site.

**Comment by ade5hmukh** [comment]
@vmaffione that's right. it worked for me. Thanks!
