### ISSUE TITLE
Rasbperry Pi support?

### ISSUE THREAD

**Issue by drudru** [luigirizzo/netmap#277]
Hi - netmap looks great. Has anyone in your group tried getting it working on a Raspberry Pi (2 or 3)?

**Comment by vmaffione** [comment]
Hi,
  No, afaik, but it if you try it would be great to have your feedback.
In theory the compilation process should be the same.

**Comment by drudru** [comment]
OK - I will give it a go this week. I need to set up a cross compiler first.
