### ISSUE TITLE
How to fix this type of error

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#281]
Hi, guys.

I'm currently using 8 queues with 82599, and I'm getting the following error:

```
Mar  1 09:12:02 localhost kernel: 522.433546 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 471 c 470 t 471 rh 471 rc 470 rt 471 hc 470 ht 471
Mar  1 09:12:02 localhost kernel: 522.433962 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:21 localhost kernel: 541.565970 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 783 c 781 t 783 rh 783 rc 781 rt 783 hc 781 ht 783
Mar  1 09:12:21 localhost kernel: 541.566379 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:27 localhost kernel: 547.361553 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 223 c 222 t 223 rh 223 rc 222 rt 223 hc 222 ht 223
Mar  1 09:12:27 localhost kernel: 547.361963 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:43 localhost kernel: 563.111776 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 603 c 602 t 603 rh 603 rc 602 rt 603 hc 601 ht 603
Mar  1 09:12:43 localhost kernel: 563.112196 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:51 localhost kernel: 571.416898 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 876 c 875 t 876 rh 876 rc 875 rt 876 hc 875 ht 876
Mar  1 09:12:51 localhost kernel: 571.417310 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:54 localhost kernel: 574.932946 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 1590 c 1588 t 1590 rh 1590 rc 1588 rt 1590 hc 1588 ht 1590
Mar  1 09:12:54 localhost kernel: 574.933356 [1694] netmap_ring_reinit        called for eth0 RX8
Mar  1 09:12:56 localhost kernel: 576.263838 [1651] nm_rxsync_prologue        eth0 RX8: fail 'cur < head || cur > kring->nr_hwtail' h 682 c 681 t 682 rh 682 rc 681 rt 682 hc 681 ht 682
Mar  1 09:12:56 localhost kernel: 576.264251 [1694] netmap_ring_reinit        called for eth0 RX8
```

My question is, if I'm using 8 queues, then the queues related to my card, would be from 0 to 7, but it shows in the log RX8, is this host stack ring, or is this really the queue number 8 ?

And, in case the error happens in TX ring, will I see TX in the log, or can it still show RX this way ?

Looking for some advices to track & fix it properly, thanks.

**Comment by vmaffione** [comment]
RX8 is the host RX ring. In case you have this kind of error on a TX ring, you will see TX* in the log.

This error is likely due to your program doing invalid things with rxring->cur and rxring->head, possibly because you are accessing it concurrently without locking (but not necessarily). You can refer to the netmap manual to know how the application should update head and cur and check tail.
In general, applications always keep head == cur, while from your log it's clear this is not true.

**Comment by Fr3DBr** [comment]
Yes, you're right, this is due to threading, but it wasn't clear where I had to look at. :)

Now I know that this is rx / host stack ring, I can start checking where there's an issue. Thanks. 👍

**Comment by vmaffione** [comment]
Ok, in the meanwhile I'll close this, since it's not a netmap issue.

**Comment by Fr3DBr** [comment]
Hey, another question, I didn't told you, but when messing with RX host stack ring, I'm already using a mutex (locking / unlocking), and this is the only place I call:

```
                        pthread_mutex_lock(&hs_lock);
                        // TX must have space available of course.
                        if (nm_ring_space(txring)) {
                                k = txring->cur; /* TX */
                                struct netmap_slot *ts = &txring->slot[k];
                                /* swap packets */
                                if (ts->buf_idx < 2 || rs->buf_idx < 2) {
                                        D("{%d} wrong index rx[%d] = %d  -> tx[%d] = %d", pTI->ring_id, j, rs->buf_idx, k, ts->buf_idx);
                                }
                                if (pTI->zerocopy) {
                                        ts->len = rs->len;
                                        uint32_t pkt = ts->buf_idx;
                                        ts->buf_idx = rs->buf_idx;
                                        rs->buf_idx = pkt;
                                        /* report the buffer change. */
                                        ts->flags |= NS_BUF_CHANGED;
                                        rs->flags |= NS_BUF_CHANGED;
                                } else {
                                        ts->len = rs->len;
                                        char *txbuf = NETMAP_BUF(txring, ts->buf_idx);
                                        nm_pkt_copy(rxbuf, txbuf, ts->len);
                                }
                                // When Dropping Packets, we shouldn't move K forward, but only J
                                k = nm_ring_next(txring, k);
                                txring->head = txring->cur = k;
                        }
                        pthread_mutex_unlock(&hs_lock);
````

To have it incremented, as you can see, but still I get these messages, all the threads, will rely in this pthread_mutex, as this is my "process_ring" function.

It works like this:

Case 1: (NIC TX -> Host RX)

Lock when incrementing txring (host ring), but not rxring (nic ring) as every nic ring has its own thread.

Case 2: (Host TX -> NIC RX)

Lock the whole thing, while the packet is inserted into the NIC RX ring (since each RX NIC has it's own thread, it's fine, I just use lock in this case, for safety).

Do you believe there's an issue here ?

**Comment by Fr3DBr** [comment]
Also, do you see it's always off by 1 only ?

**Comment by vmaffione** [comment]
There is not enough information, this is just a snippet.
In any case, you need to lock the host RX ring (I guess that "rs" is a slot of the host RX ring) to prevent concurrent access. Your code does not seem to do so.

**Comment by Fr3DBr** [comment]
I'm 100% sure, I'm locking any interaction with ring_id 8 / direction = 1 I've tested it, and indeed it is getting locked, but still I'm getting the error log from netmap, there might be something else necessary to be done, but I'm not sure what's it yet.

**Comment by Fr3DBr** [comment]
I've updated the code snippet above, with the whole process_ring function, so you have an idea of what's being done. It is a really simple code.

**Comment by Fr3DBr** [comment]
Maybe the host side, is messing up with the ring counters, causing netmap_ring_reinit to be necessary ?

**Comment by Fr3DBr** [comment]
The problem seens to really be poll() call, since it is trying to read host stack ring all the time, while I'm writing to the host stack ring, so it is finding inconsistencies, in fact, it requires a way to prevent this. So the only two options is either implement a lock for host stack ring in netmap (so we can actually use it, likely in my scenario) or there must be multiple host rings, to match the number of rings in the NIC equally if possible. (I'm not talking about performance, as I know it shouldn't change, but merely about corruption during read/write operations to these rings when multi-threading).

**Comment by Fr3DBr** [comment]
Yes, this is happening in Host RX ring as you said, this is the same as operating system TX and it happens because there are threads concurrently calling poll to the same Host RX rings while it is current "dispatching packets" from it. Basically, since I can't lock poll() I cannot properly synchronize this between all the threads, not sure what to do, honestly speaking. But the current design, doesn't allows you to make a multi-threaded application if you plan to be using the Host Stack RX Ring. :( :( :(

**Comment by Fr3DBr** [comment]
@vmaffione 

I've made a cleanup in my previous messages, as they were wrong, now I've understand what is happening:

1) My threads are calling poll() all the time.
2) I cannot lock before and unlock after the poll() call as this results in severe contention and dead locking as well.
3) Due to 1) and 2), the host stack rx ring is getting "corrupted" because netmap "thinks" its count is incorrect, but this is because, there are packets being processed "in the middle" when the ring is reinitialized.

The current design, doesn't allows you to make a multi-threaded application if you plan to be using the Host Stack RX Ring, do you have any idea I could use ? It would be happy if you could share with me, thanks and have a nice weekend.

**Comment by Fr3DBr** [comment]
@vmaffione 

Once I've made Host Stack RX polling in a single thread, the problem was gone, because now it calls poll first and then loop Host Stack RX, but this is not how I've wanted to design it, I wanted that the threads would compete themselves for Host Stack RX available data, it would be pretty nice if netmap could have multiple host stack rx rings, not even speaking about TX as it wouldn't matter, but just to increase the throughput from Host -> NIC or at least, to use threading without having issues due to poll() call.

Basically, this is what is happening:

1) My threads are calling poll() all the time.
2) I cannot lock before and unlock after the poll() call as this results in severe contention and dead locking as well.
3) Due to 1) and 2), the host stack rx ring is getting "corrupted" because netmap "thinks" its count is incorrect, but this is because, there are packets being processed "in the middle" when the ring is reinitialized.

The current design, doesn't allows you to make a multi-threaded application if you plan to be using the Host Stack RX Ring, do you have any idea I could use ? It would be happy if you could share with me, thanks and have a nice weekend.

**Comment by vmaffione** [comment]
Your code does not show what pa_rxring and pb_rxring are, for each thread. It seems also that you are using something you call "rxring" as it was a txring.
I've no idea how do you call nm_open and so which file descriptors are bound to what. In any case, if two threads access the same ring concurrently,or if they concurrently call poll on two file descriptor bound to the same ring,  then your program is wrong, and you get those errors.

**Comment by Fr3DBr** [comment]
@vmaffione 

I'm using bridge example, basically I'm calling nm_open "per ring" pb = ring 1, 2, 3, 4, 5, 6 and 7 from my NIC and pa is always the host stack. The only issue I have, is with calling poll() on pa from multiple threads, even when there's a lock protecting process_ring, poll() call will mess UP host stack rx ring in this mode, do you understand now ?

**Comment by Fr3DBr** [comment]
@vmaffione 

I'm using bridge example, basically I'm calling nm_open "per ring" pb = ring 0, 1, 2, 3, 4, 5, 6 and 7 from my NIC and pa is always the host stack. The only issue I have, is with calling poll() on pa from multiple threads, even when there's a lock protecting process_ring, poll() call will mess UP host stack rx ring in this mode, do you understand now ? The log in /var/log/messages is very clear, it shows exactly this, the host stack rx ring count is off, and this is due to concurrency reading it's values in a moment it couldn't.

```
        pTI->pa = nm_open(pTI->ifa, NULL, NM_OPEN_IFNAME, NULL);
        if ( pTI->pa == NULL ) {
                D("{%d} Interface Opening Error: %s %s", pTI->ring_id, pTI->ifa, strerror(errno));
                do_abort = 1;
                return NULL;
        }
        struct nm_desc pba = *pTI->pa;
        pba.self = &pba;
        pba.req.nr_flags &= ~NR_REG_MASK;
        pba.req.nr_flags |= NR_REG_ONE_NIC;
        pba.req.nr_ringid = pTI->ring_id;
        pTI->pb = nm_open(pTI->ifb, NULL, NM_OPEN_IFNAME | NM_OPEN_NO_MMAP, &pba);
        if ( pTI->pb == NULL ) {
                D("{%d} Interface Opening Error: %s %s", pTI->ring_id, pTI->ifb, strerror(errno));
                do_abort = 1;
        }

        pTI->zerocopy = 1 && (pTI->pa->mem == pTI->pb->mem);

        /* pre-selecting rings */
        pTI->pa_rxring = NETMAP_RXRING(pTI->pa->nifp, pTI->pa->cur_rx_ring);
        pTI->pa_txring = NETMAP_TXRING(pTI->pa->nifp, pTI->pa->cur_tx_ring);
        pTI->pb_rxring = NETMAP_RXRING(pTI->pb->nifp, pTI->pb->cur_rx_ring);
        pTI->pb_txring = NETMAP_TXRING(pTI->pb->nifp, pTI->pb->cur_tx_ring);

        D("{%d} Wait %d secs for link to come up...", pTI->ring_id, wait_link);

        sleep(wait_link);
```

I've included the way I'm opening the rings before the thread loop.

**Comment by vmaffione** [comment]
Ok, but what's the value for pTI->ifa and pTI->ifb?
I guess you are doing is something equivalent to:

````
pa = nm_open("ethX^", NULL, 0, NULL); // bind the host rings
pb = nm_open("ethX-0", NULL, NM_OPEN_NO_MMAP, pa); //bind la NIC hw pair n. 0, reusing the mmap
````

It's wrong to call poll() on host RX ring (using pa) from different threads without any lock. Kernel won't crash (as you see), but you got those problems.

Going for multiple host RX rings could be a viable idea (assuming there are no unseen blocking factors), but it may be quite a lof of effort.

**Comment by Fr3DBr** [comment]
Hi @vmaffione Yes, the problem is, if I add a simple lock around 'poll call', everything freezes and gets deadlocked lol. :(

**Comment by vmaffione** [comment]
Yeah, point that you should not use host RX ring from multiple threads...

**Comment by Fr3DBr** [comment]
Hi, @vmaffione

Yeah, I've learnt it the hard way. :(

Currently I'm using one of my threads, to perform the poll call in Host Stack rx, it has solved the issue temporarily, but the performance isn't what I expected, because now, this introduced a bit of extra latency, in comparison to when we could concurrently poll it all the time. :(

Oh well. :(

**Comment by murali-rd** [comment]
hi guys,

I am using the standard bridge example (bride between host (eth0^) and netmap rings (eth0)). now if i start some tcp server on top of host stack, and try to do connect from remote TCP client it fails. after checking found that SYN is received from remote which is pushed to host ring using move function, but when host kernel stack replies with SYN-ACK , dont see it in any queues.  is there any thing i m missing here.

thanks.

**Comment by vmaffione** [comment]
You need to disable the offloadings https://github.com/luigirizzo/netmap/blob/master/LINUX/README#L240

**Comment by murali-rd** [comment]
It works fine after disabling the offloading.
Thanks
