### ISSUE TITLE
IXGBE Statistics / Linux

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#282]
Hi, guys.

I've noticed that when using ixgbe drivers optimized for netmap, that the statitics for packets & bytes received/sent, aren't processed anymore, they're 0 all the time, while netmap hooks the NIC. Is there any way that these counters could keep working ? When using netmap in FreeBSD this used to works without any issues, but after I moved to Linux I've noticed this difference.

If this is not possible, then it's not a real problem, but since I missed it, I wanted to let you know. 👍

**Comment by vmaffione** [comment]
Statistics are not accounted in order not to impact performance (a lock would be needed, I think).

Looking at the ixgbe driver patch for FreeBSD sys/dev/netmap/ixgbe_netmap.h I don't see any stats counter incremented, so I don't seeing why you are seing the counter being incremented in FreeBSD. Maybe in FreeBSD you were using the emulaunderstandted adapter (so the unpatched driver increments the counters), or you are seeing some hardware counters.

**Comment by Fr3DBr** [comment]
I was checking it via ifconfig or vnstat. It used to work in FreeBSD but not in Linux, but maybe this is due to the emulated driver, who knows. I'll check better later. :)
