### ISSUE TITLE
Kernel crash with e1000e driver in NR_RX_RINGS_ONLY mode only

### ISSUE THREAD

**Issue by slobodantomic** [luigirizzo/netmap#287]
Hi,

When nm_open() e1000e NIC in NR_RX_RINGS_ONLY mode kernel crashes immediately:

Example command: pkt-gen -i eno1/R -f rx
Distribution: Fedora 25
Kernel: 4.9.14-200.fc25.x86_64

Apr 02 22:45:14 strider kernel: Modules linked in: e1000e_netmap(OE) xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 fuse tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables vboxpci(OE) vboxnetadp(OE) vboxnetflt(OE) openvswitch nf_conntrack_ipv6 nf_nat_ipv6 nf_defrag_ipv6 libcrc32c vboxdrv(OE) xt_multiport xt_conntrack iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass eeepc_wmi crct10dif_pclmul asus_wmi crc32_pclmul sparse_keymap iTCO_wdt iTCO_vendor_support ghash_clmulni_intel intel_cstate rfkill snd_hda_codec_realtek snd_hda_codec_hdmi snd_hda_codec_generic intel_uncore intel_rapl_perf snd_soc_rt5640 snd_hda_intel snd_soc_rl6231 snd_soc_ssm4567 snd_soc_core joydev snd_hda_codec
Apr 02 22:45:14 strider kernel:  snd_compress snd_pcm_dmaengine ac97_bus snd_hda_core snd_seq snd_hwdep snd_seq_device i2c_i801 mei_me netmap(OE) lpc_ich i2c_smbus shpchp snd_pcm mei snd_timer snd snd_soc_sst_acpi tpm_infineon snd_soc_sst_match elan_i2c soundcore tpm_tis tpm_tis_core i2c_designware_platform i2c_designware_core spi_pxa2xx_platform tpm acpi_pad dw_dmac nfsd auth_rpcgss nfs_acl lockd grace sunrpc binfmt_misc hid_logitech_hidpp hid_logitech_dj nouveau i915 mxm_wmi ttm i2c_algo_bit drm_kms_helper crc32c_intel drm serio_raw r8169 ptp sdhci_acpi mii sdhci pps_core mmc_core video wmi fjes i2c_hid [last unloaded: e1000e]
Apr 02 22:45:14 strider kernel: CPU: 5 PID: 6353 Comm: pkt-gen Tainted: G           OE   4.9.14-200.fc25.x86_64 #1
Apr 02 22:45:14 strider kernel: Hardware name: ASUS All Series/MAXIMUS VII RANGER, BIOS 0904 06/13/2014
Apr 02 22:45:14 strider kernel: task: ffff9fba96830000 task.stack: ffffba4a41bc4000
Apr 02 22:45:14 strider kernel: RIP: 0010:[<ffffffffc095d95b>]  [<ffffffffc095d95b>] e1000_configure+0x87b/0xd70 [e1000e_netmap]
Apr 02 22:45:14 strider kernel: RSP: 0018:ffffba4a41bc7b48  EFLAGS: 00010246
Apr 02 22:45:14 strider kernel: RAX: 0000000000000000 RBX: ffff9fbaaa850ff0 RCX: 0000000000000000
Apr 02 22:45:14 strider kernel: RDX: 0000000000000000 RSI: ffffba4a4dd91000 RDI: 00000000ffffff00
Apr 02 22:45:14 strider kernel: RBP: ffffba4a41bc7bc8 R08: 0000000000000000 R09: 0000000000000000
Apr 02 22:45:14 strider kernel: R10: 0000000304b52800 R11: ffff9fba85b90100 R12: ffff9fbb7d013800
Apr 02 22:45:14 strider kernel: R13: 0000000000000100 R14: ffff9fbb4c852c80 R15: ffffba4a4217b7d8
Apr 02 22:45:14 strider kernel: FS:  00007f7fc2ecee80(0000) GS:ffff9fbbafb40000(0000) knlGS:0000000000000000
Apr 02 22:45:14 strider kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 02 22:45:14 strider kernel: CR2: 0000000000000000 CR3: 0000000306351000 CR4: 00000000001426e0
Apr 02 22:45:14 strider kernel: Stack:
Apr 02 22:45:14 strider kernel:  ffff9fbb7e642b00 ffff9fbb4c852c80 ffff9fbb4c852600 ffff9fbadf5f48c0
Apr 02 22:45:14 strider kernel:  ffff9fbadf5f48c0 0df3ef01988d8fb5 0a95db567f7dc285 3b5bda6a92e07e50
Apr 02 22:45:14 strider kernel:  60da850d10f4bc2f 76bc3ca651e87579 00000000c651fb50 ffff9fbadf5f48c0
Apr 02 22:45:14 strider kernel: Call Trace:
Apr 02 22:45:14 strider kernel:  [<ffffffffc0960ab2>] e1000e_up+0x12/0x60 [e1000e_netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffffc09614fb>] e1000_netmap_reg+0x11b/0x1c0 [e1000e_netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffffc0824ba4>] netmap_hw_reg+0x34/0x90 [netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffffc08279b1>] netmap_do_regif+0x2a1/0x330 [netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffffc0829210>] netmap_ioctl+0x6f0/0xa80 [netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffff8d272a19>] ? dput+0xd9/0x260
Apr 02 22:45:14 strider kernel:  [<ffffffff8d27bfe4>] ? mntput+0x24/0x40
Apr 02 22:45:14 strider kernel:  [<ffffffff8d26450e>] ? terminate_walk+0x8e/0xf0
Apr 02 22:45:14 strider kernel:  [<ffffffffc082adc7>] linux_netmap_ioctl+0xc7/0x160 [netmap]
Apr 02 22:45:14 strider kernel:  [<ffffffff8d0e7c74>] ? __wake_up+0x44/0x50
Apr 02 22:45:14 strider kernel:  [<ffffffff8d26b455>] ? do_filp_open+0xa5/0x100
Apr 02 22:45:14 strider kernel:  [<ffffffff8d26e5d3>] do_vfs_ioctl+0xa3/0x5f0
Apr 02 22:45:14 strider kernel:  [<ffffffff8d26eb99>] SyS_ioctl+0x79/0x90
Apr 02 22:45:14 strider kernel:  [<ffffffff8d81dc77>] entry_SYSCALL_64_fastpath+0x1a/0xa9
Apr 02 22:45:14 strider kernel: Code: 24 14 76 73 49 8b 54 24 20 89 cf 03 7a 2c 8b 72 28 89 fa 78 2e 29 f7 39 d6 0f 4e d7 48 63 d2 49 8b b4 24 08 01 00 00 48 c1 e2 04 <8b> 14 10 41 39 94 24 10 01 00 00 76 ac 48 c1 e2 04 48 8b 74 16 
Apr 02 22:45:14 strider kernel: RIP  [<ffffffffc095d95b>] e1000_configure+0x87b/0xd70 [e1000e_netmap]
Apr 02 22:45:14 strider kernel:  RSP <ffffba4a41bc7b48>
Apr 02 22:45:14 strider kernel: CR2: 0000000000000000
Apr 02 22:45:14 strider kernel: ---[ end trace e36c5ba32c0d26d5 ]---

NIC info:
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection (2) I218-V
        Subsystem: ASUSTeK Computer Inc. Device 85c4
        Flags: bus master, fast devsel, latency 0, IRQ 28
        Memory at f7900000 (32-bit, non-prefetchable) [size=128K]
        Memory at f793c000 (32-bit, non-prefetchable) [size=4K]
        I/O ports at f080 [size=32]
        Capabilities: [c8] Power Management version 2
        Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [e0] PCI Advanced Features
        Kernel driver in use: e1000e-netmap

Please let me know if I can provide you with more information:

**Comment by slobodantomic** [comment]
I think I have fixed this in PR #288

**Comment by vmaffione** [comment]
Should be fixed now, can you check?

**Comment by slobodantomic** [comment]
Working just fine! Thanks.

**Comment by vmaffione** [comment]
Thanks for confirming!
