### ISSUE TITLE
Is mSwitch integrated with VALE?

### ISSUE THREAD

**Issue by rahulshcse** [luigirizzo/netmap#289]
Hello,

mSwitch has been presented in paper _**mSwitch: A Highly-Scalable, Modular Software Switch**_ as an improvement over VALE. Has it been integrated with VALE code or is it available separately for use.

Thanks,
Rahul

**Comment by vmaffione** [comment]
Hi,
  Yes, mSwitch is now part of VALE.

**Comment by rahulshcse** [comment]
Please answer one last query.
So does it mean when I use **valeX:Y** it automatically uses **mSwitch** capabilities without further parameter passing? Also I suppose each port of VALE with mSwitch capability exposes single pair of rings (does not provide mutiple pair of queues to process/VM).

**Comment by vmaffione** [comment]
disclaimer: @giuseppelettieri and @micchie know more than me on this topic

VALE has been improved with the work described in the mSwitch paper. There is no distinction between VALE and mSwitch right now.
You can create VALE ports with multiple pairs of TX/RX rings, by setting the nr_tx_rings and nr_rx_rings fields in the struct nmreq, at NIOCREGIF time (or nm_open).

**Comment by micchie** [comment]
Yes all the features in the mSwitch paper is in VALE. You can also create OS-visible vale ports (i.e.,. you can see with "ip link show".
To do so, 
vale-ctl -n vi0
(creates an interface vi0. not yet attached to any bridge. You can see vi0 with ip link show command too)
vale-ctl -a vale0:vi0
(attach vi0 to vale0)
vale-ctl -d vale0:vi0
(detach vi0 from vale0)
vale-ctl -r vi0
(delete interface vi0, also no longer visible with ip link show)

**Comment by rahulshcse** [comment]
Thanks All.
By setting **nr_tx_rings** and **nr_rx_rings** during **nm_open**, I was able to access mutiple rings corresponding to VALE port in a process.
But when I use **ptnet-pci** to export a **VALE port** to a **VM**, I am not able to access multiple rings using above approach from within a VM. Should I do something more so that I can access multiple rings corresponding to VALE port from within a VM via **ptnet-pci**?

**Comment by rahulshcse** [comment]
I solved the problem of **multiple queues** corresponding to **VALE port** exported to VM when using **ptnet-pci** in follwing way (please suggest whether this is the right way to do, as I could see **multiple queues** when using **pkt-gen** inside VM):
1) Created an interface **inf1** using: **vale-ctl -n inf1 -C 1024,1024,4,4 (for 4 queues)**
2) Attached it to VALE switch: **vale-ctl -a vale0:inf1**
3) Passed **vale0:inf1** as interface name exported via **ptnet-pci** when creating a KVM VM.
4) Checked using **pkt-gen**, which showed **4 queues** corresponding to **vNIC** inside **VM**.

**Comment by vmaffione** [comment]
Hi @rahulshcse 
I guess you are following the instruction in #240  to setup netmap passthrough.
Your solution is correct. When you use the ptnet-pci QEMU device to passthrough a netmap host port, you pass-through all the queues of that host port.

However, if you run QEMU with VALE ephemeral ports (e.g. the ones created on the fly), they get 1 port by default, simply because QEMU netmap support currently does not take an option to specify the number of queues. But this is something that we can add easily, and push upstream.

**Comment by vmaffione** [comment]
Should you need a fast temporary hack for ephemeral VALE ports:
````
diff --git a/net/netmap.c b/net/netmap.c
index b9c6d9b35a..d5b4dad711 100644
--- a/net/netmap.c
+++ b/net/netmap.c
@@ -124,6 +124,8 @@ static struct nm_desc *netmap_open(const NetdevNetmapOptions *nm_opts,
         req.nr_flags |= NR_PTNETMAP_HOST;
     }
 #endif /* CONFIG_NETMAP_PASSTHROUGH */
+    req.nr_tx_rings = 4;
+    req.nr_rx_rings = 4;
 
     nmd = nm_open(nm_opts->ifname, &req, NETMAP_NO_TX_POLL | NM_OPEN_NO_MMAP,
                   NULL);
(END)

````

**Comment by rahulshcse** [comment]
Ok. Thanks for help @vmaffione.
I guess when using **multiple rings** of **VALE port**, flows are distributed among rings based on 4-tuple. Is that true?

**Comment by micchie** [comment]
@vmaffione will follow, but VALE by default forwards packets to the ring of the same index with the source ring index. The mSwitch module can decide to which ring packets are forwarded. In other words, for example, distribution across multiple destination rings based on 4-tuple, is a functionality that should be implemented in the module.

**Comment by rahulshcse** [comment]
Thanks @micchie, so it means that I need to write and insert a module to make mSwitch use 4-tuple for distribution. Can you please tell precisely where in code the module be inserted to acheive this?

**Comment by vmaffione** [comment]
@rahulshcse , yes by default the same ring is used.
What you can do is to write a simple kernel module that replaces the VALE lookup function (`netmap_bdg_learning`).

To see an example of registering a custom lookup function, look for `netmap_bdg_ops`, `ovs_vale_ops` and `netmap_bdg_ctl` in utils/switch-modules/ovs-2.6.1/

**Comment by rahulshcse** [comment]
Thanks @vmaffione, I shall try that.

**Comment by micchie** [comment]
If you want, I can give you an example kernel module. Please give me 1 day.

**Comment by rahulshcse** [comment]
Ok @micchie, would be helpful if you can provide one.

**Comment by micchie** [comment]
I temporarily put the stuff here: https://github.com/micchie/mymodule.
To compile, please type following (I assume you have netmap and mymodule in /home/vagrant, and have compiled and loaded netmap kernel module. I also assume you have a Linux kernel source code at /home/vagrant/net-next):
# cd mymodule
# make KSRC=/home/vagrant/net-next NSRC=/home/vagrant/netmap
(Now you have compiled the mSwitch module)

Then, please first create a persistent virtual port using
# vale-ctl -n vi0
Then attach it to vale0, with:
# vale-ctl -a vale0:vi0.
Then you are ready to load the mSwitch module
# insmod mymodule_lin.ko

Now, you can play with this sample module. I created a simple command line tool, mmctl.c in the module directory.
just run "make" in the same directory.
You can run this command like:
# mmctl 0 2
Above means packets from switch port 0 always go to switch port 2.

Overall, this sample module gives you an example of how to create a kernel module, how to implement switching logic and an access method to that logic.

**Comment by rahulshcse** [comment]
@micchie, I followed the instructions and was able to compile and insert **mymodule_lin** module. Also I created 3 virtual interfaces **vi0**, **vi1** and **vi2** and attached them to **vale0**. On running `mmctl 0 2` , I was able to transmit packets from **vale0:vi0** to **vale0:vi2** but not to **vale0:vi1**, which is expected behavior.
@vmaffione and @micchie, thanks for clearing the doubts and for providing necessary help. Now I can modify mymodule_lin.c according to my needs to make switch work on 4-tuples.

**Comment by micchie** [comment]
Awesome! For implementing these things, you could use struct nm_*hdr in netmap_kern.h which is already included by mymodule.c. Therefore, you can use these structures without any additional include files. Use of these header structures is useful to make your code potable.

**Comment by rahulshcse** [comment]
Ok @micchie
