### ISSUE TITLE
Netmap performance on single/multi threads

### ISSUE THREAD

**Issue by debian89** [luigirizzo/netmap#290]
I made some tests with bridge util from build-apps and for me is very strange why if I start it with one thread (bridge -i netmap:eth2 -i netmap:eth4) netmap is able to bridge about 14M PPS via single core (which is on 100%), but if I start bridge on few threads (for i in `seq 0 7`; do taskset -c $i ./bridge -i netmap:eth2-$i -i netmap:eth4-$i) it also able to bridge 14M PPS, but load on all cores is about 60%. Is it that normal?

**Comment by vmaffione** [comment]
If the input rate is uniformly distributed across queues, it means that you get 1.75 Mpps per-queue, and so 1.75 Mpps per process/thread. 1.75 Mpps is low enough that you can get an low RX batch (#packets/#poll) on average (maybe 1-10, you should measure it).

On the other hand, if you use a single thread reading from all the queues, that thread gets 14 Mpps, so the RX batch will be way higher.

A lower batch means each thread is less efficient, spending more time in doing poll() and wake-ups. Also, you have to multiply this inefficiency for the number of threads that you have.

So yes, I think the behaviour you describe makes sense, but there is nothing wrong in it.

**Comment by debian89** [comment]
Hello,
Thank you for the reply!
Please explain me what you mean with single thread reading?

The bridge server have 8 cores, I am using i40e netmap patched driver (intel x710 card)
From one server I am generating 14M packets with pkt-gen and destination is another server to which traffic pass netmap bridge. Every NIC port have 8 rx/tx IRQ (same as core numbers)

When I use netmap:$interface-$queue I am reading packets from all queues or only with what I have chosen?
If I run single process which read and bridge on all queues (bridge -i netmap:eth2 -i netmap:eth4) I am able to bridge 14M packets without problems.

**Comment by debian89** [comment]
Hello,

Thank you a lot for your explanation!

Is it there some tricks and ways to bridge 14M pps without overload one of cpu cores?
Like if I divide bridges on few per protocol (ethtool -N $interface flow-type $protocol action $core) or the r/w batches will be also short?
Or I need to find a cpu with higher frequency?

**Comment by vmaffione** [comment]
So you are saying for you is better to spend 130% of cpu time across two cpus than 100% of a cpu?
An unusual requirement but ok.

You can do what you say, but the more queues you use the shorter the batch. Also, typically the card goes slower when you use traffic classification. Just try and measure.
