### ISSUE TITLE
Our software vendor claims design limitations from Netmap

### ISSUE THREAD

**Issue by leleobhz** [luigirizzo/netmap#299]
Hello Developers!

We have a proprietary software in our structure that uses netmap to fast-capture packets from a port-mirror (10Gbps port ixgbe) and analyse the traffic profile of a DDoS. This week, the support team told us that is not possible to analyse and divert the packet to a PCAP file because a design limitation from Netmap (Limitation that appear to not exist in PF_RING and libpcap support from this app), as told below:

![captura de tela de 2017-04-20 10-40-08](https://cloud.githubusercontent.com/assets/201189/25234325/1f21c61e-25b8-11e7-9c56-f25395496473.png)

What I can ask the support about this limitation?

And a offtopic from this issue: I can archive the same performance if I use netmap-pcap support instead using a direct netmap support? Does PCAP implicates some penality by itself?

Thanks!

**Comment by vmaffione** [comment]
Netmap is just a framework for fast network I/O and you can use it to read packets from a NIC for traffic profiling purposes.
Once you read the packets you can do whatever you want with them, including analyze them and dump them to a PCAP file.
So the claim about design limitation is wrong.

Of course you need PCAP software to do the PCAP dump, but this is completely orthogonal to netmap.
It may be that the netmap-enabled libpcap library has some limitations, but this is another story.

You can expect somewhat worse performance if you use netmap-enabled libpcap, compared to using the netmap API directly.

**Comment by leleobhz** [comment]
Hello @vmaffione !

This also does not make any sense to me, but the awnser for the ticket was the following:

> Netmap offers access to the NIC exclusively to a single listener. In this case the Packet Sensor is the sole listener. Any other listeners can still get the packets but only if they open the interface in a so called "monitor" mode. This is no bug but a design decision of netmap, and there is no reason for us to start arguing with netmap developers on public forums. You are free to use other capturing engines if you don't want to use netmap in conjunction our software and tshark.

Does it make any sense to you? If does, it's possible to do a Workarround?

Thanks!

**Comment by giuseppelettieri** [comment]
Hi @leleobhz, if you are using tshark with netmap-libpcap, it should be possible to use it concurrently with that other proprietary software, whatever that is. As they say, you just need to attach a monitor to the netmap-opened port. Assume, for example, that you are using the 'netmap:eth0' port. Then open 'netmap:eth0/rt' in tshark. The '/rt' part will add a monitor capturing both rx and tx packets. Note that the monitor may drop packets if tshark is not fast enough in processing them.

**Comment by leleobhz** [comment]
Hello @giuseppelettieri 

> Note that the monitor may drop packets if tshark is not fast enough in processing them.

The cited software calls netmap directly. Open with tshark -i netmap:p2p1/rt will prejudice the cited software or in both softwares I'll need to use libpcap-netmap?

Thanks for you attention!

**Comment by vmaffione** [comment]
It does not matter the api you use, under the hood the same netmap api is
used anyway.

Il 24 apr 2017 3:13 AM, "Leonardo Amaral" <notifications@github.com> ha
scritto:

**Comment by leleobhz** [comment]
Hello @vmaffione 

Thanks for you awnser! A last question: Did you measured the difference from a packet dump using netmap directly and using netmap-libpcap? Exist a way to see if the packet capture/processing lose packets due overhead?

Again, thanks a lot for you help!

**Comment by vmaffione** [comment]
No, I didn't measure the difference.
But the performance also depends on how you process the packets.

To read with netmap directly you can use pkt-gen, which does not even touch the packets read:
   $ pkt-gen -i netmap:eth0

If you use tcpdump with netmap-libpcap I guess the performance will be lower, but just because tcpdump is touching the packets.

**Comment by leleobhz** [comment]
Hello @vmaffione 

Can I use pkt-gen to save dump to file? This is the use for tshark (Im using tshark/dumpcap to save packets to pcap files). Also I think disk IO can hit more than capture or dumpcap performance, its right?

Thanks!

**Comment by vmaffione** [comment]
No, pkt-gen does not allow you to dump to pcap file. You should modify it to do that

**Comment by leleobhz** [comment]
Hello @vmaffione 

Thanks for all you awnsers! Ill close this issue now.

Keep rocking :)
