### ISSUE TITLE
Difference between external igb and kernel igb as to updating tail?

### ISSUE THREAD

**Issue by larseggert** [luigirizzo/netmap#300]
The `w_nic_tx()` code at the end of https://github.com/NTAP/warpcore/blob/master/lib/backend_netmap.c works OK for the external `igb` driver, but results in an endless loop with the in-kernel one on Linux 4.10. (It works OK for both the external and in-kernel `ix` and `ixl` drivers.)

Is there some difference with regards to if/when tail is updated with the in-kernel `igb` driver?

**Comment by giuseppelettieri** [comment]
If there is some difference, it is a bug. Have you looked at the tail values to see whether they make any sense?

**Comment by larseggert** [comment]
Here is what I see when I trace how `tail` and other pointers change.

With 4.8 and external drivers:
```
eth_tx eth.c:125 placing iov idx 8194 into tx ring 0 slot 0 (swap with 4098)
eth_tx eth.c:139 Eth 90:1b:e:f:1e:95 -> 90:1b:e:f:1e:65, type 2054, len 42
w_nic_tx backend_netmap.c:279 tx ring 0: tail 2047, cur 1, head 1
w_nic_tx backend_netmap.c:279 tx ring 0: tail 0, cur 1, head 1
w_nic_tx backend_netmap.c:290 moving idx 8194 from ring 0 slot 0 back into w_iov after tx (swap with 4098)
```

With 4.10 and internal drivers:
```
eth_tx eth.c:125 placing iov idx 8194 into tx ring 0 slot 0 (swap with 4098)
eth_tx eth.c:139 Eth 90:1b:e:f:1e:95 -> 90:1b:e:f:1e:65, type 2054, len 42
w_nic_tx backend_netmap.c:279 tx ring 0: tail 2047, cur 1, head 1
w_nic_tx backend_netmap.c:279 tx ring 0: tail 2047, cur 1, head 1
w_nic_tx backend_netmap.c:279 tx ring 0: tail 2047, cur 1, head 1
w_nic_tx backend_netmap.c:279 tx ring 0: tail 2047, cur 1, head 1
...
```

It seems that tail never moves forward.

**Comment by giuseppelettieri** [comment]
There were a few bugs in the kernel-version dependent code -- to many kernels to test. May you please try with the latest commit?

**Comment by larseggert** [comment]
That fixed it
