### ISSUE TITLE
Default NIC drivers not downloaded

### ISSUE THREAD

**Issue by matiaselo** [luigirizzo/netmap#301]
Hi,

After the commit f1a0bfda "linux/i40e: only set the i40e@patch var when i40e is external" none of the default out-of-tree NIC drivers are being downloaded anymore. This was observed on Ubuntu 16.04.2 (4.4.0-75-generic).

Configure log:
`./configure --kernel-sources=./linux-4.4.0 --drivers=i40e,ixgbe
**********************************  NOTE   **********************************
*** Now running compile tests to adapt the code to your
*** kernel version. Please wait.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems copying the sources of driver ixgbe.
*** 
*** If you need this driver, please check that the ixgbe@src variable 
*** points to the correct path contaning the driver sources.
*** 
*** Disabling ixgbe.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems building the external driver ixgbe.
*** 
*** Please note that this is not related to the netmap patches,
*** that were not applied.
*** 
*** Disabling ixgbe.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems building the external driver i40e.
*** 
*** Please note that this is not related to the netmap patches,
*** that were not applied.
*** 
*** Disabling i40e.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems copying the sources of driver ixgbe.
*** 
*** If you need this driver, please check that the ixgbe@src variable 
*** points to the correct path contaning the driver sources.
*** 
*** Disabling ixgbe.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems copying the sources of driver i40e.
*** 
*** If you need this driver, please check that the i40e@src variable 
*** points to the correct path contaning the driver sources.
*** 
*** Disabling i40e.
*****************************************************************************
**********************************  ERROR  **********************************
*** It looks like we are not able to build kernel modules for the current
*** configuration. Please check 'config.log' for possible clues.
***
***
***     Current configuration values:
***
*** kernel directory            /lib/modules/4.4.0-75-generic/build
***                             [/usr/src/linux-headers-4.4.0-75-generic]
*** kernel sources              /home/NNN/dev/netmap.git/LINUX/linux-4.4.0
*** linux version               4043b  [4.4.59]
*** module file                 netmap.ko
*** 
*** subsystems                  generic monitor pipe vale
*** apps                        vale-ctl nmreplay tlem lb bridge pkt-gen
*** native drivers              
*** 
*** Contents of the drivers.mak file:
*** i40e@conf := CONFIG_I40E
*** i40e@src := cp -Rp /home/NNN/dev/netmap.git/LINUX/linux-4.4.0/drivers/net/ethernet/intel/i40e i40e
*** i40e@patch := patches/vanilla--i40e--40400--40700
*** ixgbe@conf := CONFIG_IXGBE
*** ixgbe@src := cp -Rp /home/NNN/dev/netmap.git/LINUX/linux-4.4.0/drivers/net/ethernet/intel/ixgbe ixgbe
*** ixgbe@patch := patches/vanilla--ixgbe--31300--40900
*****************************************************************************`

**Comment by giuseppelettieri** [comment]
Thanks for reporting. May you please try the latest commit?

**Comment by matiaselo** [comment]
The latest commit (caaf8e93) fixed the problem. Thanks!
