### ISSUE TITLE
False negative message

### ISSUE THREAD

**Issue by spinenkoia** [luigirizzo/netmap#303]
Good afternoon.
I found the following messages in kernel.log when loading (and unloading) the kernel module netmap.
```
Kernel: 307.695732 [3385] netmap_init run mknod / dev / netmap c 10 54 # error 0
Kernel: netmap: loaded module
Kernel: netmap: unloaded module.
```
But they are all with the level of ERROR, although it should be INFO.
Looked at the source code, there's that.
```
printf ("netmap: loaded module \ n");
return (0);
```
A printf, it is defined like this.
`#define printf (fmt, arg ...) printk (KERN_ERR fmt, ## arg)`

**Comment by vmaffione** [comment]
Yes, for portability across FreeBSD and Linux we do not preserve the log level.
That's not clean, I know. We should have two separate sets of macros, one for errors and one for info, and change all the places in the code where the macros are used (a lot).

**Comment by socketpair** [comment]
```C
#ifdef FREEBSD
#define log (level, message ...) ???
#else
#define log (level, arg ...) printk (level message, ##arg)
#endif

// And after that in code :

log(KERN_ERR, "message");
log(KERN_INFO, "message");
```

Why not ?

**Comment by vmaffione** [comment]
Yes, that's exactly what I said, but you need to change all the usages of D() and RD() in the code.

**Comment by socketpair** [comment]
Well, I have editted comment and provide quicker fix

**Comment by spinenkoia** [comment]
Here, I created pullrequest https://github.com/luigirizzo/netmap/pull/304
