### ISSUE TITLE
strange behaviour i40e

### ISSUE THREAD

**Issue by jugean2** [luigirizzo/netmap#307]
Dear all,

I use an XL710 40 Gb board with i40e driver, linux 3.10, QSFP+ split, board in 4*10 Gb mode
I use only one queue thanks to : 
find /sys/kernel/debug/i40e/ -name command -exec sh -c 'echo  "set rss_size 1" > {}' {} ';'

When I test my setup with pkt-gen, payload 1024 B, after fresh reboot I got the following output : 
885.074223 main_thread [2406] 0.000 pps (0.000 pkts 0.000 bps in 1001012 usec) 0.00 avg_batch 99999 min_space
886.075211 main_thread [2406] 819.205 Kpps (820.014 Kpkts 6.718 Gbps in 1000988 usec) 10.59 avg_batch 321 min_space
887.076209 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.618 Gbps in 1000997 usec) 10.51 avg_batch 346 min_space
888.077227 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.616 Gbps in 1001019 usec) 10.87 avg_batch 346 min_space
889.078210 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.615 Gbps in 1000982 usec) 10.78 avg_batch 345 min_space
890.079208 main_thread [2406] 1.173 Mpps (1.175 Mpkts 9.622 Gbps in 1000999 usec) 10.67 avg_batch 346 min_space
891.080208 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.618 Gbps in 1001000 usec) 10.72 avg_batch 344 min_space
892.081210 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.616 Gbps in 1001002 usec) 10.66 avg_batch 347 min_space
893.082212 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.620 Gbps in 1001001 usec) 10.79 avg_batch 345 min_space
894.083214 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.621 Gbps in 1001003 usec) 10.79 avg_batch 347 min_space
895.084210 main_thread [2406] 1.172 Mpps (1.174 Mpkts 9.615 Gbps in 1000996 usec) 10.84 avg_batch 347 min_space
896.085208 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.620 Gbps in 1000998 usec) 10.75 avg_batch 347 min_space
897.086210 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.616 Gbps in 1001002 usec) 10.77 avg_batch 345 min_space
898.087210 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.616 Gbps in 1001000 usec) 10.67 avg_batch 346 min_space
899.088214 main_thread [2406] 1.173 Mpps (1.174 Mpkts 9.618 Gbps in 1001003 usec) 10.68 avg_batch 347 min_space
900.089209 main_thread [2406] 816.135 Kpps (816.947 Kpkts 6.692 Gbps in 1000995 usec) 11.17 avg_batch 1 min_space
901.090212 main_thread [2406] 514.364 Kpps (514.880 Kpkts 4.218 Gbps in 1001003 usec) 12.43 avg_batch 436 min_space
902.091223 main_thread [2406] 514.352 Kpps (514.873 Kpkts 4.218 Gbps in 1001012 usec) 12.00 avg_batch 431 min_space
903.092226 main_thread [2406] 514.294 Kpps (514.810 Kpkts 4.217 Gbps in 1001003 usec) 12.55 avg_batch 432 min_space
904.093209 main_thread [2406] 514.259 Kpps (514.765 Kpkts 4.217 Gbps in 1000983 usec) 12.37 avg_batch 428 min_space
905.094209 main_thread [2406] 514.366 Kpps (514.880 Kpkts 4.218 Gbps in 1001000 usec) 12.49 avg_batch 424 min_space
906.095214 main_thread [2406] 514.299 Kpps (514.816 Kpkts 4.217 Gbps in 1001005 usec) 13.30 avg_batch 434 min_space
907.096227 main_thread [2406] 514.359 Kpps (514.880 Kpkts 4.218 Gbps in 1001013 usec) 12.86 avg_batch 438 min_space
908.097209 main_thread [2406] 514.311 Kpps (514.816 Kpkts 4.217 Gbps in 1000982 usec) 12.98 avg_batch 434 min_space
909.098211 main_thread [2406] 514.301 Kpps (514.816 Kpkts 4.217 Gbps in 1001002 usec) 13.03 avg_batch 431 min_space
910.099208 main_thread [2406] 514.305 Kpps (514.818 Kpkts 4.217 Gbps in 1000997 usec) 12.29 avg_batch 432 min_space
911.100213 main_thread [2406] 514.362 Kpps (514.878 Kpkts 4.218 Gbps in 1001004 usec) 12.63 avg_batch 430 min_space
912.101210 main_thread [2406] 514.303 Kpps (514.816 Kpkts 4.217 Gbps in 1000997 usec) 13.06 avg_batch 430 min_space
913.102224 main_thread [2406] 514.358 Kpps (514.880 Kpkts 4.218 Gbps in 1001014 usec) 12.77 avg_batch 431 min_space
914.103208 main_thread [2406] 514.309 Kpps (514.816 Kpkts 4.217 Gbps in 1000985 usec) 12.39 avg_batch 431 min_space
915.104210 main_thread [2406] 514.301 Kpps (514.816 Kpkts 4.217 Gbps in 1001002 usec) 12.13 avg_batch 430 min_space
916.105209 main_thread [2406] 514.303 Kpps (514.816 Kpkts 4.217 Gbps in 1000998 usec) 13.12 avg_batch 428 min_space

Almost link speed for a few seconds and then bad performance with softinterrupt process at 40 % (on an other core). Can't reach more 4.2 Gb/s until reboot.
I use a switch between the generator (which is always at link speed) and I tested, on the same computer, same numa node, pkt-gen bound to same core, through the same switch on a x520 (ixgbe) which easily reaches link speed.
Flow control disabled on both sides (not in the switch) irqbalance stopped. 
I tried with 20 queues (2*10 cores), same result.

Any idea ?

Thanks in advance.

Best, 

Julien.

**Comment by vmaffione** [comment]
What pkt-gen command are you using? I think you are receiving with netmap, but this is not clear from your description.
I don't know what's the effect of setting that rss size, but if you want to use only one nic queue why don't you set the number of queues with
´´´´
 ethtool -L eth0 combined 1
´´´´
And then run pkt-gen in receive mode?

**Comment by jugean2** [comment]
Yes, receiving and emitting with netmap pkt-gen
Thanks, I didn't know this command.
But same behaviour...

**Comment by vmaffione** [comment]
But maybe the rss option (or other non-default options) are still in place. You should do a fresh reboot, change the number of queues and retry.

**Comment by jugean2** [comment]
same result : 
272.485650 main_thread [2406] 0.000 pps (0.000 pkts 0.000 bps in 1000984 usec) 0.00 avg_batch 99999 min_space
272.485673 receiver_body [1719] waiting for initial packets, poll returns 0 0
273.486646 main_thread [2406] 273.520 Kpps (273.792 Kpkts 2.243 Gbps in 1000996 usec) 7.43 avg_batch 305 min_space
274.487647 main_thread [2406] 1.188 Mpps (1.189 Mpkts 9.744 Gbps in 1001001 usec) 7.45 avg_batch 342 min_space
275.488661 main_thread [2406] 1.188 Mpps (1.189 Mpkts 9.742 Gbps in 1001013 usec) 7.64 avg_batch 339 min_space
276.489646 main_thread [2406] 1.188 Mpps (1.189 Mpkts 9.742 Gbps in 1000986 usec) 7.45 avg_batch 340 min_space
277.490646 main_thread [2406] 1.188 Mpps (1.189 Mpkts 9.743 Gbps in 1001000 usec) 7.47 avg_batch 341 min_space
278.491646 main_thread [2406] 1.188 Mpps (1.190 Mpkts 9.745 Gbps in 1001000 usec) 7.48 avg_batch 341 min_space
279.492648 main_thread [2406] 1.187 Mpps (1.188 Mpkts 9.736 Gbps in 1001002 usec) 7.47 avg_batch 335 min_space
280.493652 main_thread [2406] 1.189 Mpps (1.190 Mpkts 9.747 Gbps in 1001004 usec) 7.58 avg_batch 341 min_space
281.494646 main_thread [2406] 1.190 Mpps (1.191 Mpkts 9.757 Gbps in 1000994 usec) 7.34 avg_batch 1 min_space
282.495648 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.767 Gbps in 1001002 usec) 7.27 avg_batch 338 min_space
283.496646 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.766 Gbps in 1000998 usec) 7.08 avg_batch 340 min_space
284.497646 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.763 Gbps in 1001000 usec) 7.09 avg_batch 285 min_space
285.498646 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.766 Gbps in 1001000 usec) 7.00 avg_batch 28 min_space
286.499651 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.767 Gbps in 1001005 usec) 7.03 avg_batch 339 min_space
287.500645 main_thread [2406] 1.190 Mpps (1.192 Mpkts 9.762 Gbps in 1000994 usec) 7.01 avg_batch 338 min_space
288.501647 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.767 Gbps in 1001002 usec) 7.03 avg_batch 339 min_space
289.502646 main_thread [2406] 1.191 Mpps (1.192 Mpkts 9.769 Gbps in 1000998 usec) 7.17 avg_batch 339 min_space
290.503646 main_thread [2406] 1.192 Mpps (1.193 Mpkts 9.772 Gbps in 1001001 usec) 7.16 avg_batch 338 min_space
291.504648 main_thread [2406] 1.192 Mpps (1.193 Mpkts 9.771 Gbps in 1001002 usec) 7.13 avg_batch 340 min_space
292.505646 main_thread [2406] 772.832 Kpps (773.603 Kpkts 6.337 Gbps in 1000998 usec) 8.77 avg_batch 338 min_space
293.506650 main_thread [2406] 514.275 Kpps (514.791 Kpkts 4.217 Gbps in 1001004 usec) 14.37 avg_batch 435 min_space
294.507646 main_thread [2406] 514.304 Kpps (514.816 Kpkts 4.217 Gbps in 1000996 usec) 14.35 avg_batch 428 min_space
295.508649 main_thread [2406] 514.364 Kpps (514.880 Kpkts 4.218 Gbps in 1001003 usec) 13.79 avg_batch 431 min_space
296.509647 main_thread [2406] 514.310 Kpps (514.823 Kpkts 4.217 Gbps in 1000998 usec) 13.94 avg_batch 432 min_space
297.510645 main_thread [2406] 514.296 Kpps (514.809 Kpkts 4.217 Gbps in 1000998 usec) 13.72 avg_batch 270 min_space
298.511660 main_thread [2406] 514.357 Kpps (514.879 Kpkts 4.218 Gbps in 1001015 usec) 13.63 avg_batch 433 min_space
299.512647 main_thread [2406] 514.301 Kpps (514.809 Kpkts 4.217 Gbps in 1000987 usec) 14.48 avg_batch 1 min_space
300.513650 main_thread [2406] 514.303 Kpps (514.818 Kpkts 4.217 Gbps in 1001002 usec) 14.63 avg_batch 440 min_space
301.514661 main_thread [2406] 514.303 Kpps (514.823 Kpkts 4.217 Gbps in 1001011 usec) 14.66 avg_batch 432 min_space

**Comment by jugean2** [comment]
Found !!
it was the adaptive coalescence parameter which was activated...

But CPU usage seems higher than with ixgbe. 50 % instead of 24 %

**Comment by jugean2** [comment]
And with smaller packets I receive 10 times more packets with ixgbe than with i40e on one 10 Gb link !

**Comment by vmaffione** [comment]
It must be something related to nic configuration. Interrupt coalescing parameters in particular may have an important effect. You can monitor the interrupt rate on the nic to see if they are too few or too many

**Comment by jugean2** [comment]
OK. Thank you very much for your help, I close the issue and will eventually open a new one about performance discrepancy between ixgbe and i40e if it remains.
