### ISSUE TITLE
Poll / CPU Usage

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#308]
Hi, guys.

Currently I'm using poll to check for incoming data in the NIC rings, but to achieve the maximum performance I have to adjust the poll latency to "0", this way it keeps polling non stop, my question is, is this the only way to reach linerate performance, or are there other methods ? Because right now, my CPU keeps maxed at 100% all the time. :)

**Comment by Fr3DBr** [comment]
Ah, this is happening because POLLOUT is set to the poll fd, it seems poll returns instantly when this flag is set, probably to dispatch any pending packets as fast a possible right ? :)

**Comment by vmaffione** [comment]
POLLOUT returns immediately if there is space in the tx rings, as per poll manual.
If you want to busywait on receive you can use rxsync, it is slightly faster.
In general you can and should receive at line rate at 10gbit and short packets without busy waiting. Sometimes it is necessary to tune the NIC interrupt coalescing parameters with ethtool, e.g., rx-usecs and the like.

**Comment by Fr3DBr** [comment]
Hey @vmaffione I've wanted to send/receive packets as fast as possible, but saving CPU Power if not really necessary, currently now I've achieved this with pollin+pollout, but it goes at 100% CPU in all my threads. :P

**Comment by vmaffione** [comment]
That's because of the pollout flag. You should set it only when there is no
space on the ring and you want to transmit something.

Il 25 mag 2017 10:51 AM, "Fred :)" <notifications@github.com> ha scritto:

**Comment by Fr3DBr** [comment]
Hey @vmaffione  I know it's due to pollout now, yes indeed, but my question is, how can I detect something must be written, instead of having to wait until the buffer is full ? I'm asking this to avoid extra delay/latency added my the application. :)

**Comment by vmaffione** [comment]
Sorry, I don't understand the question. Can you reformulate?

**Comment by Fr3DBr** [comment]
Dear @vmaffione, if I only issue pollout when the buffer is full, there is extra latency added to my application and sometimes, some packets are lost (even on ping test I can notice this), so what would be a way to once there's a packet to be sent, issue pollout instead of doing it once the buffer is full ?

**Comment by vmaffione** [comment]
If you only want to transmit the pending packets you can call ioctl(TXSYNC).
Or you can call poll() without POLLOUT: by default, poll() calls txsync, unless you specify NETMAP_NO_TX_POLL.
Of course you don't need to wait for the ring to become full to transmit pending packets.

**Comment by Fr3DBr** [comment]
Hey @vmaffione but what is the difference when using the ioctl or pollout ? I saw in bridge.c there are two cases, one where ioctl is used and another where it is not, but I didn't figure which is better hehe.

**Comment by vmaffione** [comment]
it is written in the netmap manual (man netmap).
ioctl() is for non-blocking I/O poll() for blocking I/O.

**Comment by Fr3DBr** [comment]
Dear @vmaffione I'm reading this manual, I suspect it is the same/updated right: https://www.freebsd.org/cgi/man.cgi?query=netmap&sektion=4 ? I saw the mention for ioctl, but when're on a learning curve, it's a bit hard to absorb all of it and know exactly where are the use cases for all the information there hehehe. 👍

**Comment by vmaffione** [comment]
The most updated manual is in the netmap sources.
Both pkt-gen and bridge programs use ioctl() in "busywait" mode and poll for normal "blocking mode".

**Comment by Fr3DBr** [comment]
Dear @vmaffione  Ok, I will try to use ioctl instead of poll and see what happens, maybe it will work in my case, as I'm using netmap in the edge of a network, so I suspect this must be the way to go. :)

**Comment by Fr3DBr** [comment]
Dear @vmaffione I've compiled the bridge example with -DBUSYWAIT to check how it works, but the result is even more interesting than before, a simple ping test in the bridge, results in a huge latency with packet loss, like this:

```
Reply from 93.158.236.7: bytes=32 time=2615ms TTL=62
Reply from 93.158.236.7: bytes=32 time=1147ms TTL=62
Reply from 93.158.236.7: bytes=32 time=406ms TTL=62
Reply from 93.158.236.7: bytes=32 time=2359ms TTL=62
Request timed out.
Reply from 93.158.236.7: bytes=32 time=117ms TTL=62
Reply from 93.158.236.7: bytes=32 time=408ms TTL=62
Request timed out.
Request timed out.
Request timed out.
Reply from 93.158.236.7: bytes=32 time=781ms TTL=62
Reply from 93.158.236.7: bytes=32 time=1616ms TTL=62
Reply from 93.158.236.7: bytes=32 time=410ms TTL=62
Reply from 93.158.236.7: bytes=32 time=3532ms TTL=62
Reply from 93.158.236.7: bytes=32 time=206ms TTL=62
Reply from 93.158.236.7: bytes=32 time=275ms TTL=62
Reply from 93.158.236.7: bytes=32 time=1724ms TTL=62
Reply from 93.158.236.7: bytes=32 time=1371ms TTL=62
Reply from 93.158.236.7: bytes=32 time=2274ms TTL=62
Reply from 93.158.236.7: bytes=32 time=3454ms TTL=62
Reply from 93.158.236.7: bytes=32 time=2101ms TTL=62
Reply from 93.158.236.7: bytes=32 time=303ms TTL=62
```

Although, when you start "pushing traffic", the latency reduces to around 4~5ms, is this expected ?

**Comment by vmaffione** [comment]
No, there is something wrong with your configuration. Try to put the nic in
promiscuous mode and disable all the nic offloadings

Il 25 mag 2017 7:45 PM, "Fred :)" <notifications@github.com> ha scritto:

**Comment by Fr3DBr** [comment]
Hi, @vmaffione I'm doing this at boot time:

ethtool -K ens1f0 gro off gso off tso off lro off rx off tx off
ethtool -A ens1f0 rx off tx off
ethtool -G ens1f0 rx 2048 tx 2048

Regarding promiscuous mode, what do you mean ?

**Comment by Fr3DBr** [comment]
Hi @vmaffione I still didn't found what could be wrong. :P

**Comment by Fr3DBr** [comment]
Hello @vmaffione I know this is a very old topic, but did you had a chance to check my last question ? I'm trying to understand what could be the cause for this, since I didn't found an answer yet so far. 👍

**Comment by Fr3DBr** [comment]
Hey guys, after studying this a bit more, I've figured out, that the main problem here was that I was polling frequent enough to cause "busywaiting", however doing it by poll is bad, ioctl is the way for it. But of course, by watching the packet queues, to check if this is necessary or not. After modifying it to proper pollout, only when needed, things become smooth. 👍
