### ISSUE TITLE
Unable to unload netmap with i40e driver

### ISSUE THREAD

**Issue by desbma** [luigirizzo/netmap#311]
I am using Netmap with the Intel i40e driver (with Netmap patch) on Intel XL710 10 GbE NICs.

If I run a Netmap program (for example the pkt-gen example in rx mode), and then stop it, I am unable to unload the i40e module.

If I run `rmmod i40e`, the process blocks and I get the following kernel traces for ever:
`unregister_netdevice: waiting for enp15s0f1 to become free. Usage count = 2`

A soft reboot won't even work because this blocks kernel shutdown. Also `ip link` does not show the interface anymore.

If I try to unload the Netmap module I get the (expected) `Module netmap is in use by: i40e` message.

I did reproduce with:
* Netmap from master branch, Intel i40e patched Netmap driver version 1.5.25
* Netmap from master branch, Intel i40e patched Netmap driver version 1.6.42
* Netmap from master branch, Intel i40e patched Netmap driver version 2.0.19

I did **not** reproduce with:
* Netmap from master branch, **without** the Intel i40e patched Netmap driver (stock Ubuntu 16.04 driver, which is i40e 1.4.25)
* Netmap 11.2, with the Intel i40e patched Netmap driver version 1.5.25

So it seems the bug is specific to Netmap and appeared sometime between the 11.2 release and the current git head.

EDIT: I could run a `git bisect` to find the commit which caused the regression but my machine takes 5 minutes to boot, so it would take a rather long time...

**Comment by jha** [comment]
Can confirm this is an issue

**Comment by giuseppelettieri** [comment]
I am trying to reproduce this using Intel 2.0.19 driver + netmap patch, 4.10.0-26-generic Ubuntu kernel (from 17.04), but I am unable to.

What I have done:
- insmod netmap.ko
- insmod i40e/i40.ko
1) ifconfig interface up
- pkt-gen -i interface
2) Ctrl+C
- rmmod i40e # works just fine

It also works if I omit any of 1) or 2).

Is there something different that you are doing?

**Comment by desbma** [comment]
@giuseppelettieri did you receive som frames with pkt-gen before sending SIGINT?

**Comment by jha** [comment]
I'm running 3.16.0-4-amd64 and Debian 8

**Comment by giuseppelettieri** [comment]
@desbma, yes, 36Mpps for several seconds. Are you using the same or similar kernel as @jha?

**Comment by desbma** [comment]
I am using Ubuntu 16.04 x86_64 with Linux kernel 4.8.

**Comment by giuseppelettieri** [comment]
The path for the release of the interface is `linux_netmap_release` (which should be called by the kernel when pkt-gen closes /dev/netmap) -> `netmap_dtor` -> `netmap_priv_delete` -> `netmap_unget_na` -> `if_rele` (which finally calls `dev_put` on linux). May you check that the chain is actually followed?

**Comment by desbma** [comment]
@giuseppelettieri Thanks, I will try to follow the call chain and see where it breaks.

**Comment by desbma** [comment]
I have added printk traces at beginning and end of each function you mentioned.

`if_rele` never gets called in `netmap_unget_na` because `ifp` is NULL. 
Here are the traces, when running `./pkt-gen -f rx -i enp15s0f0` (stopped immediately because of an unrelated memory error) :

    [   84.059755] netmap_unget_na ENTRY ifp = 0x          (null), na = 0xffff880e66ade000
    [   84.059756] netmap_unget_na EXIT
    [   84.059783] netmap_dtor ENTRY
    [   84.059784] netmap_priv_delete ENTRY
    [   84.059785] netmap_unget_na ENTRY ifp = 0x          (null), na = 0x          (null)
    [   84.059786] netmap_unget_na EXIT
    [   84.059787] netmap_priv_delete EXIT
    [   84.059787] netmap_dtor EXIT

Running `rmmod i40e` then gets me the `unregister_netdevice: waiting for enp15s0f0 to become free. Usage count = 1` kernel trace.

I you can suggest more tests to help you reproduce or fix this, I'll be happy to help.

**Comment by desbma** [comment]
I can lo longer reproduce on commit bff7ffd9fcd59a82690f147ff7838f9b85213092.
@jha do you confirm ?

So it seem to have been fixed between 3947b2174f13fd54ae6db5e4831846a1811cd8c3 and bff7ffd9fcd59a82690f147ff7838f9b85213092, maybe by e0217c3b2609c2e9484d66014d0075801669fc33?

**Comment by borislavmatvey** [comment]
@desbma, I would expect that #329 (e7df975863ba5539bf33d84dd2985b58f9409c8e) fixes this issue, can you check?

**Comment by desbma** [comment]
Indeed I can reproduce at commit 370234dc429273dea77756ca561d9d04ac4bd648 but not at e7df975863ba5539bf33d84dd2985b58f9409c8e.

Mystery solved then, I'm closing this.

Thanks for the fix @borislavmatvey !
