### ISSUE TITLE
[netmap + rt patches] nm_inject not working

### ISSUE THREAD

**Issue by lauuuuuura** [luigirizzo/netmap#312]
I'm running Linux Kernel 4.4.66 with real time patches and the following setup:
## Scenario:
C1 -----> C2 -----> C3

- C1 is running pkt-gen and sends packets to C2's MAC address.
- C2 is forwarding packets and changing dst MAC address to be C3's.
- C3 is running pkt-gen in order to receive packets.

I've run this tests before, using Linux Kernel 4.9 (without real time patches) and netmap worked without any problem. The reason why I made a kernel "downgrade" was to use a stable version of rt patches.

### Test 1:
C2 is running fastclick with the following config:
`FromNetmapDevice($IF, QUEUE $Q, N_QUEUES 1) -> MarkMACHeader -> AdjustEther(SRC $IFMAC, DST $SINKMAC) -> ToNetmapDevice($IF, QUEUE $Q, N_QUEUES 1);`

C3 is not receiving any packets. Debugging shows that fastclick is looping in `ioctl(fd,NIOCTXSYNC,0);`. This made me wonder and I've build the next testing scenario.

### Test 2:

> static void
> my_cb(u_char *arg, const struct nm_pkthdr *h, const u_char *buf)
> {
> 	u_char *p = (u_char *)buf;
> 	memcpy(p + 6, p, 6); // modify MACsrc
> 	p[0] = [...]; p[1] = [...]; p[2] = [...]; p[3] = [...]; p[4] = [...]; p[5] = [...]; // modify MACdst
> 
> 	struct pollfd f;
> 	f.fd = d->fd;
> 	f.events = POLLOUT; 
> 
> 	int n = nm_inject(d, p, h->len);
> 	poll(&f, 1, -1);
> }
> 
> int
> main(int argc, char *argv[])
> {
> 	struct pollfd pfd;
> 	unsigned char buf[2048];
> 	bzero(&pfd, sizeof(pfd));
>
> 	d = nm_open(argv[1], NULL, 0, NULL);
> 	if (d == NULL) {
> 		fprintf(stderr, "no netmap\n");
> 		exit(0);
> 	}
> 
> 	pfd.fd = d->fd;
> 	pfd.events = POLLIN;
> 	for (;;) {
> 		poll(pfd, 1, -1);
> 		if (pfd.events == POLLIN) {
> 			nm_dispatch(d, -1, my_cb, NULL);
> 		} 
> 		pfd.fd = d->fd;
> 		pfd.events = POLLIN;
> 	}
> 	nm_close(d);
> 	return 0;
> }

The above code is run on C2 and is doing mostly the same thing as test scenario 1, but it's still not working.

I managed to make it work by using **NR_REG_NIC_SW** in _struct nmreq_ (the second argument of _nm\_open_). C1 is sending 128B packets at 8Mpps, and C3 is receiving at ~2Mpps (as expected, since I inject one packet at a time and also using poll + debugging messages that are not shown above).

click/fastclick are using default configurations with _nm\_open_ (the second argument is NULL), and the default flag is **NR_REG_ONE_NIC**.

Any hints about why is not working with the default configuration? How and why would real time patches affect netmap functionality?

**Comment by vmaffione** [comment]
I don't know what rt patches actually do, but in principle they should be completely independent from netmap.
Have you tried to run the bridge program on C2?
````
# ./bridge -i netmap:eth0 -i netmap:eth1
````
where eth0 and eth1 are the forwarding interfaces of C2.
