### ISSUE TITLE
DKMS build fails on Debian Stretch

### ISSUE THREAD

**Issue by ghost** [luigirizzo/netmap#319]
Hi,

building netmap doesnt work using dkms procedure. It fails on the i40e kernel module.:

`root@debian:/opt/netmap/LINUX/dkms# make install-dkms`
`root@debian:/opt/netmap/LINUX/dkms# dkms install netmap/0.0.1`

Error:
`if [ -d i40e ] && [ -e Module.symvers ]; then cp Module.symvers i40e; fi
make -C i40e CFLAGS_EXTRA=" -I/var/lib/dkms/netmap/0.0.1/build -I/var/lib/dkms/netmap/0.0.1/build/LINUX -I/var/lib/dkms/netmap/0.0.1/build/LINUX/../sys -I/var/lib/dkms/netmap/0.0.1/build/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE"  NETMAP_DRIVER_SUFFIX= KSRC=/lib/modules/4.9.0-3-amd64/build
make[1]: Entering directory '/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src'
make[2]: Entering directory '/usr/src/linux-headers-4.9.0-3-amd64'
  CC [M]  /var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.o
In file included from /var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.c:138:0:
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h: In function ‘i40e_netmap_attach’:
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h:225:42: error: ‘*vsi->tx_rings’ is a pointer; did you mean to use ‘->’?
  na.num_tx_desc = NM_I40E_TX_RING(vsi, 0)->count;
                                          ^~
                                          ->
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h:226:42: error: ‘*vsi->rx_rings’ is a pointer; did you mean to use ‘->’?
  na.num_rx_desc = NM_I40E_RX_RING(vsi, 0)->count;
                                          ^~
                                          ->
/usr/src/linux-headers-4.9.0-3-common/scripts/Makefile.build:298: recipe for target '/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.o' failed
make[5]: *** [/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.o] Error 1
/usr/src/linux-headers-4.9.0-3-common/Makefile:1507: recipe for target '_module_/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src' failed
make[4]: *** [_module_/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src] Error 2
Makefile:150: recipe for target 'sub-make' failed
make[3]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.9.0-3-amd64'
Makefile:70: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src'
netmap.mak:82: recipe for target 'build-i40e' failed
make: *** [build-i40e] Error 2`

[make.log.txt](https://github.com/luigirizzo/netmap/files/1087921/make.log.txt)

I'd be happy about any help or advise.

Best,
Simon

**Comment by bdrung** [comment]
The relevant part of the error properly formatted:
```
  CC [M]  /var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.o
In file included from /var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.c:138:0:
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h: In function ‘i40e_netmap_attach’:
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h:225:42: error: ‘*vsi->tx_rings’ is a pointer; did you mean to use ‘->’?
  na.num_tx_desc = NM_I40E_TX_RING(vsi, 0)->count;
                                          ^~
                                          ->
/var/lib/dkms/netmap/0.0.1/build/LINUX/i40e_netmap_linux.h:226:42: error: ‘*vsi->rx_rings’ is a pointer; did you mean to use ‘->’?
  na.num_rx_desc = NM_I40E_RX_RING(vsi, 0)->count;
                                          ^~
                                          ->
/usr/src/linux-headers-4.9.0-3-common/scripts/Makefile.build:298: recipe for target '/var/lib/dkms/netmap/0.0.1/build/i40e-2.0.26/src/i40e_main.o' failed
```

**Comment by vmaffione** [comment]
What happens if you follow the normal build procedure?
````
 $ ./configure
 $ make
 $ sudo make install
````

**Comment by vmaffione** [comment]
This should be fixed, please reopen if necessary.
