### ISSUE TITLE
Issue with single RX queue

### ISSUE THREAD

**Issue by ValGrid** [luigirizzo/netmap#326]
Hi,

I'm trying to get a single RX queue working and have run into some problems, maybe with the configuration?

My application uses udp port 9300 (data port, receive-only) for only receiving data from a client. My application also sends and receives control data on udp port 9303 (control port) with the same client. I'd like my application to use the single RX queue functionality for processing the data coming in on the data port while leaving traffic on the control port to travel to and from the client through the network stack as usual. 

I'm using the nm-single-rx-queue example to test with my unmodified application. I'll start my application first to make sure it's correctly receiving data. I'll then start the nm-single-rx-queue example and my application will then stop seeing any packets from the client on either port. The nm-single-rx-queue output shows one entry (with 2500 pps for example) and then 0 pps thereafter. 

I'm using netmap v11.3 and Intel X550-T1 NIC (v4.5.4) with the netmap-patched ixgbe driver. I have 4 ixgbe supported NICs on the system so when loading the driver, I use:

`modprobe ixgbe RSS=8,8,8,8` 

I also ran the following commands to use receive queue 4: 

`sudo ethtool -X enp1s0f1 weight 1 1 1 1 0 1 1 1`
`sudo ethtool -K enp1s0f1 ntuple on`
`sudo ethtool -N enp1s0f1 flow-type udp4 dst-port 9300 action 4`

After my application is running, I'll start the example:

`./nm-single-rx-queue enp1s0f1 4`

As mentioned once the example starts, my application will no longer receive neither data or control packets from the client.

The main reasons for me wanting to use netmap/single-rx-queue is to reduce CPU usage (reduce number of system calls/context switches) and improve performance as there is a lot of data coming in. 

Thanks.

**Comment by vmaffione** [comment]
The example you are mentioning is not part of the netmap repo, we are not familiar with that program.
Assuming your ethtool commands for hardware receive steering are correct, I don't see how data packets should move between the nm-single-rx-queue program and your unmodified application. They don't.

In any case, what you want to do is definitely possible with netmap. You can avoid ethtool tricks and modify your application to receive all the packets arriving to any of the NIC RX queues, and filter them in software: UDP packets on port 9300 can be processed as data packets as you need, while all the other ones can be passed unmmodified to the host TX ring (so that they are injected back to the network stack where they can reach the socket layer). Your application must also forward the packets from the host RX ring to the NIC TX rings.
You may probably want to read the netmap manual and related documentation to understand how host rings work.

**Comment by ValGrid** [comment]
Thanks for your response.

Assuming my ethtool commands are correct, I would expect that the nm-single-rx-queue example would remove the data packets (port 9300) from the network stack preventing my app from seeing them, however I would not expect that the control packets (port 9303) would also be removed.

The nm-single-rx-queue example is from cloudflare who submitted the single rx/tx queue kernel bypass changes to netmap. The example displays a count of the number of packets received on the specified rx queue. The plan is to modify my app to use netmap on the receive data queue and to continue using a regular socket for the control packets.

I would prefer to do it this way because eventually I would like to run multiple instances of my application, each one communicating with a different client. So each instance would handle a different receive queue on the same NIC. Unless there is a better way?

I'll verify my ethtool commands are correct and look into the netmap docs some more.

Thanks.

**Comment by vmaffione** [comment]
If you nm_open("netmap:enp1s0f1-4", ...) then netmap will only intercept packets coming on RX queue #4 AND packets that the kernel decides to transmit on TX queue #4 (this is a problem, because also control packets will end up in the host RX ring if the kernel decides to transmit them on TX queue #4). Packets received/sent on the other queues will keep going their way through the network stack.

**Comment by ValGrid** [comment]
If I use single RX queue mode, ex. nm_open("netmap:enp1s0f1-4/R",...), like the example app does, shouldn't that mean netmap will only intercept packets coming in on RX queue #4 and that netmap would not touch packets that would be transmitted on TX queue #4? With the ethtool commands I specified, I expected netmap to only place received packets for udp port 9300 onto RX queue #4. The issue is that it appears that received packets for udp port 9303 (as well as any other ports) are also being filtered by netmap. If I am correct in the way I think it should work, then maybe the issue is with the ethtool commands I used to ensure that only the specified udp port traffic flow to the netmap queue. FYI, I used the instructions here: https://blog.cloudflare.com/single-rx-queue-kernel-bypass-with-netmap/

Thanks.

**Comment by vmaffione** [comment]
You are correct, if you use nm_open() in that way (R flag) netmap only intercepts RX packets coming on the single queue, and it doesn't steal any TX packet coming from the host stack.
You could even use a patch like this to make sure netmap is not stealing TX packets for some reason
````
diff --git a/sys/dev/netmap/netmap.c b/sys/dev/netmap/netmap.c
index c3bb0228..c0e4986e 100644
--- a/sys/dev/netmap/netmap.c
+++ b/sys/dev/netmap/netmap.c
@@ -3127,9 +3127,11 @@ netmap_transmit(struct ifnet *ifp, struct mbuf *m)
        tx_kring = &NMR(na, NR_TX)[txr];
 
        if (tx_kring->nr_mode == NKR_NETMAP_OFF) {
+                D("intercept mbuf %d, let it go", m->len);
                return MBUF_TRANSMIT(na, ifp, m);
        }
 
+        D("intercept mbuf %d, steal", m->len);
        q = &kring->rx_queue;
 
        // XXX reconsider long packets if we handle fragments

````

You can debug which packets are received on which RX queue using "ethtool -S ethX", while netmap applications are not being executed.

**Comment by vmaffione** [comment]
Please always use the code on the master branch, which is the more stable. Don't use tagged versions.

**Comment by ValGrid** [comment]
Thanks for your help.  I'll switch to the code on the master branch and debug this with your patch.

Thanks.

**Comment by ValGrid** [comment]
Sorry for the delay. The issue was that when enabling the netmap interface, traffic was interrupted on the interface. This caused the control connection to temporarily stop receiving responses. I initially thought that the responses were being filtered out by netmap. Thanks again for your help.
