### ISSUE TITLE
Null byte packets

### ISSUE THREAD

**Issue by markabey** [luigirizzo/netmap#331]
I've got an issue using netmap on linux to load balance packets to a network monitoring tool called Bro where sometimes everything appears to be working fine (statistics show forwarded packets), but the packets are actually all empty null bytes (and hence invalid).

I saw this on my dev server, and it happened inconsistently (using custom netmap igb driver). It occurs with Bro which uses a plugin for the netmap api, as well as with tcpdump/netmap-libpcap. Perhaps as I am starting and stopping lb and bro independently a lot.

I then tried to reproduce on a small VM and got a consistent case, where if I start lb first, then tcpdump, it works. If I start tcpdump first, then lb, I get null packets.

Example packets:
```
tcpdump: listening on netmap:bro}0, link-type EN10MB (Ethernet), capture size 262144 bytes
12:00:12.244449 00:00:00:00:00:00 > 00:00:00:00:00:00, 802.3, length 0: LLC, dsap Null (0x00) Individual, ssap Null (0x00) Command, ctrl 0x0000: Information, send seq 0, rcv seq 0, Flags [Command], length 60
	0x0000:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0030:  0000 0000 0000 0000 0000 0000            ............
12:00:12.245005 00:00:00:00:00:00 > 00:00:00:00:00:00, 802.3, length 0: LLC, dsap Null (0x00) Individual, ssap Null (0x00) Command, ctrl 0x0000: Information, send seq 0, rcv seq 0, Flags [Command], length 60
	0x0000:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0030:  0000 0000 0000 0000 0000 0000            ............
12:00:12.245567 00:00:00:00:00:00 > 00:00:00:00:00:00, 802.3, length 0: LLC, dsap Null (0x00) Individual, ssap Null (0x00) Command, ctrl 0x0000: Information, send seq 0, rcv seq 0, Flags [Command], length 52
	0x0000:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
	0x0030:  0000 0000                                ....

```

Description of my system + commands:
Ubuntu 16.04 using netmap master from June 13th 9317a62012 
[netmap-empty-packets.txt](https://github.com/luigirizzo/netmap/files/1130948/netmap-empty-packets.txt)

Log Archive containing:
7 packet Pcap file replayed using tcpreplay:
logs when starting lb first
logs when starting tcpdump first
[netmap-empty-packets-logs.zip](https://github.com/luigirizzo/netmap/files/1130952/netmap-empty-packets-logs.zip)

**Comment by giuseppelettieri** [comment]
Yes, you should start lb first and tcpdump, bro or whatever last. This is due to a current limitation in the API on how memory areas are attached to ports. A pipe like 'bro}0' will get a private memory area by default, and this cannot be changed while the pipe is open. This memory area will be different from the one the 'lb' will use, therefore the zero-copy will not work and you will get null packets. If you start lb first, instead, everything will be good, since the pipes will now start with the memory area selected by lb.

To mitigate this situation, I am going to let lb fail if it finds out that the pipes are using a memory area different from the intended one.

**Comment by giuseppelettieri** [comment]
The latest commit causes lb to fail if pipes cannot be open in the intended way.

**Comment by markabey** [comment]
This commit? bc0395f7b5 "vale: accept nic-attach syntax only for proper commands" From July 5th (before my issue was posted)

**Comment by giuseppelettieri** [comment]
Sorry, I forgot to push. The commit I was referring to is https://github.com/luigirizzo/netmap/commit/a56bdfff8418bf6dd7b448456459268cea075141 ("lb: fail if pipes cannot be used in zero-copy")

**Comment by markabey** [comment]
That commit didn't resolve for me. I still see `sucessfully opened pipe #1 netmap:bro{0/xT@1 (tx slots: 1024)` when lb starts after tcpdump. And tcpdump gets null byte packets.

**Comment by giuseppelettieri** [comment]
Does anything change if you use `pktgen -i netmap:bro}0` instead of tcpdump?

**Comment by markabey** [comment]
I see the same behaviour using `pkt-gen -i netmap:bro}0 -f rx -X` . The packet counts and sizes are right, but the contents are just null bytes.

**Comment by giuseppelettieri** [comment]
What do you see if you use pipes named after the name of the input lb port? E.g., `eth0}0` if lb is reading from `eth0`.

**Comment by markabey** [comment]
That works correctly, as expected. using eth1}0 and starting applications in either order works as expected.
The reason we wanted to use pipes name differently, if because we sometimes want to consume packets by multiple applications (not in zero copy). Eg have bro listen all the time, and have a pipe ready to connect to with tcpdump or something else.
Or do something where we merge multiple input interfaces together before forwarding into the bro pipe (eg each half of a network tap)

**Comment by giuseppelettieri** [comment]
You can connect with tcpdump (or anything else) at any moment using monitor ports. With. e.g., `tcpdump -i netmap:eth1/rt`, tcpdump will listen on a monitor port that will receive a copy of each packet received or transmitted on `netmap:eth1`.

**Comment by markabey** [comment]
As far as I can tell doing that won't let you load balance packets, or use multiple application output pipes - eg `-p app1:3 -p app2:1`

**Comment by markabey** [comment]
Any idea where we can look to resolve this? Any guesses as to why it is occurring?

**Comment by markabey** [comment]
Is it because naming an output "app1" makes a netmap pipe, but naming it "eth1" is a physical interface? Are they treated differently when connecting to them?

Is there a function which lists all the netmap pipes/interfaces that are currently open and available from /dev/netmap? Then we can check if something is up and sending to that pipe before connecting to it.

**Comment by vmaffione** [comment]
Yes, if you open "netmap:app1", a VALE port will be created and a pipe pair attached to it. This happens because "app1" is not the name of a physical interface.
The netmap API works the same for any netmap port (VALE port, pipe, physical NIC, etc.).

No, unfortunately there is no function right now to know the netmap ports currently open.
