### ISSUE TITLE
Is the Linux version still "experimental code"?

### ISSUE THREAD

**Issue by hmijail** [luigirizzo/netmap#332]
The LINUX/README file says 

> REMEMBER
	THIS IS EXPERIMENTAL CODE WHICH MAY CRASH YOUR SYSTEM.
	USE IT AT YOUR OWN RISK.

However, this file also seems to be not really up-to-date. 

So, as of July 2017, is Netmap still experimental on Linux? Or can it be considered usable in production?

**Comment by vmaffione** [comment]
Many people use netmap in production and that file was actually updated some months ago.
That sentence simply states that we don't guarantee it won't crash. It's open source software, if problems show up we will fix it.

Anyway, it is quite stable on Linux.

**Comment by hmijail** [comment]
Thank you for your answer, and sorry for the confusion. I'm used to the "no guarantees" language in various open source licenses, but the text here sounded distinctly more serious, so that's why I asked. I was concerned that Netmap in Linux might be more for experimentation than for production use, so it's particularly good to know that the intention is to fix any problems that show up.

Regarding the "not really up-to-date", I said that because the Revision History stops at 2012, while it's apparent that there has been development in Netmap and friends since then. It would be useful to have more milestones in there to know what has been happening. (Of course one can go into the commit history itself, but it's much harder to get a high-level idea of what has been the evolution and what is the current status)

**Comment by vmaffione** [comment]
what do you mean by "Revision History"? Netmap is basically rolling release, we only maintain the latest version.

**Comment by hmijail** [comment]
The before-last section in LINUX/README is  "Revision History", which only lists 3 dates in 2012.

**Comment by vmaffione** [comment]
Ah I see. You're right, that is a leftover. We should just remove it.
