### ISSUE TITLE
Chaining zero copy monitors now supported?

### ISSUE THREAD

**Issue by desbma** [luigirizzo/netmap#339]
I found this comment in the code:

```
 * Several copy monitors may be active on any ring.  Zero-copy monitors,
 * instead, need exclusive access to each of the monitored rings.  This may
 * change in the future, if we implement zero-copy monitor chaining.
```
https://github.com/luigirizzo/netmap/blob/6292c40b417146a94b78eb07828fe9c0345db77f/sys/dev/netmap/netmap_monitor.c#L69-L71

However this seems to be contradicted by this commit: 5bb3df9c3112951f6ec9b942b86cbf552718fec4.

Also doing a quick tests, I was able to run the following commands in parallel:
* `./pkt-gen -f rx -i netmap:enp15s0f0`
* `./pkt-gen -f rx -i netmap:enp15s0f0/z`
* `./pkt-gen -f rx -i netmap:enp15s0f0/z`

And receive packets normally in the 3 processes, which seem to indicate the comment is obsolete as we can now chain several zero copy monitors.

So is chaining zero copy monitors now supported?

**Comment by giuseppelettieri** [comment]
Yes, you are right, the comment is obsolete. If you want to send a patch removing/updating it, that would be great.
