### ISSUE TITLE
e1000: Failed to intercept received packets on CentOS 7.x

### ISSUE THREAD

**Issue by krishnasrk** [luigirizzo/netmap#348]
When I am running the bridge example on centOS 7.3 (3.10.0-514.26.2.el7.x86_64), I see that packets are going directly from NIC to host stack. Packets that send from host stack to NIC are reaching the bridge application and send out. 

command ran:
./bridge -i netmap:eth0 -i netmap:eth0^ or ./bridge -i netmap:eth0^ -i netmap:eth0 or ./bridge -i netmap:eth0

I see packets only from host -> net. not from net -> host. (i.e no packets are getting queued in NIC RX rings)
network driver e1000
$ lsmod | grep e1000
e1000                 142051  0 
netmap                149412  1 e1000

is there any options to debug this issue?

**Comment by vmaffione** [comment]
The "host->net" debug print is misleading.
Actually the program works as expected, forwarding packets in the two directions (NIC RX rings --> host TX ring, host RX rings --> NIC TX rings).
You can see that if you use the -v flag, where you'll see something like this
````
958.412772 process_rings [109] host->net sent 1 packets to 0x7efcc301c000
[...]
959.406709 process_rings [109] net->host sent 1 packets to 0x7efcc300a000
````
where the txring address changes, alternating between the NIC TX ring and the host TX ring (i.e. the two directions).

We should just fix the wrong debug print. If you wish you can also propose a patch.

**Comment by krishnasrk** [comment]
Thanks @vmaffione  I think it is not just a print issue. Following is my observation. when running the bridge application as below.
./bridge -i netmap:eth0 -i netmap:eth0^
1. Whenever a UDP message is send from an UDP application (where bridge app is running) to a UDP server running in a different server. I see the following debugs getting printed (packet is going out from host->net
```
      092.538060 main [332] poll ok [0] ev 1 0 rx 0@0 tx 242, [1] ev 1 1 rx 1@13 tx 255
      092.538080 main [332] poll ok [0] ev 5 4 rx 0@0 tx 242, [1] ev 0 0 rx **1@13** tx 255
      092.538086 process_rings [108] host->net sent 1 packets to 0x7fccc25f0000
      095.040646 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 241, [1] ev 1 0 rx 0@14 tx 255

```
2. Whenever  a UDP message is send to UDP server running with bridge app, then I see Message is delivered to UDP server but just seeing poll timeout **poll timeout [0] ev 1 0 rx 0@0** 
```
    302.744416 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    305.246964 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    307.748337 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    310.250943 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    312.753507 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    315.256090 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255
    317.758686 main [332] poll timeout [0] ev 1 0 rx 0@0 tx 240, [1] ev 1 0 rx 0@15 tx 255

```

Also I see that
```
                if (pollfd[0].revents & POLLOUT)
                        move(pb, pa, burst, 0);

                if (pollfd[1].revents & POLLOUT)
                        move(pa, pb, burst, 1);

```
in the above code, only move under ``` pollfd[0].revents & POLLOUT ```  is getting called since.  I alway see "[0] ev 1 0 rx 0@0" (no packets in NIC Rx Ring)

**Comment by krishnasrk** [comment]
Hi I found the root-cause for this issue.  In e1000 driver,  e1000_clean_rx_irq  NETMAP hook is missed. So packets are directly going to host stack from NIC
In ```final-patches/vanilla--e1000--20620--31200``` following needs to be added  for ```e1000_clean_rx_irq```
```
#ifdef DEV_NETMAP
    ND("calling netmap_rx_irq");
    if (netmap_rx_irq(netdev, 0, work_done))
        return 1; /* seems to be ignored */
#endif /* DEV_NETMAP */
```

**Comment by vmaffione** [comment]
I'm sorry, I was wrong about the debug message, it is actually correct as you say. bridge works fine to me with e1000, either using the native or generic adapter. I see both directions working. I'm using Linux 4.12, though.
Are you using a very old kernel?

In any case, are you sure you're using the latest netmap code? In the file you are saying the RX hook is there: https://github.com/luigirizzo/netmap/blob/master/LINUX/final-patches/vanilla--e1000--20620--31200#L64-L72

Maybe you are using jumbo frames? That may be your problem

**Comment by krishnasrk** [comment]
Thanks @vmaffione , The patch you pointed out is actually applying on ```e1000_clean_jumbo_rx_irq```  instead of ``` e1000_clean_rx_irq ```  with below steps the make executes. patch for e1000 is not in sync with linux-3.10.0-514.26.2.el7 version e1000 driver so the issue.
```
cp -Rp /home/krishnasrk/rpmbuild/SOURCES/linux-3.10.0-514.26.2.el7/drivers/net/ethernet/intel/e1000 e1000
patch --posix --quiet --force -p1 < patches/vanilla--e1000--20620--31200
```

**Comment by vmaffione** [comment]
I see, that's very unlucky, because it results into a subtle issue that does not show up as a compilation failure.
Unfortunately there are many versions and variants, and it's very hard to support them all. Centos probably applies many patches to the vanilla version.

Fortunately we don't have this problems with the most interesting drivers (e.g. ixgbe, i40e, ixgbevf, and even e1000e and igb), because we patch the Linux-version-independent drivers provided directly by Intel instead of patching the (Linux-version-dependent) vanilla Linux drivers. Intel however does not provide anymore drivers for e1000, that's why you ran into this.

It is also true that e1000 is only 1Gbps, so using the emulated netmap adapter does not make an huge difference (at least in terms of packet rate).

**Comment by krishnasrk** [comment]
Yes I got your point @vmaffione , it very difficult to maintain out of tree code to support all versions.  I think we can add some note in README with providing the details of patch (like where netmap hooks should be applied) so someone can do manual verification

**Comment by vmaffione** [comment]
Yes. Or maybe we can add a note to the LINUX/README, "COMMON PROBLEMS" section. We can say that the user of e1000 should check the result of patch when not using a vanilla driver, in particular checking that the rx hook applies to `e1000_clean_rx_irq` rather than `e1000_clean_jumbo_rx_irq`.
Would you mind preparing a pull request with this documentation change? Thanks!

**Comment by krishnasrk** [comment]
Sure @vmaffione  I can do so. Can you please provide the Permission to the luigirizzo/netmap.git repo?

**Comment by krishnasrk** [comment]
@vmaffione  Created the pull request https://github.com/luigirizzo/netmap/pull/350 for the same.

**Comment by olproff** [comment]
Hi @vmaffione , @krishnasrk , I have the same problem at Intel 540,  bridge app from trunk (host->net, net-> host) working about 10 secs, after that i see poll timeout on tx.  tested on kernel 4.4, 4.8, 4.10.

**Comment by vmaffione** [comment]
In the current patches we intercept both `e1000_clean_rx_irq` and `e1000_clean_jumbo_rx_irq`, so problem should be gone. We also added proper support for Jumbo frames btw.
