### ISSUE TITLE
Running multiple pkt-gen applications for receiving packets 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luigirizzo/netmap#35]
```
What steps will reproduce the problem?
1. netmap and ixgbe driver is loaded succesfully.
2. When 40M packets are sent from another server, single pkt-gen application 
can receive packets without packet loss.
3. When I try to run two independant pkt-gen application to receive packets, 
neither one can capture the packets; both capture a few hundred packets.

What is the expected output? What do you see instead?

I expect each pkt-gen to receive its own copy of packets, near 40M packet with 
packet loss. Is there a way to run netmap mechanism such that I can run 
multiple independent pkt-gen applications and each pkt-gen application will 
receive a copy of incoming traffic without interfering others.  

What version of the product are you using? 

A patched version according to the guidance in "ISSUE 23". 

On what operating system?

x86_64 Redhat Linux with 3.8.11 kernel version.

Please provide any additional information below.


```

Original issue reported on code.google.com by `berraa...@gmail.com` on 21 Nov 2014 at 7:57

**Comment by obhessen** [comment]
I tried the same thing and saw the same problem.

The problem I was trying to solve was how to scale a single process that uses too much CPU on each
packet to process all incoming packets.  The usual design pattern on unix is to have more then one 
reader thread or process. 

I expected that each process could open their own netmap device and start reading. Each 
process would then see the same shared memory region and would need some locking
to coordinate operating on the same rxring. I also tried to use a single process that opened file descriptors and then use several threads that in parallell calling poll, reading packets.

Maybe you can discuss this use pattern on your man page and suggested solutions
that suits the netmap philosophy.

**Comment by vmaffione** [comment]
If you don't have multi queue support in the nic,you can still let a single reader spread packets across multiple netmap pipes. The lb program in apps does exactly this
