### ISSUE TITLE
Question about object allocation for private memory allocators

### ISSUE THREAD

**Issue by ameske** [luigirizzo/netmap#354]
I had a question about a calculation made to determine the number of netmap_if structures to preallocate when creating a new private memory allocator, and the default setting of a maximum of 100 interfaces for private memory allocators.

https://github.com/luigirizzo/netmap/blob/377410064fe83884e6c5babe0fbe09ac19a250e1/sys/dev/netmap/netmap_mem2.c#L1499-L1524

In the linked code, I understand the calculations for the number of rings and buffers needed. However, I'm not sure I understand why the calculation for the number of interfaces is (2 + 4 * numpipes). From what I understand, every file descriptor will require an interface structure. Is the 4 in that equation related to the fake rings that exist for compatibility with the physical interfaces? I'm mainly curious, but it is related.

https://github.com/luigirizzo/netmap/blob/377410064fe83884e6c5babe0fbe09ac19a250e1/sys/dev/netmap/netmap_mem2.c#L446-L476

Here is what I'm running into, which was why I was wondering about the calculation to determine the number of interfaces needed. I was trying to set up a VALE port with space for 32 pipes. From the calculations in the first code snippet, 32 pipes requires 260 rings. That is well within the max limits defined within the second code snippet. However, 32 pipes would require 130 interfaces, which is above the limit of 100. I believe the defined maximum number of pipes is 64, but the max interfaces parameter by default would instead cap it out at 24. (at least for the private memory allocators, I think it's fine for the global allocator)

Is the limit of 100 interfaces significant? Would it be ok to increase that value to accommodate the 32 pipes in a private memory allocator?

**Comment by vmaffione** [comment]
Hi, your question is very specific, so I'll let the author of this part of the code (@giuseppelettieri) answer when he is back. But did you know that you can play with all the private allocator parameters through the sysfs /sys/module/netmap/parameters ? No need to recompile.
I think the 4 comes from the fact that you could open the tx,rx,host rx and host tx rings of a pipe separately, eg with 4 different nm_open.

**Comment by ameske** [comment]
Thanks, @vmaffione! That makes sense, you'd want to at least guarantee the ability to have an interface for each ring at minimum.

I checked out the sysfs parameters, but unfortunately they adjust the default minimum number of objects for the pool, I'm running up against the default maximum number of objects. (specifically the interfaces).

https://github.com/luigirizzo/netmap/blob/377410064fe83884e6c5babe0fbe09ac19a250e1/sys/dev/netmap/netmap_mem2.c#L493-L498

I'll wait for @giuseppelettieri thoughts on this one. I'm able to recompile and test this out, but I just wanted to make sure there wasn't anything subtle that might cause problems that I wouldn't notice without better understanding of the code base.

Thanks again for your reply!

**Comment by vmaffione** [comment]
Ok, but if you raise the minimum (priv_if_num and priv_ring_num) above the number you need, kill all netmap applications and run them again I think you should obtain what you need.

**Comment by giuseppelettieri** [comment]
Hi @ameske. The 4 in that line is just a wild guess: you certainly need at least two ifs for each pipe (one for each endpoint), but you may also want to open each endpoint two times (one for each direction).

The hard-coded max values are also educated guesses at what may be reasonable scenarios, but there is nothing magical in them and you can change them as you wish. You do have to patch the code, though.

This whole configuration stuff is rather cumbersome and we should move to something more flexible sometime in the future.

**Comment by ameske** [comment]
Thanks, @giuseppelettieri! If I run into any issues that I can concretely trace back to my changes to that value I'll make sure to document it here and do what I can to diagnose it. So far, so good though! Thanks to both of you for your input!
