### ISSUE TITLE
netmap does not compile on Raspberry Pi

### ISSUE THREAD

**Issue by jmtilli** [luigirizzo/netmap#357]
I tried for fun to compile netmap on Raspberry Pi. The main kernel module was built successfully but applications fail to build:

In file included from /home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:112:0:
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c: In function ‘pcap_prod’:
/home/pi/netmap/LINUX/../sys/net/netmap_user.h:175:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:774:2: note: in expansion of macro ‘D’
  D("alloc %ld bytes for queue failed, exiting",(_P64)need);
  ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c: In function ‘main’:
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:97:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1264:6: note: in expansion of macro ‘ED’
      ED("%ld -> %ld maxq %d round %ld",
      ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:97:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1264:6: note: in expansion of macro ‘ED’
      ED("%ld -> %ld maxq %d round %ld",
      ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:97:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 10 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1264:6: note: in expansion of macro ‘ED’
      ED("%ld -> %ld maxq %d round %ld",
      ^
In file included from /home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:112:0:
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c: In function ‘uniform_delay_parse’:
/home/pi/netmap/LINUX/../sys/net/netmap_user.h:175:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 7 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1532:2: note: in expansion of macro ‘D’
  D("dmin %ld dmax %ld", (_P64)dmin, (_P64)dmax);
  ^
/home/pi/netmap/LINUX/../sys/net/netmap_user.h:175:10: error: format ‘%ld’ expects argument of type ‘long int’, but argument 8 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1532:2: note: in expansion of macro ‘D’
  D("dmin %ld dmax %ld", (_P64)dmin, (_P64)dmax);
  ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c: In function ‘exp_delay_run’:
/home/pi/netmap/LINUX/../sys/net/netmap_user.h:175:10: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 7 has type ‘uint64_t’ [-Werror=format=]
   struct timeval _t0;    \
          ^
/home/pi/netmap/LINUX/../sys/net/netmap_user.h:193:13: note: in expansion of macro ‘D’
             D(format, ##__VA_ARGS__);                           \
             ^
/home/pi/netmap/LINUX/../apps/nmreplay/nmreplay.c:1595:2: note: in expansion of macro ‘RD’
  RD(5, "delay %lu", (_P64)q->cur_delay);
  ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'nmreplay' failed
make[1]: *** [nmreplay] Error 1
make[1]: Leaving directory '/home/pi/netmap/LINUX/build-apps/nmreplay'
netmap.mak:122: recipe for target 'build-app-nmreplay' failed
make: *** [build-app-nmreplay] Error 2

Is the 32-bit ARM a supported platform or am I trying to do something that will never work?

**Comment by vmaffione** [comment]
These are trivial format mismatch errors. Since you have the platform to compile, would you mind fixing those and submit a pull request?

**Comment by vmaffione** [comment]
this should be solved
