### ISSUE TITLE
OpenWRT Makefile does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luigirizzo/netmap#36]
```
Hello!

The OpenWRT Makefile is currently not working with the OpenWRT 14.07 version.
I made some changes in order to work properly. I provide a patch with the 
changes.
I hope you can add them to the tree :)

Carlos Ferreira
```

Original issue reported on code.google.com by `carlosmf...@gmail.com` on 25 Nov 2014 at 9:48

Attachments:
- [openWRT-Makefile.patch](https://storage.googleapis.com/google-code-attachments/netmap/issue-36/comment-0/openWRT-Makefile.patch)

**Comment by vmaffione** [comment]
Hi,
  Could you please report the steps required to build OpenWRT with netmap enabled? Or maybe provide a link page with further instructions?

**Comment by davidzodelin** [comment]
Hello, I have tried again with the Makefile you published and the same result, I failed to compile all the modules I selected from Netmap. The steps I follow are to select the Netmap modules and start compiling the LEDE Firmware. I do not know if it will have to patch before the kernel? Any ideas?
