### ISSUE TITLE
pkt-gen shows packets sent while interface has no carrier with i40e

### ISSUE THREAD

**Issue by borislavmatvey** [luigirizzo/netmap#366]
If cable is disconnected while sending packets with `pkt-gen` over i40e interface, then `pkt-gen` will continue reporting generated packets, although they cannot actually exit the interface.

Start with:

```
./pkt-gen -i eth0 -f tx -n 0 -l 1500
```

While above is running physically unplug the cable from the interface. After this `pkt-gen` will continue reporting packets being sent:

```
265.331813 main_thread [2416] 4.113 Mpps (4.117 Mpkts 49.402 Gbps in 1001015 usec) 4.72 avg_batch 99999 min_space
266.332822 main_thread [2416] 4.111 Mpps (4.115 Mpkts 49.386 Gbps in 1001008 usec) 4.72 avg_batch 99999 min_space
267.333830 main_thread [2416] 4.112 Mpps (4.116 Mpkts 49.392 Gbps in 1001009 usec) 4.72 avg_batch 99999 min_space
268.334838 main_thread [2416] 4.112 Mpps (4.116 Mpkts 49.390 Gbps in 1001008 usec) 4.73 avg_batch 99999 min_space
269.335845 main_thread [2416] 4.112 Mpps (4.116 Mpkts 49.394 Gbps in 1001007 usec) 4.74 avg_batch 99999 min_space
```

Checking the flags for eth0 with `ip link show dev eth0` will show:

```
i40e: <NO-CARRIER,BROADCAST,MULTICAST,UP> ...
```

I tried with ixgbe interface and there the packets report stops after the cable is unplugged, showing 0 pps transmitted.

**Comment by vmaffione** [comment]
Maybe we should check both?

**Comment by borislavmatvey** [comment]
@vmaffione maybe bug is more accurate label
