### ISSUE TITLE
lb stops forwarding packets to correct output_ring

### ISSUE THREAD

**Issue by m1357** [luigirizzo/netmap#371]
System is FreeBSD 11.1p1. After lb has run for a while, it begins to report the following:
 
{"ts":1505936087.400130,"interface":"netmap:ix0","output_ring":null,"packets_received":1228069980,"packets_forwarded":1167970528,"packets_dropped":59267429,"non_ip_packets":7077,"data_forward_rate_Mbps":8212.2356,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":812.1040,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}

This is followed by all traffic stopping to bro workers.  all stats after this report the output_ring as null

sysctl of netmap 

 sysctl -a | grep netmap
device	netmap
dev.netmap.ixl_rx_miss_bufs: 0
dev.netmap.ixl_rx_miss: 0
dev.netmap.iflib_rx_miss_bufs: 0
dev.netmap.iflib_rx_miss: 0
dev.netmap.iflib_crcstrip: 1
dev.netmap.bridge_batch: 1024
dev.netmap.default_pipes: 0
dev.netmap.priv_buf_num: 4098
dev.netmap.priv_buf_size: 2048
dev.netmap.buf_curr_num: 1000000
dev.netmap.buf_num: 1000000
dev.netmap.buf_curr_size: 2048
dev.netmap.buf_size: 2048
dev.netmap.priv_ring_num: 4
dev.netmap.priv_ring_size: 20480
dev.netmap.ring_curr_num: 800
dev.netmap.ring_num: 800
dev.netmap.ring_curr_size: 131072
dev.netmap.ring_size: 131072
dev.netmap.priv_if_num: 1
dev.netmap.priv_if_size: 1024
dev.netmap.if_curr_num: 100
dev.netmap.if_num: 100
dev.netmap.if_curr_size: 1024
dev.netmap.if_size: 1024
dev.netmap.generic_rings: 1
dev.netmap.generic_ringsize: 1024
dev.netmap.generic_mit: 100000
dev.netmap.admode: 0
dev.netmap.fwd: 0
dev.netmap.flags: 0
dev.netmap.adaptive_io: 0
dev.netmap.txsync_retry: 2
dev.netmap.no_pendintr: 1
dev.netmap.mitigate: 1
dev.netmap.no_timestamp: 0
dev.netmap.verbose: 0
dev.netmap.ix_rx_miss_bufs: 371353443
dev.netmap.ix_rx_miss: 256791211
dev.netmap.ix_crcstrip: 0

**Comment by m1357** [comment]
Lowering buf_num to 900000 seems to prolong the crash (took almost a full day). 
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"p[root@itsec-prod-bro-5 ~/scripts]# tail nohup.out
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}
{"ts":1506018166.458372,"interface":"netmap:ix0","output_ring":null,"packets_received":41897008932,"packets_forwarded":36239100055,"packets_dropped":5657254911,"non_ip_packets":327746,"data_forward_rate_Mbps":5844.0955,"data_drop_rate_Mbps":0.0000,"packet_forward_rate_kpps":748.4600,"packet_drop_rate_kpps":0.0000,"free_buffer_slots":0}

**Comment by vmaffione** [comment]
Is this still reproducible?
