### ISSUE TITLE
NetMap in interrupt mode

### ISSUE THREAD

**Issue by murali-rd** [luigirizzo/netmap#372]
hi,

The NetMap uses polling instead of the interrupt mechanism to notify the packet arrivals, its understand  that it helps in fast packet processing and for optimizing the performance. But do we have option in netmap for using interrupt mechanism instead of default netmap polling mechanism. 
are NETMAP_BDG_POLLING_OFF and NETMAP_BDG_POLLING_ON meant for this?

thanks and regards,
murali

**Comment by vmaffione** [comment]
No, netmap uses interrupts normally (see the netmap papers, man page and README. Those flags are only for when you attach a physical NIC to a VALE switch.
