### ISSUE TITLE
Feasible to add metadata at end of buffer?

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#373]
Hi, I'm fascinated by Netmap but am not a packet processing expert like you guys. So here's my (hopefully not silly) question that came up while learning Netmap:

For a packet processing application I thought about adding metadata to packets before they enter the processing chain. Most importantly ingress interface.

The idea is that regular Ethernet frames (not jumbo frames) have max size of 1514 Byte (without VLAN tag). Those they are always smaller than the 2048 Byte Netmap buffer size. So as a side-effect there should already be some room left at the end of the buffer.

It would be great if somebody can confirm that it's feasible to use for example the last 100 Byte of the 2kb Netmap buffer for application internal metadata.

Many thanks, Franz

**Comment by vmaffione** [comment]
Yes, you are free to use them. You can also use the per-slot 64 bytes here https://github.com/luigirizzo/netmap/blob/master/sys/net/netmap.h#L169 (unless you use indirect buffers on VALE ports).

**Comment by ramaza** [comment]
Thanks for your helpful answer! I hope it's ok if I open a new issue for another question.
