### ISSUE TITLE
Are Netmap-pipes and "unbound buffers" the same?

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#375]
Hi, while learning Netmap I try to better understand multithreading and also IPC in combination with Netmap.

There's quite some explanation around Netmap-pipes. To me as a newcomer it sound like a good approach to pass a buffer descriptor via Netmap-pipes from one process (producer) to another (consumer). But my gut-feeling says there is likely a better way for multithreaded applications. The manpage briefly mentions "unbound buffers". But I'm not sure how it differs from Netmap-pipes and if it's the thing I should try to better understand.

I guess I'm just looking for a hint on the recommended approach to design a Netmap application that behaves like a unidirectional chain of Netmap-interlinked threads. Meaning a packet processing application with mulitple threads where only the first and last thread in the chain are actually talking to a NIC.

Many thanks in advance!

**Comment by vmaffione** [comment]
"Unbound buffers" in the man page refers to the netmap "extra buffers" that you can ask at NIOCREGIF time (for whatever netmap port). It's an advanced feature, and I don't think you need it if you want to build a chain of processes communicating through netmap pipes.

Netmap pipes are a particular kind of netmap ports, that can be used for very fast zero-copy local IPC. There is no particular relationship with the "extra buffers".

Building a chain like you say:
````
netmap:eth0 <--->[ Proc1 ]<---> netmap:pipe{0 == netmap:pipe}0 <---> [Proc2]<---> netmap:pipe{1 == netmap:pipe}1 <---> [Proc3] <---> netmap:eth1
````
is very common and makes sense for many deployments. The Proc1, Proc2, etc. can be separate processes or separate threads in the same process; it does not make any difference for netmap.
You can build a simple chain like that using the `bridge` program (that just forwards between two ports), and then extend `bridge` with your custom processing. Example:
````
# bridge netmap:eth0 netmap:pipe{0 &
# bridge netmap:pipe}0 nemap:pipe{1 &
# bridge netmap:pipe}1 netmap:eth1 &
````
You may also want to take a look at the netmap tutorial: https://github.com/vmaffione/netmap-tutorial

**Comment by ramaza** [comment]
I will definitely look at your Netmap tutorial.

If I understood correct then Netmap pipes are the recommended solution for passing Netmap buffers between processes AND between threads as well. Those it might be easier to implement the envisioned processing chain with separate processes (instead of separate threads). Like you nicely described with the bridge-example.

Maybe you can once more confirm that the Netmap related processing overhead is perfectly similar between threads AND between processes as well. Because in both cases the same amount of NIOCTXSYNC and NIOCRXSYNC system calls are happening, right?

**Comment by vmaffione** [comment]
Yes, there is no difference as you say.

Il 3 ott 2017 7:39 AM, "ramaza" <notifications@github.com> ha scritto:

**Comment by ramaza** [comment]
Great. Many thanks!

**Comment by ramaza** [comment]
You thankfully provided the following example related to Netmap pipes. After reading more about Netmap pipes and starting to play around with it I'm afraid I'm now confused as to how zero-copy feature can be achieved through the whole chain.

`netmap:eth0 <--->[ Proc1 ]<---> netmap:pipe{0 == netmap:pipe}0 <---> [Proc2]<---> netmap:pipe{1 == netmap:pipe}1 <---> [Proc3] <---> netmap:eth1`

As far as I understand a pipe needs to share the name of a real Ethernet interface to enable zero-copy. For example "netmap:eth0{0". But which pipes in your example should now share the name of "eth0" and which one should share the name of "eth1".

Would be great if you can give a hint that helps me to resolve my confusion. Many thanks!

**Comment by giuseppelettieri** [comment]
Hi @ramaza,

that example works since both eth0 and eth1 are "hardware ports" and therefore they both use the same memory region.

Please be aware, however, that this implicit sharing of memory among all hardware ports is legacy netmap behaviour and may change in the future. A new syntax will be made available to specify more precisely when and how you want to share memory.

**Comment by vmaffione** [comment]
But you are right that zerocopy is not possible in the example. You can fix it in this way.
````
netmap:eth0 <--->[ Proc1 ]<---> netmap:eth0{0 == netmap:eth0}0 <---> [Proc2]<---> netmap:eth0{1 == netmap:eth0}1 <---> [Proc3] <---> netmap:eth1
````

As @giuseppelettieri says, this works because netmap:eth1 and netmap:eth0 are in the same memory region by default. On the other hand, `netmap:pipe` is a netmap port that uses a separate memory region, so zerocopy wouldn't be possible with hardware ports.

**Comment by ramaza** [comment]
Makes sense. Thank you both for the explanation.

Is there maybe an API feature that I missed which helps to create Netmap pipes with arbitrary names and among different processes and still keep them in the global memory region?

For example a chain of netmap-processes without any real hardware interface involved. Although I have to admit that it's a rather useless example in practice.

**Comment by ramaza** [comment]
I guess I found the answer to my last question about API feature to force global memory region. It's the "nr_arg2" argument in combination with NIOCREGIF ioctl.

Would be great though if you can confirm that it also works for pipes with arbitrary names.

**Comment by giuseppelettieri** [comment]
Yes, that works for any netmap port, with the caveat that you cannot change the memory region of an already opened port, so you should always check the contents of nr_arg2 after the NIOCREGIF to see what memory region was actually assigned.

nm_open() understands the '@num' syntax for setting nr_arg2. Therefore, if you happen to now the id of the memory region (e.g., the global one has id 1), you can do something like:

netmap:pipe{0@1

to (try to) open pipe{0 in region 1.

At the moment, the only way to know the memory region assigned to a port is to write a program that calls NIOGETINFO on the port and reads nr_arg2.

**Comment by ramaza** [comment]
As far as I understand the different memory regions are not a performance related aspect but much more a security aspect, right?

As my application is a typical networking middlebox I guess it's ok to have all ports in the global region.

**Comment by vmaffione** [comment]
It's performance related, because you can only zerocopy forward between two ports that are in the same memory region. If they are not in the same region you can only copy.
If two processes sharing the same netmap memory region is a security concern for you, you can use separate regions and copy.

**Comment by ramaza** [comment]
I'm afraid I formulated my question ambiguous. I will rephrase:

Are there any other reasons (next to security concerns) to NOT keep all Netmap ports (hardware ports, pipes, ...) in one global memory region?

**Comment by vmaffione** [comment]
No, or at least I cannot think of any. Different memory regions are used to provide isolation/security between applications.

**Comment by ramaza** [comment]
Great. I think I slowly get the hang of Netmap :blush:

I still have difficulties to understand some aspects of the memory allocation process. But that's a topic for a separate thread.
