### ISSUE TITLE
Packet drops on first runs of RX pkt-gen

### ISSUE THREAD

**Issue by borislavmatvey** [luigirizzo/netmap#376]
While playing with one 2 port x520 card sending traffic from the second port to the first I encountered #355. After applying the [patch](https://github.com/luigirizzo/netmap/issues/355#issuecomment-331156069) provided I encountered a different issue - the RX pkt-gen was not receiving all the packets generated by TX pkt-gen. It receives packets for a couple of seconds and then it either stops or receives just part of the generated traffic. The missing packets are counted as `rx_no_dma_resources` on the RX interface, which according to the datasheet should mean that there is no free space in the ring(s) for the NIC to fill with RX packets.

Steps to reproduce:
1. Reload netmap and ixgbe driver.
1. Start TX pkt-gen against the other port, e.g.:

    ```
    ./pkt-gen-b -i eth1 -f tx -s 10.10.145.110 -D xx:xx:xx:xx:xx:xx -a 6 -R 30 -Z
    ```
1. Wait a couple of seconds. Note that if you wait a couple of minutes the problem is not present.
1. Start RX pkt-gen to listen for incoming packets, e.g.:

    ```
    ./pkt-gen -f rx -i eth0

    428.693988 main [2700] interface is eth0
    428.694040 main [2825] using default burst size: 512
    428.694080 main [2833] running on 1 cpus (have 44)
    428.694514 extract_ip_range [464] range is 10.0.0.1:1234 to 10.0.0.1:1234
    428.694545 extract_ip_range [464] range is 10.1.0.1:1234 to 10.1.0.1:1234
    428.694568 nm_open [856] overriding ARG1 0
    428.694582 nm_open [860] overriding ARG2 0
    428.694597 nm_open [864] overriding ARG3 0
    428.694608 nm_open [868] overriding RING_CFG
    428.694618 nm_open [877] overriding ifname eth0 ringid 0x0 flags 0x8001
    429.071818 main [2932] mapped 334980KB at 0x7fbabdca4000
    Receiving from netmap:eth0: 44 queues, 1 threads and 1 cpus.
    429.071846 start_threads [2375] Wait 2 secs for phy reset
    431.071940 start_threads [2377] Ready...
    431.072011 receiver_body [1725] reading from netmap:eth0 fd 3 main_fd 3
    432.073017 main_thread [2465] 121.000 pps (121.000 pkts 58.080 Kbps in 1001045 usec) 6.72 avg_batch 0 min_space
    433.074081 main_thread [2465] 10.000 pps (10.000 pkts 4.800 Kbps in 1001064 usec) 1.00 avg_batch 511 min_space
    434.075140 main_thread [2465] 15.000 pps (15.000 pkts 7.200 Kbps in 1001060 usec) 1.00 avg_batch 511 min_space
    435.076198 main_thread [2465] 12.000 pps (12.000 pkts 5.760 Kbps in 1001058 usec) 1.00 avg_batch 511 min_space
    436.077244 main_thread [2465] 19.000 pps (19.000 pkts 9.120 Kbps in 1001046 usec) 1.27 avg_batch 507 min_space
    437.078302 main_thread [2465] 7.000 pps (7.000 pkts 3.360 Kbps in 1001058 usec) 1.00 avg_batch 511 min_space
    438.079357 main_thread [2465] 18.000 pps (18.000 pkts 8.640 Kbps in 1001055 usec) 1.38 avg_batch 506 min_space
    439.080416 main_thread [2465] 16.000 pps (16.000 pkts 7.680 Kbps in 1001059 usec) 2.29 avg_batch 502 min_space
    440.081485 main_thread [2465] 11.000 pps (11.000 pkts 5.280 Kbps in 1001069 usec) 2.20 avg_batch 505 min_space
    441.082552 main_thread [2465] 2.000 pps (2.000 pkts 960.000 bps in 1001066 usec) 1.00 avg_batch 511 min_space
    442.083619 main_thread [2465] 4.000 pps (4.000 pkts 1.920 Kbps in 1001068 usec) 1.00 avg_batch 511 min_space
    443.084684 main_thread [2465] 6.000 pps (6.000 pkts 2.880 Kbps in 1001065 usec) 1.00 avg_batch 511 min_space
    ```

    While the above happens `rx_no_dma_resource` is counting the packets which are not received and TX pkt-gen is solid 30pps.

Notes:
  1. Subsequent calls of RX pkt-gen usually doesn't experience the problem until you reload the drivers again.

  1. NetMap is latest 3a100e22ac0a1a4289c137a07ad31a437783f017 with [patch](https://github.com/luigirizzo/netmap/issues/355#issuecomment-331156069) by @giuseppelettieri in #355

  1. Linux kernel is 4.9.50

**Comment by borislavmatvey** [comment]
Forgot to mention that I'm using ixgbe, native mode.

**Comment by giuseppelettieri** [comment]
Does this bug also depends on the Intel ixgbe driver version? I.e., do you see it if you use, say, ixgbe 4.5.4?

**Comment by borislavmatvey** [comment]
You are correct, it actually depends on ixgbe version. I tried with different versions and the issue is introduced in 5.2.1, the previous version - 5.1.3 works OK.

I also noted that the first batch of packets RX pkt-gen reports is different based on whether the issue is present:

* issue not present:

    ```
    011.464049 receiver_body [1725] reading from netmap:eth0 fd 3 main_fd 3
    012.465019 main_thread [2465] 7.000 pps (7.000 pkts 5.072 Kbps in 1001048 usec) 1.00 avg_batch 0 min_space
    013.466092 main_thread [2465] 30.000 pps (30.000 pkts 14.400 Kbps in 1001073 usec) 1.00 avg_batch 511 min_space
    014.467174 main_thread [2465] 32.000 pps (32.000 pkts 15.360 Kbps in 1001083 usec) 1.00 avg_batch 511 min_space
    ```

* issue present:

    ```
    431.072011 receiver_body [1725] reading from netmap:eth0 fd 3 main_fd 3
    432.073017 main_thread [2465] 121.000 pps (121.000 pkts 58.080 Kbps in 1001045 usec) 6.72 avg_batch 0 min_space
    433.074081 main_thread [2465] 10.000 pps (10.000 pkts 4.800 Kbps in 1001064 usec) 1.00 avg_batch 511 min_space
    434.075140 main_thread [2465] 15.000 pps (15.000 pkts 7.200 Kbps in 1001060 usec) 1.00 avg_batch 511 min_space
    ```

I wonder whether there could be a change in the configuration sequence after `NIOCREGIF` between the two drivers.

**Comment by giuseppelettieri** [comment]
Does anything change if you use the current master? (note: it already includes the patch in #355)

**Comment by borislavmatvey** [comment]
Yep, the issue is not present anymore. 1597e0cb9e7b541f11d9c9aad2afe620ea339596 nails it.

Thank you!
