### ISSUE TITLE
VPP support?

### ISSUE THREAD

**Issue by rmurthy716** [luigirizzo/netmap#380]
Hi I'm trying to run mtcp on top of netmap which will be on top of vpp. I've gotten vpp working and mtcp/netmap to work but I can't seem to stitch the two together. I know vpp has their own branch but I can't get it to compile with my kernel version on ubuntu due to a change in some of the bsd structures. 

Specifically the error is this:

/path/netmap/LINUX/bsd_glue.h:128:26: error: ‘struct page’ has no member named ‘count’
atomic_set(&(page)[i].count, 1);

The latest version of netmap compiles on my system and I can see in the issues history that this was resolved. However, I'm wondering if there's anything special in the vpp branch of netmap that the master branch does not have that's preventing this from working. Any help would be appreciated. Thanks!

**Comment by rmurthy716** [comment]
Also if this is relevant when I insert the module I can see an error is dmesg when making the device node netmap_init               run mknod /dev/netmap c 10 55 # error 0.

When creating the netmap interfaces in vpp I can see in dmesg that the interface is created. netmap_vp_create          nr_arg2 0

Running the packet generator works with the new interface created

ip netns exec vpp1 ./pkt-gen -i vale00:vpp1 -f tx -c 1 -a 0 -b 64

However, when running vppctl show interfaces I don't see any frames being transmitted or received even though the interfaces have a layer 2 connection. 

set int l2 xcon netmap-vale00:vpp1 netmap-vale00:vpp2 
set int l2 xcon netmap-vale00:vpp2 netmap-vale00:vpp1

**Comment by vmaffione** [comment]
This
````
netmap_init run mknod /dev/netmap c 10 55 # error 0
````
is not an error (return code is 0).

What "vpp" branch are you talking about, exactly? I am not aware of any vpp branch in netmap.

**Comment by rmurthy716** [comment]
Thanks for the response! Here is a link to the vpp branch [](https://github.com/vpp-dev/netmap)

**Comment by rmurthy716** [comment]
Looking at the commit history it appears there's only one commit that does not match the master branch commit history 

https://github.com/vpp-dev/netmap/commit/36333539b4b316467540511e8587f427403f0957

**Comment by vmaffione** [comment]
It seems this "vpp branch" is simply a very outdated version of netmap, with a custom patch to disable namespaces.
In any case the branch is not part of the official netmap repository (this one), so it's not something we maintain.

**Comment by rmurthy716** [comment]
Merging the change worked for the mtcp example, but I'm having issues using the pkt_gen program is still having issues. However, this is out of scope for this project. Thanks for the help!
