### ISSUE TITLE
Question about netmap mode

### ISSUE THREAD

**Issue by bvital1976** [luigirizzo/netmap#385]
Hi

Is it possible to find out in which mode works underling NIC, native or emulated? I need this to properly choose Ethernet interface name in case of VLANs. For example, I am going to attach to eth1.100 in case of underling NIC eth1 is in emulated mode or to eth1 if it works in native mode.

**Comment by vmaffione** [comment]
The emulated mode is a fallback (and has its own limitations, for instance your netmap application wont' see the VLAN header, see the LINUX/README).
You should always use the native mode when available.

For now there is no direct way to know which mode you are using, unfortunately. But you can check which one is being used by looking at the kernel log. If you see something like:
````
[53150.498342] 355.675848 [1259] generic_netmap_attach     Emulated adapter for eth0 created (prev was           (null))
````
it means that `eth0` was put in netmap emulated mode.
