### ISSUE TITLE
Need help understanding netmap extra buffers

### ISSUE THREAD

**Issue by muratbalaban43** [luigirizzo/netmap#390]
Hi netmap tiger team!

I'm allocating extra buffers via the nr_arg3 parameters for NIOCREGIF.

Question is do I need to kind of release these buffers when my application shuts down? Does that happen automatically when the kernel closes file descriptor associated with a netmap instance?

What I happen to see with FreeBSD 11.1-STABLE is that, when my application shuts down the buffers are not released, and when the app starts working again I happen to allocate just some more memory for the buffers. Some logs below:

ov  1 11:26:28 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:26:29 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:27:55 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:27:55 bsd11_1 kernel: 875.774027 [2215] netmap_ioctl              requested 10000 extra buffers
Nov  1 11:27:55 bsd11_1 kernel: 875.774087 [ 736] netmap_extra_alloc        allocate buffer 51027 -> 0
Nov  1 11:27:55 bsd11_1 kernel: 875.774116 [ 736] netmap_extra_alloc        allocate buffer 51028 -> 51027
Nov  1 11:27:55 bsd11_1 kernel: 875.774140 [ 736] netmap_extra_alloc        allocate buffer 51029 -> 51028
Nov  1 11:27:55 bsd11_1 kernel: 875.774163 [ 736] netmap_extra_alloc        allocate buffer 51030 -> 51029
Nov  1 11:27:55 bsd11_1 kernel: 875.774185 [ 736] netmap_extra_alloc        allocate buffer 51031 -> 51030
Nov  1 11:27:55 bsd11_1 kernel: 875.775415 [2218] netmap_ioctl              got 10000 extra buffers
Nov  1 11:27:56 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:44:19 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:44:20 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:44:59 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:44:59 bsd11_1 kernel: 899.338604 [2215] netmap_ioctl              requested 10000 extra buffers
Nov  1 11:44:59 bsd11_1 kernel: 899.338641 [ 736] netmap_extra_alloc        allocate buffer 61027 -> 0
Nov  1 11:44:59 bsd11_1 kernel: 899.338681 [ 736] netmap_extra_alloc        allocate buffer 61028 -> 61027
Nov  1 11:44:59 bsd11_1 kernel: 899.338707 [ 736] netmap_extra_alloc        allocate buffer 61029 -> 61028
Nov  1 11:44:59 bsd11_1 kernel: 899.338733 [ 736] netmap_extra_alloc        allocate buffer 61030 -> 61029
Nov  1 11:44:59 bsd11_1 kernel: 899.338758 [ 736] netmap_extra_alloc        allocate buffer 61031 -> 61030
Nov  1 11:44:59 bsd11_1 kernel: 899.340054 [2218] netmap_ioctl              got 10000 extra buffers
Nov  1 11:45:00 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:45:02 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:45:03 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:45:13 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:45:13 bsd11_1 kernel: 913.183336 [2215] netmap_ioctl              requested 10000 extra buffers
Nov  1 11:45:13 bsd11_1 kernel: 913.183374 [ 736] netmap_extra_alloc        allocate buffer 71027 -> 0
Nov  1 11:45:13 bsd11_1 kernel: 913.183398 [ 736] netmap_extra_alloc        allocate buffer 71028 -> 71027
Nov  1 11:45:13 bsd11_1 kernel: 913.183421 [ 736] netmap_extra_alloc        allocate buffer 71029 -> 71028
Nov  1 11:45:13 bsd11_1 kernel: 913.183444 [ 736] netmap_extra_alloc        allocate buffer 71030 -> 71029
Nov  1 11:45:13 bsd11_1 kernel: 913.183467 [ 736] netmap_extra_alloc        allocate buffer 71031 -> 71030
Nov  1 11:45:13 bsd11_1 kernel: 913.185370 [2218] netmap_ioctl              got 10000 extra buffers
Nov  1 11:45:14 bsd11_1 kernel: em0: link state changed to UP
Nov  1 11:45:16 bsd11_1 kernel: em0: link state changed to DOWN
Nov  1 11:45:17 bsd11_1 kernel: em0: link state changed to UP

**Comment by giuseppelettieri** [comment]
Yes, unfortunately. The version of netmap available here and in FreeBSD HEAD will free the buffers by itself when everybody has stopped using a memory region, but the version included in 11.1 does not.

To free the buffers you need to recreate the linked list before closing the netmap file descriptor. If you crash before that, you leak.

**Comment by muratbalaban43** [comment]
Hi Giuseppe,

Thanks for the swift reply. Understood. 

Any plans to merge it back to FreeBSD 11.1?

**Comment by vmaffione** [comment]
We are not FreeBSD committers, so we can't do that directly.
If we find a committer willing to do that, we could prepare a patch to update the netmap source files.

**Comment by muratbalaban43** [comment]
Thanks for the answer and for netmap at all!.
