### ISSUE TITLE
nm_dispatch does not handle multiple rings correctly

### ISSUE THREAD

**Issue by aayla-secura** [luigirizzo/netmap#392]
`nm_dispatch` loops through the rings starting from the `cur_rx_ring`, incrementing each time. But when it determines it has gone over the last one, it keeps checking the `first_rx_ring`, rather than wrapping around properly:

```
for (c=0; c < n && cnt != got; c++) {
		...
		
		ri = d->cur_rx_ring + c;
		if (ri > d->last_rx_ring)
			ri = d->first_rx_ring;
```

So unless always setting `cur_rx_ring` to `first_rx_ring` before calling `nm_dispatch` (and hence avoiding the wrapping), all rings after the first and before the current will not be checked.

**Comment by giuseppelettieri** [comment]
You are right. May you please try the following patch?

```
diff --git a/sys/net/netmap_user.h b/sys/net/netmap_user.h
index d8cf04d..066cb46 100644
--- a/sys/net/netmap_user.h
+++ b/sys/net/netmap_user.h
@@ -1072,9 +1072,6 @@ nm_dispatch(struct nm_desc *d, int cnt, nm_cb_t cb, u_char *arg)
                /* compute current ring to use */
                struct netmap_ring *ring;
 
-               ri = d->cur_rx_ring + c;
-               if (ri > d->last_rx_ring)
-                       ri = d->first_rx_ring;
                ring = NETMAP_RXRING(d->nifp, ri);
                for ( ; !nm_ring_empty(ring) && cnt != got; got++) {
                        u_int idx, i;
@@ -1090,6 +1087,9 @@ nm_dispatch(struct nm_desc *d, int cnt, nm_cb_t cb, u_char *arg)
                        d->hdr.ts = ring->ts;
                        ring->head = ring->cur = nm_ring_next(ring, i);
                }
+               ri++;
+               if (ri > d->last_rx_ring)
+                       ri = d->first_rx_ring;
        }
        if (d->hdr.buf) { /* from previous round */
                d->hdr.flags = 0;
```

**Comment by vmaffione** [comment]
it seems that `nm_inject()` has the same broken logic

**Comment by aayla-secura** [comment]
Yes, the above fixes it. Though there is no direct way to check, since `cur_rx_ring` is not modified before calling the `cb` handler. May I suggest doing so? Also for `nm_inject`, it would be easier to just increment ri as part of the loop definition, which works for `nm_dispatch` too:

```
diff --git a/sys/net/netmap_user.h b/sys/net/netmap_user.h
index d8cf04d1..03622e34 100644
--- a/sys/net/netmap_user.h
+++ b/sys/net/netmap_user.h
@@ -1024,13 +1024,13 @@ fail:
 static int
 nm_inject(struct nm_desc *d, const void *buf, size_t size)
 {
-	u_int c, n = d->last_tx_ring - d->first_tx_ring + 1;
+	u_int c, n = d->last_tx_ring - d->first_tx_ring + 1,
+		ri = d->cur_tx_ring;
 
-	for (c = 0; c < n ; c++) {
+	for (c = 0; c < n ; c++, ri++) {
 		/* compute current ring to use */
 		struct netmap_ring *ring;
 		uint32_t i, idx;
-		uint32_t ri = d->cur_tx_ring + c;
 
 		if (ri > d->last_tx_ring)
 			ri = d->first_tx_ring;
@@ -1068,13 +1068,13 @@ nm_dispatch(struct nm_desc *d, int cnt, nm_cb_t cb, u_char *arg)
 	 * of buffers and the int is large enough that we never wrap,
 	 * so we can omit checking for -1
 	 */
-	for (c=0; c < n && cnt != got; c++) {
+	for (c=0; c < n && cnt != got; c++, ri++) {
 		/* compute current ring to use */
 		struct netmap_ring *ring;
 
-		ri = d->cur_rx_ring + c;
 		if (ri > d->last_rx_ring)
 			ri = d->first_rx_ring;
+		d->cur_rx_ring = ri;
 		ring = NETMAP_RXRING(d->nifp, ri);
 		for ( ; !nm_ring_empty(ring) && cnt != got; got++) {
 			u_int idx, i;
@@ -1095,7 +1095,6 @@ nm_dispatch(struct nm_desc *d, int cnt, nm_cb_t cb, u_char *arg)
 		d->hdr.flags = 0;
 		cb(arg, &d->hdr, d->hdr.buf);
 	}
-	d->cur_rx_ring = ri;
 	return got;
 }
```

**Comment by aayla-secura** [comment]
On a side note, I spotted this bug while I was trying to figure out in what order netmap fills the rx rings. It seems to me that it only fills the current ring and will drop packets when that one fills up even if the rest are empty, is that true? In which case there would be a performance gain if one does `NIOCRXSYNC` after checking each ring. I don't know if it would make sense to do that in `nm_dispatch`.

**Comment by giuseppelettieri** [comment]
Netmap only gives you (protected) access to the hardware rings. The RX filling pattern is determined by your card settings and the traffic, not by anything that netmap does.

**Comment by aayla-secura** [comment]
Sorry I should have clarified, I am wondering how vale ports are filled. I am testing with two vale ports, `vi0` and `vi1`, attached to the same vale switch, `vale0`. I send (`nm_inject`) on `vale0:vi0`, and receive on `vale0:vi1` and as expected there is no correlation between which tx ring on `vi0` the packet is injected to and which rx ring in `vi1` it is received in. So I'm wondering at least for vale ports how the rx ring to be used is determined.

**Comment by giuseppelettieri** [comment]
Ah, OK. The default VALE behaviour is to put packets on the output ring numbered like the input one (modulo the number of available rings). Moreover, broadcasts always go to ring 0. The former behaviour can be changed by installing your own VALE lookup functions. This requires writing a kernel module, though.

**Comment by aayla-secura** [comment]
I see, thanks for clarifying!

**Comment by giuseppelettieri** [comment]
@aayla-secura, may you please create a merge request with your patch? It is easier and follow and comment that way.

**Comment by aayla-secura** [comment]
Yes, did that (after commiting with wrong authorship, having to squash that commit).

**Comment by giuseppelettieri** [comment]
Merged, thank!
