### ISSUE TITLE
Purpose of overflow queue in load balancer example

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#396]
Hi! What is the idea behind the overflow queue in the load balancer example? It looks like it's optional but I'm sure there is a good reason why it was implemented.

Many thanks in advance for helping me to understand this detail.

**Comment by giuseppelettieri** [comment]
There is an optional pool of buffers that can be used to temporarily extend any of the output pipes rings with an "overflow queue". This helps avoid dropping packets when some client on the receiving side of a pipe undergoes unexpected delays or longer-than-usual per-packet processing times.

The mechanics also tries to prevent a dead client from keeping the pool empty: before dropping new packets, some buffers are stolen from the longest extant overflow queue.

**Comment by giuseppelettieri** [comment]
I am closing this. Please reopen if you need further clarification.
