### ISSUE TITLE
Memory leak in kernel

### ISSUE THREAD

**Issue by borislavmatvey** [luigirizzo/netmap#397]
I noticed that latest NetMap (e76c23000a4f5237f82a715dd1473801a59b5f81) consumes increasingly more and more memory until the machine reboots itself.

This is reproducible only if you start `pkt-gen` on two (probably more) interfaces simultaneously. I used this script to reproduce the issue fast:

```bash
for ((;;)); do for i in {0..1}; do ./pkt-gen -i eth${i}-0 -f rx &>/dev/null & done; sleep 7; killall pkt-gen; done
```

You can monitor the memory continuously increasing using `watch -n 1 -d free -m`. At some point OOM will start wreaking havoc.

Looks like it was introduced recently, as on 3c3ab5faa2ab9c89db09cd8339d0e96a1a78c41a it is not reproducible.

**Comment by vmaffione** [comment]
Hi, the commit you refer to as "the latest netmap" actually looks older (Jun 29). Can you retry on the current master?

**Comment by borislavmatvey** [comment]
Sorry, copied an old SHA1.

I retried with 2e4ddbbd9b036d110a83dded4d2e9bf5b212a05c and it reproduces.

**Comment by giuseppelettieri** [comment]
Hi @borislavmatvey. I cannot check by myself right now, but I am inclined to blame the new dma_mapping thing. May you please add some debug message to ```nm_alloc_plut``` and ```nm_free_plut``` (bot in ```sys/dev/netmap/netmap_mem2.c``` to check that the plut of each pkt-gen is correctly deallocated?

**Comment by borislavmatvey** [comment]
Hi, great suggestion. I added a print of the pointer to the memory allocated in `nm_alloc_plut` and then a print of the pointer passed to `nm_free_plut`. After running a couple of `pkt-gen`s the allocations match deallocations, sadly.

I noticed something else though - If I modify `LINUX/default-config.mak.in_` to use ixgbe 5.2.1, then the issue is not present. I'll try the other two intermediate versions and write again.

**Comment by borislavmatvey** [comment]
So this problem is reproduced only with ixgbe version 5.3.3. Hope this info helps.

Sorry, I missed to specify that I'm using ixgbe while playing with NetMap.

**Comment by giuseppelettieri** [comment]
Very helpful, thanks.

**Comment by giuseppelettieri** [comment]
may you please try with the current master? The last commit should be related to the memory leak.

**Comment by borislavmatvey** [comment]
Tried with 3415ba93f7d194e719d08c3253f35bb3327fe29b and the leak doesn't reproduce. Thanks for you effort!
