### ISSUE TITLE
hyper-V driver netvsc support?

### ISSUE THREAD

**Issue by guesslin** [luigirizzo/netmap#399]
Hi,

I'm trying to use netmap in Azure cloud for packet pipes. But it seems to me the netmap_generic driver in Azure did not perform as well as expected. So I'm looking for is there netmap driver for hyper-V. Does anyone has some ideas or researches?

**Comment by vmaffione** [comment]
There is currently no netmap support for netvsc, but it can be implemented (like we have support for virtio-net, for example).
Which performance are you looking for, and for which workload?
