### ISSUE TITLE
zerocopy swap not always successful

### ISSUE THREAD

**Issue by sunxiaoye0116** [luigirizzo/netmap#400]
I have a single thread netmap program that bridges a physical nic and the host stack and the program does the following things.
1. forward packets from host stack to the nic and vice versa using "zero-copy" (the same as what the bridge.c app does).
2. generate customized packets and send them to the physical nic ring (each of the customized packets is tagged with a contiguous sequence number).

However, I found that the buffer swap in zero-copy does not always successes which results in the packet in the original buffer got sent out.

There is a sequence of things happened in a concrete example.
assume the ring has 512 slots. 
1. customized packets [10] [11] [12] [13] are filled to slots [99] [100] [101] [102] respectively.
2. customized packets keep filling in slots.
3. then customized packets [522] [523] are filled into slots [99] [100].
4. a packet from the host stack is swapped to slot [101].
5. customized packet [524] is filled in slots [102]
However at the receiver side, it sees packet [10][11][12][13]...[522][523][12][524].
There is a duplicate [12].
I think this is due to the buffer swapping does not succeed so that the content in the old buffer got sent out.
This error happens randomly. it does not always fail.
This error won't happen if the program does not use zero-copy

I use nm_ring_space to check the number of remaining space in the ring before putting new packet to a slot.

I am using Linux 3.16.0-4-amd64, ixgbe driver (4.5.4) in netmap v11.3. ONLY one of the nic queue s is used by my netmap program.

**Comment by vmaffione** [comment]
There's a bunch of things that you can try to narrow down your issue.
You have already seen that doing copy instead of zerocopy removes the bug, so zerocopy is likely to be related.

You can try to see it the issue depends on the ixgbe patched driver. You can try to use the emulated netmap adapter instead of the native netmap adapter (just load netmap with `admode` parameter set to `2`), to see if the issue disappears.

**Comment by vmaffione** [comment]
Also, is there any reason why are you using v11.3? You should use the current master, which has many bugfixes that are not in v11.3.

**Comment by sunxiaoye0116** [comment]
Hi Vincenzo,
doing copy instead of zerocopy or set `admode` to 2 can remove the bug.

**Comment by vmaffione** [comment]
Ok. Can you you check if bug happens with current master?
Also, you should try to see if the bug disappears when switching to older version of ixgbe like 5.2.3, 5.2.1, 5.0.4, 4.5.4, or 4.4.6. You can change the version by modifying the corresponding line in this file `LINUX/default-config.mak.in_`.
