### ISSUE TITLE
ixgbe (external) tail issue

### ISSUE THREAD

**Issue by larseggert** [luigirizzo/netmap#404]
My NIC looks like this:
```
0.365   backend_init backend_netmap.c:141 tx ring 0 has 512 slots (1026-1537)
        backend_init backend_netmap.c:141 tx ring 1 has 512 slots (1538-2049)
        backend_init backend_netmap.c:148 rx ring 0 has 512 slots (2-513)
        backend_init backend_netmap.c:148 rx ring 1 has 512 slots (514-1025)
```
When placing a packet into ring 0, slot 0 and doing a TX, this is what happens:
```
        eth_tx eth.c:138 placing iov idx 2050 into tx ring 0 slot 0 (swap with 1026)
        eth_tx eth.c:154 Eth 90:e2:ba:39:39:51 -> 90:e2:ba:18:9b:3d, type 2048, len 98
        w_nic_tx backend_netmap.c:370 tx ring 0: old tail 511, tail 0, cur 1, head 1
        w_nic_tx backend_netmap.c:383 move idx 2050 from ring 0 slot 0 to w_iov (swap w/1026)
        w_nic_tx backend_netmap.c:370 tx ring 1: old tail 511, tail 127, cur 0, head 0
```
Ring 0 is fine, but the tail on ring 1 jumps by 127.

The same code runs fine on igb and i40e interfaces, so I suspect an ixgbe issue?

For comparison, here is what happens on an i40e NIC:
```
        eth_tx eth.c:138 placing iov idx 10242 into tx ring 0 slot 0 (swap with 5122)
        eth_tx eth.c:154 Eth 68:5:ca:32:b:98 -> 68:5:ca:32:15:d0, type 2048, len 98
        w_nic_tx backend_netmap.c:370 tx ring 0: old tail 511, tail 0, cur 1, head 1
        w_nic_tx backend_netmap.c:383 move idx 10242 from ring 0 slot 0 to w_iov (swap w/5122)
        w_nic_tx backend_netmap.c:370 tx ring 1: old tail 511, tail 511, cur 0, head 0
```
Here, ring 1 doesn't change when ring 0 is used for TX.

**Comment by giuseppelettieri** [comment]
May you try the current master? There was a missing initialization of the ixgbe heads, plus other silliness by myself.

**Comment by larseggert** [comment]
I am now getting a bunch of messages like the ones below with the *kernel* driver:
```
[ 1307.968143] 997.755649 [ 407] ixgbe_netmap_txsync       eth3 TX0: h 1
[ 1307.975333] 997.762839 [ 407] ixgbe_netmap_txsync       eth3 TX1: h 0
[ 1307.982672] 997.770178 [ 407] ixgbe_netmap_txsync       eth3 TX0: h 1
[ 1308.953694] 998.741208 [ 407] ixgbe_netmap_txsync       eth3 TX0: h 1
[ 1308.960881] 998.748395 [ 407] ixgbe_netmap_txsync       eth3 TX1: h 0
[ 1308.968223] 998.755737 [ 407] ixgbe_netmap_txsync       eth3 TX0: h 1
[ 1308.975413] 998.762927 [ 407] ixgbe_netmap_txsync       eth3 TX1: h 0
[ 1308.982751] 998.770265 [ 407] ixgbe_netmap_txsync       eth3 TX0: h 1
```

**Comment by larseggert** [comment]
Same outputs with external ixgbe driver. Performance in both cases is abysmal.

**Comment by giuseppelettieri** [comment]
Yep. Please pull again (debug message turned off).

**Comment by larseggert** [comment]
Done. Trying the external drivers first.

The good news is that the original issue (tail jumping after TX on an untouched ring is gone.

The bad news is that on the *second* TX on ring 0, tail doesn't seem to to move anymore:
```
        eth_tx eth.c:138 placing iov idx 2050 into tx ring 0 slot 0 (swap with 1026)
        w_nic_tx backend_netmap.c:370 tx ring 0: old tail 511, tail 511, cur 1, head 1
        w_nic_tx backend_netmap.c:370 tx ring 0: old tail 511, tail 0, cur 1, head 1
        w_nic_tx backend_netmap.c:381 move idx 2050 from ring 0 slot 0 to w_iov (swap w/1026)
        eth_tx eth.c:138 placing iov idx 2050 into tx ring 0 slot 1 (swap with 1027)
        w_nic_tx backend_netmap.c:370 tx ring 0: old tail 0, tail 0, cur 2, head 2
```

`tail` should have moved to 1 after the second TX (in the last line shown)

I will try the kernel drivers next.

**Comment by larseggert** [comment]
Same issue with kernel drivers.

**Comment by giuseppelettieri** [comment]
What are you using for sending? Is it ```poll()``` or ```ioctl(fd, NIOCTXSYNC)```?

**Comment by larseggert** [comment]
ioctl()

https://github.com/NTAP/warpcore/blob/master/lib/src/backend_netmap.c#L363

**Comment by larseggert** [comment]
I also set `NETMAP_NO_TX_POLL`, in case that matters?

https://github.com/NTAP/warpcore/blob/master/lib/src/backend_netmap.c#L90

**Comment by giuseppelettieri** [comment]
```NETMAP_NO_TX_POLL``` should not matter.

Unfortunately I cannot test on any ixgbe right now (I am at home with a flu), but I can give you enough information on what is going on, in case you want to investigate by yourself.

The relevant piece of code in ```LINUX/ixgbe_netmap_linux.h``` is
```
	if ((flags & NAF_FORCE_RECLAIM) || nm_kr_txempty(kring)) {
		u32 h = ACCESS_ONCE(*ina->heads[ring_nr].phead);
		ND(5, "%s: h %d", kring->name, h);
		kring->nr_hwtail = nm_prev(netmap_idx_n2k(kring, h), lim);
	}
```
which is executed with ```NAF_FORCE_RECLAIM``` set whenever you issue the ```ioctl()```. The ```ACCESS_ONCE``` is reading the ring head written back into memory by the NIC itself. ```netmap_idx_n2k``` should return ```h```, if ```kring->nkr_hwofs``` is zero (as it usually is). Therefore, the NIC head (minus 1) becomes the netmap ring tail that you than see (```kring->nr_hwtail``` is copied verbatim into the userspace ring ```tail``` later on).

So, unless there is some hardware misconfiguration, the ```tail``` you see ultimately comes from what the NIC itself is reporting. Is the second packet actually sent? Does ```tail``` remain constant forever, even after other ```ioctl(fd, NIOCTXSYNC)```s?

**Comment by larseggert** [comment]
Thanks, I'll dig around a bit.

Based on the last log I posted, you see that `head` is moving to 2, but `tail` stays at 0. So the code you quote above fails to set it to `head` minus 1?

How could the hardware be misconfigured?

**Comment by giuseppelettieri** [comment]
Sorry, there is something I did not tell you. The one you are referring to is the userspace ```head```, while I was talking about the _NIC_ head. When you advance the userspace ```head```, the NIC _tail_ is advanced. Conversely, when the NIC head is updated, the userspace ```tail``` is updated (by the code above).

The misconfiguration is possible, since the linux driver (either the one distributed with the kernel, or the Intel one) does not configure the NIC to write back its head into memory. Instead, the driver reads the NIC head from the ```TDH``` NIC register. It is the current netmap patch that changes this configuration, and we may have messed it up. It is possible that the write-back updates are rate-limited or coalesced, for example. Or something more serious is going on, and the NIC stops sending at all. This latter scenario can be excluded if you just check that the packets you are sending are actually received.

You can also revert to the old behaviour by defining ```NM_IXGBE_USE_TDH``` ad the beginning of ```LINUX/ixgbe_netmap_linux.h```, to force netmap to use the ```TDH```.

**Comment by larseggert** [comment]
Ah!

I was dumping out the netmap information (via RD in the block you quoted above) and looked at the corresponding trace from my code. It does look like there is a discrepancy between when netmap says the HW state is and what it reports up to the application.

I will build with `NM_IXGBE_USE_TDH` and report.

**Comment by larseggert** [comment]
I can confirm that defining `NM_IXGBE_USE_TDH` makes the issue go away.

**Comment by giuseppelettieri** [comment]
I am back at work and I am trying to reproduce what you see, but I am unable to. My setup on TX end:
```
ethtool -L enp1s0f0 combined 2
pkt-gen-b -i enp1s0f0 -ftxseq -R1
```
This will send one packet per second using ```ioctl()s``` instead of ```poll()```.  The ```txseq``` function only uses the first NIC ring.

In the ixgbe module I undef ```NM_IXGBE_USE_THD``` and turn on the debug message in the code snipped I showed above:
```
   RD(5, "%s: h %d", kring->name, h);
```
(this will print the ```h``` value at most 5 times per second)

On the RX end, I run
```
pkt-gen -i enp1s0f1 -frxseq
```

What I see is that all packets are received, and the kernel logs show the ```h``` value of the ```TX0``` ring go up regularly (the one from the ```TX1``` ring stays at 0). I have tried with IOMMU both enabled and disabled, and the results are the same.

May you please run the above commands to see if they also work on your setup?

**Comment by larseggert** [comment]
I won't get to this until after my winter vacation - sorry

**Comment by larseggert** [comment]
I did manage to do a quick test. I do see packet transmitted and received on the other end, but I see no messages on the console regarding the head changing. (I see one message exactly for the first packet.)

**Comment by giuseppelettieri** [comment]
are you using ```pkt-gen-b```? It is a different binary than ```pkt-gen```.

**Comment by larseggert** [comment]
No

**Comment by giuseppelettieri** [comment]
Well, I assume its too late now, enjoy your vacation :) In the meantime, I may try to use warpcore.

**Comment by larseggert** [comment]
Issue still exists today with 4.15

**Comment by giuseppelettieri** [comment]
Even with ```pkt-gen-b```?

**Comment by larseggert** [comment]
Things work with both `pkt-gen` and `pkt-gen-b`.

With warpcore (and without `NM_IXGBE_USE_TDH`) I still see the stuck tail.

**Comment by larseggert** [comment]
With `NM_IXGBE_USE_TDH` things work, as expected.

By the way, does `NM_IXGBE_USE_TDH` have a performance impact?

**Comment by giuseppelettieri** [comment]
Not that big. The real problem is that it is discouraged by the datasheet, and people have observed TX stalls when changing the NIC slots at high rates. You can check by yourself if you are affected by this issue by running ```pkt-gen-b -ftx -l 800 -l 400 -i ...```, which sends packets with random sizes between 400 and 800 bytes.

**Comment by giuseppelettieri** [comment]
Well, I guess that the NIC does not write-back its ring pointer if you don't ask for it. ```pkt-gen``` and ```pkt-gen-b``` set the ```NS_REPORT``` slot flag in the last slot of each batch. You can do the same: this will translate in the proper flag for the NIC, which should then report its pointer when it moves past that slot.

**Comment by larseggert** [comment]
I will try this. Do I need to set this in the last slot used on each ring, if my batch spans rings?

**Comment by giuseppelettieri** [comment]
Yes, do it in each ring.

**Comment by larseggert** [comment]
Setting `NS_REPORT` in this manner fixes things
