### ISSUE TITLE
Unloading of DMA mappings is not correct

### ISSUE THREAD

**Issue by dusancerhaty** [luigirizzo/netmap#407]
Mappings created by netmap_load_map() are not unmapped correctly. The cycle, which maps paddrs using dma_map_single(), starts at index 0 and use p->_clustsize, but the cycle, which unloads them, starts at index 2 and use size of netmap buf size. It results in freeing of only a small portion of previously mapped area, thus leading to map another parts of memory on next interface registering, as those previously mapped are not usable. After couple of runs of my test utility I end up in kernel oop, as linux is not able to handle paging request. The problem is more significant when IOMMU is enabled.

I am trying to use netmap on NVIDIA's jetsontx2, Ubuntu 16.04, Linux 4.4.38, but I think it's common problem of any platform.

I attached a patch resolving this issue, of course I am not able to say whether it is corrent. Could you please take a look?

Thanks

[0001-mem-fix-unloading-of-dma-mappings.txt](https://github.com/luigirizzo/netmap/files/1555002/0001-mem-fix-unloading-of-dma-mappings.txt)

**Comment by giuseppelettieri** [comment]
Thanks for catching this. Please prepare a pull request.

**Comment by giuseppelettieri** [comment]
merged, I am closing this.
