### ISSUE TITLE
Missing dma synchronization from device

### ISSUE THREAD

**Issue by dusancerhaty** [luigirizzo/netmap#409]
Packets received from NIC are not consistent with packets sent to device. It happens quite often. It's caused by missing dma_buffers/caches sync, like DMA-API documentation recommends for streaming DMA mappings, using dma_sync_single_for_*(). I attached a patch solving the issue for RX rings only, as this is all I need now. There's a need to fix it for TX rings also.

Could you take a look please?

Thanks

[0002-mem-sync-dma-rx-buffers-from-device.txt](https://github.com/luigirizzo/netmap/files/1557023/0002-mem-sync-dma-rx-buffers-from-device.txt)

**Comment by giuseppelettieri** [comment]
Thanks. As I mentioned elsewhere, DMA-mapping was skipped during the port to Linux, and has been left in that state for a long time, since it apparently did not make any difference on Intel-based architectures. Are you experiencing these cache problems on ARM?

Either way, please prepare a pull request for your patch.

**Comment by dusancerhaty** [comment]
Yes, this issue emerged on ARM. But after I've read your post, I tested it on intel-based machine without syncing and the problem didn't appear. In spite of this I wouldn't rely on this test result. I didn't find any mention about syncing not being necessary on x86, nor another architecture. Also DMA-API doc recommends to sync. So I leave the patch as is, e.g. it'll be supported for all archs, it has no affect on performance.

**Comment by giuseppelettieri** [comment]
Thanks for testing. No, it is generally not needed on Intel, and that is why we could avoid supporting it for so long. Anyway, I agree that we should do right thing and follow the API. In fact, I was not suggesting to drop the patch. To the contrary, I would like to merge it with proper credit and apply the change to the other drivers and to the TX path.

Up until recently we did not support ARM at all, so you are up for a tough ride :)

**Comment by giuseppelettieri** [comment]
I am leaving this open since it needs to be done on the other drivers, too. Moreover, we need to do the right thing on the TX path also. We may need to some help to test that, though, since we do not own any ARM hardware.

**Comment by dusancerhaty** [comment]
Now I'm trying to find out how to correctly handle syncing of TX buffers, so I can manage TX path if you wish.

Regarding the testing on ARM, do no hesitate to contact me whenever in the future.

Further, at the beginning of next year, I'm going to implement full support for IOMMU, 'cause I need to manage more NIC's ports on one machine what is not possible now if they belongs to different IOMMU groups.

Anyway, great job done on this project, saved me a lot time.
