### ISSUE TITLE
i40e_vsi_configure NULL pointer dereference

### ISSUE THREAD

**Issue by jmtilli** [luigirizzo/netmap#416]
I bumped up my thread count from 2 to 6. When pressing ^C for the application, after all threads have exited and the main function after joining the threads calls nm_close() for all of the descriptors, I got this issue:

<pre>
[  734.558433] BUG: unable to handle kernel NULL pointer dereference at 0000000000000100
[  734.558496] IP: i40e_vsi_configure+0x62a/0x7b0 [i40e]
[  734.558520] PGD 81b068067 
[  734.558521] PUD 8191b8067 
[  734.558536] PMD 0 

[  734.558574] Oops: 0000 [#1] SMP
[  734.558592] Modules linked in: i40e(OE) netmap(OE) openvswitch nf_conntrack_ipv6 nf_nat_ipv6 nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_defrag_ipv6 nf_nat nf_conntrack binfmt_misc ipmi_ssif intel_rapl sb_edac edac_core x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm dcdbas irqbypass intel_cstate input_leds joydev intel_rapl_perf mei_me ioatdma mei shpchp lpc_ich dca mac_hid ipmi_si ipmi_devintf ipmi_msghandler acpi_power_meter acpi_pad ib_iser rdma_cm iw_cm ib_cm ib_core configfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq raid1 raid0 multipath linear mgag200 i2c_algo_bit ttm crct10dif_pclmul crc32_pclmul drm_kms_helper ghash_clmulni_intel syscopyarea pcbc hid_generic sysfillrect
[  734.558899]  aesni_intel bnx2x sysimgblt aes_x86_64 fb_sys_fops usbhid crypto_simd ahci ptp glue_helper mdio pps_core drm libahci hid megaraid_sas cryptd libcrc32c wmi [last unloaded: netmap]
[  734.558979] CPU: 5 PID: 15861 Comm: netmapproxy1 Tainted: G           OE   4.11.0-14-generic #20~16.04.1-Ubuntu
[  734.559020] Hardware name: Dell Inc. PowerEdge R720/0X3D66, BIOS 2.5.4 01/22/2016
[  734.559052] task: ffff888a47130000 task.stack: ffffa859c97c8000
[  734.559084] RIP: 0010:i40e_vsi_configure+0x62a/0x7b0 [i40e]
[  734.559109] RSP: 0018:ffffa859c97cbcf8 EFLAGS: 00010286
[  734.559133] RAX: 0000000000000100 RBX: ffff888a5b460c40 RCX: 0000000000000000
[  734.559164] RDX: 0000000000000000 RSI: 00000000000001ff RDI: ffff88924ebac000
[  734.559194] RBP: ffffa859c97cbd70 R08: ffffa859ce000000 R09: 0000000000000015
[  734.559224] R10: 0000000000000001 R11: 0000000000000019 R12: ffff889256b09d00
[  734.559254] R13: ffff889258464000 R14: ffff88925478d000 R15: ffff88925478d000
[  734.559285] FS:  00007f0ea5bf0700(0000) GS:ffff88925f080000(0000) knlGS:0000000000000000
[  734.559318] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  734.559344] CR2: 0000000000000100 CR3: 00000007db209000 CR4: 00000000001406e0
[  734.559374] Call Trace:
[  734.559398]  i40e_up+0x12/0x30 [i40e]
[  734.559422]  i40e_netmap_reg+0x72/0x180 [i40e]
[  734.559449]  netmap_hw_reg+0x34/0x90 [netmap]
[  734.559474]  netmap_do_unregif+0x90/0x240 [netmap]
[  734.559501]  netmap_priv_delete+0x37/0x80 [netmap]
[  734.560553]  netmap_dtor+0x21/0x30 [netmap]
[  734.561548]  linux_netmap_release+0x1a/0x30 [netmap]
[  734.562545]  __fput+0xe7/0x220
[  734.563520]  ____fput+0xe/0x10
[  734.564498]  task_work_run+0x7e/0xa0
[  734.565462]  exit_to_usermode_loop+0xaa/0xb0
[  734.566418]  syscall_return_slowpath+0x59/0x60
[  734.567366]  entry_SYSCALL_64_fastpath+0xab/0xad
[  734.568305] RIP: 0033:0x7f0ea57d057d
[  734.569245] RSP: 002b:00007ffd4f5c1920 EFLAGS: 00000293 ORIG_RAX: 0000000000000003
[  734.570199] RAX: 0000000000000000 RBX: 0000000000da7970 RCX: 00007f0ea57d057d
[  734.571152] RDX: 0000000000000000 RSI: 0000000014721000 RDI: 0000000000000005
[  734.572095] RBP: 00007ffd4f5c1be0 R08: 00000000000000ca R09: 0000000000000001
[  734.573024] R10: 0000000000000130 R11: 0000000000000293 R12: 00007ffd4f5c1d70
[  734.573942] R13: 0000000000000000 R14: 0000000000000006 R15: 000560b84962f929
[  734.574857] Code: 03 53 2c 78 38 41 89 d0 41 29 f8 39 d7 41 0f 4e d0 48 63 d2 48 63 f9 4d 8b 85 18 01 00 00 48 c1 e2 04 48 c1 e7 04 49 03 7c 24 08 <8b> 14 10 41 3b 95 20 01 00 00 73 ad 49 8b 14 d0 eb aa 01 fa eb 
[  734.576823] RIP: i40e_vsi_configure+0x62a/0x7b0 [i40e] RSP: ffffa859c97cbcf8
[  734.577818] CR2: 0000000000000100
[  734.578837] ---[ end trace ffeee559a6bc9689 ]---
</pre>

**Comment by vmaffione** [comment]
Same crash as #412. I think we can close this.

**Comment by jmtilli** [comment]
Yes, indeed. Sorry for the noise! I thought the issue would be avoided by rewriting parts of my application, but it still occurs, albeit more rarely. I'll click "Close and comment", let's hope it closes the issue.
