### ISSUE TITLE
Upstream the Linux kernel module

### ISSUE THREAD

**Issue by DemiMarie** [luigirizzo/netmap#420]
This is a feature request to get the Linux kernel module submitted upstream to [kernel.org](https://www.kernel.org).

**Comment by vmaffione** [comment]
The maintainers have decided not to include it, so they won't accept it.

**Comment by marcusschiesser** [comment]
Just curious - did the kernel maintainers tell why?

**Comment by vmaffione** [comment]
They don't think it fits well in a general purpose kernel (but they are happy with XDP).
In general, the maintainters of the Linux networking subsystem are not open to changes coming from external people.

**Comment by DemiMarie** [comment]
I know that per Greg, any module that required special drivers or had any sort of kernel abstraction layer would not be accepted.
