### ISSUE TITLE
How to increase the size of vale ring

### ISSUE THREAD

**Issue by v8oss** [luigirizzo/netmap#423]
Using latest git.

I'm opening a vale pipe like this:

```
    nmd= nm_open( "vale:rtx}0", NULL, 0, NULL);
```

and the number of slots is 1024. It is unclear how I should increase this. 

I cannot increase it by altering any sysctl - should I be able to? If so which one? I tried altering all the values that are 1024 to 2048 but they had no effect.

So I tried:

```
    struct nmreq nmr;
    memset(&nmr, 0, sizeof(nmr));
    nmr.nr_tx_rings = 1;
    nmr.nr_rx_rings = 1;
    nmr.nr_tx_slots = 2048;
    nmr.nr_rx_slots = 2048;

    nmd= nm_open( "vale:rtx}0", &nmr, NM_OPEN_RING_CFG, NULL);
```

I'm not sure if this is correct, but when I try to open I get:

```
NIOCREGIF failed: Cannot allocate memory vale:rtx}0
```

So it looks like something else needs to be altered.

How can I do this?

**Comment by giuseppelettieri** [comment]
You are doing it right, but the the preallocated rings are too small for that number of slots. You should see something like this in the logs:
```
2_ring request size 33024 too large
```
You can change the size of the preallocated rings via the ```priv_ring_size``` module parameter:
```
echo 33024 > /sys/module/netmap/parameters/priv_ring_size
```
(or the equivalent sysctl in FreeBSD).

**Comment by v8oss** [comment]
Ah. I should have figured that out... thank you.
