### ISSUE TITLE
Debian DKMS package error

### ISSUE THREAD

**Issue by peylight** [luigirizzo/netmap#424]
Hello
In the ubuntu 16.04 when i try to install maked debian (dkms) package i see an error:
```
ERROR ( dkms apport ): kernel package linux -headers-4.4.0-104-generic is not supported
Error! build of forcedeth.ko faild for: 4.4.0-104-generic (x86_64)
```
Anyone can make debian package?

**Comment by pouralijan** [comment]
Hi,

We have faced the same problem. We will grateful if someone can help us.
