### ISSUE TITLE
Is nm_okt_copy thread-safe?

### ISSUE THREAD

**Issue by Flow-It** [luigirizzo/netmap#425]
The title says it all. Knowing that the netmap API is modeled in parts after the libpcap API, do I have to take special care when multiple threads call nm_pkt_copy() on the same ring?

**Comment by vmaffione** [comment]
`nm_pkt_copy` is thread-safe. But it's not thread safe to concurrently modify `ring->cur` and `ring->head` or concurrently call `poll()`/`ioctl()` on the same netmap file descriptor.
