### ISSUE TITLE
Netmap Performance measurement.

### ISSUE THREAD

**Issue by murali-rd** [luigirizzo/netmap#427]
Hi all,

Trying to measure netmap performance and conclude performance benefits of same. 
basically what i m doing is 
1) run the pkt-gen application to reach max throughput of 940 mbps and check the CPU utilization using top command. 
2) for linux kernel performance using iperf to reach max throughput of 940 mbps and check the CPU utilization using top command.  
(driver - e1000e, system config: Llinux 4.4.0-103-generic . 4 core, Intel i5=4300M APU @ 2.60Ghz, both machines are connected directly)

as i mention in both test the throughput remains same, but the CPU is :
1) netmap with pkt gen with modified driver is.
100%
2) iperf with linux kernel stack is
12%
these results not good with respect to cpu utilization which is key for my demonstration.
the Iperf flow involves kernel + linux stack and user copy and still the CPU is 12%, but the pkt-gen which just involves netmap and application takes 100% CPU (using poll and not busywait . i.e.pkt-gen-b application is used for test).
wanted to know:
1) Is there any point i m missing while comparing or any other method for comparing.
2) whats the reason we have so much difference in CPU utilization.

Thanks and regards,
murali

**Comment by giuseppelettieri** [comment]
Maybe I am misreading you. Are you using ```pkt-gen-b``` or ```pkt-gen```?

**Comment by murali-rd** [comment]
i am using pkt-gen-b.

**Comment by giuseppelettieri** [comment]
OK, that program uses busy waiting, so 100% CPU usage is expected. You should try with the other one.

**Comment by murali-rd** [comment]
i took the performance with busywait mode by using pkt-gen the cpu utilization is lot better but still more than iperf. iperf as i mentioned before it is 12% but with pkt-gen  its around 15%.

**Comment by markwebster** [comment]
Could you post the full pkt-gen command you're using for your tests?

**Comment by vmaffione** [comment]
You are not mentioning packet size, which is the key issue for your comparison.
pkt-gen and iperf may be not directly comparable. If you are sending TCP traffic with iperf, you'll benefit from TSO offloading, which allows you to have a larger packet size that what can you have with pkt-gen.

The CPU utilization difference could be explained by this. Can you paste the full iperf and pkt-gen commands you are using?

**Comment by murali-rd** [comment]
hi,

For pkt-gen test i m specifying the size as 1500. i.e.
pkt-gen -i enp0s25 -f rx      and  pkt-gen -i enp0s25 -f tx -l 1500

for iperf i use:
server : iperf -s
client : iperf -c server_ip_address

and the iperf cpu data is without disabling TSO offloading. i tested iperf by disabling the offloading the iperf CPU utilization almost doubles.

regards,
murali

**Comment by vmaffione** [comment]
Ok, that's expected.
A fair comparison is indeed between pkt-gen and iperf/netperf without TSO/UFO. You see that in this case pkt-gen consumes less CPU, as expected.

Point here is that netmap is normally used for middlebox processing, where you cannot use TSO or UFO, because your application is not the endpoint of a TCP or UDP connection. As a result, in those cases it is more CPU efficient to use netmap rather than raw sockets or similar techniques.
IOW, OS stacks are already efficient to support endpoint of TCP/UDP sockets (mainly because of offloadings), but they are not at middlebox processing.

**Comment by murali-rd** [comment]
ok thankyou. i was trying to check the kernel pktgen details as mentioned in the netmap paper. could you please provide the command used to run pktgen of linux. is there any particular way or command or script which i need to use for same?

**Comment by vmaffione** [comment]
I used the script in `LINUX/scripts/linux-pktgen.sh`.
(It's been a long time, I don't remember all the details of that test).
