### ISSUE TITLE
Syslog errors reported on Linux despite no visible problem

### ISSUE THREAD

**Issue by andrewbonney** [luigirizzo/netmap#428]
Hi,
I've been experiencing an issue since bringing our codebase up to date against the latest netmap master. We're seeing error messages reported in syslog like the following, despite no changes to our code:

```
Jan 10 16:28:10 ap-1018r-2 kernel: [518070.870553] 690.614081 [1667] nm_rxsync_prologue        eth0}0 RX0: fail 'cur < head || cur > kring->nr_hwtail' h 3330 c 3328 t 3330 rh 3330 rc 3328 rt 3330 hc 3328 ht 3332
Jan 10 16:28:10 ap-1018r-2 kernel: [518070.870556] 690.614087 [1710] netmap_ring_reinit        called for eth0}0 RX0
Jan 10 16:28:11 ap-1018r-2 kernel: [518072.071801] 691.815397 [1667] nm_rxsync_prologue        eth0}0 RX0: fail 'cur < head || cur > kring->nr_hwtail' h 3198 c 3162 t 3198 rh 3198 rc 3162 rt 3198 hc 3162 ht 3198
Jan 10 16:28:11 ap-1018r-2 kernel: [518072.071808] 691.815409 [1710] netmap_ring_reinit        called for eth0}0 RX0
Jan 10 16:28:12 ap-1018r-2 kernel: [518072.384038] 692.127656 [1667] nm_rxsync_prologue        eth0}0 RX0: fail 'cur < head || cur > kring->nr_hwtail' h 3006 c 2966 t 3006 rh 3006 rc 2966 rt 3006 hc 2966 ht 3006
Jan 10 16:28:12 ap-1018r-2 kernel: [518072.384041] 692.127662 [1710] netmap_ring_reinit        called for eth0}0 RX0
```

Whilst I'm not 100% sure on the issue, I believe I've tracked it to this commit, as reverting it suppresses the messages: https://github.com/luigirizzo/netmap/commit/c3ad05b5b8cfa49a35a4e990a24d7eec3e7600fc

**Comment by vmaffione** [comment]
Hi,
  This looks like a bug in your application. I don't think the commit you mention is related, although it may expose the issue because it changes the timing.
It looks like you forgot to update `ring->cur` on `eth0}0`. You should normally have `ring->cur==ring->head` all the time (or at least every time you use a netmap syscall, i.e. poll/ioctl). But the log shows clearly that `ring->cur` and `ring->head` are different.

**Comment by andrewbonney** [comment]
Ok thanks. I had seen your comments in #362 so checked on our updating of pointers before ioctl/poll prior to reporting this issue, but presumably I've missed something. I'll take another look at it tomorrow.

**Comment by andrewbonney** [comment]
Following a good amount of further debugging, I believe we've found the issue and it is indeed in the application. We're using a poll to identify when we need to wake a thread to process more incoming packets, but this poll can occur when this thread is still mid-way through its processing (ie. when cur/head don't match).

It looks like we were previously being protected by the following in that commit, which is now only executing on FreeBSD:

```
	if (want_rx) {
		enum txrx t = NR_RX;
		want_rx = 0; /* look for a reason to run the handlers */
		for (i = priv->np_qfirst[t]; i < priv->np_qlast[t]; i++) {
			kring = &NMR(na, t)[i];
			if (kring->ring->cur == kring->ring->tail /* try fetch new buffers */
			    || kring->rhead != kring->ring->head /* release buffers */) {
				want_rx = 1;
			}
		}
		if (!want_rx)
			revents |= events & (POLLIN | POLLRDNORM); /* we have data */
	}
```

We'll have a think about how best to go preventing that unnecessary poll when we're still handling the last batch of packets.

**Comment by vmaffione** [comment]
Ok, but pay attention to locking issues.
It is not legal to call `poll()` or `ioctl()` on a netmap port and accessing the rings of the same port concurrently without proper locking. Usually the thread calling `poll` and `ioctl` is the same the accesses the rings.
