### ISSUE TITLE
vmxnet3 + Jumbo frames

### ISSUE THREAD

**Issue by bvital1976** [luigirizzo/netmap#430]
I am adding netmap support to vmxnet3 driver. I have a question about handling Jumbo frames. 9014 bytes frames may occupy up to 3 descriptors (1522 + 4096 + 4096) which may point to two different NIC rings. May I combine/copy those 3 buffers in a single netmap slot (preferred for me)? Will it be a problem if a  NIC uses 3 indices while netmap uses only one index for a packet? Or I should use NS_MOREFRAG flag. I am especially concerned about host rings because I have to pass some jumbo packets to the host stack.

**Comment by vmaffione** [comment]
Hi,
  What do you mean by "a frame may point to different NIC rings"?

You can implement the adapter as you wish, but keep in mind that netmap will pass you head/tail when user calls txsync/rxsync, and so it's handy to have one-to-one correspondency between the netmap rings and the NIC rings.
However, it also depends on which kind of datapath API the vmxnet3 has with the hypervisor. For instance the virtio API (for virtio_net driver) does not directly expose a "ring": the API is something like `virtqueue_add_outbuf`, `virtqueue_add_inbuf` and `virtqueue_get_buf`, so in that case the correspondency is kind of hidden or not important.
If the API is just a ring, I would suggest using `NS_MOREFRAG`, similarly to what `ixgbe` and `i40e` adapters do. 

I don't understand your concern about the host rings. Host rings is not something you support in the driver, but they are handled by netmap core module. And host rings don't currently support `NS_MOREFRAG`.

**Comment by bvital1976** [comment]
I meant descriptors may point to different NIC rings. In vmxnet3 driver also there is no direct access to a ring with data buffers. There is a "command" ring with instructions where to get actual data. Data buffers are also organized as rings so data chunks may be in two different rings depending on size.

My application passes some packets to host rings. If host rings do not support NS_MOREFRAG then the driver should combine data chunks in a packet. Therefore I cannot follow your suggestion to use NS_MOREFRAG.

**Comment by vmaffione** [comment]
Ok, so the one-to-one slot mapping argument does not apply. Or it may apply between a netmap ring and a command ring. Are there any specification of vmxnet3 device or one needs to reverse engineer the Linux or freebsd driver?

Support for `NS_MOREFRAG` is necessary wherever you need to store (in a netmap ring) a packet  that is larger than the netmap `buf_size`. This applies to any netmap ring, so both hardware netmap ring and software (host) netmap rings. To avoid `NS_MOREFRAG` you may simply increase the `buf_size` sysctl, paying in increased memory footprint.

**Comment by bvital1976** [comment]
There is no specification for vmxnet3 device but there are three drivers available in source code: from open-vm-tools,  from VMWare and from DPDK.

**Comment by bvital1976** [comment]
I added netmap support to vmxnet3 driver from Centos 7.4 kernel sources. I tested it on VMWare Workstation and ESXi 6.5 using my application. pkt-gen sends/receives ~450Kpps in my environment.
Could you take a look whether I correctly implemented netmap related functions and hopefully add my enhancements to your project?

**Comment by giuseppelettieri** [comment]
Sure, just create a pull request.

**Comment by bvital1976** [comment]
The latest master does not want to build vmxnet3 driver because of:
********************************** WARNING **********************************
*** 'vmxnet3': no applicable patch found and no override provided.
*** Disabling driver.
*****************************************************************************
If I rename vanilla--vmxnet3--31000--99999 to vanilla--vmxnet3--10000--99999 then building succeeds.

**Comment by giuseppelettieri** [comment]
It does not build for me on vanilla kernels older than 3.16. What kernel are you building it for?

**Comment by bvital1976** [comment]
3.10.0-693.17.1.el7.x86_64

**Comment by giuseppelettieri** [comment]
That is not vanilla. Please override the default behaviour using ```config.mak```:

````
make distclean
echo 'vmxnet3@patch=patches/vanilla--vmxnet3--31000--99999' > config.make
./configure
make
````
