### ISSUE TITLE
ixgbevf TX lockup

### ISSUE THREAD

**Issue by G8EjlKeK7CwVQP2acz2B** [luigirizzo/netmap#431]
I am running 10G simultaneous TX/RX using 400 byte packets on two CPUs using an ixgbevf driver in a LINUX VM.  Thank you very much for netmap, this works really well.

Sometimes I get a TX lockup however -- repeated poll() calls never report any free TX buffers in the TX ring.  It seems to be easiest to reproduce when running near max frame rates.

The netmap code I am running is from October -- perhaps this is some sort of known bug?

**Comment by vmaffione** [comment]
I guess by `lockup` you mean livelock or deadlock. Do you get any kernel crash?
In any case please use the latest master, as bug fixes come in continuously.

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
Vincenzo Maffione wrote:
> I guess by |lockup| you mean livelock or deadlock. Do you get any kernel
> crash?
> In any case please use the latest master, as bug fixes come in continuously.

What I see is that at some point the TX ring runs out of buffers and never gets any more.  No kernel crash.

I just updated to the latest GIT from the website and this has aggravated the problem *tremendously*.

I just ran a test that sent 1695 frames, of which 566 made it onto the fiber, and only 44 made it into the RX ring (remote equipment is looping the frames back).

This test should have sent around 180 million frames!

I will try some different rates and frame sizes and see if I can find anything out.

Joe Buehler

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
Upgrading netmap also upgraded the ixgbevf driver.  I rolled back to the driver version I had been using (4.2.1) just in case but that didn't fix anything.

Running at 9.999G (400 byte frames) results in an almost immedate (1080 frames sent) stuck TX ring.

Running at 1.0G results in (almost precisely) 2/3 of frames being lost in TX direction and 2/3 in RX direction.

Joe Buehler

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
The rate doesn't seem to matter, running at 1 megabit results in the same frame loss rates.  The latency is very high also -- about 1 second max round trip latency -- typically has been hundreds of microseconds max.

Joe Buehler

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
Some further info if it helps.  The TX frames follow a pattern that appears to be independent of frame size and rate: 341 frames with 50% of the frames I handed to netmap missing (precisely every other one -- they have sequence numbers in them), then 342 frames with nothing missing, repeated ad infinitum.  Which is about 1/3 frame loss.  This doesn't happen with the older October version I was using -- no difference in my code, just changing netmap versions triggers this.  I note that 341 + 341 + 342 == 1024 which is the number of slots in the TX ring.

**Comment by giuseppelettieri** [comment]
What do you observe if you increase the buffer size to a full page?

# echo 4096 > /sys/module/netmap/parameters/buf_size

(then restart your app)

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
I set buf_size=4096 on the module load, but it caused no change in behavior.

How do I change the number of buffers in the rings?  That might be of interest also.

**Comment by giuseppelettieri** [comment]
The size of the netmap rings is the same as the size of the NIC rings, so you have to change that:
```
ethtool -G $INTERFACE tx $TXSIZE rx $RXSIZE
```

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
very interesting, I cut the ring size to 256 and now the frame sequence number pattern is of period 256

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
OK this was a mistake on my part -- the user headers changed and I am using old ones.  Now that it is working properly I see that the latency looks reduced compared to the October version I was using.

Now back to tracking down my lockup issues.

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
upgarding to latest git appears to have fixed my tx stall issues at high rates
