### ISSUE TITLE
Question regarding bandwidth measurement in netmap enabled patched driver 

### ISSUE THREAD

**Issue by mwaldiya** [luigirizzo/netmap#437]
Hi All,
I am using netmap with igb patched driver on linux machine.
As i start the userlevel netmap application i have no way to measure the input bandwidth of traffic on particular NIC.
Is there a way to measure that with standard available application like bwm-ng or bmon etc ?

Thanks

**Comment by vmaffione** [comment]
Hi,
  No, there is no way right now, you need to do these measurement in your application.
