### ISSUE TITLE
Issue in adding Physical NIC to Vale

### ISSUE THREAD

**Issue by ppnaik1890** [luigirizzo/netmap#446]
Hi,

I have a netmap vale setup on host. I have enabled support for multiqueue NIC from vale using the patch attached.
[netmap_vale_mq_2048.txt](https://github.com/luigirizzo/netmap/files/1695302/netmap_vale_mq_2048.txt)

 I am creating new interfaces for the VMs using the following commands:
```
./vale-ctl -n vi1 -C 2048,2048,3,3  // 3 queues for 3 core VM
./vale-ctl -a vale0:vi1
ifconfig vi1 hw ether 00:aa:bb:cc:dd:05

```
With such interfaces to the VM, VMs can communicate amongst themselves. 
Now, I am trying to add the physical interface of the host to vale using the following command:
```
./vale-ctl -h vale0:enp1s0f1



```
I am seeing two interfaces in vale after this:
```
./vale-ctl 
718.344951 bdg_ctl [149] bridge:0 port:0 vale0:vi3
718.345000 bdg_ctl [149] bridge:0 port:1 vale0:vi2
718.345006 bdg_ctl [149] bridge:0 port:2 vale0:vi1
718.345010 bdg_ctl [149] bridge:0 port:3 vale0:vi4
718.345014 bdg_ctl [149] bridge:0 port:4 vale0:enp1s0f1
718.345019 bdg_ctl [149] bridge:0 port:5 vale0:enp1s0f1^

```
Also, I assigned the same subnet IP as the VMs to enp1s0f1. But, I am unable to establish communication between enp1s0f1 and the VM. Please help me resolve this issue.

Thanks in advance,
Priyanka

**Comment by ppnaik1890** [comment]
Hi,

The dmesg log gives the following error:

`nm_os_generic_xmit_frame  Warning: dev_queue_xmit() is dropping [2]`

Please help me reolve this.

**Comment by ppnaik1890** [comment]
Hi,

I am sorry if I am answering incorrectly. I compiled the netmap with ixgbe driver, so enp1s0f1 would be using ixgbe?

Thanks,
Priyanka

**Comment by vmaffione** [comment]
You can check the driver you are using is
````
$ ethtool -i enp1s0f1 | grep driver
````

**Comment by ppnaik1890** [comment]
```
ethtool -i enp1s0f1 | grep driver
driver: igb
```
So I will have to compile netmap with igb driver?

**Comment by vmaffione** [comment]
yes, but apart from compiling you need to rmmod the old igb.ko and load the patched igb.ko.
You were not doing that because I see in the log that you are using the emulated adapter.

**Comment by ppnaik1890** [comment]
Ok I will try that. I will post back if I face any issue. Thanks a lot. :)
