### ISSUE TITLE
Is Netmap compatible with 32Bit MIPS hardware?

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#451]
Hi! Before we invest more time in porting an embedded network driver to Netmap I would kindly like to ask if there is a chance that we could fail because Netmap might not work on 32Bit MIPS hardware.

We are using a Mediatek MT7621 SoC with a dual-core MIPS 1004Kc core and 256MB DDR3 RAM.

I have to admit that our Netmap application code is very early-stage but we are seeing crashes during memory allocation that we don't see within an x86 VM (64Bit). Those we came up with the question that Netmap might have some special CPU requirements. Maybe some special MMU feature or the like.

Sorry for this vague explanation. I'm everything but a CPU export.

Many thanks!

**Comment by giuseppelettieri** [comment]
In principle, it should work wherever Linux or FreeBSD work. In practice, it has only been tested on IA32_64/AMD64 architectures. Only recently we have started testing it on ARM, and I don't know anybody who has used it on MIPS. You should at the very minimum try to install the unmodified sources on your platform and check that at least the software-only ports work correctly (VALE ports and netmap pipes), then you can start playing with hardware ports.

**Comment by ramaza** [comment]
Testing with software-only ports helped us to narrow down our current problem. Thanks for your helpful feedback.
