### ISSUE TITLE
maximum pipes(Can not allocate memory)

### ISSUE THREAD

**Issue by A-AR-R** [luigirizzo/netmap#452]
i am creating a vale switch,and attached two ports to it(one of them is physical port and has 10G traffic attach to it) then i am load balancing on the virtual port with lb but after opening the forth one i get "Can not allocate memory".
./vale-ctl -n v0
./vale-ctl -n v1
./vale-ctl -a vale0:v0
./vale-ctl -a vale0:v1
./vale-ctl -a vale0:enp2s0f0
./lb -i v1 -p v2:6

./pkt-gen -i v2}0 -f rx      --------------> works correctly
./pkt-gen -i v2}1 -f rx      --------------> works correctly
./pkt-gen -i v2}2 -f rx      --------------> works correctly
./pkt-gen -i v2}3 -f rx      --------------> Unable to open netmap:v2}3: Cannot allocate memory

**Comment by giuseppelettieri** [comment]
You should increase the number of preallocated interfaces, rings and buffers. Please take a look at the module parameters in ```/sys/module/netmap/parameters```. The ones you are interested in are ```priv_if_num``` (interfaces, you need one for each port or pipe), ```priv_ring_num``` (rings, you need a couple for each port or pipe), ```priv_buf_num``` (buffers, you need at least enough to fill all the rings).
