### ISSUE TITLE
Cannot open a netmap pipe after starting/stopping several pkt-gen

### ISSUE THREAD

**Issue by sylgal** [luigirizzo/netmap#454]
Hello,

I'm using FreeBSD 11.1 STABLE, after running several (~50)

`pkt-gen -i 'netmap:ix0{1'
`

it cannot allocate any more netmap pipe (returning: nm_open [608] NIOCREGIF failed: Cannot allocate memory ix0{1):

I can reproduce same issue running following code:

```
#define NETMAP_WITH_LIBS

#include <sys/time.h>
#include <sys/types.h>
#include <net/if.h>
#include <net/netmap.h>
#include <net/netmap_user.h>
#include <errno.h>

int main(int argc,char **argv)
{
  int   n = 1;

  while (1)
    {
      struct nm_desc    *nm_desc = NULL;
      char      buffer_ifname[128];
      uint64_t new_flags = 0;
      int       pipe_id = 1;

      nm_desc = nm_open("netmap:ix0{1",NULL,new_flags,nm_desc);
      if (nm_desc == NULL)
        {
          perror("nm_open");
          exit(1);
        }
      else
        {
          printf("created %d pipe\n",n++);
          nm_close(nm_desc);
        }
    }
}

```

**Comment by jmtilli** [comment]
I have observed similar problems using Linux, but using VALE instead of netmap pipes. Note sure if this is the same issue or a different one.

**Comment by giuseppelettieri** [comment]
You program works fine for me using the current netmap master on Linux, with either pipes, or VALE. @sylgal, may you please try the current netmap master in FreeBSD? See #445 for instructions.

**Comment by sylgal** [comment]
Thanks,

I did same same on latest FreeBSD-CURRENT and it's work fine.
I have to wait FreeBSD to merge netmap CURRENT to 11.1 STABLE.
