### ISSUE TITLE
Bad UDP checksums with pkt-gen and txseq mode

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#456]
I constantly see broken UDP checksums with pkt-gen in txseq mode. After verifying every component within the test setup I'm afraid I have to ask if there could be some problem with pkt-gen itself.

Here are more details about the test setup:

**TX SIDE:**
- DEVICE: Notebook + Ubuntu 16.04 + Intel e1000e + Netmap (source from 23rd of February)
- APP: pkt-gen -i enp0s25 -f txseq -R 1

**RX SIDE:**
- DEVICE: Desktop PC + Ubuntu 16.04 + USB Network adapter
- APP: tcpdump

**VERIFIED:**
- Promisc mode ON at TX and RX side
- NIC offload features OFF at TX and RX side
- Tested with NATIVE and EMULATED Netmap mode

**SCREENSHOT:**
```
14:09:39.002249 00:00:00:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 60: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 46)
    10.0.0.1.1234 > 10.1.0.1.1234: [bad udp cksum 0xf84e -> 0xf84d!] UDP, length 18
14:09:40.002332 00:00:00:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 60: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 46)
    10.0.0.1.1234 > 10.1.0.1.1234: [bad udp cksum 0xf84d -> 0xf84c!] UDP, length 18
14:09:41.002335 00:00:00:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 60: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 46)
    10.0.0.1.1234 > 10.1.0.1.1234: [bad udp cksum 0xf84c -> 0xf84b!] UDP, length 18
14:09:42.002401 00:00:00:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 60: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 46)
    10.0.0.1.1234 > 10.1.0.1.1234: [bad udp cksum 0xf84b -> 0xf84a!] UDP, length 18
14:09:43.002490 00:00:00:00:00:00 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 60: (tos 0x10, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 46)
    10.0.0.1.1234 > 10.1.0.1.1234: [bad udp cksum 0xf84a -> 0xf849!] UDP, length 18
```

**Comment by giuseppelettieri** [comment]
No need to be afraid :). There was indeed a regression in txseq_body. May you please try the latest master?

**Comment by ramaza** [comment]
Looks good now. I could only test on Ubuntu + x86 but not on our real target platform. Which is OpenWRT + MIPS. We still have troubles to compile the latest Netmap source there. But that's a different story and I know that MIPS is not officially supported.

Many thanks for your fast response!
