### ISSUE TITLE
tcpdump: netmap:eth0: No such device exists

### ISSUE THREAD

**Issue by maialenzab** [luigirizzo/netmap#458]
Hi, I'm trying to use tcpdump with netmap but I when I start the capture, tcpdump doesn't see the device

`~/netmap-libpcap$ sudo LD_LIBRARY_PATH=. tcpdump -i netmap:eth0 `
tcpdump: netmap:eth0: No such device exists
(SIOCGIFHWADDR: No such device)

The netmap module is loaded (I can see it with "lsmod") and I'm using the netmap-libpcap library: 

`$ sudo LD_LIBRARY_PATH=. tcpdump --version `
tcpdump version 4.9.0
libpcap version 1.6.0-PRE-GIT_2018_03_12
OpenSSL 1.0.2g  1 Mar 2016

Any ideas of what might I be doing wrong?
Thanks in advance!

**Comment by vmaffione** [comment]
Hi,
  What if you try to open a VALE port
````
# tcpdump -i vale1:2
````
?

The upstream version of libpcap already includes netmap (see for instance https://github.com/netmap-unipi/libpcap). We should deprecate https://github.com/luigirizzo/netmap-libpcap as soon as possible.
Can you try to use the upstream libpcap?
