### ISSUE TITLE
Slow host forwarding performance only in emulated mode

### ISSUE THREAD

**Issue by lttlrck** [luigirizzo/netmap#459]
Hello,

I have an odd issue. I have an application that is using `NR_FORWARD` on *all* packets so it is connecting the host stack transparently.

With the ixgbe driver `admode=1`, iperf to this host measures 1Gb/sec - as expected. In emulated mode, `admode=2`, the performance is terrible: ~3Mbit/sec. 

I tried `pkt-gen` with `admode=2` between the hosts I easily get 1Mpps in both directions with 60 byte packets, so there aren't any fundamental issues in emulated mode or the hosts, it seems to be a problem with forwarding **plus** emulated mode. 

Are there any known issues? Any idea where I could look or try to narrow it down further? Or any commits that spring to mind that may be causing this? My code works perfectly with the ixgbe driver, but maybe there are some subtle differences with emulated mode that affect the function?

Thanks.

**Comment by lttlrck** [comment]
here's the handler:

```
void onReceive()
{
    unsigned int ri = mDesc->cur_rx_ring;
    const auto nifp = mDesc->nifp;

    do {

        struct netmap_ring *ring = NETMAP_RXRING( mDesc->nifp, ri);

        ring->flags |= NR_TIMESTAMP; // everything received now will have the same timestamp - saves CPU
        ring->flags |= NR_FORWARD;   // enable the slot forwarding flag

        while (!nm_ring_empty(ring)) {

            const u_int i   = ring->cur;
            const u_int idx = ring->slot[i].buf_idx;
            u_char *buf     = (u_char *)NETMAP_BUF(ring, idx);

            ring->slot[i].flags |= NS_FORWARD;

            // handler code here removed

            ring->cur          = nm_ring_next(ring, i);
            ring->head         = ring->cur;
            mDesc->cur_rx_ring = ri;
        }

        ri++;

        if (ri > mDesc->last_rx_ring) {

            ri = mDesc->first_rx_ring;
        }

    } while (ri != mDesc->cur_rx_ring);
}
```

**Comment by lttlrck** [comment]
I may be onto something. I'm going to close it until I've worked through it. I'll reopen if necessary.

**Comment by lttlrck** [comment]
More info:

As I get exactly the same result with my receive handler and with `bridge` application, I focused on the `bridge` application.

*without* netmap: 1Gb/sec 
`admode= 1` + bridge: 1Gb/sec - bridge CPU = 60%
`admode= 2` + bridge: ~3Mb/sec - bridge CPU = 1%

The low CPU suggests `bridge` isn't receiving packets with `admode=2`. So I added a packet counter to `bridge` and it is obvious that with `admode=2` fewer packets are received and it very uneven.

I tested this with TCP and UDP the results are the same: it looks like significant incoming packets are lost in emulated mode. It doesn't look like a host stack related issue.

I understand that perhaps emulated mode has some overhead and I should not expect it to perform as well as the patched drivers, but this seems very wrong. 

I will continue investigating, but any suggestions would be greatly appreciated.

**Comment by vmaffione** [comment]
Yes, emulated mode is a sort of fallback, so one cannot expect great performance in general.
But it is also true that 3 Mbps is way too low, which means that this is not a performance problem, but rather a bug (e.g. missing notifications somewhere) or misconfiguration.
Have you disabled all the offloadings on on `p1p1`? Have you enabled promisc mode on `p1p1`?

**Comment by vmaffione** [comment]
IOW check that you don't get messages like these in the host:
````
[   86.307843] 921.570090 [3623] netmap_transmit           ens4 drop mbuf that needs offloadings
````
I just tried the emulated adapter on an e1000 device (`ens4`) inside a QEMU VM, running bridge:
````
# ip link set ens4 up
# bridge netmap:ens4 netmap:ens4
````
I flood ens4 with UDP packets using `pkt-gen` on the TAP device (on the host), and see `bridge` in the host forwarding about 300Kpps, which looks good.

Then I configured an IP on `ens4`, disabling the offloadings
````
# ip addr add 10.11.12.2/24 dev ens4
# ethtool -K ens4 tx off rx off tso off gro off gso off
# netserver
````
And running `netperf` from the host I get:
````
netperf -H 10.11.12.2          
MIGRATED TCP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.11.12.2 () port 0 AF_INET : demo
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

 87380  16384  16384    10.02    1293.28   
````

**Comment by lttlrck** [comment]
I see something strange, with `admode=2` :

If I turn *on* offloading I see that error:

`# ethtool -K p1p1 tx on rx on tso on gro on gso on`
```
```
[16019.293395] 174.130180 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16020.573328] 175.410176 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16021.277302] 176.114186 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16022.557230] 177.394176 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16023.325181] 178.162167 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16024.285149] 179.122181 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16025.245098] 180.082177 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16026.269050] 181.106180 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
[16027.357000] 182.194183 [3166] netmap_transmit           p1p1 drop mbuf that needs offloadings
```

**Comment by lttlrck** [comment]
I see that messages with offloading is *on*!

```
# ethtool -K p1p1 tx on rx on tso on gro on gso on
# cat /sys/module/netmap/parameters/admode
2
# ./bridge -w 2 -i netmap:p1p1 
..
# dmesg -w
[16019.293395] 174.130180 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16020.573328] 175.410176 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16021.277302] 176.114186 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16022.557230] 177.394176 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16023.325181] 178.162167 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16024.285149] 179.122181 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16025.245098] 180.082177 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16026.269050] 181.106180 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
[16027.357000] 182.194183 [3166] netmap_transmit p1p1 drop mbuf that needs offloadings
```

turn them off:

```
# ethtool -K p1p1 tx off rx off tso off gro off gso off
# cat /sys/module/netmap/parameters/admode
2
# ./bridge -w 2 -i netmap:p1p1 
..
# dmesg -w
-- error not seen
```

NIC features after running `ethtool -K p1p1 tx on rx on tso on gro on gso on`

```
# ethtool -k p1p1                                 
Features for p1p1:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: off [fixed]
	tx-checksum-ip-generic: on
	tx-checksum-ipv6: off [fixed]
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: on
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp-mangleid-segmentation: on
	tx-tcp6-segmentation: on
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: on
generic-receive-offload: on
large-receive-offload: off
rx-vlan-offload: off
tx-vlan-offload: off
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: off
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: on
tx-gre-csum-segmentation: on
tx-ipxip4-segmentation: on
tx-ipxip6-segmentation: on
tx-udp_tnl-segmentation: on
tx-udp_tnl-csum-segmentation: on
tx-gso-partial: on
tx-sctp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
busy-poll: on [fixed]
hw-tc-offload: off
```

**Comment by lttlrck** [comment]
Sorry, I misunderstood your message, I *should* always have offloading *off* in which case the behaviour I see above is correct. 

I I found the issue, I wasn't disabling `gro` and `gso`. Will confirm.

**Comment by lttlrck** [comment]
Yes!

Thank you so much for prodding me in the right direction. I've been playing with netmap for a couple of years and although I have had very few issues, whenever I have the responses has been very quick and helpful.

Grazie.
