### ISSUE TITLE
What netmap+kernel+driver versions currently work for e1000e?

### ISSUE THREAD

**Issue by debatem1** [luigirizzo/netmap#460]
Hello,

I'm attempting to use netmap with an e1000e pcie card. However, attempting to build tip of tree master against recent kernel versions (eg, 4.14 LTS) yields a variety of compile errors during the configure step. This leads me to conclude that I have some combination of the incorrect kernel version, netmap version, or perhaps I'm pulling down the wrong out-of-tree intel driver (defaults to 3.3.6). 

Can you please clarify what the most recent known-working combination should be?

Thanks!

**Comment by vmaffione** [comment]
Hello,
  There are so many combinations that it is hard to tell. In general, Intel out of tree drivers take a while to add support for recent kernels. This is what happens in your case, and there is no other solution than wait (or fix it yourself).
You should simply use the in-tree drivers (using `--no-ext-drivers` and `--kernel-sources` to specify the source code location), those will work.

**Comment by debatem1** [comment]
Thanks, this works-- the drivers now build.

However, I'm seeing considerably higher CPU utilization than I expected upon running pkt-gen (100% cpu utilization) and I suspect that I've messed something up. Some questions for you:

1/ Is it expected that sending 60B packets at ~510Mbps would soak up 1Ghz? This is on ARM64, if that helps. By ~400B packets I'm able to hit 1Gbps, but it still soaks up the whole core.

2/ What is the current correct way to confirm that I am not hitting the generic driver path? By deliberately attaching to an unsupported NIC I can confirm that I see the generic_netmap_attach messages in dmesg for that NIC. When I attach to the e1000e I do not get these messages. Is this proof positive that I am not hitting the generic driver path on the e1000e? Alternatively, is there a better test?

3/  I've run the following to disable offloading:

ethtool -K enp0s0 tx off rx off gso off tso off gro off lro off rxhash off rxvlan off

Should this be sufficient or is there more which needs to be done to ensure that offloading isn't throwing off my results?

4/ Are there other checks or issues with my environment which may prevent me from seeing the low CPU utilization described elsewhere?

Thanks, apologies if I'm making a simple mistake, and please let me know if I should re-title this issue.

**Comment by debatem1** [comment]
Ah, forgot my pkt-gen output. Here you go:

"""
root@espressobin:~# ./pkt-gen -i enp0s0 -f tx -n 500111222 -l 60 -w 5
068.105981 main [2740] interface is enp0s0
068.106134 main [2865] using default burst size: 512
068.106254 main [2873] running on 1 cpus (have 2)
068.107412 extract_ip_range [464] range is 10.0.0.1:1234 to 10.0.0.1:1234
068.107464 extract_ip_range [464] range is 10.1.0.1:1234 to 10.1.0.1:1234
068.107543 nm_open [853] overriding ARG1 0
068.107554 nm_open [857] overriding ARG2 0
068.107562 nm_open [861] overriding ARG3 0
068.107570 nm_open [865] overriding RING_CFG
068.107577 nm_open [874] overriding ifname enp0s0 ringid 0x0 flags 0x8001
068.292549 main [2972] mapped 334980KB at 0x7fa0b60000
Sending on netmap:enp0s0: 1 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
068.292703 main [3069] Sending 512 packets every  0.000000000 s
068.292772 start_threads [2412] Wait 5 secs for phy reset
073.292889 start_threads [2414] Ready...
073.293231 sender_body [1519] start, fd 3 main_fd 3
073.388513 sender_body [1603] drop copy
074.294226 main_thread [2502] 1.067 Mpps (1.068 Mpkts 512.782 Mbps in 1001039 usec) 18.18 avg_batch 0 min_space
075.295338 main_thread [2502] 1.068 Mpps (1.070 Mpkts 513.404 Mbps in 1001112 usec) 17.13 avg_batch 99999 min_space
076.296452 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.545 Mbps in 1001114 usec) 16.99 avg_batch 99999 min_space
077.297569 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.520 Mbps in 1001116 usec) 16.98 avg_batch 99999 min_space
078.298690 main_thread [2502] 1.068 Mpps (1.070 Mpkts 513.403 Mbps in 1001121 usec) 17.19 avg_batch 99999 min_space
079.299802 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.696 Mbps in 1001113 usec) 16.92 avg_batch 99999 min_space
080.299945 main_thread [2502] 1.069 Mpps (1.069 Mpkts 513.024 Mbps in 1000144 usec) 16.93 avg_batch 99999 min_space
081.301050 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.678 Mbps in 1001104 usec) 16.93 avg_batch 99999 min_space
082.302157 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.615 Mbps in 1001107 usec) 16.92 avg_batch 99999 min_space
083.303271 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.652 Mbps in 1001114 usec) 16.93 avg_batch 99999 min_space
084.304378 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.568 Mbps in 1001108 usec) 16.91 avg_batch 99999 min_space
085.305478 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.685 Mbps in 1001099 usec) 16.93 avg_batch 99999 min_space
086.306585 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.552 Mbps in 1001106 usec) 16.93 avg_batch 99999 min_space
087.307699 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.648 Mbps in 1001115 usec) 16.93 avg_batch 99999 min_space
088.308818 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.483 Mbps in 1001119 usec) 17.11 avg_batch 99999 min_space
089.309935 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.631 Mbps in 1001117 usec) 16.92 avg_batch 99999 min_space
090.311042 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.571 Mbps in 1001107 usec) 16.91 avg_batch 99999 min_space
091.312146 main_thread [2502] 1.069 Mpps (1.070 Mpkts 513.650 Mbps in 1001104 usec) 16.92 avg_batch 99999 min_space
^C091.833385 sigint_h [519] received control-C on thread 0x7fb54c1000
091.833483 sender_body [1647] flush tail 158 head 158 on thread 0x7fa0b5f200
091.833486 main_thread [2502] 1.069 Mpps (557.062 Kpkts 267.390 Mbps in 521340 usec) 16.94 avg_batch 99999 min_space
092.834578 main_thread [2502] 0.000 pps (0.000 pkts 0.000 bps in 1001092 usec) 0.00 avg_batch 99999 min_space
Sent 19813534 packets 1188812040 bytes 1163554 events 60 bytes each in 18.54 seconds.
Speed: 1.069 Mpps Bandwidth: 512.964 Mbps (raw 718.150 Mbps). Average batch: 17.03 pkts
"""

CPU utilization as measured by top -b pegs at 100% for the entire run, but I can provide that too if it helps (and isn't too verbose).

**Comment by vmaffione** [comment]
Hi,
1. I don't have that much experience with ARM64, so I don't know how fast or slow that hardware is. You are transmitting at ~720Kpps I guess. Are you able to send at the same rate using the Linux stack? If yes, how much CPU does it consume? You could do such a comparison to check that pkt-gen utilization is lower.
2. To be 100% sure you are not hitting the emulated netmap mode you can set the admode parameter to 1 (and restart your applications). Netmap will refuse to work in emulated mode in this case. Also you can check with lsmod that e1000e depends on netmap, to make sure you are using the patched driver.
3. Yes. But anyway offloadings do not really throw off your results in case you are using netmap only. Disabling offloading is mostly important when you are using the host rings (so you are using netmap and the host stacks/sockets together). If you don't disable them, netmap will drop packets coming from the host stack, making communication with the host stack impossible.
4. Make sure ethernet flow control is disabled. I see that your average batch is not very high (17). You could try to add a `usleep()` after the `poll()` call in `sender_body()`. Try wih 1, 5, 10, 50, 100, 200, 500, ... microseconds. You may be able to increase the average batch and so improve CPU utilization. Independently, check how many interrupts are you getting per seconds, and change the interrupt moderation settings of your NIC accordingly (higher moderation interval will improve the batch).

**Comment by debatem1** [comment]
Hello,

1/ Yes, iperf can hit the same rates at lower CPU utilization (~14%).

2/ Thank you, I've confirmed that I am using the netmap driver using the tests you've described.

3/ Interesting, I'll bear that in mind. Thank you.

4/ Adding the usleep() does indeed reduce CPU consumption-- in fact, the drop is quite substantial. I can get it down into the 5% range and still saturate the link with 1500B packets.  Hitting 1Mpps with 60B packets is possible at roughly 30% CPU utilization. Setting the interrupt moderation doesn't seem to produce very significant performance swings (a few percent at most).

Overall I'm still somewhat surprised that we don't seem to be hitting the performance that back-of-napkin math indicates should be possible. In particular, dividing down from the 14.88Mpps/Ghz number suggests that we should be able to do roughly 1.44Mpps with about 10% CPU utilization but under no circumstances do we do so. Around 700kpps, where we would expect to see 5% utilization, we instead see 24% utilization, and so on. I'm content to close this bug and grind down performance issues on my own, but if you have any other pointers for helping get closer to the theoretical limits I'd really appreciate them.

Thank you for your help,

**Comment by vmaffione** [comment]
For point (1), are you really sure that iperf is sending over 700 Kpps of **60 bytes** frames while consuming only 14% of a CPU? Maybe iperf is transmitting larger frames? iperf must pay a system call, data copy and sk_buff allocation for each packet, so it is not realistic that it can consume less CPU than netmap, for multiple reasons: netmap transmits many packets (avg batch) with a single system call and does not need any data copy or skbuff allocation.

Are you taking the "14.88Mpps/Ghz" number from the netmap paper? That is true, but it is assuming a large average batch experienced by the application (e.g. `avg_batch` in `pkt-gen`), something like 512. There is a relevant fixed cost that you pay per batch (e.g. syscall, kernel txsync), plus a smaller cost per packet. The bigger the batch, the less you pay on average per packet, so the less CPU consumption, and the higher the throughput. If you are interested to this kind of producer/consumer performance issues, and the role of batching, you may look at this paper https://doi.org/10.1093/comjnl/bxx092
