### ISSUE TITLE
Does nm_nextpkt invalidate past packets?

### ISSUE THREAD

**Issue by jmtilli** [luigirizzo/netmap#470]
Hi,

I'm developing a high-performance wrapper around both raw PF_PACKET sockets and netmap. It allows an application to use PF_PACKET sockets when the netmap kernel module is not loaded, and netmap otherwise. Now, packet reception requires an expensive virtual function call through a function pointer due to the abstraction layer. I would prefer to receive multiple packets at once, therefore, to keep performance as high as possible.

The use case is like this, except the 128 nm_nextpkt calls are abstracted in a function pointer:

    for (i = 0; i < 128; i++)
      pkt[i] = nm_nextpkt(nmd, &hdr[i]);
    for (i = 0; i < 128; i++)
      process_packet(pkt[i], &hdr[i]);

(for simplicity, I left out the check to see if received packet is NULL meaning there are no more packets right now)

There is no ioctl or poll system call between the call to look at next 128 packets and the call to process the packets. No other thread uses the nmd or its file descriptor. `process_packet` may inject packets out via a different nmd bound to the same interface, but it does not use the same nmd. It may call `NIOCTXSYNC` using the other nmd and its file descriptor. I have `NETMAP_NO_TX_POLL` flag set.

My question is, does this work now properly? Will it work in the future as well?

I would like to avoid memory copy from the netmap data input area to somewhere else, as every memory copy reduces performance considerably. So that's why it would be nice if netmap keeps the input area accessible across `nm_nextpkt` calls.

**Comment by vmaffione** [comment]
Netmap memory area for an interface (including buffers) is always accessbile as long as you keep the netmap file descriptor open. So no copy is required. And the pointers to netmap buffers will be always valid until you close the descriptors.

In any case, I strongly recommend to avoid using `nm_inject`, `nm_dispatch` and `nm_nextpkt`, as those are there only to provide easy integration with already existing libpcap software.
If you are writing a new application, just use the netmap API directly (e.g. directly scanning the rings). That would give you the best performance.
You should look at the examples in the netmap tutorial (https://github.com/netmap-unipi/netmap-tutorial): `intro.pdf`, `codelab/` `solutions/`

**Comment by jmtilli** [comment]
Ok, thanks for the pointers! I suppose it works, then, but I have to investigate whether the raw netmap API gives better performance. If it does, I'm definitely going to take advantage of it!

An additional question: can I modify packet in the netmap input buffer? My application does not pass the packet unmodified, it has to make small changes to it. The changes do not modify the packet length. There are two ways I can modify it:

1. Directly modify the packet in the input buffer, and then put the packet to the output buffer
2. Copy the packet from the input buffer to a temporary memory area, modify packet in the temporary memory area, then put the packet to the output buffer

Approach (1) would save a memory copy. But can I modify packets directly in the input buffer?

**Comment by vmaffione** [comment]
I would say better performance and simpler code.
Netmap buffers are read write,e you are free to do any modification you wish. You can then zero-copy forward packets by packet swapping (see the tutorial), which means that you don't have to copy the modified input buffer into the output buffer, but just swap the input buffer with the output buffer.

**Comment by jmtilli** [comment]
Thanks! I definitely will take a look at the tutorial.
