### ISSUE TITLE
Vale pipe: the buffer flags are not transmitted

### ISSUE THREAD

**Issue by KGergo88** [luigirizzo/netmap#483]
I am currently working on an IPC communication using vale pipes. I would like to send packets that are bigger than the default 2048 byte slot length with the flag NS_MOREFRAG. The problem is that flag values that are being set on the transmitter side are not received on the other side. Writing the flags to NS_MOREFRAG or 0xFF will for example result in 0x00 on the receiver side.

The functionality work perfectly with the tagged version v11.3 but not in the [more recent (non-tagged) commit](https://github.com/luigirizzo/netmap/commit/53caf0a8be56ec21d5d4c2f0945408ce31367589).
The reason why I would like to use the recent commits is that the tag v11.4 does not compile and the tags before that have issues with high frequency packet transmission (packets are lost or sent not in order or sent duplicated).

**Comment by giuseppelettieri** [comment]
I assume you are referring to netmap pipes. Yes, the flags where not being copied. May please try with the latest commit?

**Comment by KGergo88** [comment]
It seems to be working now with the new commit.

Thank you for your help!
