### ISSUE TITLE
netmap.c: In function ‘netmap_attach_ext’ , netmap.c:3071:14: error: ‘struct net_device_ops’ has no member named ‘ndo_change_mtu’

### ISSUE THREAD

**Issue by varuns-zetaris** [luigirizzo/netmap#487]
Linux kernel - 3.10.0-862.2.3.el7.x86_64
CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)

Trying to build netmap. But get this error

**Comment by giuseppelettieri** [comment]
Please try again with the latest master.

**Comment by vmaffione** [comment]
This has been fixed.
