### ISSUE TITLE
Assistance with issue in Tcpreplay

### ISSUE THREAD

**Issue by fklassen** [luigirizzo/netmap#488]
Hi, I have someone reporting an issue which seems to be from some version of netmap. I am having trouble recreating it. Do you know which version they are using? Are you familiar with any changes in this area?

[Here](https://github.com/appneta/tcpreplay/issues/424) is the issue.

**Comment by vmaffione** [comment]
Hi,
  We are not familiar with tcpreplay.
Netmap macros have not been changed.
It may be that your application is not updating correctly `ring->head` and `ring->cur`.

In any case you would need to collect only the aspects of the issue that are specific to netmap, as opposed to information specific to tcpreplay.

**Comment by fklassen** [comment]
Thanks for the insight. Nothing has changed in Tcpreplay and it was fully tested last beta release. Can't reproduce.
