### ISSUE TITLE
clang failure: error: arithmetic on a pointer to void

### ISSUE THREAD

**Issue by bmerry** [luigirizzo/netmap#489]
With the latest HEAD (f13b878) I get an error when compiling against the netmap header using clang:
```
/home/travis/build/ska-sa/spead2/netmap/sys/net/netmap_user.h:1051:8: error: arithmetic on a pointer to void
   buf += ring->nr_buf_size;
   ~~~ ^
1 error generated.
```

I haven't bisected, but from git blame it looks like 0da480dd is responsible.

**Comment by giuseppelettieri** [comment]
Correct. May you please try again with the latest master?

**Comment by bmerry** [comment]
Confirmed, master is now compiling successfully. Thanks.
