### ISSUE TITLE
How to set the number of expected pipes?

### ISSUE THREAD

**Issue by Crosse** [luigirizzo/netmap#490]
The netmap(4) man page states that when calling the `NIOCREGIF` ioctl, one can specify the number of pipes one intends to open in that memory region so that the netmap kernel module can "...reserve extra space in the memory region."

However, I see in 8c3fddc that the ability to specify this "expected" number of pipes in `nr_arg1` of the `nmreq` struct was removed from the code base, but I couldn't find much information about why the change was made. I also noticed that the man page has not been updated to reflect the change, which had me wondering if it was an accidental oversight, or if the ability to set `nr_pipes` was simply a refactoring that wasn't finished yet:

https://github.com/luigirizzo/netmap/blob/eeade5e5e468d9382117404d2289c00dc342cf17/share/man/man4/netmap.4#L637-L641

I had reason to update the version of Netmap we use internally and stumbled upon this change due to some of our processes not being able to start the number of pipes they needed (we have a few memory regions that require upwards of 16–24 pipes, which is too many for the memory allocated by default to handle).

So I think my question here is this: is there a new way to specify the number of pipes we expect to open in a memory region, or has this ability been removed for good? If the former, I'd love to know more about it and am willing to submit a PR to update the man page with the new details! Also, if there's some work that we can do to help, please let me or @ameske know!

**Comment by giuseppelettieri** [comment]
Hi @Crosse, you are right about the fact that it is a partially unfinished refactoring. For now, you can increase the number of preallocated netmap ifs, rings and buffers for private memory regions. Just write the values in ```/sys/module/netmap/parameters/priv_{if,ring,buf}_num``` before starting the apps. You need one "if" per ```NIOCREGIF```, a couple of rings per pipe *endpoint*, and enough buffers to fill all the rings. If you are using each pipe unidirectionally, and you are opening the pipe endpoints with the  ```/T``` (for tx) and ```/R```  (for rx) flags, you only need one ring per pipe endpoint.

**Comment by Crosse** [comment]
Thank you for the information! I'll see how I can fit this into my application.
