### ISSUE TITLE
packets too large at destination

### ISSUE THREAD

**Issue by robabram** [luigirizzo/netmap#491]
I am running scp to copy a large file from a test machine to a destination machine, in the middle is another machine using two netmap enabled i211 nics (igb driver) running a bridge program.  The problem is after a certain number of packets are sent, the packets start arriving with data appended that wasn't there.  Additionally IP header total length value has also been changed.  This seems related to TCP segments. This behavior does not show up when doing normal internet activity over the bridge (IE: browsing web pages, watching videos).  Only when I use scp or rsync.

When I dump the packets in the bridge program right at the time the bridge program does a zero copy (non-zero copy copy same result) the packets are identical to the source machine's packet capture.

Below are the wireshark screen shots.  The left side is a dump from the bridge program right at the time of the zero copy.  The right side is the destination machine.  All packet the data is identical except the ip header total length value has been changed and extra (random) data appears after where the original packet ends up to the end of the new length value given in the IP header.

![bad-size-packets](https://user-images.githubusercontent.com/5098968/40880844-b0f595bc-6675-11e8-8ddd-332fe420205a.png)

The bridge machine is running CentOS 7 and yesterday I grabbed and built new netmap drivers from master.  There was no change in behavior bumping the igb driver from 5.3.5.15 to 5.3.5.18. I have also swapped both the source, bridge and destination machines with other machines with no change in behavior. Lastly, I tried swapping rsync with scp with no affect either.  

All off-loads (tso, gso) and check-summing are disabled on the bridge nics.

I am really stumped on what/where the IP header total length value is being changed and extra data added.  It seems like this is happening somewhere between the ioctl() call and the packet being transmitted on the bridge adapter.

I am hoping that someone might have an idea as to why this is happening. Thanks.

**Comment by robabram** [comment]
I realized the source machine was sending to the gateway/firewall mac which is on the other side of the bridge. I captured the packets on the gateway and they are correct.  So the issue must lie with the destination machine, not the netmap bridge machine.

**Comment by vmaffione** [comment]
I was about to say that netmap and the patched drivers do not modify the packets in any way.
Since the IP length changes together with the IP header checksum, it's clear that some middlebox doing some manipulation on your packets (on purpose).

**Comment by robabram** [comment]
Why and where that is happening is a real mystery, although I think it has to do with NAT.  I've been developing a high performance host filtering firewall using netmap and those packets were being NAT'd by the bridge program.
