### ISSUE TITLE
Linux: ixgbe module error

### ISSUE THREAD

**Issue by pothos** [luigirizzo/netmap#492]
Hello,

maybe someone can help? If netmap is compiled with `make` then `insmod netmap.ko; insmod ./ixgbe/ixgbe.ko` fails with `Unknown symbol linux_netmap_set_ringparam` in `dmesg`. Both on recent Fedora with Linux 4.16 and on Ubuntu 16.4 with Linux 4.8 or 4.13. (However `cd ixgbe; make; insmod ./ixgbe.ko` works but then it is not used but the generic driver which also is not usabe because of `netmap adapter hook is busy`.)

**Comment by giuseppelettieri** [comment]
May you please try again with the latest master?

**Comment by pothos** [comment]
Thanks for the quick response, yes, compilation and loading of the modules works. The generic driver receives packets but there is some issue with ixgbe immediately stalling the kernel on RX/TX usage – I try to find out more.
