### ISSUE TITLE
Ubuntu 18，failed in "open("/dev/netmap", 0)". Did i failed in installing netmap?

### ISSUE THREAD

**Issue by Cukuyo** [luigirizzo/netmap#493]
> sy@sy-VirtualBox:/dev$ ls | grep net
net
network_latency
network_throughput
vhost-net

No "/dev/netmap" ,Did i failed in installing netmap?

**Comment by Cukuyo** [comment]
This is my "./configure"
`kernel directory            /lib/modules/4.15.0-22-generic/build
                            [/usr/src/linux-headers-4.15.0-22-generic]
kernel sources              /lib/modules/4.15.0-22-generic/build
                            [/usr/src/linux-headers-4.15.0-22-generic]
linux version               40f11  [4.15.17]
module file                 netmap.ko

subsystems                  generic monitor pipe vale
apps                        dedup vale-ctl nmreplay tlem lb bridge pkt-gen
native drivers              i40e ixgbe

Contents of the drivers.mak file:
mlx5@conf := CONFIG_MLX5_CORE_EN
mlx5@src := tar xf /home/sy/netmap/LINUX/ext-drivers/mlnx-en-3.3-1.0.0.0.tgz && tar xf mlnx-en-3.3-1.0.0.0/SOURCES/mlnx-en_3.3.orig.tar.gz && ln -s mlnx-en-3.3 mlx5
mlx5@patch := patches/mellanox--mlx5--3.3
i40e@conf := CONFIG_I40E
i40e@src := tar xf /home/sy/netmap/LINUX/ext-drivers/i40e-2.4.6.tar.gz && ln -s i40e-2.4.6/src i40e
i40e@patch := patches/intel--i40e--2.4.6
ixgbevf@conf := CONFIG_IXGBEVF
ixgbevf@src := tar xf /home/sy/netmap/LINUX/ext-drivers/ixgbevf-4.3.2.tar.gz && ln -s ixgbevf-4.3.2/src ixgbevf
ixgbevf@patch := patches/intel--ixgbevf--4.3.2
ixgbe@conf := CONFIG_IXGBE
ixgbe@src := tar xf /home/sy/netmap/LINUX/ext-drivers/ixgbe-5.3.7.tar.gz && ln -s ixgbe-5.3.7/src ixgbe
ixgbe@patch := patches/intel--ixgbe--5.3.7
igb@conf := CONFIG_IGB
igb@src := tar xf /home/sy/netmap/LINUX/ext-drivers/igb-5.3.5.12.tar.gz && ln -s igb-5.3.5.12/src igb
igb@patch := patches/intel--igb--5.3.5.12
e1000e@conf := CONFIG_E1000E
e1000e@src := tar xf /home/sy/netmap/LINUX/ext-drivers/e1000e-3.4.0.2.tar.gz && ln -s e1000e-3.4.0.2/src e1000e
e1000e@patch := patches/intel--e1000e--3.4.0.2`
And my "sudo make"、"sudo make install" are successful.No error and warning.

**Comment by vmaffione** [comment]
Please read the instructions (https://github.com/luigirizzo/netmap/blob/master/LINUX/README#L181). You are missing the `insmod` step.

**Comment by Cukuyo** [comment]
@vmaffione Thanks.
`sy@sy-VirtualBox:~/netmap/LINUX$ find . -name '*.ko'
./ixgbe-5.3.7/src/ixgbe.ko
./netmap-tmpdir/ixgbe-5.3.7/src/ixgbe.ko
./netmap-tmpdir/i40e-2.4.6/src/i40e.ko
./i40e-2.4.6/src/i40e.ko
./netmap.ko`
Should I insmod all ? Or , What I should insmod depends on "./configue".

**Comment by Cukuyo** [comment]
@vmaffione 

> sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./ixgbe-5.3.7/src/ixgbe.ko
insmod: ERROR: could not insert module ./ixgbe-5.3.7/src/ixgbe.ko: Unknown symbol in module
sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./i40e-2.4.6/src/i40e.ko
insmod: ERROR: could not insert module ./i40e-2.4.6/src/i40e.ko: Unknown symbol in module

I tried to insmod , but failed.

**Comment by Cukuyo** [comment]
@vmaffione 
I resolve the questions above , and I insmod all and turn up my interface .

sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./i40e-2.4.6/src/i40e.ko
insmod: ERROR: could not insert module ./i40e-2.4.6/src/i40e.ko: Unknown symbol in module
sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./ixgbe-5.3.7/src/ixgbe.ko 
insmod: ERROR: could not insert module ./ixgbe-5.3.7/src/ixgbe.ko: Unknown symbol in module
sy@sy-VirtualBox:~/netmap/LINUX$ dmesg | tail
[16558.542320] i40e: Unknown symbol ptp_clock_unregister (err 0)
[16578.759101] ixgbe: Unknown symbol dca_remove_requester (err 0)
[16578.759125] ixgbe: Unknown symbol ptp_clock_index (err 0)
[16578.759167] ixgbe: Unknown symbol dca_add_requester (err 0)
[16578.759177] ixgbe: Unknown symbol ptp_clock_register (err 0)
[16578.759201] ixgbe: Unknown symbol dca_unregister_notify (err 0)
[16578.759211] ixgbe: Unknown symbol dca_register_notify (err 0)
[16578.759223] ixgbe: Unknown symbol ptp_clock_event (err 0)
[16578.759231] ixgbe: Unknown symbol dca3_get_tag (err 0)
[16578.759241] ixgbe: Unknown symbol ptp_clock_unregister (err 0)
sy@sy-VirtualBox:~/netmap/LINUX$ sudo modprobe dca
sy@sy-VirtualBox:~/netmap/LINUX$ sudo modprobe ptp
sy@sy-VirtualBox:~/netmap/LINUX$ sudo modprobe netmap
sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./i40e-2.4.6/src/i40e.ko
sy@sy-VirtualBox:~/netmap/LINUX$ sudo insmod ./ixgbe-5.3.7/src/ixgbe.ko
sy@sy-VirtualBox:~/netmap/LINUX$ sudo ifconfig enp0s3 up

After this , I find the "netmap" folder appeared .
> sy@sy-VirtualBox:/dev$ ls | grep "ap"
> mapper
> netmap
> snapshot

But when I run  my program , It is still failed .

>     int fd = open("/dev/netmap", 0);
    if (fd < 0) {
        printf("error in open:端口和环是通过一个文件描述符打开一个特殊的设备创建和控制的\n");
        return 0;
    }

**Comment by giuseppelettieri** [comment]
What is the error message returned by ```open```? (```perror("/dev/netmap")```)

**Comment by Cukuyo** [comment]
I find the answer ! I should run my program by root .
But  it is still failed , failed in flow code 

>     int err = ioctl(fd, NIOCREGIF, &req);//offset of the structure
    if (err) {
        printf("error in ioctl:code=%d:Unable to get virtio-net header length\n",err);
        return 0;
    }

out : error in ioctl:code=-1:Unable to get virtio-net header length
But why?
