### ISSUE TITLE
Linux hangs

### ISSUE THREAD

**Issue by pothos** [luigirizzo/netmap#497]
In most cases, the kernel hangs after some (short) time when using `pkg-gen` with `-f rx` or `-f tx`. In (Fedora) Linux 4.16 it normally crashes directly after startup, but in (Ubuntu) Linux 4.8 it sometimes works but then may crash the next time. Kernel parameter `intel_iommu=off` is used and also reducing the value in `/sys/module/netmap/parameters/buf_num` to `20000` did not make a difference.
First I thought that not assigning an IP does help, but still it fails often. I also checked that NetworkManager is not running if managing the device would cause problems.
Also I turned flow control and offloading off with `ethtool -K enp1s0f0 tx off rx off gso off tso off gro off` and `ethtool --pause enp1s0f0 rx off`. Is there anything else I should do?

The next step I had planned to try was `--select-version=ixgbe:4.2.1` but it won't compile… it targets which kernel version?

Thanks a lot for any help.

**Comment by giuseppelettieri** [comment]
Do you know when these problems started to appear? May you please try with an oldest commit, like 79bac01af30ed4e0376?

**Comment by pothos** [comment]
Good idea, yet it's also hanging as soon a packet is to be received.

**Comment by giuseppelettieri** [comment]
Maybe I have found it. May you please try with the latest master?

**Comment by pothos** [comment]
Yes, it works, wonderful! :+1:
Thanks a lot to take my report seriously and even investigating yourself.
I haven't used netmap before, and now I'm  very happy to get started :)

**Comment by pothos** [comment]
Btw: The generic driver still hangs - should I open another issue or is it related to this fix here?

**Comment by pothos** [comment]
I can confirm that the introduced patch leads to a hang when the generic driver is used.

**Comment by giuseppelettieri** [comment]
yep, the fix exposed some uninitialized field elsewhere. Please try again with the current master, and thanks for reporting.

**Comment by pothos** [comment]
Good, it's fixed and both work.
