### ISSUE TITLE
Does netmap support i40evf driver?

### ISSUE THREAD

**Issue by wtao0221** [luigirizzo/netmap#498]
Hi,

I just want to run netmap in VM with a i40evf pci-passthrough NIC.

Does netmap support it?

**Comment by wtao0221** [comment]
It seems that netmap does not support i40evf.

So how to add the support? Do you have any suggestions?

**Comment by giuseppelettieri** [comment]
No, there is no support for i40evf yet. If you want to work on it, you may take a look at how we patch ```i40e_main.c``` and ```i40e_rxtx.c```, and the functions defined in ```LINUX/i40e_netmap_linux.h```. You should do something similar in the corresponding files of i40evf. The functions defined in  ```i40e_netmap_linux.h```  are probably reusable for the most part and also most of the places where you need to call them are easily identifiable. The trickiest part may be switch the card in and out of netmap mode: you need to bring the card down, toggle the netmap flag and bring it up again. From a cursory look at the code, it looks that up and down operation are handled asynchronously in this driver, and you need to find a way to wait for the for the card to complete the procedure.

**Comment by wtao0221** [comment]
Thanks for the suggestions. I will try.
