### ISSUE TITLE
How to check RSS of netmap

### ISSUE THREAD

**Issue by wtao0221** [luigirizzo/netmap#500]
Hi,

As I hack the codes, I only know ```nr_ringid``` may be the index of ```netmap``` ring index. But how does the ```netmap``` maps the underlying multi-queue NIC's queues to ```netmap``` ring buffer?

Could you please offer some suggestions?

**Comment by vmaffione** [comment]
There is a simple one-to-one mapping. For each TX queue of the NIC there will be a netmap TX ring.
For each RX queue of the NIC there will be a netmap RX ring.

**Comment by wtao0221** [comment]
Hi, @vmaffione 

Thanks.

But how to check that? For example, which ```netmap``` ring is mapped to the physical ```q-0``` ?

**Comment by vmaffione** [comment]
Netmap rings are just numbered in the same way.
Netmap tx ring 0 corresponds to NIC physical TX ring 0.
Netmap tx ring 1 corresponds to NIC physical TX ring 1.
...
Netmap tx ring N-1 corresponds to NIC physical TX ring N-1.
The same for RX rings.

You can use the `NETMAP_RXRING` and `NETMAP_TXRING` macros to get a pointer to a certain ring.
Example `NETMAP_TXRING(nifp, 3)` returns a `struct netmap_ring *` pointing to the TX ring 3, which is mapped to the physical NIC ring 3.

**Comment by WqyJh** [comment]
When there's multiple nic queues, does it need more threads to handle the rings. Such as a 10GbE card with 37 RX/TX queues, I don't think a single thread [lb](https://github.com/luigirizzo/netmap/tree/master/apps/lb) was able to handle this.
```
RX:		37
TX:		37
Other:		0
Combined:	74
Current hardware settings:
RX:		0
TX:		0
Other:		0
Combined:	4
```
