### ISSUE TITLE
Error message while testing Netmap passthrough

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#505]
Hi. I'm testing Netmap passthrough according to https://github.com/luigirizzo/netmap/blob/master/README.ptnetmap

Everything looks ok and I can ping between two Qemu virtual machines through a Netmap pipe. Each VM shows an `eth0` interface which is backed by `ptnetmap-guest-driver`. When I do `pkt-gen -i eth0 -f rx` inside one of the VMs it immediately quits with the error-message `error: netmap buf size (0) < device MTU (1500)`.

I would be happy for some advice how to narrow down this problem.

```
root@linux:/# pkt-gen -i eth0 -f tx
706.383768 main [2738] interface is eth0
706.384563 main [2863] using default burst size: 512
706.385509 main [2871] running on 1 cpus (have 1)
706.386473 extract_ip_range [466] range is 10.0.0.1:1234 to 10.0.0.1:1234
706.387715 extract_ip_range [466] range is 10.1.0.1:1234 to 10.1.0.1:1234
706.388942 nm_parse_one [692] name eth0
706.389738 nm_parse [900] parse OK
706.390384 nm_parse [916] parsed name: eth0
706.391173 nm_open [1035] overriding ARG1 0
706.391955 nm_open [1039] overriding ARG2 0
706.392703 nm_open [1043] overriding ARG3 0
706.393493 nm_open [1047] overriding RING_CFG
706.394273 nm_open [1056] overriding ifname eth0 ringid 0x0 flags 0x8001

[ 2179.135491] ptnet_nm_config: txr 1, rxr 1, txd 1024, rxd 1024
[ 2179.136846] error: netmap buf size (0) < device MTU (1500)
706.398109 nm_open0
706.399252 main [2966] Unable to open netmap:eth0: Invalid argument
706.400333 main [3032] aborting
```

Many thanks in advance!

**Comment by vmaffione** [comment]
Yes, I should stress it in the documentation. Technically if you blindly follow the instructions you won't run into that error (as there is no `git checkout v11.4` in the guest side instructions.

You can ignore the `vnet-hdr` message, is not an error. It simply means that QEMU is probing the passed-through netmap port to see if it supports the virtio-net header. More information here https://github.com/luigirizzo/netmap/blob/master/README.ptnetmap#L151-L173 and http://info.iet.unipi.it/~luigi/papers/20160613-ptnet.pdf
VALE ports support that, but netmap pipes don't at the moment being.
I will probably suppress that message at some point.
