### ISSUE TITLE
netmap_bdg.c not hooked into FreeBSD build

### ISSUE THREAD

**Issue by larseggert** [luigirizzo/netmap#506]
`netmap_bdg.c` needs to be added to `sys/conf/files` and `sys/modules/netmap/Makefile`, I think.

CC @micchie

**Comment by micchie** [comment]
Yes, but there is no way to do so within this netmap repo:/ We will fix it next time syncing with FreeBSD, which should be before 12-RELEASE.

**Comment by larseggert** [comment]
Ah, of course

**Comment by vmaffione** [comment]
Sorry for the inconvenience.
I will keep aligning this repo to FreeBSD HEAD since end of August (when I'll be able to use my commit bit).

**Comment by vmaffione** [comment]
... and of course I'll update `sys/conf/files`
