### ISSUE TITLE
Netmap application crashes with ptnetmap-guest-driver when using host-ring.

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#509]
Inside a Qemu VM our Netmap application crashes when we open the host-ring of a `ptnet` interface. Before we start to analyze this problem in more detail I would like to ask if `ptnet` does support host-ring access in the current master version.

```
[    6.481338] ptnet_nm_config: txr 1, rxr 1, txd 1024, rxd 1024, rxbufsz 2048
[    6.482892] 400.659378 [ 780] netmap_update_config      configuration changed for eth1: txring 1 x 1024, rxring 1 x 1024, rxbufsz 2048
[    6.490699] 400.667183 [1713] nm_rxsync_prologue        eth1 RX1: fail 'head < kring->nr_hwcur || head > kring->nr_hwtail' h 1 c 1 t 1 rh 1 rc 1 rt 0 hc 0 ht 0
[    6.493706] 400.670193 [1758] netmap_ring_reinit        called for eth1 RX1
[    6.495184] 400.671670 [1774] netmap_ring_reinit        bad index at slot 0 idx 0 len 0 
[    6.496876] 400.673362 [1774] netmap_ring_reinit        bad index at slot 1 idx 0 len 0 
[    6.498582] 400.675069 [1774] netmap_ring_reinit        bad index at slot 2 idx 0 len 0 
[    6.500274] 400.676761 [1774] netmap_ring_reinit        bad index at slot 3 idx 0 len 0 
[    6.501958] 400.678445 [1774] netmap_ring_reinit        bad index at slot 4 idx 0 len 0 
```

**Comment by vmaffione** [comment]
In theory the host rings are something general and there is no dependency on the specificy netmap port (ptnet, physical port, VALE, veth, etc.). Host rings of ptnet ports used to work well.

Maybe some recent changes to the host rings setup introduced the problem?
From your output it seems that the host rings have not been allocated for some reason (the netmap_slot.buf_idx is 0 for all of them). This is consistent with what I see with `bridge`:
````
sudo bridge netmap:ens4
bridge built Jul  7 2018 04:47:17

744.826695 main [244] same interface, endpoint 0 goes to host
744.837169 nm_mmap [984] do not mmap, inherit from parent
744.837405 main [266] ------- zerocopy supported
744.837527 main [273] Wait 4 secs for link to come up...
748.838057 main [277] Ready to go, ens4 0x1/1 <-> ens4 0x0/1.
748.838745 process_rings [80] wrong index rx[1] = 2078  -> tx[30] = 0
750.839632 process_rings [80] wrong index rx[2] = 2079  -> tx[31] = 0
752.840705 process_rings [80] wrong index rx[3] = 2080  -> tx[32] = 0
754.841815 process_rings [80] wrong index rx[6] = 0  -> tx[35] = 2085
756.842889 process_rings [80] wrong index rx[7] = 0  -> tx[36] = 2086
758.843985 process_rings [80] wrong index rx[8] = 0  -> tx[37] = 2087
760.845070 process_rings [80] wrong index rx[9] = 0  -> tx[38] = 2088
762.846046 process_rings [80] wrong index rx[10] = 0  -> tx[39] = 208
````
@giuseppelettieri any ideas?

**Comment by giuseppelettieri** [comment]
This is what I am seeing, unless I am missing something. The host netmap creates the host rings as expected, but Qemu is opening the host port with ```NR_REG_ALL_NIC```, the only mode currently supported for passthrough, and therefore it is receiving 0 in the host rings entries of the ```netmap_if```. The problem is that we should fix this in the host, but we are stuck with 4.11 for now.

**Comment by vmaffione** [comment]
The fix could be something like
````
diff --git a/sys/dev/netmap/netmap.c b/sys/dev/netmap/netmap.c
index 9d0add41..6fbd7226 100644
--- a/sys/dev/netmap/netmap.c
+++ b/sys/dev/netmap/netmap.c
@@ -1784,6 +1784,7 @@ netmap_interp_ringid(struct netmap_priv_d *priv, uint16_t ringid, uint32_t flags
        }
 
        if ((flags & NR_PTNETMAP_HOST) && ((reg != NR_REG_ALL_NIC &&
+                    reg != NR_REG_NIC_SW &&
                     reg != NR_REG_PIPE_MASTER && reg != NR_REG_PIPE_SLAVE) ||
                        flags & (NR_RX_RINGS_ONLY|NR_TX_RINGS_ONLY))) {
                D("Error: only NR_REG_ALL_NIC supported with netmap passthrough");
````
and then qemu could be invoked with `ifname=vale1:10*`, with the `*` used to open also the host rings.
Maybe the TAG can be advanced or recreated?

**Comment by giuseppelettieri** [comment]
This would land on a branch diverging from master, and we don't want to maintain that.

**Comment by giuseppelettieri** [comment]
Personally, I am not sure that the patch would do what we want. It will create a pair of rings connected with the *host* stack, while we probably need them to be connected with the *guest* one.

**Comment by vmaffione** [comment]
@giuseppelettieri is right, sorry for the confusion.
I was confused myself because I thought this needs to be fixed in the host. But maybe this is not true.
If I'm not wrong, we could fix it by modifying these two loops here https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap_mem2.c#L2654-L2669 to allocate the host rings instead of just setting the pointers (like we must do for the passed through "normal" rings).
The code to create the host rings should be this one https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap_mem2.c#L1886-L1938
Am I missing something?

**Comment by giuseppelettieri** [comment]
In the current implementation all the if/ring/buf allocation is done in the host. The guest has no way to ask the host for further allocations after the initial one done by the hypervisor on ```nm_open()``` of the passed-through port.  In the 4.11 host, the ptnetmap wrapper is allocating a pair of rings in the position normally used by the host rings, even if the ```nm_open()``` has not asked for them, just for the purpose of letting the guest use these rings as its own host rings. This "feature" was broken when we started putting 0 in the ```netmap_if``` slots of the rings not mentioned in the ```NIOCREGIF``` (https://github.com/luigirizzo/netmap/blob/v11.4/sys/dev/netmap/netmap_mem2.c#L1944-L1968), so now the guest does not know where they are.

**Comment by vmaffione** [comment]
My bad, I forgot that the guest ptnetmap allocator cannot allocate further objects without extensions to the guest/host API.
Your explanation also confirms why I remember there was a time this worked.

**Comment by ramaza** [comment]
I kindly want to ask about the status of this issue. It sounds like it's not going to be easy to solve this problem.

We could try to work around it by not using host-rings of `ptnet` Interface. Instead we could use the host-rings of a separate `virtio-net` interface. But combining the rather special `ptnet-passthrough` interfaces with regular `virtio-net-netmap` interfaces inside the same Qemu process sounds like trouble.

**Comment by giuseppelettieri** [comment]
The proper fix requires other things to go in first, but this patch should fix your problem in the meantime:
```
diff --git a/sys/dev/netmap/netmap_mem2.c b/sys/dev/netmap/netmap_mem2.c
index 32555af1..d23807e2 100644
--- a/sys/dev/netmap/netmap_mem2.c
+++ b/sys/dev/netmap/netmap_mem2.c
@@ -2009,8 +2009,7 @@ netmap_mem2_if_new(struct netmap_adapter *na, struct netmap_priv_d *priv)
 		 * ring, like we do for buffers? */
 		ssize_t ofs = 0;
 
-		if (na->tx_rings[i]->ring != NULL && i >= priv->np_qfirst[NR_TX]
-				&& i < priv->np_qlast[NR_TX]) {
+		if (na->tx_rings[i]->ring != NULL) {
 			ofs = netmap_ring_offset(na->nm_mem,
 						 na->tx_rings[i]->ring) - base;
 		}
@@ -2021,8 +2020,7 @@ netmap_mem2_if_new(struct netmap_adapter *na, struct netmap_priv_d *priv)
 		 * ring, like we do for buffers? */
 		ssize_t ofs = 0;
 
-		if (na->rx_rings[i]->ring != NULL && i >= priv->np_qfirst[NR_RX]
-				&& i < priv->np_qlast[NR_RX]) {
+		if (na->rx_rings[i]->ring != NULL) {
 			ofs = netmap_ring_offset(na->nm_mem,
 						 na->rx_rings[i]->ring) - base;
 		}
```
Please be aware that this patch must be considered a temporary workaround and is not going to be merged.

**Comment by ramaza** [comment]
Thanks. We will test the patch and provide feedback. The fact that it's not going to be merged is ok as our setup is anyway very experimental.

**Comment by ramaza** [comment]
While testing the patch I was unsure if it's meant to be applied to Host or VM. My intuition says it should be applied to the Host installation of Netmap but technically the patch seems to be written for the master branch which is running inside the VM.

**Comment by giuseppelettieri** [comment]
You are right, the patch is for the host but I prepared it for master instead of v11.4, sorry. Did you manage to apply it anyway?

**Comment by ramaza** [comment]
Yes, I could apply the patch to v11.4 with minor modifications. It looks almost similar.

```
diff --git a/sys/dev/netmap/netmap_mem2.c b/sys/dev/netmap/netmap_mem2.c
index afb2c22e..d8cbf00d 100644
--- a/sys/dev/netmap/netmap_mem2.c
+++ b/sys/dev/netmap/netmap_mem2.c
@@ -1947,8 +1947,7 @@ netmap_mem2_if_new(struct netmap_adapter *na, struct netmap_priv_d *priv)
                 * ring, like we do for buffers? */
                ssize_t ofs = 0;
 
-               if (na->tx_rings[i].ring != NULL && i >= priv->np_qfirst[NR_TX]
-                               && i < priv->np_qlast[NR_TX]) {
+               if (na->tx_rings[i].ring != NULL) {
                        ofs = netmap_ring_offset(na->nm_mem,
                                                 na->tx_rings[i].ring) - base;
                }
@@ -1959,8 +1958,7 @@ netmap_mem2_if_new(struct netmap_adapter *na, struct netmap_priv_d *priv)
                 * ring, like we do for buffers? */
                ssize_t ofs = 0;
 
-               if (na->rx_rings[i].ring != NULL && i >= priv->np_qfirst[NR_RX]
-                               && i < priv->np_qlast[NR_RX]) {
+               if (na->rx_rings[i].ring != NULL) {
                        ofs = netmap_ring_offset(na->nm_mem,
                                                 na->rx_rings[i].ring) - base;
                }
```

**Comment by vmaffione** [comment]
Netmap passthrough has been completely refactored. Tag v11.4 should not be used anymore, just use netmap master and the latest patched QEMU. See `README.ptnetmap`.

**Comment by ramaza** [comment]
We moved from Netmap v11.4 in the host computer to master version as you suggested. Unfortunately the host-rings within Qemu seem to be broken again.

As a brief reminder: This issue was initally about broken host rings with Netmap v11.4 in combination with `ptnet` driver and Qemu. You thankfully provided a provisional patch to work around the problem which did the job. Until now at least.

Any plans to fix host-rings for ptnet or should it work and I should investigate in more detail?

**Comment by vmaffione** [comment]
Yes, sorry for that. Actually, this is a long standing problem, that we plan to solve soon. It has always been broken, or more precisely "unsupported", as it requires an allocation protocol between the guest and the hypervisor, which is now missing.

There is a workaround, though, that you can use while we fix it.
Use this patch in netmap:
````
diff --git a/sys/dev/netmap/netmap.c b/sys/dev/netmap/netmap.c
index cf6b4bc0..8a1e101f 100644
--- a/sys/dev/netmap/netmap.c
+++ b/sys/dev/netmap/netmap.c
@@ -2018,7 +2018,8 @@ netmap_csb_validate(struct netmap_priv_d *priv, struct nmreq_opt_csb *csbo)
 
        tot_rings = 0;
        for_rx_tx(t) {
-               num_rings[t] = priv->np_qlast[t] - priv->np_qfirst[t];
+               num_rings[t] = min(priv->np_qlast[t], nma_get_nrings(priv->np_na, t))
+                               - min(priv->np_qfirst[t], nma_get_nrings(priv->np_na, t));
                tot_rings += num_rings[t];
        }
        if (tot_rings <= 0)
diff --git a/sys/dev/netmap/netmap_kloop.c b/sys/dev/netmap/netmap_kloop.c
index 92f0d7e8..64a5f156 100644
--- a/sys/dev/netmap/netmap_kloop.c
+++ b/sys/dev/netmap/netmap_kloop.c
@@ -482,8 +482,8 @@ netmap_sync_kloop(struct netmap_priv_d *priv, struct nmreq_header *hdr)
                return err;
        }
 
-       num_rx_rings = priv->np_qlast[NR_RX] - priv->np_qfirst[NR_RX];
-       num_tx_rings = priv->np_qlast[NR_TX] - priv->np_qfirst[NR_TX];
+       num_rx_rings = min(priv->np_qlast[NR_RX], nma_get_nrings(priv->np_na, NR_RX)) - priv->np_qfirst[NR_RX];
+       num_tx_rings = min(priv->np_qlast[NR_TX], nma_get_nrings(priv->np_na, NR_TX)) - priv->np_qfirst[NR_TX];
        num_rings = num_tx_rings + num_rx_rings;
 
        /* Validate notification options. */
diff --git a/sys/dev/netmap/netmap_pipe.c b/sys/dev/netmap/netmap_pipe.c
index 51b4f161..e51d999b 100644
--- a/sys/dev/netmap/netmap_pipe.c
+++ b/sys/dev/netmap/netmap_pipe.c
@@ -748,7 +748,7 @@ netmap_get_pipe_na(struct nmreq_header *hdr, struct netmap_adapter **na,
        mna->up.nm_krings_create = netmap_pipe_krings_create;
        mna->up.nm_krings_delete = netmap_pipe_krings_delete;
        mna->up.nm_mem = netmap_mem_get(pna->nm_mem);
-       mna->up.na_flags |= NAF_MEM_OWNER;
+       mna->up.na_flags |= NAF_MEM_OWNER | NAF_HOST_RINGS;
        mna->up.na_lut = pna->na_lut;
 
        mna->up.num_tx_rings = req->nr_tx_rings;
diff --git a/sys/dev/netmap/netmap_vale.c b/sys/dev/netmap/netmap_vale.c
index 13dda8d4..4c940530 100644
--- a/sys/dev/netmap/netmap_vale.c
+++ b/sys/dev/netmap/netmap_vale.c
@@ -1297,7 +1297,7 @@ netmap_vale_vp_create(struct nmreq_header *hdr, struct ifnet *ifp,
        if (netmap_verbose)
                D("max frame size %u", vpna->mfs);
 
-       na->na_flags |= NAF_BDG_MAYSLEEP;
+       na->na_flags |= NAF_BDG_MAYSLEEP | NAF_HOST_RINGS;
        /* persistent VALE ports look like hw devices
         * with a native netmap adapter
         */
````
and this for QEMU:
````
diff --git a/net/netmap.c b/net/netmap.c
index 81a34c6fe3..d640b67011 100644
--- a/net/netmap.c
+++ b/net/netmap.c
@@ -130,7 +130,7 @@ static int netmap_open(NetmapState *s, Error **errp)
     hdr.nr_reqtype = NETMAP_REQ_REGISTER;
     hdr.nr_body    = (uintptr_t)&req;
     hdr.nr_options = (uintptr_t)NULL;
-    req.nr_mode    = NR_REG_ALL_NIC;
+    req.nr_mode    = NR_REG_NIC_SW;
     req.nr_flags   = NR_EXCLUSIVE | NR_NO_TX_POLL;
     ret            = ioctl(s->fd, NIOCCTRL, &hdr);
     if (ret) {

````

**Comment by ramaza** [comment]
Unfortunately it took a few months but recently I could test the patch you provided to make host-rings work again with Qemu + Netmap-Passthrough.

The compilation works fine but changing the one line within Qemu makes the following error appear:
`qemu-system-x86_64: Failed to register pipe}11: Invalid argument`

Leaving Qemu unpatched makes it run as expected but at the same time the host-rings aren't working within Qemu. This is expected without the patch.

Maybe the simple reason that I waited too long for testing the patch and now it no longer fits to the most recent Netmap release (v13).

**Comment by vmaffione** [comment]
You miss this one
````
diff --git a/sys/dev/netmap/netmap_pipe.c b/sys/dev/netmap/netmap_pipe.c
index c15a0831..cd2662d5 100644
--- a/sys/dev/netmap/netmap_pipe.c
+++ b/sys/dev/netmap/netmap_pipe.c
@@ -683,7 +683,7 @@ netmap_get_pipe_na(struct nmreq_header *hdr, struct netmap_adapter **na,
                return EINVAL;
        }
 
-       if (req->nr_mode != NR_REG_ALL_NIC && req->nr_mode != NR_REG_ONE_NIC) {
+       if (req->nr_mode != NR_REG_ALL_NIC && req->nr_mode != NR_REG_ONE_NIC && req->nr_mode != NR_REG_NIC_SW) {
                /* We only accept modes involving hardware rings. */
                return EINVAL;
        }
@@ -771,7 +771,7 @@ netmap_get_pipe_na(struct nmreq_header *hdr, struct netmap_adapter **na,
        mna->up.nm_krings_create = netmap_pipe_krings_create;
        mna->up.nm_krings_delete = netmap_pipe_krings_delete;
        mna->up.nm_mem = netmap_mem_get(pna->nm_mem);
-       mna->up.na_flags |= NAF_MEM_OWNER;
+       mna->up.na_flags |= NAF_MEM_OWNER | NAF_HOST_RINGS;
        mna->up.na_lut = pna->na_lut;
 
        mna->up.num_tx_rings = req->nr_tx_rings;

````

**Comment by ramaza** [comment]
I could finally test the following combination with success:

Netmap v13.0 + Qemu + Passthrough + Hostring

Thank you very much for the patches and assistance. I'm closing this issue now.
