### ISSUE TITLE
Do I have to use all rings?

### ISSUE THREAD

**Issue by Flow-It** [luigirizzo/netmap#510]
Depending on the NIC, a netmap interface provides access to multiple ring structs. Is it enough for an application to only read from a single ring (let's say 0) and receive all packets anyway, or is my application required to loop through all rings?

**Comment by giuseppelettieri** [comment]
netmap gives you one ring for each ring configured in the NIC. The NIC will put incoming packets on different rings, based on their flow, and if you only look at only one ring you are going to miss some packets. Alternatively, you can change the NIC configuration before putting it in netmap mode:
```
ethtool -L eth0 combined 1
```
This wil configure only one ring for direction in interface ```etht0```.
