### ISSUE TITLE
Recent changes do not support NS_MOREFRAG for --no-drivers option

### ISSUE THREAD

**Issue by john-gress** [luigirizzo/netmap#512]
I'm using netmap on CentOS 7.4 with no problems. Recently, I tried updating to CentOS 7.5 (kernel 3.10.0-862.3.2.el7.x86_64) and needed to update to the master/head. Now I'm getting the following error:

 kernel: error: large MTU (9000) needed but eno2 does not support NS_MOREFRAG

I'm not using the modified drivers (configure --no-drivers). It looks like the error is telling me that I need to use the modified drivers to get NS_MOREFRAG support. Is that correct?

**Comment by vmaffione** [comment]
Do you really need jumbo frames?
If not you could set the MTU of eno2 to 1500.
````
$ sudo ip link set mtu 1500 dev eno2
````
Or you may set both the MTU and the netmap_buf_size to 4096, also this should work.

**Comment by john-gress** [comment]
I tried an MTU of 2048, and it appears the performance of reading from the interface was negatively impacted when running the latest netmap code on CentOS 7.5. This is compared to the performance of netmap code from approximately 4-Jan-2018 built on CentOS 7.4.

I will try buf_size/MTU of 4096 and report back.

If I can increase the buf_size/MTU to 4096, why can't I increase both to 9000?

**Comment by john-gress** [comment]
Thanks for looking into the issue and getting back to me. Initial testing with the code change appears to work. We are doing some more testing, and I'll let you know the results of that next week.

One other question: currently I'm changing the netmap buf_size using, 
`echo 9000 > /sys/module/netmap/parameters/buf_size`

Is there an easy way to do this programmatically either prior to calling nm_open() or as part of that call?

**Comment by vmaffione** [comment]
No, there is no way right now. You could set the parameter ad `modprobe` time or simply write the sysfs entry from your program.
Note that the buffer size is a property of a netmap allocator, and not of a single netmap port. Many netmap ports may be served by a single netmap allocator.
Physical ports share the same netmap allocator, aka the "global" netmap allocator.

There was an effort to allow fine grained configuration read and write for netmap ports and allocators using JSON. Maybe @giuseppelettieri has more insight on this.

**Comment by john-gress** [comment]
@vmaffione, thanks for your help. There are lots of ways we can set the buf_size. We'll work one out and use it.

We ran additional tests with the `na->rx_buf_maxsize = 32768;` code change and everything looks good.

**Comment by john-gress** [comment]
Opened pull request with the one line code change: https://github.com/luigirizzo/netmap/pull/518

**Comment by vmaffione** [comment]
Thanks! @giuseppelettieri could you please merge that?

**Comment by john-gress** [comment]
The change in #518 has been working well.
