### ISSUE TITLE
How to modify netmap kernel function and include that in my program

### ISSUE THREAD

**Issue by obligingxx** [luigirizzo/netmap#514]
Hi 
I can use netmap example apps now , but I want to do like #256 issue to count drop packets numbers,
when I include some netmap head file or c file in my sample test code and link missed file compiler said ,after that also report errors.

My problem is how can I use kernel function like nm_rxsync_prologue() in netmap.c in my program ,
and how should I modify that can count drop packets numbers in which file's function.
( ixgbe_netmap_linux.h , netmap_linux.c , netmap.c , netmap_kern.h or another file )

The following is that I include ixgbe_netmap_linux.h in my program and link missed file compiler said.

My platform Nvidia TX2 with intel x540 NIC card.

> /usr/src/linux-headers-4.4.38-tegra/include/linux/stddef.h:10:2: error: expected identifier before ‘false’
  false = 0,
  ^
/usr/src/linux-headers-4.4.38-tegra/include/linux/stddef.h:10:2: error: expected ‘}’ before ‘false’
/usr/src/linux-headers-4.4.38-tegra/include/linux/stddef.h:10:2: error: expected unqualified-id before ‘false’
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:14:26: error: conflicting declaration ‘typedef struct __kernel_fd_set fd_set’
 typedef __kernel_fd_set  fd_set;
                          ^
In file included from /usr/include/aarch64-linux-gnu/sys/types.h:219:0,
                 from /usr/include/stdlib.h:314,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/select.h:75:5: note: previous declaration as ‘typedef struct fd_set fd_set’
   } fd_set;
     ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:15:25: error: conflicting declaration ‘typedef __kernel_dev_t dev_t’
 typedef __kernel_dev_t  dev_t;
                         ^
In file included from /usr/include/stdlib.h:314:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/types.h:60:17: note: previous declaration as ‘typedef __dev_t dev_t’
 typedef __dev_t dev_t;
                 ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:25:26: error: conflicting declaration ‘typedef __kernel_timer_t timer_t’
 typedef __kernel_timer_t timer_t;
                          ^
In file included from /usr/include/pthread.h:24:0,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr-default.h:35,
                 from /usr/include/aarch64-linux-gnu/c++/5/bits/gthr.h:148,
                 from /usr/include/c++/5/ext/atomicity.h:35,
                 from /usr/include/c++/5/bits/ios_base.h:39,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from test.cpp:4:
/usr/include/time.h:103:19: note: previous declaration as ‘typedef void* timer_t’
 typedef __timer_t timer_t;
                   ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:29:9: error: ‘_Bool’ does not name a type
 typedef _Bool   bool;
         ^
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:45:26: error: conflicting declaration ‘typedef __kernel_loff_t loff_t’
 typedef __kernel_loff_t  loff_t;
                          ^
In file included from /usr/include/stdlib.h:314:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/types.h:44:18: note: previous declaration as ‘typedef __loff_t loff_t’
 typedef __loff_t loff_t;
                  ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:111:17: error: conflicting declaration ‘typedef __u64 uint64_t’
 typedef  __u64  uint64_t;
                 ^
In file included from /usr/lib/gcc/aarch64-linux-gnu/5/include/stdint.h:9:0,
                 from /usr/local/include/net/netmap_user.h:90,
                 from test.cpp:16:
/usr/include/stdint.h:55:27: note: previous declaration as ‘typedef long unsigned int uint64_t’
 typedef unsigned long int uint64_t;
                           ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:112:17: error: conflicting declaration ‘typedef __u64 u_int64_t’
 typedef  __u64  u_int64_t;
                 ^
In file included from /usr/include/stdlib.h:314:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/types.h:203:1: note: previous declaration as ‘typedef long unsigned int u_int64_t’
 __u_intN_t (64, __DI__);
 ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:113:17: error: conflicting declaration ‘typedef __s64 int64_t’
 typedef  __s64  int64_t;
                 ^
In file included from /usr/include/stdlib.h:314:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/types.h:197:1: note: previous declaration as ‘typedef long int int64_t’
 __intN_t (64, __DI__);
 ^
In file included from /usr/include/aarch64-linux-gnu/asm/sigcontext.h:19:0,
                 from /usr/include/aarch64-linux-gnu/bits/sigcontext.h:27,
                 from /usr/include/signal.h:306,
                 from /usr/local/include/net/netmap_user.h:167,
                 from test.cpp:16:
/usr/src/linux-headers-4.4.38-tegra/include/linux/types.h:134:23: error: conflicting declaration ‘typedef long unsigned int blkcnt_t’
 typedef unsigned long blkcnt_t;
                       ^
In file included from /usr/include/stdlib.h:314:0,
                 from /usr/include/c++/5/cstdlib:72,
                 from /usr/include/c++/5/bits/stl_algo.h:59,
                 from /usr/include/c++/5/algorithm:62,
                 from test.cpp:10:
/usr/include/aarch64-linux-gnu/sys/types.h:235:20: note: previous declaration as ‘typedef __blkcnt_t blkcnt_t’
 typedef __blkcnt_t blkcnt_t;  /* Type to count number of disk blocks.  */
                    ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/stdio.h:27,
                 from test.cpp:2:
/usr/include/signal.h:375:1: error: expected declaration before ‘}’ token
 __END_DECLS

**Comment by vmaffione** [comment]
Kernel code cannot be included in your program in this way.
