### ISSUE TITLE
Intel ixgbe driver from Sourcesorge

### ISSUE THREAD

**Issue by GoogleCodeExporter** [luigirizzo/netmap#52]
```
Hello, folks!

I need your help. I'm using ixgbe drivers with netmap and everything work fine. 
But my NIC has bunch of options which I can't tune/control with upstream driver 
and I need driver from Intel's repo at Sourceforge.

I thoroughly read all your patches line by line and patch ixgbe 3.23.2.1 driver 
in same manner and put it to GitHub 
https://github.com/pavel-odintsov/ixgbe-linux-netmap (you could saw patches in 
commits).

But it dod not work correctly and my system fails everytime :( I checked 
multiple times and I really sure patch applied correctly. But something went 
wrong ;(

Could you review my patch and suggest any ideas what wrong with it? 
```

Original issue reported on code.google.com by `pavel.odintsov` on 25 Mar 2015 at 5:08

**Comment by pavel-odintsov** [comment]
It's very important.... Could anybody help with it?

**Comment by pavel-odintsov** [comment]
I implemented it! You could find code here: https://github.com/pavel-odintsov/ixgbe-linux-netmap

Will be fine if you add this drivers from Sourceforge into official repo. This approach could provide ability to compile on any platforms without depends on kernel source and difficult build process.

**Comment by pavel-odintsov** [comment]
Well, this driver is enough stable I backported few patches from netmap-next and it work with flying colors! :)

**Comment by vmaffione** [comment]
This is supported by the current code
