### ISSUE TITLE
link_elf_obj: symbol nm_bdg_polling undefined

### ISSUE THREAD

**Issue by kogdenko** [luigirizzo/netmap#525]
Hello!
I compiled netmap (575ec5aa36c82dd9ff694d24e473e3f3e3d85040) on x86_64 FreeBSD 11.1
And unable to load module:
```bash
# kldload ./netmap.ko
kldload: an error occurred while loading the module. Please check dmesg(8) for more details.
# dmesg
link_elf_obj: symbol nm_bdg_polling undefined
linker_load_file: Unsupported file type
```

**Comment by vmaffione** [comment]
Yes, because you need to add `netmap_bdg.c` and `netmap_kloop.c` to `sys/conf/files`, in the netmap section.

**Comment by vmaffione** [comment]
This has been fixed upstream.
