### ISSUE TITLE
Help: where can I find a demo that use multithread to read pkts from multi interface 

### ISSUE THREAD

**Issue by iProbe3x** [luigirizzo/netmap#526]
Hi, All

This is a help.
Who can tell me the method to read pkts from multi interfaces on one nic card with multi-thread? or tell me the code path in the netmap source.
And my problem is, with nm_open, per interface will read by only one thread, and one thread can only read a interface. but I want to read 4 interfaces on one card with 16 threads, how can I do?
Please give me help!
Thanks very much!

**Comment by vmaffione** [comment]
In the usual terminology, "NIC" and "interface" are the same thing. I assume you mean that you have a NIC with multiple queues (rings), and you want to receive/transmit from/to each queue with a different thread.
The `pkt-gen` program is able to do this when you use the `-p` option, e.g.:
````
# Use 4 threads to read from the first 4 rings of interface eth0
$ sudo pkt-gen -i eth0 -f rx -p 4
````

**Comment by iProbe3x** [comment]
Hi, vamffione

Thanks for you reply.
I mean, one NIC, could have 4 ethX(s)  on a PCB, for example, eth0 eth1 eth2 eth3, I call them 4 interfaces, and every ethX could has multiple queues(rings), default is ring0~ring15。
I want to use 16 threads to read all of 4 ethX from 4*16 rings, as I need to make sure that all of the packets in a session will process with one thread, but they may be come from different ethX.

the code of pktgen could not process the contidion.

**Comment by vmaffione** [comment]
You need to write a custom program.
I would suggest following the netmap tutorial available here https://github.com/netmap-unipi/netmap-tutorial to learn how to write netmap programs. There are examples with solutions, and you can probably reuse much of the code from the examples.
