### ISSUE TITLE
netmap module vs NIC builtin?

### ISSUE THREAD

**Issue by G8EjlKeK7CwVQP2acz2B** [luigirizzo/netmap#538]
I am looking into modifying an (out of mainline) LINUX driver for netmap and have run into the issue that this driver is not currently set up to be buildable as a module.

Can I just build the modified driver into the kernel while leaving netmap as a module?

Joe Buehler

**Comment by vmaffione** [comment]
No, you can't, because your driver needs to depend on netmap.
But your issue is certainly solvable.
What do you mean by "driver not buildable as a module", since it is out of tree?

**Comment by vmaffione** [comment]
I don't think you can build your driver module in-tree and netmap out of tree if the driver depends on netmap (but I may be wrong).
My advice would be to add your driver to the netmap repo, and build it together with the other drivers that netmap builds (e.g. igb, ixgbe, virtio-net, e1000, ...)

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
OK I have it building in the LINUX tree and it indeed does not like some missing netmap symbols in the modpost step.  Is it as simple as copying the driver source under the netmap tree somewhere?

**Comment by vmaffione** [comment]
Look at configure here https://github.com/luigirizzo/netmap/blob/master/LINUX/configure#L112-L136
and add your driver. (see for instance how ixgbe is handled).
Then you need to define some variables that say how to build your module:
xxx@fetch
xxx@src
etc..
(see https://github.com/luigirizzo/netmap/blob/master/LINUX/default-config.mak.in_#L2-L10)

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
I modeled my changes against forcedeth as an example.  It appears to be attempting to do the right thing, I just need to work out the driver Makefile issues.

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
I am running into an issue initializing "pdev" in my netmap attach function.  What is this supposed to be set to?

**Comment by vmaffione** [comment]
You need to set that to the `struct device *` corresponding to your network interface private struct.
Typically your driver specific adapter will have a "struct pci_dev *xxx" field, and what you need is `&xxx->dev`.
http://opengrok.net/source/xref/linux/include/linux/pci.h#360

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
sorry, that was a bit cryptic, I was talking about an internal data structure in the driver -- it seems to have been the correct choice

I don't have docs for the hardware and the mfr won't provide them even under NDA.  So what I am doing is leaving the NIC rings as-is during netmap config (suspending rx/tx during config).

For the RX ring I am setting nkr_hwofs to (ring size - next rx index).  What should it be set to for TX?

**Comment by vmaffione** [comment]
You are not supposed to touch that field.
