### ISSUE TITLE
nm_open error:  no such device or address when a device has `-` in the name 

### ISSUE THREAD

**Issue by iguberman** [luigirizzo/netmap#542]
I narrowed down the problem after attempting the bridge app: `bridge -i netmap:Te1-0` I had a really weird error about invalid interface `Te1-0^`   (trying to put the entire thing in quotes `"Te1-0"` or `'Te1-0'` rendered the same error).  Seemed like it doesn't like the `-` in the name so I renamed the interface to `te1` and voila! -- both my app below and the bridge app are now working!    Anyway, the issue still remains, though it is much narrower now, whew! 

The same code base I'm running (very simple, slightly modified version of https://github.com/netmap-unipi/netmap-tutorial/blob/master/solutions/sink.c)  works perfectly fine on my VirtualBox VM's interface ( `e1000` driver) but not a linux host interface ( `ixgbe` driver )   identical and successful installation of netmap on both (with patched drivers).      

However I can't get past `nm_open` on linux due to ioctl error (apparently happening at `sys/net/netmap_user.h:884`):

```
$sudo timeout 10 ./a.out -i netmap:Te1-0 -p 5678
Port    : netmap:Te1-0
TCP port: 5678
122.902560 nm_open [945] NIOCREGIF failed: No such device or address netmap:Te1-0
Failed to nm_open(netmap:Te1-0): No such device or address
```

`Te1-0` is a perfectly valid device (not sure about `netmap:Te1-0` but like I said `netmap:enp0s3` works on my VM no problem and plain `Te1-0` is `not a netmap device`, so I believe that's the one and only correct way to name it).   Some info provided below just in case. 

```  
$uname -a
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

$ls -lt /dev/netmap
crw------- 1 root root 10, 58 Sep 10 22:24 /dev/netmap

$lsmod | grep ixgbe
ixgbe                 315392  0
netmap                163840  1 ixgbe
dca                    16384  1 ixgbe
ptp                    20480  1 ixgbe


$ls /sys/devices/pci0000:00/0000:00:09.0/0000:05:00.0/net/Te1-0
addr_assign_type  addr_len   carrier          device  dev_port  duplex  gro_flush_timeout  ifindex  link_mode  name_assign_type  operstate     phys_port_name  power       queues  statistics  tx_queue_len  uevent
address           broadcast  carrier_changes  dev_id  dormant   flags   ifalias            iflink   mtu        netdev_group      phys_port_id  phys_switch_id  proto_down  speed   subsystem   type

$cat /sys/devices/pci0000:00/0000:00:09.0/0000:05:00.0/net/Te1-0/address
00:1b:21:cc:20:45

$sudo lspci -v 
...
05:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
	Subsystem: Intel Corporation Ethernet Server Adapter X520-1
	Flags: bus master, fast devsel, latency 0, IRQ 34
	Memory at d0000000 (64-bit, non-prefetchable) [size=512K]
	I/O ports at ece0 [size=32]
	Memory at d0100000 (64-bit, non-prefetchable) [size=16K]
	Expansion ROM at d0080000 [disabled] [size=512K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
	Capabilities: [70] MSI-X: Enable+ Count=64 Masked-
	Capabilities: [a0] Express Endpoint, MSI 00
	Capabilities: [e0] Vital Product Data
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 00-1b-21-ff-ff-bb-19-40
	Capabilities: [150] Alternative Routing-ID Interpretation (ARI)
	Capabilities: [160] Single Root I/O Virtualization (SR-IOV)
	Kernel driver in use: ixgbe
	Kernel modules: ixgbe  



$ip addr show
...
Te1-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:cc:20:45 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.10/24 brd 192.168.10.255 scope global Te1-0
       valid_lft forever preferred_lft forever
    inet6 ...
```

**Comment by vmaffione** [comment]
Hi,
  Yes, unfortunately `nm_open()` does not support a "-" in the name.
This happens because `nm_open()` parses the name passed as first argument, and the "-N" syntax means "only open ring(s) number N".

I would suggest changing the interface name if possible.
In alternative, you need to avoid `nm_open()` and use the native API directly (see `USING THE NATIVE API` section in the netmap man page).

**Comment by iguberman** [comment]
Thank you very much for the feedback @vmaffione!    Changing the interface name works for me. :)
