### ISSUE TITLE
LINUX alloc_pages needs __GFP_WAIT ?

### ISSUE THREAD

**Issue by G8EjlKeK7CwVQP2acz2B** [luigirizzo/netmap#546]
We have an embedded LINUX device with 512 MB of RAM.  When we attach to netmap after a lot of the RAM is used for buffer/cache, the netmap attach fails.  Adding __GFP_WAIT to the alloc_pages() call in bsd_glue.h fixes the issue.

I leave it to the experts as to whether this is wise.

**Comment by vmaffione** [comment]
I thing `__GFP_WAIT` has been replaced with `__GFP_RECLAIM` in later versions.
Can you check if your problem is fixed when using `GFP_KERNEL`?

**Comment by G8EjlKeK7CwVQP2acz2B** [comment]
I switched to GFP_KERNEL and the issue is still fixed so we will use that.
