### ISSUE TITLE
pps rate confusion

### ISSUE THREAD

**Issue by mutluit** [luigirizzo/netmap#548]
LINE RATE
    pkt_size \	100M	1G	10G	40G
	  64	.1488	1.488	14.88	59.52

I unfortunately don't understand what the values in this table represent.
Does it mean that with a 1G line and pkt_size=64 bytes, the pakets-per-second is just 1.488 ?  :-)

**Comment by muratbalaban43** [comment]
It's millions of packets at 64 bytes packet size. So:
100 Mbps -> 148.000
1 Gbps -> 1.488.000
10 Gbps -> 14.880.000
40 Gbps -> 59.520.000
