### ISSUE TITLE
pkt-gen generates broken IP and UDP checksumms

### ISSUE THREAD

**Issue by pavel-odintsov** [luigirizzo/netmap#55]
Hello!

I trying to build custom packet generator on top on pkt-gen.c and found bugs.

I run pkt-gen.c in following way:

``` bash
./pkt-gen -f tx -i netmap:eth6 -s 128.0.0.1:1025-223.255.255.254:65535 -d 10.10.10.150:80 -l 60 -p 1
```

Is can you see we change src IP and port for UDP packets.

Secondly, for clear test I disabled all offload features on receiver side:

``` bash
ethtool -K eth1 tx off rx off gro off tso off gso off
```

And then I run tshark with UDP checksum validation:

``` bash
tshark -n  -i eth1 -c 10 -V -o udp.check_checksum:TRUE
```

The first packet arrived correctly:

``` bash
Source: 128.0.0.1 (128.0.0.1)
Destination: 10.10.10.150 (10.10.10.150)
User Datagram Protocol, Src Port: 1025 (1025), Dst Port: 80 (80)
Header checksum: 0xa60e [correct]
UDP Checksum: 0x9a34 [correct]
```

But second packet become broken for UDP header (because port changed):

``` bash
Source: 128.0.0.1 (128.0.0.1)
Destination: 10.10.10.150 (10.10.10.150)
User Datagram Protocol, Src Port: 1026 (1026), Dst Port: 80 (80)
Header checksum: 0xa60e [correct]
Checksum: 0x9a34 [incorrect, should be 0x9a33 (maybe caused by "UDP checksum offload"?)]
```

Well, IP cheksum is OK because src/dst IP is not changed. Wait few minutes.

``` bash
    Source: 128.0.14.199 (128.0.14.199)
    Destination: 10.10.10.150 (10.10.10.150)
User Datagram Protocol, Src Port: 45773 (45773), Dst Port: 80 (80)
Header checksum: 0xa60e [incorrect, should be 0x9748 (may be caused by "IP checksum offload"?)]
Checksum: 0x9a34 [incorrect, should be 0xdca1 (maybe caused by "UDP checksum offload"?)]
```

Finally, we can see troubles in IP and UDP cheksum generation.

**Comment by pavel-odintsov** [comment]
Cheksum error detected even by Linux kernel:
```bash
[166596.086623] UDP: bad checksum. From 128.0.0.1:1026 to 10.20.20.100:80 ulen 26
[166596.086633] UDP: bad checksum. From 128.0.0.1:1027 to 10.20.20.100:80 ulen 26
[166596.086641] UDP: bad checksum. From 128.0.0.1:1028 to 10.20.20.100:80 ulen 26
[166596.086649] UDP: bad checksum. From 128.0.0.1:1029 to 10.20.20.100:80 ulen 26
[166596.086657] UDP: bad checksum. From 128.0.0.1:1030 to 10.20.20.100:80 ulen 26
[166596.086664] UDP: bad checksum. From 128.0.0.1:1031 to 10.20.20.100:80 ulen 26
[166596.086686] UDP: bad checksum. From 128.0.0.1:1032 to 10.20.20.100:80 ulen 26
[166596.086702] UDP: bad checksum. From 128.0.0.1:1033 to 10.20.20.100:80 ulen 26
[166596.086709] UDP: bad checksum. From 128.0.0.1:1034 to 10.20.20.100:80 ulen 26
[166596.086716] UDP: bad checksum. From 128.0.0.1:1035 to 10.20.20.100:80 ulen 26
```

**Comment by victordetoni** [comment]
hello guys, I created a ugly and single patch that fix cksum problem. Follow below:

--- pkt-gen.c	2015-10-20 06:33:26.705236000 -0200
+++ pkt-gen2.c	2016-03-29 06:33:32.057760000 -0300
@@ -505,6 +505,71 @@
 	return sum;
 }
 
+uint16_t
+ipv4_hdr_cksum(struct ip *ip_h)
+{
+        uint16_t *v16_h;
+        uint32_t ip_cksum;
+
+        /*
+         * Compute the sum of successive 16-bit words of the IPv4 header,
+         * skipping the checksum field of the header.
+         */
+        v16_h = (uint16_t *) ip_h;
+        ip_cksum = v16_h[0] + v16_h[1] + v16_h[2] + v16_h[3] +
+                v16_h[4] + v16_h[6] + v16_h[7] + v16_h[8] + v16_h[9];
+
+        /* reduce 32 bit checksum to 16 bits and complement it */
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (~ip_cksum) & 0x0000FFFF;
+        return (ip_cksum == 0) ? 0xFFFF : (uint16_t) ip_cksum;
+}
+
+/* set tcp checksum: given IP header and UDP datagram */
+void compute_udp_checksum(struct ip *pIph, unsigned short *ipPayload) {
+        register unsigned long sum = 0;
+        struct udphdr *udphdr = (struct udphdr*)(ipPayload);
+        unsigned short udpLen = htons(udphdr->uh_ulen);
+        //printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~udp len=%d\n", udpLen);
+        //add the pseudo header
+        //printf("add pseudo header\n");
+        //the source ip
+        sum += (pIph->ip_src.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_src.s_addr)&0xFFFF;
+        //the dest ip
+        sum += (pIph->ip_dst.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_dst.s_addr)&0xFFFF;
+        //protocol and reserved: 17
+        sum += htons(IPPROTO_UDP);
+        //the length
+        sum += udphdr->uh_ulen;
+
+        //add the IP payload
+        //printf("add ip payload\n");
+        //initialize checksum to 0
+        udphdr->uh_sum = 0;
+        while (udpLen > 1) {
+                sum += * ipPayload++;
+                udpLen -= 2;
+        }
+    //if any bytes left, pad the bytes and add
+    if(udpLen > 0) {
+                //printf("+++++++++++++++padding: %d\n", udpLen);
+        sum += ((*ipPayload)&htons(0xFF00));
+    }
+        //Fold sum to 16 bits: add carrier to result
+        //printf("add carrier\n");
+        while (sum>>16) {
+                sum = (sum & 0xffff) + (sum >> 16);
+        }
+        //printf("one's complement\n");
+        sum = ~sum;
+        //set computation result
+        udphdr->uh_sum = ((unsigned short)sum == 0x0000)?0xFFFF:(unsigned short)sum;
+
+}
+
 static u_int16_t
 wrapsum(u_int32_t sum)
 {
@@ -565,36 +630,61 @@
 	uint16_t p;
 	struct ip *ip = &pkt->ip;
 	struct udphdr *udp = &pkt->udp;
+//	uint16_t paylen = g->pkt_size - sizeof(struct ether_header) - sizeof(struct ip);
 
     do {
+	 /*   ip->ip_src.s_addr = random();
+            ip->ip_dst.s_addr = inet_addr("192.168.10.80");
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	//printf("src=%d dst=%d sum=%d\n",ip->ip_src.s_addr,ip->ip_dst.s_addr,ip->ip_sum);
+	break;
+	    udp->uh_sport = random();
+	udp->uh_sport = htons(g->src_ip.port0); it works*/
+	
 	p = ntohs(udp->uh_sport);
-	if (p < g->src_ip.port1) { /* just inc, no wrap */
+	if (p < g->src_ip.port1) { // just inc, no wrap 
 		udp->uh_sport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	udp->uh_sport = htons(g->src_ip.port0);
+	compute_udp_checksum(ip, (unsigned short*)udp);
 
 	a = ntohl(ip->ip_src.s_addr);
-	if (a < g->src_ip.end) { /* just inc, no wrap */
+	if (a < g->src_ip.end) { // just inc, no wrap 
 		ip->ip_src.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_src.s_addr = htonl(g->src_ip.start);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	udp->uh_sport = htons(g->src_ip.port0);
 	p = ntohs(udp->uh_dport);
-	if (p < g->dst_ip.port1) { /* just inc, no wrap */
+	if (p < g->dst_ip.port1) { // just inc, no wrap 
 		udp->uh_dport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
-	udp->uh_dport = htons(g->dst_ip.port0);
+	udp->uh_dport = htons(g->dst_ip.port0);		
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	a = ntohl(ip->ip_dst.s_addr);
-	if (a < g->dst_ip.end) { /* just inc, no wrap */
+	if (a < g->dst_ip.end) { // just inc, no wrap 
 		ip->ip_dst.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_dst.s_addr = htonl(g->dst_ip.start);
+	
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+
     } while (0);
     // update checksum
 }
@@ -619,7 +709,7 @@
 	pcap_t *file;
 	struct pcap_pkthdr *header;
 	const unsigned char *packet;
-	
+
 	/* Read a packet from a PCAP file if asked. */
 	if (targ->g->packet_file != NULL) {
 		if ((file = pcap_open_offline(targ->g->packet_file,

**Comment by victordetoni** [comment]
> --- pkt-gen.c	2015-10-20 06:33:26.705236000 -0200
+++ pkt-gen2.c	2016-03-29 06:33:32.057760000 -0300
@@ -505,6 +505,71 @@
 	return sum;
 }
 
+uint16_t
+ipv4_hdr_cksum(struct ip *ip_h)
+{
+        uint16_t *v16_h;
+        uint32_t ip_cksum;
+
+        /*
+         * Compute the sum of successive 16-bit words of the IPv4 header,
+         * skipping the checksum field of the header.
+         */
+        v16_h = (uint16_t *) ip_h;
+        ip_cksum = v16_h[0] + v16_h[1] + v16_h[2] + v16_h[3] +
+                v16_h[4] + v16_h[6] + v16_h[7] + v16_h[8] + v16_h[9];
+
+        /* reduce 32 bit checksum to 16 bits and complement it */
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (~ip_cksum) & 0x0000FFFF;
+        return (ip_cksum == 0) ? 0xFFFF : (uint16_t) ip_cksum;
+}
+
+/* set tcp checksum: given IP header and UDP datagram */
+void compute_udp_checksum(struct ip *pIph, unsigned short *ipPayload) {
+        register unsigned long sum = 0;
+        struct udphdr *udphdr = (struct udphdr*)(ipPayload);
+        unsigned short udpLen = htons(udphdr->uh_ulen);
+        //printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~udp len=%d\n", udpLen);
+        //add the pseudo header
+        //printf("add pseudo header\n");
+        //the source ip
+        sum += (pIph->ip_src.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_src.s_addr)&0xFFFF;
+        //the dest ip
+        sum += (pIph->ip_dst.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_dst.s_addr)&0xFFFF;
+        //protocol and reserved: 17
+        sum += htons(IPPROTO_UDP);
+        //the length
+        sum += udphdr->uh_ulen;
+
+        //add the IP payload
+        //printf("add ip payload\n");
+        //initialize checksum to 0
+        udphdr->uh_sum = 0;
+        while (udpLen > 1) {
+                sum += * ipPayload++;
+                udpLen -= 2;
+        }
+    //if any bytes left, pad the bytes and add
+    if(udpLen > 0) {
+                //printf("+++++++++++++++padding: %d\n", udpLen);
+        sum += ((*ipPayload)&htons(0xFF00));
+    }
+        //Fold sum to 16 bits: add carrier to result
+        //printf("add carrier\n");
+        while (sum>>16) {
+                sum = (sum & 0xffff) + (sum >> 16);
+        }
+        //printf("one's complement\n");
+        sum = ~sum;
+        //set computation result
+        udphdr->uh_sum = ((unsigned short)sum == 0x0000)?0xFFFF:(unsigned short)sum;
+
+}
+
 static u_int16_t
 wrapsum(u_int32_t sum)
 {
@@ -565,36 +630,61 @@
 	uint16_t p;
 	struct ip *ip = &pkt->ip;
 	struct udphdr *udp = &pkt->udp;
+//	uint16_t paylen = g->pkt_size - sizeof(struct ether_header) - sizeof(struct ip);
 
     do {
+	 /*   ip->ip_src.s_addr = random();
+            ip->ip_dst.s_addr = inet_addr("192.168.10.80");
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	//printf("src=%d dst=%d sum=%d\n",ip->ip_src.s_addr,ip->ip_dst.s_addr,ip->ip_sum);
+	break;
+	    udp->uh_sport = random();
+	udp->uh_sport = htons(g->src_ip.port0); it works*/
+	
 	p = ntohs(udp->uh_sport);
-	if (p < g->src_ip.port1) { /* just inc, no wrap */
+	if (p < g->src_ip.port1) { // just inc, no wrap 
 		udp->uh_sport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	udp->uh_sport = htons(g->src_ip.port0);
+	compute_udp_checksum(ip, (unsigned short*)udp);
 
 	a = ntohl(ip->ip_src.s_addr);
-	if (a < g->src_ip.end) { /* just inc, no wrap */
+	if (a < g->src_ip.end) { // just inc, no wrap 
 		ip->ip_src.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_src.s_addr = htonl(g->src_ip.start);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	udp->uh_sport = htons(g->src_ip.port0);
 	p = ntohs(udp->uh_dport);
-	if (p < g->dst_ip.port1) { /* just inc, no wrap */
+	if (p < g->dst_ip.port1) { // just inc, no wrap 
 		udp->uh_dport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
-	udp->uh_dport = htons(g->dst_ip.port0);
+	udp->uh_dport = htons(g->dst_ip.port0);		
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	a = ntohl(ip->ip_dst.s_addr);
-	if (a < g->dst_ip.end) { /* just inc, no wrap */
+	if (a < g->dst_ip.end) { // just inc, no wrap 
 		ip->ip_dst.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_dst.s_addr = htonl(g->dst_ip.start);
+	
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+
     } while (0);
     // update checksum
 }
@@ -619,7 +709,7 @@
 	pcap_t *file;
 	struct pcap_pkthdr *header;
 	const unsigned char *packet;
-	
+
 	/* Read a packet from a PCAP file if asked. */
 	if (targ->g->packet_file != NULL) {
 		if ((file = pcap_open_offline(targ->g->packet_file,

**Comment by victordetoni** [comment]
--- pkt-gen.c	2015-10-20 06:33:26.705236000 -0200
+++ pkt-gen2.c	2016-03-29 06:33:32.057760000 -0300
@@ -505,6 +505,71 @@
 	return sum;
 }
 
 +uint16_t 
 +ipv4_hdr_cksum(struct ip *ip_h)
 +{
 +        uint16_t *v16_h;
+        uint32_t ip_cksum;
+
+        /*
+         * Compute the sum of successive 16-bit words of the IPv4 header,
+         * skipping the checksum field of the header.
+         */
+        v16_h = (uint16_t *) ip_h;
+        ip_cksum = v16_h[0] + v16_h[1] + v16_h[2] + v16_h[3] +
+                v16_h[4] + v16_h[6] + v16_h[7] + v16_h[8] + v16_h[9];
+
+        /* reduce 32 bit checksum to 16 bits and complement it */
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (ip_cksum & 0xffff) + (ip_cksum >> 16);
+        ip_cksum = (~ip_cksum) & 0x0000FFFF;
+        return (ip_cksum == 0) ? 0xFFFF : (uint16_t) ip_cksum;
+}
+
+/* set tcp checksum: given IP header and UDP datagram */
+void compute_udp_checksum(struct ip *pIph, unsigned short *ipPayload) {
+        register unsigned long sum = 0;
+        struct udphdr *udphdr = (struct udphdr*)(ipPayload);
+        unsigned short udpLen = htons(udphdr->uh_ulen);
+        //printf("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~udp len=%d\n", udpLen);
+        //add the pseudo header
+        //printf("add pseudo header\n");
+        //the source ip
+        sum += (pIph->ip_src.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_src.s_addr)&0xFFFF;
+        //the dest ip
+        sum += (pIph->ip_dst.s_addr>>16)&0xFFFF;
+        sum += (pIph->ip_dst.s_addr)&0xFFFF;
+        //protocol and reserved: 17
+        sum += htons(IPPROTO_UDP);
+        //the length
+        sum += udphdr->uh_ulen;
+
+        //add the IP payload
+        //printf("add ip payload\n");
+        //initialize checksum to 0
+        udphdr->uh_sum = 0;
+        while (udpLen > 1) {
+                sum += * ipPayload++;
+                udpLen -= 2;
+        }
+    //if any bytes left, pad the bytes and add
+    if(udpLen > 0) {
+                //printf("+++++++++++++++padding: %d\n", udpLen);
+        sum += ((*ipPayload)&htons(0xFF00));
+    }
+        //Fold sum to 16 bits: add carrier to result
+        //printf("add carrier\n");
+        while (sum>>16) {
+                sum = (sum & 0xffff) + (sum >> 16);
+        }
+        //printf("one's complement\n");
+        sum = ~sum;
+        //set computation result
+        udphdr->uh_sum = ((unsigned short)sum == 0x0000)?0xFFFF:(unsigned short)sum;
+
+}
+
 static u_int16_t
 wrapsum(u_int32_t sum)
 {
@@ -565,36 +630,61 @@
 	uint16_t p;
 	struct ip *ip = &pkt->ip;
 	struct udphdr *udp = &pkt->udp;
+//	uint16_t paylen = g->pkt_size - sizeof(struct ether_header) - sizeof(struct ip);
 
     do {
+	 /*   ip->ip_src.s_addr = random();
+            ip->ip_dst.s_addr = inet_addr("192.168.10.80");
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	//printf("src=%d dst=%d sum=%d\n",ip->ip_src.s_addr,ip->ip_dst.s_addr,ip->ip_sum);
+	break;
+	    udp->uh_sport = random();
+	udp->uh_sport = htons(g->src_ip.port0); it works*/
+	
 	p = ntohs(udp->uh_sport);
-	if (p < g->src_ip.port1) { /* just inc, no wrap */
+	if (p < g->src_ip.port1) { // just inc, no wrap 
 		udp->uh_sport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	udp->uh_sport = htons(g->src_ip.port0);
+	compute_udp_checksum(ip, (unsigned short*)udp);
 
 	a = ntohl(ip->ip_src.s_addr);
-	if (a < g->src_ip.end) { /* just inc, no wrap */
+	if (a < g->src_ip.end) { // just inc, no wrap 
 		ip->ip_src.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_src.s_addr = htonl(g->src_ip.start);
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	udp->uh_sport = htons(g->src_ip.port0);
 	p = ntohs(udp->uh_dport);
-	if (p < g->dst_ip.port1) { /* just inc, no wrap */
+	if (p < g->dst_ip.port1) { // just inc, no wrap 
 		udp->uh_dport = htons(p + 1);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
-	udp->uh_dport = htons(g->dst_ip.port0);
+	udp->uh_dport = htons(g->dst_ip.port0);		
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
 
 	a = ntohl(ip->ip_dst.s_addr);
-	if (a < g->dst_ip.end) { /* just inc, no wrap */
+	if (a < g->dst_ip.end) { // just inc, no wrap 
 		ip->ip_dst.s_addr = htonl(a + 1);
+		ip->ip_sum = ipv4_hdr_cksum(ip);
+		compute_udp_checksum(ip, (unsigned short*)udp);
 		break;
 	}
 	ip->ip_dst.s_addr = htonl(g->dst_ip.start);
+	
+	compute_udp_checksum(ip, (unsigned short*)udp);
+	ip->ip_sum = ipv4_hdr_cksum(ip);
+
     } while (0);
     // update checksum
 }
@@ -619,7 +709,7 @@
 	pcap_t *file;
 	struct pcap_pkthdr *header;
 	const unsigned char *packet;
-	
+
 	/* Read a packet from a PCAP file if asked. */
 	if (targ->g->packet_file != NULL) {
 		if ((file = pcap_open_offline(targ->g->packet_file,

**Comment by victordetoni** [comment]
hello guys, I update pkt-gen in my branch to ugly fix, but you can use more than 1 ip address or udp port :)
here: [https://github.com/victordetoni/netmap/blob/master/examples/pkt-gen2.c]

**Comment by vmaffione** [comment]
Hi, can you issue a pull request?

2016-03-29 3:15 GMT+02:00 Victor <notifications@github.com>:

> hello guys, I update pkt-gen in my branch to ugly fix, but you can use
> more than 1 ip address or udp port :)
> here: [
> https://github.com/victordetoni/netmap/blob/master/examples/pkt-gen2.c]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/55#issuecomment-202653341>
>



-- 
Vincenzo Maffione

**Comment by victordetoni** [comment]
Hi, I just do it. So, I couldn't use original cksum functions, maybe this
pull request can be improved.

https://github.com/luigirizzo/netmap/pull/159

On Tue, Mar 29, 2016 at 6:03 AM, Vincenzo Maffione <notifications@github.com
