### ISSUE TITLE
Extra Buffers Question

### ISSUE THREAD

**Issue by sdpetrides** [luigirizzo/netmap#550]
I am interested in allocating extra buffers to create a pool of buffers that an application can use to avoid RX buffer-overwrite. I am requesting the buffers with `nr_arg3` and this has worked well. However, on `close` I am getting an the following error if I have swapped 256 or more buffers.

```
[28058.515201] 011.672952 [1161] netmap_extra_free         breaking with head 1079902209
```

This may or may not be an issue with my code. Still, there is a piece of documentation that I am not sure how to interpret. It is at line [114](https://github.com/luigirizzo/netmap/blob/master/sys/net/netmap.h#L114) of netmap.h or pasted below.

```
 *   The buffers are linked to each other using the first uint32_t
 *   as the index. On close, ni_bufs_head must point to the list of
 *   buffers to be released.
```

Can explain what is meant by this statement? Specifically, how are the buffers `linked` together and is the `ni_bufs_head` field meant to changed and set to something specific before `close`?

**Comment by vmaffione** [comment]
Yes, it's basically a simple linked list. The `ni_bufs_head` is the index (`buf_idx`) of the first buffer in the list.
The first buffer contains the index of the next buffer in the first 4 bytes, and so on.
If you allocated 256 extra buffers on `nm_open`, you need to release 256 extra buffers on `nm_close`, typically reconstructing a list in `ni_bufs_head`. The extra buffers you relase do not need to be the same ones, only the number counts.

Examples:
 - fetch extra bufs after `nm_open`: https://github.com/luigirizzo/netmap/blob/master/utils/functional.c#L1091
 - release extra bufs before `nm_close`: https://github.com/luigirizzo/netmap/blob/master/utils/functional.c#L1179

Also the `lb` application uses the extra buffers, so you can look at that (looking for `ni_bufs_head`) to see how they are used.

**Comment by sdpetrides** [comment]
I think I understand it now. I assumed that `ni_bufs_head` was the lowest index in the pool of extra buffers but this is incorrect. It is the head of the linked list and the index of the next buffer is held in the first four bytes of the buffer.

I will use the following snippet to get the bounds on the extra buffers.
```
int i;
uint32_t idx, *buf;
for (i = 0, idx = ifp->ni_bufs_head; i < (req.nr_arg3 - 1); i++) {
    buf = (uint32_t *)NETMAP_BUF(channel->rxring, idx);
    if (idx != (*buf + 1))
        LOG("extra buffers are not contiguous");
    idx = *buf;
}
LOG("first buffer idx %u", idx);
LOG("last buffer idx  %u", ifp->ni_bufs_head);
```

Thank you for the explanation.

**Comment by vmaffione** [comment]
I think it should be `i< req.nr_arg3`.
Extra buffers are not guaranteed to be contiguous, nor sorted in any way by idx.

Programs using extra buffer usually fetch them and put them into a private list for later use. You can see this in the examples.
