### ISSUE TITLE
eth0 drop mbuf that needs checksum offload 

### ISSUE THREAD

**Issue by posetr** [luigirizzo/netmap#553]
VMware : E1000 ethernet driver.

pkt-gen -i ens32 -f tx -l 64

not response server.

[ 3389.888461] 404.622906 [3642] netmap_transmit           eth0 drop mbuf that needs checksum offload
[ 3391.770455] 406.504901 [3642] netmap_transmit           eth0 drop mbuf that needs checksum offload
[ 3395.538445] 410.272891 [3642] netmap_transmit           eth0 drop mbuf that needs checksum offload
[ 3829.460278] e1000: ens32 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None

**Comment by vmaffione** [comment]
Please read this https://github.com/luigirizzo/netmap/blob/master/LINUX/README#L243-L255

**Comment by vmaffione** [comment]
That's not an error, and in any case you can remove the "lro off" bit
