### ISSUE TITLE
NAF_FORCE_RECLAIM can cause no ring buffers to be available 

### ISSUE THREAD

**Issue by joshraiff-sophos** [luigirizzo/netmap#561]
When doing a force reclaim, the code blindly moves nr_hwtail.

To reproduce:
insmod ./netmap.ko
insmod ./ixgbe/ixgbe.ko
ethtool -K Port9 tx off gro off gso off tso off sg off rxvlan off txvlan off
vale-ctl -h vale0:Port9
ifconfig Port9 up
vale-ctl -n host1
vale-ctl -a vale0:host1 -m 1
sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1
ip link set dev Port9 up
ip addr add 1.1.1.1/16 dev Port9
ping 1.1.1.2 -c 1
PING 1.1.1.2 (1.1.1.2) 56(84) bytes of data.
64 bytes from 1.1.1.2: icmp_seq=1 ttl=64 time=2027 ms

--- 1.1.1.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2027.677/2027.677/2027.677/0.000 ms
ip link set dev Port9 down #### Setting the link down triggers the issue.
ip link set dev Port9 up
ping 1.1.1.2 -c 1
PING 1.1.1.2 (1.1.1.2) 56(84) bytes of data.
From 1.1.1.1 icmp_seq=1 Destination Host Unreachable

--- 1.1.1.2 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

**Comment by joshraiff-sophos** [comment]
See #558

**Comment by giuseppelettieri** [comment]
please try with the current master. There was a missing re-initialization of the in memory NIC pointers after an up/down cycle.

**Comment by joshraiff-sophos** [comment]
This works.

Thanks!
