### ISSUE TITLE
netmap cannot find kernel sources on centos 7

### ISSUE THREAD

**Issue by grantcurell** [luigirizzo/netmap#563]
On a default install of CentOS 7 netmap's configuration script cannot find kernel sources.

```
*** Cannot find full kernel sources.
***
*** Please note that most distributions provide separate packages for kernel
*** headers and sources. Once you know the path to kernel sources, you can
*** rerun this script with the additional
```

![image](https://user-images.githubusercontent.com/35169230/48626989-fe80c780-e978-11e8-9107-fd53d0d749ef.png)

However this still yields:

![image](https://user-images.githubusercontent.com/35169230/48627022-1a846900-e979-11e8-813c-667e6d475f85.png)

Double check kernel sources are where they are supposed to be:

![image](https://user-images.githubusercontent.com/35169230/48627112-58818d00-e979-11e8-8e12-d7997b18b903.png)

Try manually specifying kernel source location:

![image](https://user-images.githubusercontent.com/35169230/48627172-7fd85a00-e979-11e8-93cf-6188bd998f1f.png)

**Comment by grantcurell** [comment]
Followed the instructions for CentOS to install full kernel sources here: https://wiki.centos.org/HowTos/I_need_the_Kernel_Source still no dice. Figuring out how the check in configure works. It looks like it still doesn't see the source code.

**Comment by vmaffione** [comment]
You don't need to compile the kernel. You just need the kernel sources and prepare them to compile modules:
````
$ cd /path/to/kernel/sources
$ sudo make modules_prepare
````

**Comment by grantcurell** [comment]
> You don't need to compile the kernel. You just need the kernel sources and prepare them to compile modules:
> 
> ```
> $ cd /path/to/kernel/sources
> $ sudo make modules_prepare
> ```

No but I do need the kernel source which is all the c files right? I'm still reading about all this, but if I understand correctly from https://wiki.centos.org/HowTos/I_need_the_Kernel_Source the full kernel source is provided by the source RPM kernel-3.10.0-862.14.4.el7.src.rpm. In order to install the full kernel source I have to build that rpm with RPM build and then I install the RPM and then I'll have the full kernel source which will allow me to do what you are describing correct?

The source I got from the kernel-devel didn't have any .c files which would be the actual source code for the kernel. Did I get all that right?

**Comment by vmaffione** [comment]
I'm not a Cents user, but I'm pretty sure the "kernel-devel" package contains the kernel headers, that are needed to compile external modules (e.g. netmap and modified drivers).
And the source RPM is probably the one which contains the sources (.c files).
But you don't need to compile the .c sources (e.g. build the kernel). Netmap needs the .c sources to patch some drivers and compile them as external modules.

**Comment by grantcurell** [comment]
> I'm not a Centos user, but I'm pretty sure the "kernel-devel" package contains the kernel headers, that are needed to compile external modules (e.g. netmap and modified drivers).
> And the source RPM is probably the one which contains the sources (.c files).
> But you don't need to compile the .c sources (e.g. build the kernel). Netmap needs the .c sources to patch some drivers and compile them as external modules.

Hmmmm that's what I did in my original post, but even when I do a `./configure --kernel-sources=/usr/src/kernels/3.10.0-862.14.4.el7.x86_64/` netmap reports that it can't find the kernel sources.

**Comment by grantcurell** [comment]
What OS do you guys typically run? We're a Red Hat shop is the only reason I went with Fedora/CentOS

**Comment by giuseppelettieri** [comment]
Hi @grantcurell, we mostly use Ubuntu and Arch, but we occasionally test on CentOS.

Please note that if you are only going to use the Intel drivers for ixgbe, i40e, igb and e1000e, or the virtio-net driver, you don't need the kernel sources and you can ignore the warning.

**Comment by grantcurell** [comment]
Got it working on Fedora. I haven't gone back and tried it on CentOS though. I wasn't able to get it working just using kernel-devel even if I pointed netmap at it with the kernel-sources option. I'm good to go if you want to close the ticket. Not sure if you want me to leave it open since I wasn't able to get it running on CentOS.

**Comment by vmaffione** [comment]
You can leave it open, sooner or later I will give a try with CentOS 7 in a virtual machine.

**Comment by grantcurell** [comment]
> You can leave it open, sooner or later I will give a try with CentOS 7 in a virtual machine.

Let me know what sort of user-related failure I engaged in ;-p

**Comment by vmaffione** [comment]
The `/usr/src/kernels/3.10.0-862.14.4.el7.x86_64/` directory contains the kernel build environment, but not the kernel sources.
To install the kernel sources you need to follow this rather complex procedure:
https://wiki.centos.org/HowTos/I_need_the_Kernel_Source

Once you do that, you can configure netmap in this way:
````
./configure --kernel-sources=/home/vmaffione/rpmbuild/BUILD/kernel-3.10.0-862.14.4.el7/linux-3.10.0-862.14.4.el7.x86_64 --kernel-dir=/usr/src/kernels/3.10.0-862.14.4.el7.x86_64/
````

**Comment by grantcurell** [comment]
Well, I'm glad my approach was right. I'll have to give it another shot at some point. I must have messed something up along the way. I compiled the SRPM and installed it, but I remember not getting it to work after that. I'll have to figure out why.
