### ISSUE TITLE
No more extra buffers on pipe?

### ISSUE THREAD

**Issue by larseggert** [luigirizzo/netmap#567]
I used to be able to request extra buffers when opening a pipe by setting `nr_arg3`. That seems to no longer work? `nr_arg3` is returned as zero after the ioctl.

**Comment by larseggert** [comment]
FWIW, the call still returns extra buffers when opening a regular interface.

**Comment by vmaffione** [comment]
It looks like Giuseppe just fixed this? I add a couple of unit tests to cover this, and it looks like they pass.
https://travis-ci.org/netmap-unipi/netmap/jobs/460214552#L1102-L1129

**Comment by larseggert** [comment]
Let me check. When my vagrant box built earlier, it cloned 7672a356851bd019080d23b99f4ab32fa13d1a01, which had the issue. Now there seem to be newer commits.

**Comment by larseggert** [comment]
Yep, it seems fixed

**Comment by vmaffione** [comment]
Btw, the failure was only affecting pipes on VALE ports, so I added another unit test for this specific case.
