### ISSUE TITLE
i40e driver stops passing packets after link down/link up

### ISSUE THREAD

**Issue by joshraiff-sophos** [luigirizzo/netmap#568]
Very similiar to #561.

insmod ./netmap.ko
insmod ./i40e/i40e.ko
ethtool -K PortA1 tx off gro off gso off tso off sg off rxvlan off txvlan off
ifconfig PortA1 up
vale-ctl -h vale0:PortA1
vale-ctl -n host1
vale-ctl -a vale0:host1 -m 1
sysctl -w net.ipv4.ip_forward=1
net.ipv4.ip_forward = 1
ip addr add 1.1.1.1/16 dev PortA1
ping 1.1.1.2 -c 1
PING 1.1.1.2 (1.1.1.2) 56(84) bytes of data.
64 bytes from 1.1.1.2: icmp_seq=1 ttl=64 time=0.308 ms

--- 1.1.1.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.308/0.308/0.308/0.000 ms
ip link set dev PortA1 down    # Bringing the link down then up triggers the issue.
ip link set dev PortA1 up
ping 1.1.1.2 -c 1
PING 1.1.1.2 (1.1.1.2) 56(84) bytes of data.
From 1.1.1.1 icmp_seq=1 Destination Host Unreachable

--- 1.1.1.2 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

**Comment by giuseppelettieri** [comment]
Different bug, similar effect. Please try the new master.

**Comment by joshraiff-sophos** [comment]
This works.  Thanks!
