### ISSUE TITLE
Size of the rings in the pipe

### ISSUE THREAD

**Issue by linoferrentino** [luigirizzo/netmap#572]
Hi,

I am on Linux, Centos 6, I am using netmap version

commit 7672a356851bd019080d23b99f4ab32fa13d1a01
Author: Vincenzo Maffione <v.maffione@gmail.com>
Date:   Thu Nov 22 12:57:08 2018 +0100

compiled with "no drivers".

I am trying to use netmap in this configuration:

eth0 is using the emulated driver and all is OK.

Then I want also to open two pipes on eth0 using this string "netmap:eth0{0" and "netmap:eth0}0"

The open is successfull

[---------netmap:0732] PIPE SLAVE
505.830632 nm_open [928] netmap:eth0}0 tx 0 .. 0 1 rx 0 .. 0 1
505.830667 nm_open [931] TX0 0x7f77b588c000 h 0 c 0 t 511
505.830794 nm_open [931] TX1 0x7f77b57ff000 h 0 c 1 t 1
505.830806 nm_open [935] RX0 0x7f77b5883000 h 0 c 0 t 0
505.830816 nm_open [935] RX1 0x7f77b57ff000 h 0 c 1 t 1

And also the master part is OK.

However I have a mismatch in the TX ring and RX ring. TX ring is composed
of 512 slots and RX ring is composed of 256 slots, apparently.

So on the sending part I see that I can send at most 255 slots and then the program
will crash, even if I have other free slots.

In the receiving side something is stranger because I see that something is received
BEYOND the tail for the receiving buffer but I can't go there as nm_ring_next will return
to 0.

Using "netmap:test{0" and "netmap:test}0" as names is OK, I get 1024 slots for each of
the TX and RX rings.

Am I doing something wrong? I would like to open the pipes in the "eth0" namespace
to have zerocopy between the pipe rings and the net rings.

Thanks.

**Comment by giuseppelettieri** [comment]
Both pipe ends always have the same number of slots, even if the application asks for something different. Terrible things will happen if this is not true. Can you share the snippet of code that you are using to open the pipes?

**Comment by linoferrentino** [comment]
Hi, thanks for the answer... I have made a small main that exhibits this behavior..

===================================
int main(int argc, char** argv)
{
  struct nm_desc *pa = NULL;
  struct nm_desc *pnm_pipe = NULL;

  int pipe_slave = 0;
  int use_pipe_not_eth = 0;
  int ch;

  while ((ch = getopt(argc, argv, "zp")) != -1) {
    switch(ch){
      case 'p':
        use_pipe_not_eth = 1;
        break;
      case 'z':
        pipe_slave = 1;
        break;
     default:
        printf("no recognized option");
        break;
    }
  }
  const char *ifname;
  //open all rings: hw+sw
  ifname = "netmap:eth0*";


  if (!pipe_slave){

    printf("open the interface in netmap mode %s\n", ifname);
    pa = nm_open(ifname, NULL, 0, NULL);
    printf("open pipe master\n", ifname, errno);
    if (use_pipe_not_eth){
      ifname = "netmap:test{0";
    } else {
      ifname = "netmap:eth0{0";
    }
    printf("trying to open pipe %s\n", ifname);
    pnm_pipe = nm_open(ifname, NULL, NM_OPEN_NO_MMAP, pa);

  } else {

    printf("open pipe slave\n", ifname, errno);
    if (use_pipe_not_eth){
      ifname = "netmap:test}0";
    } else {
      ifname = "netmap:eth0}0";
    }
    printf("trying to open slave %s\n", ifname);
    pnm_pipe = nm_open(ifname, NULL, 0, NULL);
  }


  struct netmap_ring *rx_pipe = NETMAP_RXRING(pnm_pipe->nifp, pnm_pipe->first_rx_ring);
  struct netmap_ring *tx_pipe = NETMAP_TXRING(pnm_pipe->nifp, pnm_pipe->first_tx_ring);

  printf("Pipe rx ring has %d slots\n", rx_pipe->num_slots);
  printf("Pipe tx ring has %d slots\n", tx_pipe->num_slots);

  nm_close(pnm_pipe);
  nm_close(pa);

}
========================

Running this without parameters I get


open the interface in netmap mode netmap:eth0*
200.505915 nm_open [928] netmap:eth0* tx 0 .. 4 4 rx 0 .. 4 4
200.505990 nm_open [931] TX0 0x7f00b7eb0000 h 0 c 0 t 511
200.505999 nm_open [931] TX1 0x7f00b7eb9000 h 0 c 0 t 511
200.506006 nm_open [931] TX2 0x7f00b7ec2000 h 0 c 0 t 511
200.506083 nm_open [931] TX3 0x7f00b7ecb000 h 0 c 0 t 511
200.506091 nm_open [931] TX4 0x7f00b7ed4000 h 0 c 0 t 511
200.506097 nm_open [935] RX0 0x7f00b7e83000 h 0 c 0 t 0
200.506101 nm_open [935] RX1 0x7f00b7e8c000 h 0 c 0 t 0
200.506119 nm_open [935] RX2 0x7f00b7e95000 h 0 c 0 t 0
200.506128 nm_open [935] RX3 0x7f00b7e9e000 h 0 c 0 t 0
200.506134 nm_open [935] RX4 0x7f00b7ea7000 h 0 c 0 t 0
open pipe master
trying to open pipe netmap:eth0{0
200.506245 nm_mmap [986] do not mmap, inherit from parent
200.506262 nm_open [928] netmap:eth0{0 tx 0 .. 0 1 rx 0 .. 0 1
200.506299 nm_open [931] TX0 0x7f00b7ee6000 h 0 c 0 t 511
200.506324 nm_open [931] TX1 0x7f00b7e6a400 h 0 c 1 t 1
200.506329 nm_open [935] RX0 0x7f00b7edd000 h 0 c 0 t 0
200.506333 nm_open [935] RX1 0x7f00b7e6a400 h 0 c 1 t 1
Pipe rx ring has 256 slots
Pipe tx ring has 512 slots


With the -p parameter (not using eth0) I get:

netmap exec argc 3 last arg -p
netmap exec argc 2 last arg -p
open the interface in netmap mode netmap:eth0*
307.187865 nm_open [928] netmap:eth0* tx 0 .. 4 4 rx 0 .. 4 4
307.187941 nm_open [931] TX0 0x7f7b53de0000 h 0 c 0 t 511
307.187949 nm_open [931] TX1 0x7f7b53de9000 h 0 c 0 t 511
307.187956 nm_open [931] TX2 0x7f7b53df2000 h 0 c 0 t 511
307.187963 nm_open [931] TX3 0x7f7b53dfb000 h 0 c 0 t 511
307.187972 nm_open [931] TX4 0x7f7b53e04000 h 0 c 0 t 511
307.187982 nm_open [935] RX0 0x7f7b53db3000 h 0 c 0 t 0
307.187986 nm_open [935] RX1 0x7f7b53dbc000 h 0 c 0 t 0
307.187993 nm_open [935] RX2 0x7f7b53dc5000 h 0 c 0 t 0
307.187999 nm_open [935] RX3 0x7f7b53dce000 h 0 c 0 t 0
307.188006 nm_open [935] RX4 0x7f7b53dd7000 h 0 c 0 t 0
open pipe master
trying to open pipe netmap:test{0
307.198569 nm_open [928] netmap:test{0 tx 0 .. 0 1 rx 0 .. 0 1
307.198604 nm_open [931] TX0 0x7f7b5153a000 h 0 c 0 t 1023
307.198612 nm_open [931] TX1 0x7f7b51532000 h 1 c 1 t 1
307.198617 nm_open [935] RX0 0x7f7b51535000 h 0 c 0 t 0
307.198621 nm_open [935] RX1 0x7f7b51532000 h 1 c 1 t 1
Pipe rx ring has 1024 slots
Pipe tx ring has 1024 slots


In this case the rx and tx rings are of the same size.


this is my system

xxxxxx@lino1_nov18_01:~/work/xxxxxxxx$ uname --all
Linux lino1_nov18_01 4.14.78 #1 SMP Mon Oct 22 12:03:06 CDT 2018 x86_64 x86_64 x86_64 GNU/Linux


and this is /var/log/messages in the case where we have the sizes different:

Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315204 [1152] generic_netmap_attach     Emulated adapter for eth0 created (prev was           (null))
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315213 [1870] netmap_interp_ringid      eth0: tx [0,5) rx [0,5) id 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315409 [ 331] generic_netmap_register   Emulated adapter for eth0 activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315416 [ 376] generic_netmap_register   Emulated adapter: ring 'eth0 RX0' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315418 [ 376] generic_netmap_register   Emulated adapter: ring 'eth0 RX1' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315419 [ 376] generic_netmap_register   Emulated adapter: ring 'eth0 RX2' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315421 [ 376] generic_netmap_register   Emulated adapter: ring 'eth0 RX3' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315422 [ 376] generic_netmap_register   Emulated adapter: ring 'eth0 RX4' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315423 [ 383] generic_netmap_register   Emulated adapter: ring 'eth0 TX0' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315425 [ 383] generic_netmap_register   Emulated adapter: ring 'eth0 TX1' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315426 [ 383] generic_netmap_register   Emulated adapter: ring 'eth0 TX2' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315427 [ 383] generic_netmap_register   Emulated adapter: ring 'eth0 TX3' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315428 [ 383] generic_netmap_register   Emulated adapter: ring 'eth0 TX4' activated
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315525 [ 834] tc_configure              ifp eth0 qdisc mq parent 4294967295 handle 3014656
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315609 [ 834] tc_configure              ifp eth0 qdisc netmapemu parent 3014657 handle 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315670 [ 834] tc_configure              ifp eth0 qdisc netmapemu parent 3014658 handle 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315731 [ 834] tc_configure              ifp eth0 qdisc netmapemu parent 3014659 handle 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.315777 [ 834] tc_configure              ifp eth0 qdisc netmapemu parent 3014660 handle 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316011 [ 726] netmap_get_pipe_na        pipe 0 not found, create 1
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316015 [ 769] netmap_get_pipe_na        Lino: req rx 0 req tx 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316018 [ 816] netmap_get_pipe_na        created master ffff8801e0cde200 and slave ffff8801f8418c00
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316021 [ 820] netmap_get_pipe_na        pipe 0 master at ffff8801e0cde200
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316024 [1870] netmap_interp_ringid      eth0{0: tx [0,1) rx [0,1) id 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316027 [ 346] netmap_pipe_krings_create ffff8801e0cde200: case 1, create both ends
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316069 [ 423] netmap_pipe_reg           ffff8801e0cde200: onoff 1
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316077 [ 509] netmap_pipe_reg           ffff8801e0cde200: case 1.a or 2.a, nothing to do
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316129 [ 423] netmap_pipe_reg           ffff8801e0cde200: onoff 0
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316131 [ 509] netmap_pipe_reg           ffff8801e0cde200: case 1.a or 2.a, nothing to do
Dec  5 10:14:01 lino1_nov18_01 kernel: 441.316133 [ 559] netmap_pipe_krings_delete ffff8801e0cde200: case 1, deleting everything


I have added a debug log "Lino" at netmap_pipe.c, I don't know if it is useful, I was
looking at the part where in the code the number of slot is fixed.

        error = netmap_attach_common(&mna->up);
        D("Lino: req rx %d req tx %d", req->nr_rx_slots, req->nr_tx_slots);

**Comment by giuseppelettieri** [comment]
OK, pipes take their number of slots from the parent adapter, by default. I think that your eth0 has a different number of slots for rx and tx. You can check it with ```ethtool -g eth0```. This is not a problem in itself, but there was a bug in the pipe initialization code that caused the two pipe ends to have their number of slots messed up. Can you try with the latest master? You should still see the 215 sand 512 slots, but the pipes should now work correctly.

**Comment by giuseppelettieri** [comment]
Yes, probably I have not explained well what I meant. The fact that you see two different sizes is expected, since the pipes take those numbers from the parent interface. My patch does not change this, but it should fix the other problems that you where seeing, like tail moving past the end the ring.

**Comment by linoferrentino** [comment]
Ah, OK.

It's clear now.

I am closing this. Thanks for the support.
