### ISSUE TITLE
fail to build netmap (ixgbe) on latest CentOS Linux release 7.6.1810 (Core) 

### ISSUE THREAD

**Issue by hmbdc-dev** [luigirizzo/netmap#578]
Hi,

Has anyone successfully built netmap(ixgbe) on CentOs7.6 (latest)?
Thanks a lot!

======
I am building netmap for a new installed CentOs7 and here is what I got:
[sli@r610 LINUX]$ uname -a
Linux r610 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[sli@r610 LINUX]$ ./configure --kernel-sources=/tmp/linux-3.10.0-957.1.3.el7 --kernel-dir=/usr/src/kernels/3.10.0-957.1.3.el7.x86_64/ --drivers=ixgbe
**********************************  NOTE   **********************************
*** We are trying to download the original sources for driver
*** ixgbe using the following command:
***   
***   test -e /home/sli/Downloads/netmap-master/LINUX/ext-drivers/ixgbe-5.3.8.tar.gz || wget https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.3.8/ixgbe-5.3.8.tar.gz -P /home/sli/Downloads/netmap-master/LINUX/ext-drivers/
*** 
*** If this fails, please download the above file and put it
*** in /home/dev/Downloads/netmap-master/LINUX/ext-drivers/, then run configure again.
*****************************************************************************
**********************************  NOTE   **********************************
*** Now running compile tests to adapt the code to your
*** kernel version. Please wait.
*****************************************************************************
********************************** WARNING **********************************
*** There were problems building the external driver ixgbe.
*** 
*** Please note that this is not related to the netmap patches,
*** that were not applied.
*** 
*** Disabling ixgbe.
*****************************************************************************
kernel directory            /usr/src/kernels/3.10.0-957.1.3.el7.x86_64
kernel sources              /tmp/linux-3.10.0-957.1.3.el7
linux version               30a00  [3.10]
module file                 netmap.ko

subsystems                  null ptnetmap generic monitor pipe vale
apps                        dedup vale-ctl nmreplay tlem lb bridge pkt-gen
native drivers              

Contents of the drivers.mak file:
ixgbe@conf := CONFIG_IXGBE
ixgbe@src := tar xf /home/sli/Downloads/netmap-master/LINUX/ext-drivers/ixgbe-5.3.8.tar.gz && ln -s ixgbe-5.3.8/src ixgbe
ixgbe@patch := patches/intel--ixgbe--5.3.8

**Comment by giuseppelettieri** [comment]
You can try with a more recent ixgbe driver for which there is a patch in ```LINUX/final-patches```. Currently we have a patch for 5.5.1 and 5.5.2 (both untested). Configure as follows:
```
./configure --select-version=ixgbe:5.5.2
```

**Comment by hmbdc-dev** [comment]
Thanks, that solved the building problem, both netmap.ko and ixgbe.ko are built, but now I got this:
[sli@r610 netmap-master]$ sudo insmod /home/sli/Downloads/netmap-master/netmap.ko
insmod: ERROR: could not insert module /home/sli/Downloads/netmap-master/netmap.ko: Unknown symbol in module

**Comment by hmbdc-dev** [comment]
Thanks a lot!
After a reboot, things are loaded fine now and here is the pkt-gen output. Btw, do you think 2.4Mpps is a reasonable output for 10G link?

sender:   sudo ./build-apps/pkt-gen/pkt-gen -i p2p1 -f tx
receiver: sudo /tmp/pkt-gen -i ens4 -f rx
278.536623 main_thread [2639] 2.453 Mpps (2.456 Mpkts 1.179 Gbps in 1001006 usec) 11.66 avg_batch 0 min_space
279.537663 main_thread [2639] 2.435 Mpps (2.438 Mpkts 1.170 Gbps in 1001040 usec) 11.43 avg_batch 224 min_space
280.538691 main_thread [2639] 2.457 Mpps (2.460 Mpkts 1.181 Gbps in 1001028 usec) 11.66 avg_batch 233 min_space
281.539718 main_thread [2639] 2.448 Mpps (2.451 Mpkts 1.176 Gbps in 1001027 usec) 11.55 avg_batch 230 min_space
282.540749 main_thread [2639] 2.436 Mpps (2.439 Mpkts 1.171 Gbps in 1001031 usec) 11.42 avg_batch 239 min_space
283.541775 main_thread [2639] 2.458 Mpps (2.461 Mpkts 1.181 Gbps in 1001026 usec) 11.65 avg_batch 238 min_space

=====================
Here is the configure options I used:
./configure --kernel-sources=/home/sli/rpmbuild/BUILD/kernel-3.10.0-957.1.3.el7/^Cnux-3.10.0-957.1.3.el7.x86_64/ --kernel-dir=/usr/src/kernels/3.10.0-957.1.3.el7.x86_64/ --drivers=ixgbe --select-version=ixgbe:5.5.2

**Comment by vmaffione** [comment]
A 10G link should get ~14 Mpps.
If you get 2.4 Mpps it can be that you have ethernet flow control enabled (`ethtool -A eth0 rx off rx off`), or that you are using the emulated netmap adapter rather than native netmap support.
Check `lsmod | grep netmap` to make sure the loaded ixgbe module depends on the netmap module (or check `dmesg | grep "Emulated adapter"`).

**Comment by hmbdc-dev** [comment]
Spot on!
The recv host didn't load the netmap version of ixgbe driver and that caused the performance woo.
The recv host has older HW and older kernel 3.10.0-327.el7.x86_64 and the send host has better HW  and 3.10.0-957.el7.x86_64 kernel. I got 9.4Mpps with pkt-gen. When reverse the sender and receiver, I got 12.5Mpps.

**Comment by vmaffione** [comment]
Yes, those numbers look reasonable. Can we close this issue?

**Comment by hmbdc-dev** [comment]
sure.

**Comment by oPiZiL** [comment]
` Unrecognized option: --select-version=ixgbe:4.6.1`
