### ISSUE TITLE
Compilation failure in Ubuntu 18.04

### ISSUE THREAD

**Issue by haha150** [luigirizzo/netmap#589]
I am trying to compile netmap for Ubuntu 18.04 LTS, and it is failing everytime because of one line of code in the file "mlx5_netmap_linux.h".

So i run: 
sudo ./configure
sudo make <--- here it fails with the mlx5_netmap_linux.h code

so the line that is failing is:
nm_printf("mlx5e switching %s native netmap mode", onoff ? "into" : "out of");
and if i uncomment this line, the compilation goes through. Why is this line failing?

**Comment by vmaffione** [comment]
That's a typo, thanks for spotting it.
Now it should be fixed.
