### ISSUE TITLE
Use the latest master code to find that rxring under vale is always empty

### ISSUE THREAD

**Issue by xiaojin2630** [luigirizzo/netmap#591]
I created a vale0, which contains multiple interfaces. Today I found that my program m is running, but I can't display the traffic of each interface, all of them are 0; I remember that the traffic can be displayed normally in the first few days.
I checked my m program source carefully, and I didn't find any important code changes through git log -p m.c; I was confused!

In the morning, I suddenly thought that I updated the netmap.git code several times (via git pull); through my troubleshooting, I found that using the latest master code, compiling my m program, m does not work properly;
Using the older netmap.git code, compile my m program, m work is normal.

My m program has more code, it is not very convenient to put it all in the github comment, so I prepared an additional 1.c program code that can reproduce the above problem;

Use the latest master code (commit dc36365a5690)
````
> i686-linux-gcc 1.c -I ../tmp/netmap-off.git/sys -o a.out.master && scp a.out.master root@172.18.16.138:/data

> /data/a.out.master
n: rxring is empty.
 n: rxring is empty.
 n: rxring is empty.
 n: rxring is empty.
 n: rxring is empty.
 n: rxring is empty.
 n^C
````
You can see that rxring is always empty;

 Use older code ( commit 5a02914ecd)
````
> /data/a.out.5a02914ecd
 n: cnt = 20240, nmd->last_rx_ring = 0
 n: cnt = 20241, nmd->last_rx_ring = 0
 n: cnt = 20242, nmd->last_rx_ring = 0
 n: cnt = 20243, nmd->last_rx_ring = 0
 n: cnt = 20244, nmd->last_rx_ring = 0
 n: cnt = 20245, nmd->last_rx_ring = 0
 n: cnt = 20246, nmd->last_rx_ring = 0
^C
As you can see, the code can go to 'cnt++' here.
````

**Comment by xiaojin2630** [comment]
#define _GNU_SOURCE /* for CPU_SET() */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <poll.h>

#define NETMAP_WITH_LIBS
#define __KERNEL__
#include <net/netmap_user.h>

int n()
{
    const char *name = __FUNCTION__;
    struct nmreq   nmreq;
    struct nm_desc *nmd;
    char *ifname = "netmap:eth7/t";
    struct pollfd pfd;
    pfd.events = POLLIN;

    struct netmap_if *nifp;
    struct netmap_ring *rxring;

    bzero(&nmreq, sizeof(struct nmreq));
    if((nmd = nm_open(ifname, &nmreq, 0, NULL)) == NULL)
    {
        printf("# %s: Unable to open %s: %s\n", name, ifname, strerror(errno));
        exit(-1);
    }

    nifp = nmd->nifp;
    pfd.fd = nmd->fd;
    int i;

    int cnt = 0;

    while(1)
    {
        poll(&pfd, 1, 1 * 1000);

        for (i = nmd->first_rx_ring; i <= nmd->last_rx_ring; i++)
        {
            rxring = NETMAP_RXRING(nifp, i);
            if (nm_ring_empty(rxring))
            {
                printf("%s: rxring is empty.\n", name);
                continue;
            }

            printf("%s: cnt = %d, nmd->last_rx_ring = %d\n",name, cnt, nmd->last_rx_ring);
            cnt ++;
        }
    }
}


int main()
{
        n();
}

**Comment by vmaffione** [comment]
I think you need to recompile netmap with the current master on the machine that runs the netmap program.

**Comment by xiaojin2630** [comment]
Thank you for your reply, I will try it.

**Comment by xiaojin2630** [comment]
it's works  normal.
