### ISSUE TITLE
obtain multiple interfaces tx, rx traffic, too many interfaces with nm_open

### ISSUE THREAD

**Issue by xiaojin2630** [luigirizzo/netmap#592]
I have a Linux, there are 4 interfaces eth4, eth5, eth6, eth7; 4 switches are connected respectively;
And 4 ports have been assigned to vale0; working normally, the traffic can be forwarded normally;
I now have a need to monitor the traffic in the tx and rx directions of the four interfaces; the final result is to display the information needed below.

eth4 TX: a(pps) b(bps); RX: c(pps) d(bps);
eth5 TX: e(pps) f(bps); RX: g(pps) h(bps);
eth6 TX: i(pps) j(bps); RX: k(pps) l(bps);
eth7 TX: m(pps) n(bps); RX: o(pps) p(bps);

I opened 8 interfaces through nm_open and created 8 pthreads to achieve this requirement. The code is as follows:

#

char *intfs[4] = {"eth4", "eth5", "eth6", "eth7"};

for(i = 0; i < 4; i ++)

    for(n = 0 ; n < 2; n ++)

    {

	if(n == 0)
	   direct = 't'

	if(n == 1)
	   direct = 'r'

	sprintf(ifname, "netmap:%s/%c", intfs[i], direct);
	nm_open(ifname, NULL, 0, NULL);
	...
	pthread_create(&id, ...);
	...
     }
}

But I think this implementation is not good enough: I don't want to open 8 interfaces and create 8 pthreads; Is there any other better way?

**Comment by vmaffione** [comment]
You don't need multiple threads, but you need to open all the interfaces that you want to monitor.
You can
````
d1=nm_open("netmap:eth4/tr", ...);
d2=nm_open("netmap:eth5/tr", ...);
d3=nm_open("netmap:eth6/tr", ...);
d4=nm_open("netmap:eth7/tr", ...);
````
and then have the main thread `poll()` on `d1->fd`, `d2->fd`, `d3->fd` and `d4->fd`.

**Comment by vmaffione** [comment]
If you want to distinguish between tx and rx traffic you actually need 8 separate `nm_open()`.

**Comment by xiaojin2630** [comment]
I see, thanks
