### ISSUE TITLE
netmap Device or resource busy

### ISSUE THREAD

**Issue by shuaidonga** [luigirizzo/netmap#597]
I have successfully built e1000e with the netmap-patch.
Then execute pkt-gen -i ens32 -f rx  error
nm_open [950] NIOCREGIF failed: Device or resource busy netmap:ens32
663.215803 main [3113] Unable to open netmap:ens32: Device or resource busy
![image](https://user-images.githubusercontent.com/16378509/53873299-0608d100-403b-11e9-846f-8430053012de.png)

**Comment by vmaffione** [comment]
Have you checked with `lsmod | grep netmap` that the `e1000e` module currently loaded actually depends on the `netmap` module?
Maybe your interface is attached to a sw bridge (e.g., check `brctl show`) or to a VALE swtich (check 'vale-ctl')
What does `dmesg` say related to netmap?

**Comment by shuaidonga** [comment]
@vmaffione 
i execute lsmod,
![image](https://user-images.githubusercontent.com/16378509/53935872-eaf19c00-40e2-11e9-825e-d55390a66b4b.png)
dmesg in the shell.Have the following display.
[   22.306523] Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dummy instead.
[   22.323385] Loading kernel module for a network device with CAP_SYS_MODULE (deprecated).  Use CAP_NET_ADMIN and alias netdev-dummy instead.
[   23.512735] device ens32 entered promiscuous mode
[   26.346508] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.346639] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.346752] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.347304] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.566608] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.566733] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.566865] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[   26.567422] [PF_RING] User is not capable, please run as root or setcap cap_net_raw
[ 2098.253961] e1000e 0000:03:00.0 ens32: removed PHC
[ 2098.324223] e1000e: ens32 NIC Link is Down
[ 2144.047601] 585.663117 [4238] netmap_init               run mknod /dev/netmap c 10 57 # returned 0
[ 2144.047631] 585.663149 [4254] netmap_init               netmap: loaded module
[ 2207.992192] e1000e: Intel(R) PRO/1000 Network Driver - 3.4.0.2
[ 2207.992195] e1000e: Copyright(c) 1999 - 2017 Intel Corporation.
[ 2207.993099] e1000e 0000:03:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
[ 2207.993194] e1000e 0000:03:00.0: irq 56 for MSI/MSI-X
[ 2207.993235] e1000e 0000:03:00.0: irq 57 for MSI/MSI-X
[ 2207.993289] e1000e 0000:03:00.0: irq 58 for MSI/MSI-X
[ 2208.042692] e1000e 0000:03:00.0 (unregistered net_device) (uninitialized): registered PHC clock
[ 2208.097425] e1000e 0000:03:00.0 eth0: (PCI Express:2.5GT/s:Width x1) 00:50:56:b2:00:f6
[ 2208.097429] e1000e 0000:03:00.0 eth0: Intel(R) PRO/1000 Network Connection
[ 2208.097475] e1000e 0000:03:00.0 eth0: MAC: 3, PHY: 8, PBA No: 000000-000
[ 2208.113787] [PF_RING] removing dev=ens32 ifindex=4 (2)
[ 2208.120870] IPv6: ADDRCONF(NETDEV_UP): ens32: link is not ready
[ 2208.205335] IPv6: ADDRCONF(NETDEV_UP): ens32: link is not ready
[ 2208.208344] e1000e: ens32 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: None
[ 2208.209430] IPv6: ADDRCONF(NETDEV_CHANGE): ens32: link becomes ready
[ 2276.011811] 717.627317 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 6122.258267] 563.873503 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 6833.709361] 275.324546 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 6840.027892] 281.643077 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 6856.839945] 298.455129 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 7218.293498] 659.908656 [1075] generic_netmap_attach     Error: netmap adapter hook is busy
[ 7221.599910] 663.215069 [1075] generic_netmap_attach     Error: netmap adapter hook is busy

**Comment by vmaffione** [comment]
This means you are not using the patched netmap driver. You are using the "emulated" netmap mode (aka generic). To use the native driver, you must `rmmod e1000e` and `insmod e1000e/e1000e.ko` from the netmap repo (once netmap is built).

In addition to that, the emulated netmap mode failed to attach to the interface probably because it is being used by `PF_RING`, as you can see from the kernel log. You need to disable `PF_RING` and any other software that may own the interface (e.g. a linux bridge).
