### ISSUE TITLE
How to use: support multiple host-rings

### ISSUE THREAD

**Issue by chalfling** [luigirizzo/netmap#599]
Hello!

Today I'm using only one pair of host-rings like:
`snprintf(nm_open_name, sizeof (nm_open_name), "netmap:%s^", nmreq.nr_name);`
`nmd = nm_open(nm_open_name, NULL, 0, NULL);`
`hrxring = NETMAP_RXRING(nmd->nifp, num);`
`htxring = NETMAP_TXRING(nmd->nifp, num);`

I have some questions about this change.

1st question: Do I need to change ioctl? I'm thinking like this:
`nmreq.nr_version = NETMAP_API;`
`nmreq.nr_host_tx_rings = num;`
`nmreq.nr_host_rx_rings = num;`
`ioctl(fd, NIOCGINFO, &nmreq);`

2nd question: Do k begin from 0? comment reference: netmap:foo^k	(the k-th host rings pair)

3rd question: How can I open each pair? I'm thinking like this:
`for (i=0;i<num;i++)`
`{`
`snprintf(nm_open_name, sizeof (nm_open_name), "netmap:%s^%d", nmreq.nr_name, i);`
`nmd[i] = nm_open(nm_open_name, NULL, 0, NULL);`
`hrxring[i] = NETMAP_RXRING(nmd[i]->nifp, num);`
`htxring[i] = NETMAP_TXRING(nmd[i]->nifp, num);`
`}`

4th question: Can I have just 1 host_rx_ring and more than 1 host_tx_ring? If yes, how can I open?

Thank you!

**Comment by vmaffione** [comment]
Hi,
  You need to use the new control API to access multi-host-ring functionality. `nm_open` uses the legacy control API. You can look at the `utils/ctrl-api-test.c::port_register()` function to see how to register a port using the new control API. The `struct nmreq_register` has `nr_host_tx_rings` and `nr_host_rx_rings` fields. Alternatively you can use the new `libnetmap/libnetmap.h`, but we still need to publish examples.

If a NIC has N hw TX rings and M host TX rings, then `NETMAP_TXRING(nifp, i)` will get the `i-th` hw TX ring if `i < N`, and the `(i-N)-th` host ring if `N <= i  < N+M`.
Same thing for RX rings.
Yes, you should be able to get a single host RX rings and multiple host TX rings by specifying different numbers for `nr_host_tx_rings` and `nr_host_rx_rings`.

**Comment by chalfling** [comment]
Oh I see.

Let me know if I'm understanding, for "num" TX HOST RINGs and "one" RX HOST RING:
`for (i=0;i<num;i++)`
`{`
`ctx_tx[i]->nr_mode   = NR_REG_ONE_SW;`
`ctx_tx[i]->nr_host_tx_rings = 1;`
`ctx_tx[i]->nr_host_rx_rings = 0;`
`ctx_tx[i]->nr_ringid = i;`
`port_register(ctx_tx[i]);`
`}`
`ctx_rx->nr_mode   = NR_REG_ONE_SW;`
`ctx_rx->nr_host_tx_rings = 0;`
`ctx_rx->nr_host_rx_rings = 1;`
`ctx_rx->nr_ringid = 0;`
`port_register(ctx_rx);`

To access rings:
`for (i=0;i<num;i++)`
`{`
`htxring[i] = NETMAP_TXRING(ctx_tx[i]->fd->nifp, num+i);`
`}`
`hrxring = NETMAP_RXRING(ctx_rx->fd->nifp, num);`

Also considering that "num" is the number os hw rings.

Thank you again!

**Comment by vmaffione** [comment]
> Oh I see.
> 
> @vmaffione Let me know if I'm understanding, for "num" TX HOST RINGs and "one" RX HOST RING:
> `for (i=0;i<num;i++)`
> `{`
> `ctx_tx[i]->nr_mode = NR_REG_ONE_SW;`
> `ctx_tx[i]->nr_host_tx_rings = 1;`
> `ctx_tx[i]->nr_host_rx_rings = 0;`
> `ctx_tx[i]->nr_ringid = i;`
> `port_register(ctx_tx[i]);`
> `}`
> `ctx_rx->nr_mode = NR_REG_ONE_SW;`
> `ctx_rx->nr_host_tx_rings = 0;`
> `ctx_rx->nr_host_rx_rings = 1;`
> `ctx_rx->nr_ringid = 0;`
> `port_register(ctx_rx);`
> 
No. When you register a port, there are two things happening: you first "create if not exists", and then you "bind" the rings that you want.
This means that the port_register() (and even the following ones) should specify the total number of host tx rings
and host rx rings that you want. The first port_register() will see that the netmap port does not exists yet, and it will create that with all the
host rings you need.
The following port_register() will find that everything has been already created, and will just bind to specific rings (specified with `nr_mode` and `nr_ringid`).

> To access rings:
> `for (i=0;i<num;i++)`
> `{`
> `htxring[i] = NETMAP_TXRING(ctx_tx[i]->fd->nifp, num+i);`
> `}`
> `hrxring = NETMAP_RXRING(ctx_rx->fd->nifp, num);`
> 
> Also considering that "num" is the number of hw rings.

Yes.

> 
> > Alternatively you can use the new `libnetmap/libnetmap.h`, but we still need to publish examples.
> 
> About that, will I open like this?
> 
> `for (i=0;i<num;i++)`
> `{`
> `snprintf(nm_open_name, sizeof (nm_open_name), "netmap:%s^%d", nmreq.nr_name, i);`
> `nmportd[i] = nmport_open(nm_open_name);`
> `htxring[i] = NETMAP_TXRING(nmportd[i]->ctx->fd->nifp, num+i);`
> `}`
> `hrxring[i] = NETMAP_RXRING(nmportdrx->ctx->fd->nifp, num);`
> 
> With this I can't control nr_host_(R|T)x_rings, right?
> 

This won't work because  you are asking netmap to open "netmap:eth0^2", but the third host ring is available only for the TX direction, and not for the RX direction.
You need to open each ring separately:
````
netmap:eth0^0/T
netmap:eth0^1/T
...
netmap:eth0^${N-1}/T
nemap:eth0^0/R
````

> Thank you again!

**Comment by chalfling** [comment]
> No. When you register a port, there are two things happening: you first "create if not exists", and then you "bind" the rings that you want.
This means that the first port_register() (and even the following ones) should specify the total number of host tx rings and host rx rings that you want. The first port_register() will see that the netmap port does not exists yet, and it will create that with all the host rings you need.
The following port_register() will find that everything has been already created, and will just bind to specific rings (specified with nr_mode and nr_ringid).

How can I do port_register() to "bind" each ring to a different ctx->fd to poll(IN|OUT) in Multithreading, like one thread to one rxring or one thread to a {N}-rxrings from a pool of num-rxrings?

> This won't work because you are asking netmap to open "netmap:eth0^2", but the third host ring is available only for the TX direction, and not for the RX direction.
You need to open each ring separately:

How about this?
```
for (i=0;i<num;i++) {
  snprintf(nm_open_name, sizeof (nm_open_name), "netmap:%s^%d/T", nmreq.nr_name, i);
  nmportd[i] = nmport_open(nm_open_name);
  htxring[i] = NETMAP_TXRING(nmportd[i]->ctx->fd->nifp, num+i);
}
snprintf(nm_open_name, sizeof (nm_open_name), "netmap:%s^%d/R", nmreq.nr_name, 0);
nmportdrx = nmport_open(nm_open_name);
hrxring = NETMAP_RXRING(nmportdrx->ctx->fd->nifp, num);
 ```

**Comment by vmaffione** [comment]
Each port register operation (e.g. `nmport_open`) will get a separate fd, that you can poll independently from a separate thread.
Your code snipped looks correct, although you should replace `nmportd->ctx->fd` with `nmportd->fd`.
You can also find the index of the ring that you bind in `nmportd->first_tx_ring` or `nmportd->first_rx_ring`. I'd suggest to carefully read `libnetmap/libnetmap.h'.

**Comment by chalfling** [comment]
Thank you very much @vmaffione =)
