### ISSUE TITLE
couldn't send out packet by host stack with netmap single rx queue enabled

### ISSUE THREAD

**Issue by lkkey80** [luigirizzo/netmap#605]
I try to send packet with host stack and receive packet reply with netmap single rx queue. So I wrote a test program, it first  nm_open a single rx queue then try to send out packet by host stack, 
 it failed. I even couldn't pcap the packet sended out. 
But if I open another process  to send packet with host stack, it succeeds, weird.

**Comment by vmaffione** [comment]
The rule is the following: when the kernel stack sends a packet to transmit queue `k` of interface `ethX`, the packet is intercepted by netmap if and only if `ethX` is in netmap mode, and transmit ring `k` is open in netmap mode (by any application).

**Comment by lkkey80** [comment]
figured out the reason, it seems netmap need long time such as ~5 seconds to fully work. If I wait some seconds after nm_open then I can send out packets with host stack.

**Comment by vmaffione** [comment]
Yes, that's because link goes down and up. Our applications usually have a `-w` option to let the application wait for some seconds after `nm_open` and before starting to access the rings.
