### ISSUE TITLE
Pin VALE to a specific core

### ISSUE THREAD

**Issue by ztz1989** [luigirizzo/netmap#606]
Dear Vincenzo, I want to pin VALE switch to an isolated core and test its performance. I have tried taskset, but it didn't seem work to me. Could you give me some hints about this? Thanks

**Comment by vmaffione** [comment]
Hi, Vale is not implemented as a dedicated thread like openvswitch or vpp. Vale performs its forwarding work in the context of each sending thread. You can pin the sending threads if you wish.

**Comment by ztz1989** [comment]
Yeah, this was what I expected. Thanks again for your reply.
