### ISSUE TITLE
How to do app-internal queuing for traffic-shaping

### ISSUE THREAD

**Issue by ramaza** [luigirizzo/netmap#607]
Hi, I want to experiment with traffic-shaping algorithms (token-bucket, leaky-bucket, dual-bucket, ...) in combination with Netmap. A prerequirement for this experiments is to have app-internal packet queues.

There was a piece of information somewhere that Netmap can provide extra rings for this use-case but I can no longer find the source of this information. My other approach would be to learn from the `tlem` app but it looks like it's implementing the internal packet queuing from scratch.

Any hints which document or code-example could be most helpful for learning how to do internal queuing and what the differences are between "unbound queues", "extra rings", "extra buffer" in relation to Netmap?

**Comment by giuseppelettieri** [comment]
Yes, ```tlem``` creates an internal queue from scratch. You can take a look at ```lb```, instead. It allocates extra buffers when passed the ```-B``` option.

**Comment by vmaffione** [comment]
Extra buffers are chained together when you grab them from netmap or when you return them to netmap.
But you can use whatever queues you want. If you use multi threading, you may be interested to these optimized single producer single consumer queues:
https://github.com/vmaffione/spscq

"Extra rings" do not exist annymore. Where did you read about that?

**Comment by ramaza** [comment]
I might have read on the FreeBSD mailing about "extra rings". This could have been outdated information. Good to know that they don't exist anymore.

I will have a look at "spscq". Thanks for the hint.
