### ISSUE TITLE
packet loss

### ISSUE THREAD

**Issue by seven9417** [luigirizzo/netmap#612]
hi, i am using an Intel 10Gbe card and  recv very high bitrate UDP streams 8Gb/s with a packet size of 8200 bytes.i have increase the buf_size 8500,the ring_size 131072,the ring_num 1024()。the cpu usage is not more than 70%,but still loss pkt occasionally，the time interval is not fixed。maybe several minutes。and everytime it loss hundreds of pkt。thanks

**Comment by seven9417** [comment]
now i have solve the problem。i change the cpu mode to performance(cpupower frequency-set  -g performance)，and increase the eth card ring-num(ethtool -G eth0 tx 2048 rx2048).

**Comment by luxl** [comment]
Hi, can you tell me how to set buf_size, ring_size, and ring_num?  I haven't figure out how to do these?

**Comment by seven9417** [comment]
#523。sudo echo 4096 | sudo tee /sys/module/netmap/parameters/ring_num
