### ISSUE TITLE
VLANs with netmap generic

### ISSUE THREAD

**Issue by calvadoscal** [luigirizzo/netmap#617]
Looking through past issues, it is known that VLAN tags are not visible to netmap in generic mode. Instead if we open VLAN itself using generic driver, the packet path works. Multiple VLANs are also supported.

However parent interface cannot be used in conjunction with VLAN interfaces simultaneously. Is this known limitation or issue?

**Comment by vmaffione** [comment]
Yes, it's expected. In general, it is not a good idea to use netmap on VLAN interfaces, since one shoud always use netmap on the parent interface (and in native mode).

**Comment by calvadoscal** [comment]
Thanks for responding. It will be helpful though to use one driver. Just to understand the limitation - are there any issues with signaling the user space program on parent interface?

**Comment by vmaffione** [comment]
In which scenario? E.g. creating VLAN interfaces or not? Opening the VLAN interface and/or the parent interface in netmap mode?

**Comment by calvadoscal** [comment]
The issue is in receiving packets on VLAN when parent is opened in netmap mode. It is quite easy to reproduce.

I setup 2 namespaces (r1 & r2). In each I created 2 vlans (.10 & .30).

[ r1 ] <eth1> ---- <eth0> [ r2 ]

root@r1:~/netmap/apps/pkt-gen# lsmod | grep netmap
netmap                192512  0

Namespace r1
--------------
root@r1:~/netmap/apps/pkt-gen# ip route show
10.1.1.0/24 dev r1eth1.10 proto kernel scope link src 10.1.1.2 
20.1.1.0/24 dev r1eth1 proto kernel scope link src 20.1.1.2 
30.1.1.0/24 dev r1eth1.30 proto kernel scope link src 30.1.1.2 


Namespace r2
---------------
root@r2:~/projects/netmap/apps/pkt-gen# ip route show
10.1.1.0/24 dev r2eth0.10 proto kernel scope link src 10.1.1.3 
20.1.1.0/24 dev r2eth0 proto kernel scope link src 20.1.1.3 
30.1.1.0/24 dev r2eth0.30 proto kernel scope link src 30.1.1.3 

The following test case works

./pkt-gen -i r1eth1.10 -f tx & ./pkt-gen -i r1eth1.30 -f tx in namespace r1 and ./pkt-gen -i r2eth0.10 -f rx & ./pkt-gen -i r2eth0.30 -f rx in namespace r2.


559.904358 main_thread [2639] 135.267 Kpps (135.436 Kpkts 65.009 Mbps in 1001249 usec) 109.31 avg_batch 1 min_space
562.212182 main_thread [2639] 460.731 Kpps (461.313 Kpkts 221.430 Mbps in 1001263 usec) 16.14 avg_batch 1 min_space

However as soon as 'tx' on parent is enabled, the 'rx' on vlan stops working. The following combination doesnt work.

./pkt-gen -i r1eth1 -f tx & ./pkt-gen -i r1eth1.30 -f tx in namespace r1 and ./pkt-gen -i r2eth0 -f rx & ./pkt-gen -i r2eth0.30 -f rx in namespace r2.

On vlan 'rx' following log is seen.

962.939568 main_thread [2639] 0.000 pps (0.000 pkts 0.000 bps in 1001176 usec) 0.00 avg_batch 0 min_space

while the parent receives packets,

993.778057 main_thread [2639] 635.799 Kpps (636.629 Kpkts 305.582 Mbps in 1001305 usec) 94.58 avg_batch 1 min_space

The following is seen in dmesg during the failure case.

[379308.006013] 020.038224 [3901] netmap_transmit           r1eth1 full hwcur 0 hwtail 0 qlen 127
[379308.042106] 020.074315 [ 690] generic_qdisc_enqueue     dropping mbuf
[379308.042113] 020.074324 [ 690] generic_qdisc_enqueue     dropping mbuf
[379308.042120] 020.074330 [1053] nm_os_generic_xmit_frame  Warning: dev_queue_xmit() is dropping [1]

**Comment by vmaffione** [comment]
This behaviour is expected, as the receiver on the parent interface (r2eth0) intercepts all the RX traffic, and r2eth0.30 sees nothing. The logs in dmesg are due to queue overflows, but this is a flow control issue, unrelated to using VLAN or not.

Since you are using network namespaces, and therefore veth pairs, why don't you use native netmap mode, and avoid the creation of VLAN interfaces? Netmap has native support for veth, if both ends of the veth are opened in netmap mode. You should directly connect the two namespaces with a veth pair, without using a bridge in between. Then in your netmap application in the containers you are free to add VLAN tags as you wish. In this way you should be able to exchange traffic at 30-40 Mpps.

**Comment by calvadoscal** [comment]
Thanks. Agree that using native driver is better.
