### ISSUE TITLE
Netmap user space code should switch interface to promisc mode

### ISSUE THREAD

**Issue by pavel-odintsov** [luigirizzo/netmap#62]
Hello!

It's another feature request from me. My application uses netmap for packet capture and very often my customers _lost_ to switch interfaces to promisc mode and capture did not work correctly.

From my point of view promisc mode should be enabled for any netmap aware application. I could offer patches for FreeBSD and Linux both. If you agree about this idea I will start my work shortly.

**Comment by UlricE** [comment]
2015-06-06 22:09 skrev Pavel Odintsov:
> Hello!
> 
> It's another feature request from me. My application uses netmap for
> packet capture and very often my customers _lost_ to switch interfaces
> to promisc mode and capture did not work correctly.

Can't you just let the application set the interface to promiscuous 
mode?

> 
> From my point of view promisc mode should be enabled for any netmap
> aware application. I could offer patches for FreeBSD and Linux both.
> If you agree about this idea I will start my work shortly.

My netmap aware application does not require the interface to be in 
promiscuous mode.

Ulric

**Comment by pavel-odintsov** [comment]
Hello!

Yep, I could do it from my app. But in many cases will be fine to have code
for this operation in library.

It could be implemented as flag and user could select value for it purposes.

воскресенье, 7 июня 2015 г. пользователь Ulric написал:

>
>
> 2015-06-06 22:09 skrev Pavel Odintsov:
> > Hello!
> >
> > It's another feature request from me. My application uses netmap for
> > packet capture and very often my customers _lost_ to switch interfaces
> > to promisc mode and capture did not work correctly.
>
> Can't you just let the application set the interface to promiscuous
> mode?
>
> >
> > From my point of view promisc mode should be enabled for any netmap
> > aware application. I could offer patches for FreeBSD and Linux both.
> > If you agree about this idea I will start my work shortly.
>
> My netmap aware application does not require the interface to be in
> promiscuous mode.
>
> Ulric
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/62#issuecomment-109715345>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
I have implemented code for switching interface from/to promisc mode for Linux https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/tests/promisc.cpp

**Comment by vmaffione** [comment]
The policy is that netmap code must not set promiscous mode on/off. This task is left to the application.
It could be a good idea to modify the bridge example application to set the promisc mode, for Linux, FreeBSD and Windows.
