### ISSUE TITLE
can we set number of slots in each ring more than  amount of descriptors per ring of physical NIC

### ISSUE THREAD

**Issue by lkkey80** [luigirizzo/netmap#620]
currently, I found netmap's slot number per ring is exactly equal descriptors per ring of physical NIC, it's less than 4096 as usual(ethtool -G ethx 4096). If we wanna buffer much data, we need increase netmap's slot number per ring. so can we do it without modifying netmap's source code ?

**Comment by vmaffione** [comment]
As you said, the number of netmap slots is always the same as the number of descriptors in the corresponding ring. You can use ethtool -G ethx tx 4096 rx 4096 or ethtool -G ethx combined 4096 to change the number of descriptors/slots to 4096.

**Comment by lkkey80** [comment]
I want to buffer hundreds of thousands of packets in netmap ring, but the max number of descriptors in the physical nic ring is 4096,  I noticed that the largest value I can set is u16_max(65535) in ixgbe driver. But if I use ethtool -G ethx 65535, when I start a netmap user process, it failed because of memory allocation problem on netmap_mem. Maybe I need to do lots of modification on netmap memory allocation to achieve the goal.

**Comment by lkkey80** [comment]
It' will be better, if Netmap allow user  to specify the number of slots per ring,  So we can buffer more packets and directly deal with packets, if not, we have to copy them to the other place and free the slots quickly.

**Comment by vmaffione** [comment]
If you want to buffer many packets you need to use "extra buffers" (look for extra bufs in the netmap man page, and look at the "lb" application). You don't need to have a large number of slots in the ring.
You can use the extra buffers to replace RX buffers that have been filled with new packets.
To address the allocation failure, you certainly need to increase the number of buffers in the netmap allocator, by using a large value for the following parameter: `/sys/module/netmap/parameters/buf_num`

**Comment by lkkey80** [comment]
Does /sys/module/netmap/parameters/buf_num has a max limit? I found /sys/module/netmap/parameters/buf_curr_num has a max limit.

**Comment by lkkey80** [comment]
It seems it is limited by total system memory size. Max buf_num is nummax(1000000), it's big enough.

**Comment by vmaffione** [comment]
Yes, there is an hardcoded maximum:

https://github.com/luigirizzo/netmap/blob/master/sys/dev/netmap/netmap_mem2.c#L556

You should change buf_num, as buf_cur_num is for reading back the actual current value.
