### ISSUE TITLE
Build failure at Raspberry Pi 3+ with Ubuntu Mate

### ISSUE THREAD

**Issue by hmbdc-dev** [luigirizzo/netmap#623]
Hi,

I have the 64bit Ubuntu Mate installed on Raspberry Pi 3+, and I keep getting netmap building errors on it:

sli@pi3bplus:~/Downloads/netmap-master$ gcc --version
gcc (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

./configure --no-drivers

sli@pi3bplus:~/Downloads/netmap-master$ make
make -C /lib/modules/4.15.0-1032-raspi2/build M=/home/sli/Downloads/netmap-master EXTRA_CFLAGS='-I/home/sli/Downloads/netmap-master -I/home/sli/Downloads/netmap-master/LINUX -I/home/sli/Downloads/netmap-master/LINUX/../sys -I/home/sli/Downloads/netmap-master/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-1032-raspi2'
  CC [M]  /home/sli/Downloads/netmap-master/netmap_mem2.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_mbq.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_legacy.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_bdg.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_kloop.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_vale.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_offloadings.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_pipe.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_monitor.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_generic.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_null.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_common.o
  CC [M]  /home/sli/Downloads/netmap-master/netmap_linux.o
/home/sli/Downloads/netmap-master/LINUX/netmap_linux.c: In function ‘ptnetmap_guest_probe’:
/home/sli/Downloads/netmap-master/LINUX/netmap_linux.c:1871:9: error: implicit declaration of function ‘pci_select_bars’; did you mean ‘pci_request_acs’? [-Werror=implicit-function-declaration]
  bars = pci_select_bars(pdev, IORESOURCE_MEM | IORESOURCE_IO);
         ^~~~~~~~~~~~~~~
         pci_request_acs
/home/sli/Downloads/netmap-master/LINUX/netmap_linux.c:1877:8: error: implicit declaration of function ‘pci_request_selected_regions’; did you mean ‘pci_request_regions’? [-Werror=implicit-function-declaration]
  err = pci_request_selected_regions(pdev, bars, PTNETMAP_MEMDEV_NAME);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
        pci_request_regions
/home/sli/Downloads/netmap-master/LINUX/netmap_linux.c:1906:2: error: implicit declaration of function ‘pci_release_selected_regions’; did you mean ‘pci_release_regions’? [-Werror=implicit-function-declaration]
  pci_release_selected_regions(pdev, bars);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  pci_release_regions
cc1: some warnings being treated as errors
/home/sli/Downloads/netmap-master/Kbuild:29: recipe for target '/home/sli/Downloads/netmap-master/netmap_linux.o' failed
make[2]: *** [/home/sli/Downloads/netmap-master/netmap_linux.o] Error 1
Makefile:1551: recipe for target '_module_/home/sli/Downloads/netmap-master' failed
make[1]: *** [_module_/home/sli/Downloads/netmap-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-1032-raspi2'
netmap.mak:81: recipe for target 'netmap.ko' failed
make: *** [netmap.ko] Error 2

**Comment by giuseppelettieri** [comment]
what is the kernel version? ```uname -r```

**Comment by hmbdc-dev** [comment]
4.15.0-1032-raspi2

**Comment by vmaffione** [comment]
As a temporary workaround you should be able to compile correctly by appending `--disable-ptnetmap` to the `./configure` invocation.

**Comment by vmaffione** [comment]
How old must that kernel code be? The missing functions were introduced in 2006, over 13 years ago
https://github.com/torvalds/linux/commit/c87deff776feacd05a7411097e8c8c57e549e638
Maybe we can just disable ptnetmap in `./configure` if these functions are not found... I would not spend time trying to fix the compilation of an optional system (such as ptnetmap) for ancient kernels.

**Comment by hmbdc-dev** [comment]
The bypass seemed to work. Ubuntu Mate’s kernel being so old is a problem, and I will move to Ubuntu server for Raspberry soon.
thx
