### ISSUE TITLE
Extra buffer memory leak

### ISSUE THREAD

**Issue by lkkey80** [luigirizzo/netmap#625]
I figured out that I need to re-build the extra buffers list before calling nm_close, but will Netmap go to an inconsistent state such as memory leak  if my app crashes unexpectedly?

**Comment by giuseppelettieri** [comment]
Yes, but the the state will be cleared when nobody is using the memory region. Therefore, if you have just one app, or if you use a private memory region, you have no problems.

**Comment by lkkey80** [comment]
If I only use one app, it crashed or exited and then it restarts, will Netmap free memory buffer pool firstly and re-allocate them when my app starts again?

**Comment by giuseppelettieri** [comment]
Yes, that's more or less what is going to happen.
