### ISSUE TITLE
veth driver missing

### ISSUE THREAD

**Issue by ztz1989** [luigirizzo/netmap#627]
Dear all, 
    I would like to use netmap's veth driver to communicate with Docker, but on my machine, when I try to compile netmap, veth.c is always reported missing with this warning message
`'veth.c': sources not found.  Disabling driver`. The command I use for compilation is `sudo ./configure --kernel-sources=/lib/modules/$(uname -r)/build/`. The reported native driver at the end of `./configure` include i40e, ixgbevf, ixgbe, igb, and e1000e. The kernel version is 4.8.0-41-generic. Could you give me some hints to enable the compilation of the veth driver? Any suggestion is highly appreciated!

  Best Regards,

**Comment by giuseppelettieri** [comment]
Are you sure that ```/lib/modules/$(uname -r)/build``` contains the full kernel sources, as opposed to just the kernel headers? The other drivers you mention are downloaded from the Intel project on sourceforge, but for veth we need to grab the source file from your kernel sources.

**Comment by ztz1989** [comment]
Hi, Giuseppe. You're right. I change to the correct path and can find the veth driver now. Thanks for your reply.
