### ISSUE TITLE
POLLOUT on fd hangs forever in userspace

### ISSUE THREAD

**Issue by brian-armstrong-discord** [luigirizzo/netmap#629]
Hello,

Thank you for creating this awesome library!

I'm trying to integrate netmap into an existing application that runs in userspace, and I've hit a bit of a snag. If I chgrp/chmod `/dev/netmap` so that the user can access it, this seems to get 90% of the way to working. Receiving and transmitting work, and `epoll()` on the interface fd works for `POLLIN`, but `POLLOUT` does not seem to work. Specifically, it seems to return once when half of the ring is available, and then on next `epoll()`, it hangs forever. If I `sudo` the application then the same code works fine and `epoll()` seems to behave as expected.

Is this simply user error? Is there something I need to do to get my application unblocked in user space?

Thanks!

**Comment by giuseppelettieri** [comment]
Strange. May you share your code (or even a minimal part of it) so that I can try to reproduce the error locally?

**Comment by brian-armstrong-discord** [comment]
Sure, I'm just attempting to graft this onto libuv, so it's not super easy to follow. The call to epoll() will be buried in libuv's event code somewhere. Also my code is very WIP-quality still, so apologies in advance :)

The idea with this code is to mimic how libuv's udp module works. Currently, in libuv you get a `uv_udp_t` which is basically a wrapper on a udp FD/socket, and then libuv has an event loop where it watches all of its FDs and dispatches rx/tx. My patch attempts to integrate netmap so that there is a single netmap interface tied to the event loop, and calls to the libuv udp functions are intercepted and instead drive rx/tx on the netmap interface. We still give the netmap file descriptor to libuv to do `epoll()` on.

Here is where we open the netmap interface https://github.com/discordapp/libuv/blob/feature/netmap/src/unix/udp.c#L346

Here is where we start to iterate over a netmap tx ring and a tx queue inside libuv, wrapping payloads into UDP packets and enqueueing them https://github.com/discordapp/libuv/blob/feature/netmap/src/unix/udp.c#L285 We get here once libuv has received a return from `epoll()` and our netmap interface was amongst the active FDs.

Here's where we decide whether to toggle POLLOUT on our fd. I've confirmed both with the printf and with strace that we have not disabled POLLOUT when this pause happens https://github.com/discordapp/libuv/blob/feature/netmap/src/unix/udp.c#L250

Here is where a call to `uv_udp_send()` triggers a POLLOUT on our fd inside libuv https://github.com/discordapp/libuv/blob/feature/netmap/src/unix/udp.c#L896

I've been thinking about this behavior some more, and it may not necessarily matter that this sleep happens. I'm encountering it in a benchmarker/tester that only transmits and doesn't receive, but in an actual application I think it's pretty unlikely that there'd be no other FDs to wake the application up from. But still I'd like to get to the bottom of it and see what happened :)

**Comment by brian-armstrong-discord** [comment]
I've started to make some progress on this. I'm going to keep looking into it but I thought I'd put what I found so far in case any of it makes sense to you :)

I've noticed that the qdisc bits don't seem to fire in userspace. I'm on linux, and netmap_linux.c:tc_configure() does seem to run successfully (and its prinf appears in syslog). However none of the qdisc ops seem to fire, for example I've confirmed with printk that generic_qdisc_dequeue and generic_qdisc_init are never called. When I run my program under sudo, these functions do fire.

I'm not familiar enough with Qdisc_ops/register_qdisc to know if this is expected behavior and if my user simply needs to be given some permission, or if this is impossible in userspace, or if the registration can add some flag to allow this. I will keep looking.

**Comment by brian-armstrong-discord** [comment]
It appears that running `sudo setcap cap_net_admin+ep` on the binary removes the need to run as sudo. From my reading of the code in netmap_linux I'm guessing this is because of permissions needed to create a qdisc. This seems like a reasonable compromise over running as root.

**Comment by giuseppelettieri** [comment]
Yes, I think that you found the problem. By the way, if you need qdiscs you are using the generic driver instead of the native drivers. Is this intentional?

**Comment by brian-armstrong-discord** [comment]
Well as far as I can tell there are no native drivers for Solarflare NICs, right? We have a variety of network interface makes/models which is part of what we find appealing about netmap. We're seeing awesome performance on IXGBE but even the generic driver on Solarflare does quite well.

**Comment by giuseppelettieri** [comment]
Yep, you are right. Good to know that the generic driver does its job.

**Comment by brian-armstrong-discord** [comment]
Closing since the mystery has been solved.

By the way, our team put our first netmap-powered service into production today, and it's running considerably faster than the standard socket version, despite running on the generic driver. I'm definitely curious to see how it does if I get a chance to write a specific driver, but either way, it's great stuff. We really appreciate the hard work everyone's put into this library.
