### ISSUE TITLE
Is there any way to know the direction of monitor traffic?

### ISSUE THREAD

**Issue by xiaojin2630** [luigirizzo/netmap#636]
I use nm_open("netmap:eth3/z", ...) to get the inbound and outbound traffic of eth3. When I process each packet, how do I know from the netmap api whether the packet is in or out? ?

**Comment by giuseppelettieri** [comment]
At the moment, you can't. If it is really needed, I guess we can set a flag in the slot.

**Comment by xiaojin2630** [comment]
If you can set a flag in the slot, that's the best. thank you very much!

**Comment by xiaojin2630** [comment]
I am currently writing a program, if there is this flag, the internal processing of the traffic will be much easier.

**Comment by xiaojin2630** [comment]
https://github.com/luigirizzo/netmap/issues/745

close it
