### ISSUE TITLE
What version of LINUX to use with netmap v13.0

### ISSUE THREAD

**Issue by kogdenko** [luigirizzo/netmap#639]
Good day
I suppose tag v13.0 point to stable/tested version of netmap.
I compiled it with longterm LINUX version 4.14.138, but quickly got kernel panic (wtith veth driver)
Tell me , please - on what version of LINUX this version of netmap tested and worked.
ps:
I just need to know any version of netmap and LINUX on which veth and ixgbe drivers compiled and worked well.
Thank you

**Comment by giuseppelettieri** [comment]
No, it doesn't. Please just use the current master.

**Comment by kogdenko** [comment]
I got it. Thank you
