### ISSUE TITLE
Could you add flag for configure for using offered drivers as is?

### ISSUE THREAD

**Issue by pavel-odintsov** [luigirizzo/netmap#64]
Hello!

I have used my custom already patched ixgbe driver. Could you add ability to specify option for configure script for disable any patches and use they as-is?

**Comment by stefano-garzarella** [comment]
Hi Pavel,
there is already an option to do disable patches in the configure script:

./configure ... --override=ixgbe-override

where ixgbe-override is a file that contains a set of GNU make variables
such as:
ixgbe-src := path/to/your/ixgbe/code
ixgbe-patch :=               #(leave empty)

Cheers,
Stefano


2015-07-06 11:53 GMT+02:00 Pavel Odintsov <notifications@github.com>:

> Hello!
>
> I have used my custom already patched ixgbe driver. Could you add ability
> to specify option for configure script for disable any patches and use they
> as-is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/64>.
>



-- 
*Stefano Garzarella*
Software Engineer

e-mail: stefano.garzarella@gmail.com
github: http://github.com/stefano-garzarella
linkedin: http://it.linkedin.com/pub/stefano-garzarella

**Comment by pavel-odintsov** [comment]
Perfect! Thanks! :)
