### ISSUE TITLE
Recent commit breaks backwards compat of netmap

### ISSUE THREAD

**Issue by brian-armstrong-discord** [luigirizzo/netmap#642]
I noticed today that an application I've written that uses netmap stopped working with `Operation not supported`. After root-causing this, it turned out to be that `sizeof(struct nmreq)` recently changed, which causes`nm_open` to fail due to the ioctl cmd changing -- the consumer was built on older netmap, but the module was built on newer. If possible, it would be great if the library could avoid these types of situations in the future or at least explicitly reject version mismatches, rather than failing in fairly subtle ways with invalid ioctls.

The sha in question is https://github.com/luigirizzo/netmap/commit/fa36d8bbcfe00a95a5dfd52a880f23c427422dd1

Thanks again for this awesome library!

**Comment by giuseppelettieri** [comment]
You are right, apologies for that. Our intention was to keep backward compatibility, but we messed up the version checks.

**Comment by brian-armstrong-discord** [comment]
Sounds like you all are on top of it :) I briefly did not believe my eyes when I saw those ioctl cmds were a bit different, but in retrospect it's easy to see how it could happen. Since you're aware I'll go ahead and close this.
