### ISSUE TITLE
freebsd panics after opening a single ring pair

### ISSUE THREAD

**Issue by dkoreshkov** [luigirizzo/netmap#647]
Hello,
here is a small program that causes a kernel panic once in a few runs.
I hope you will be able to reproduce the issue by running it in a loop:
while sudo ./a.out interface-name; do :; done

It seems the following conditions must be present:
1. OS:  FreeBSD 12.0-STABLE (definitely not reproduced with 11.x)
2. An interface with some incoming traffic, NIC family ixgbe or ixl.
3. Opening a single NIC ring, not all rings!
4. A pause between opening and exiting.
````
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
#include <err.h>
#include <net/if.h>

#define NETMAP_WITH_LIBS
#include <net/netmap.h>
#include <net/netmap_user.h>

int main(int argc, char **argv)
{
	char name[64];
	char *p = argc==2 ? argv[1] : "red";
	struct nm_desc *d;

	sprintf(name, "netmap:%s-0", p);

	d = nm_open(name, NULL, 0, NULL);
	if (!d) err(1, "open");
	printf("1\n");
	sleep(3);
	nm_close(d);
	printf("2\n");
	return 0;
}
````

**Comment by m1357** [comment]
Are you using the headers from the repo here or from the freebsd source. I have the same issue using utilities/code from current repo. looks like Freebsd is built from several version back from current code.

**Comment by dkoreshkov** [comment]
I used the headers that were installed with the OS. The API version was 14, I think.

**Comment by sylgal** [comment]
Hello,

I've also reproduced panic using FreeBSD 12-STABLE (r355890)
I did several tests using dkoreshkov code + incoming traffic on XL710 NIC:

1/ ixl with more than 1 queue
dmesg: ixl2: Using 10 RX queues 10 TX queues
-> no panic using netmap:ixl2
-> panic using netmap:ixl2-0

```
panic: vm_fault: fault on nofault entry, addr: 0xfffffe00a107c000
cpuid = 2
time = 1577180433
KDB: stack backtrace:
#0 0xffffffff80b6de47 at kdb_backtrace+0x67
#1 0xffffffff80b211ed at vpanic+0x19d
#2 0xffffffff80b21043 at panic+0x43
#3 0xffffffff80e9eb0f at vm_fault+0x251f
#4 0xffffffff80e9c4d1 at vm_fault_trap+0x61
#5 0xffffffff8103ad14 at trap_pfault+0x1a4
#6 0xffffffff8103a1f1 at trap+0x2a1
#7 0xffffffff810133bc at calltrap+0x8
#8 0xffffffff80c49b23 at iflib_rxeof+0x133
#9 0xffffffff80c448b5 at _task_fn_rx+0x75
#10 0xffffffff80b6c722 at gtaskqueue_run_locked+0x142
#11 0xffffffff80b6c368 at gtaskqueue_thread_loop+0xa8
#12 0xffffffff80ae1843 at fork_exit+0x83
#13 0xffffffff8101440e at fork_trampoline+0xe
```

2/ ixl with only 1 queue configured
dmesg: ixl2: Using 1 RX queues 1 TX queues
-> no panic (using netmap:ixl2-0 or netmap:ixl2)

**Comment by vmaffione** [comment]
This looks like it is related to iflib. The bug must have been introduced when porting intel drivers (ixl, ixgbe, igb, etc.) to iflib. Also, note that in the stack trace there is no netmap code function involved.
I would suggest filing a bug on the freebsd bugzilla https://bugs.freebsd.org/bugzilla/ 
Btw, netmap code in freebsd is no longer outdated.

**Comment by sylgal** [comment]
You are right,

after applying commit r353967 from ^/head on FreeBSD 12-STABLE I do not reproduce the panic anymore

r353967 | erj | 2019-10-23 23:20:49 +0000 (Wed, 23 Oct 2019) | 18 lines
iflib: call ether_ifdetach and netmap_detach before stop
https://reviews.freebsd.org/D22071
