### ISSUE TITLE
reset priority in netmap_linux.c only when emit is OK

### ISSUE THREAD

**Issue by linoferrentino** [luigirizzo/netmap#648]
In the function

`static netdev_tx_t
generic_ndo_start_xmit(struct mbuf *m, struct ifnet *ifp)`

in the file netmap_linux.c there is an unconditional set of the priority to zero.

`
m->priority = 0;
return gna->save_start_xmit(m, ifp); /* To the driver. */`

I am working with the emulated driver. I have observed that the emulated driver can actually return an error from the xmit function (due to lack of space), but the mbuf has already set the prioriry to zero... this will put the buffer in the RX host ring, as-if it is actually sent by the host stack (which is not).

I have patched my copy of netmap in this way.

```
diff --git a/LINUX/netmap_linux.c b/LINUX/netmap_linux.c
index 91f8b76..7280070 100644
--- a/LINUX/netmap_linux.c
+++ b/LINUX/netmap_linux.c
@@ -625,14 +625,18 @@ generic_ndo_select_queue(struct ifnet *ifp, struct mbuf *m
 static netdev_tx_t
 generic_ndo_start_xmit(struct mbuf *m, struct ifnet *ifp)
 {
+        int res_xmit;
        struct netmap_generic_adapter *gna =
                (struct netmap_generic_adapter *)NA(ifp);
 
        if (likely(m->priority == NM_MAGIC_PRIORITY_TX)) {
-               /* Reset priority, so that generic_netmap_tx_clean()
-                * knows that it can reclaim this mbuf. */
-               m->priority = 0;
-               return gna->save_start_xmit(m, ifp); /* To the driver. */
+                res_xmit = gna->save_start_xmit(m, ifp); /* To the driver. */
+                if (likely(0 == res_xmit)) {
+                        /* Reset priority, so that generic_netmap_tx_clean()
+                        * knows that it can reclaim this mbuf. */
+                        m->priority = 0;
+                }
+                return res_xmit;
        }
 
        /* To a netmap RX ring. */


```

to conditionally reset the priority only if the xmit is actually successful.

I don't know if this has other consequences, I have tested only with the emulated driver and it is working. Probably a netmap aware driver does not need it, in any case I paste it here just in case.

**Comment by jhk098** [comment]
Not clear how an `XMIT_BUSY` from the driver results into `linux_netmap_start_xmit` to be called... can you elaborate on that?

**Comment by linoferrentino** [comment]
I am writing an application that uses the generic adapter. I use special packets (UDP with a special header).

Sometimes in high stress usage I saw my packets come from the RX host rings as if the kernel wanted to send them. Clearly it was impossible because no other application (apart from mine) could send a packet like this.

I looked at the code and I saw that in some circumstances the save_start_xmit function returned a value != from zero but the packet had already the priority zeroed.

So next round it would be transmitted in the host ring as if a normal kernel packet.

**Comment by jhk098** [comment]
Ok, what happens is that if driver returns `NETDEV_TX_BUSY`, `dev_queue_xmit` will enqueue the skb again in the qdisc (after `generic_ndo_start_xmit` returns).

However, your approach is not correct, because if `res_xmit == NETDEV_TX_OK`, the skb may have been consumed, which means that `m` is a dangling pointer. This does not happen with your NIC driver, but it may happen with others.
On the contrary, you should leave the `m->priority = 0`, and reset `m->priority = NM_MAGIC_PRIORITY_TX` if `res_xmit == NETDEV_TX_BUSY`, because in that case we are sure that the skb has not been consumed. Can you try this approach and check that it works for you?

**Comment by linoferrentino** [comment]
Hi, thanks for the answer.

I did not know about the consequences but now it is more clear.

I have changed the function to this:

```
diff --git a/LINUX/netmap_linux.c b/LINUX/netmap_linux.c
index 7280070..c865c47 100644
--- a/LINUX/netmap_linux.c
+++ b/LINUX/netmap_linux.c
@@ -630,11 +630,12 @@ generic_ndo_start_xmit(struct mbuf *m, struct ifnet *ifp)
                (struct netmap_generic_adapter *)NA(ifp);
 
        if (likely(m->priority == NM_MAGIC_PRIORITY_TX)) {
+               m->priority = 0;
                 res_xmit = gna->save_start_xmit(m, ifp); /* To the driver. */
-                if (likely(0 == res_xmit)) {
-                        /* Reset priority, so that generic_netmap_tx_clean()
-                        * knows that it can reclaim this mbuf. */
-                        m->priority = 0;
+                if (unlikely(0 != res_xmit)) {
+                        /* busy driver. Reset priority so it will
+                        * be tried again. */
+                        m->priority = NM_MAGIC_PRIORITY_TX;
                 }
                 return res_xmit;
        }

```

it resets the priority before and, if not OK, it will set it again to the magic value.

It works for me.
