### ISSUE TITLE
The 'na' pointer was utilized before it was verified 

### ISSUE THREAD

**Issue by i39** [luigirizzo/netmap#654]
IMHO we should check it before using, but we use it (https://github.com/luigirizzo/netmap/blob/ff6fbe0123b0a502a4bc03616798cdb501680a8e/sys/dev/netmap/netmap_mem2.c#L1526) ant then check :(

https://github.com/luigirizzo/netmap/blob/ff6fbe0123b0a502a4bc03616798cdb501680a8e/sys/dev/netmap/netmap_mem2.c#L1528

**Comment by giuseppelettieri** [comment]
Yes, good catch, thank you. Do you have a patch for it?

**Comment by i39** [comment]
No, i'am new in this and don't know how exactly do it :) But if You show me right way i'll do it with pleasure :)

**Comment by i39** [comment]
I mean what i don't know how create the patch but i know  how rewrite the code.

**Comment by giuseppelettieri** [comment]
If you are already familiar with git it should be easy: fork the project using the "fork" button in the upper-right corner, then clone your fork and create and push a commit in it; finally, create a pull-request following these [instructions ](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

If you are not familiar with git, the following should be sufficient to create and push the commit. 
After cloning your fork, modify the code in the fork and then write
```git commit -a```
An editor fires up, write your commit message and save. Then push the patch to your clone:
```git push```

**Comment by i39** [comment]
Ok.  Big thanks, i'll try to do it! :)

**Comment by giuseppelettieri** [comment]
Fixed in #671, thank!.
