### ISSUE TITLE
Linux memory accounting - RssFile vs RssShmem

### ISSUE THREAD

**Issue by carlgsmith** [luigirizzo/netmap#660]
When applications access the memory mapped netmap memory space the netmap page fault handler allocates a page and the kernel increments the RSS memory counter for that process.

In later Linux kernels, VmRSS (/proc/meminfo) is broken up into:
<pre>
 VmRSS                       size of memory portions. It contains the three
                             following parts (VmRSS = RssAnon + RssFile + RssShmem)
 RssAnon                     size of resident anonymous memory
 RssFile                     size of resident file mappings
 RssShmem                    size of resident shmem memory (includes SysV shm,
                             mapping of tmpfs and shared anonymous mappings)
</pre>

The kernel differentiates between RssFile and RssShmem by checking the PG_swapbacked flag on the page. Because we do not set that flag in linux_netmap_fault, all of the netmap memory is listed as RssFile.

<pre>
VmRSS:    171372 kB
RssAnon:             512 kB
RssFile:          170860 kB
RssShmem:              0 kB
</pre>

If we set the PG_swapbacked flag:
<pre>
--- a/LINUX/netmap_linux.c
+++ b/LINUX/netmap_linux.c
@@ -1289,6 +1289,7 @@ linux_netmap_fault(struct vm_fault *vmf)
        if (!pfn_valid(pfn))
                return VM_FAULT_SIGBUS;
        page = pfn_to_page(pfn);
+       SetPageSwapBacked(page);
        get_page(page);
        vmf->page = page;
        return 0;
</pre>

Then the memory is counted as shared memory.
<pre>
VmRSS:   1409444 kB
RssAnon:           64848 kB
RssFile:            5460 kB
RssShmem:        1339136 kB
</pre>

This is the same as the page fault handler in the kernels shmem code. Should we not do the same for netmap?????

**Comment by giuseppelettieri** [comment]
Makes sense. Would you like to create a pull request?

**Comment by carlgsmith** [comment]
Will do. Will run some of our tests on our setup here first.
