### ISSUE TITLE
netmap + bond (linux) supported? 

### ISSUE THREAD

**Issue by johalun** [luigirizzo/netmap#666]
Hi
I'm exploring the possibilities of using netmap on a bond (two 10G interfaces, LACP, 8 queues each).
When opening the netmap device (with default module parameters) I get 16 ring pairs, however, traffic only comes in on the the 8 first ring pairs. My application seems to be working normally otherwise with high performance. What might this depend on? Is 8 or 16 ring pairs correct in this case? 
Edit: Incoming/outgoing packets are evenly distributed across the two interfaces.The only issue seem to be that netmap thinks there are 16 queues instead of 8. Is there a way to tell netmap there are actually only 8? I tried the usual module parameters like generic_rings but it makes no difference.

**Comment by vmaffione** [comment]
The `bond0` interface (with LACP) works with the emulated adapter.
I think you need to set `ethtool -L ethX combined 8` to change the number of queues on both NICs. Then netmap should see 8 ring pairs.
