### ISSUE TITLE
Increase maximum number of VALE bridges

### ISSUE THREAD

**Issue by gkatsikas** [luigirizzo/netmap#67]
Hi,

I would like to have a scenario with more than 8 VALE bridges running on the same host.
Netmap limits this number to 8 according to the variable NM_BRIDGES that is located in NETMAP_DIR/sys/dev/netmap/netmap_vale.c:147.

I changed this number but I am still unable to have more than 8 bridges. When I try to allocate the 9th bridge (vale-ctl -a vale9:br9), I get: vale9:br9: Cannot allocate memory

I have an Ubuntu 14.01 with kernel 3.13 compiled and installed from sources. I use the branch next and configure like this:
./configure --kernel-sources=/usr/src/linux-image-$(uname -r) --enable-pipe --enable-vale --enable-monitor

Is there any other variable that should be changed in order to achieve my target?
Thanks in advance!

Best,
Georgios

**Comment by giuseppelettieri** [comment]
Yes, that is a bit of unfinished work. Please look in LINUX/netmap_linux.c, in function netmap_pernet_init(), and change the assignment 'ns->num_bridges = ...';

**Comment by gkatsikas** [comment]
Thanks a lot for the prompt reply! 

Now I can create more bridges but I encountered another problem. For bridge no10, I cannot add any ports.
vale-ctl -n br10               # OK
vale-ctl -a vale10:br10   # OK
vale-ctl -a vale10:br10-ns9  # Invalid argument

Whatever name I try to attach to vale10 I get "Invalid argument".
For bridges vale1-vale9 I have absolutely no problem to create at least two ports per bridge.
I understand that the work is not finished as you said, but that might be a quick fix :)

Best regards,
Georgios

**Comment by vmaffione** [comment]
The problem here is an invalid interface name "br10-ns9", since the "-" is interpreted in a special way by `nm_open()`. Try to use an interface name without "-" or the other special characters used by `nm_open()`.
I'll close this because it's a stale thread on a very old code. Please reopen if necessary,
