### ISSUE TITLE
page allocation failure but there are reclaimable pages

### ISSUE THREAD

**Issue by carlgsmith** [luigirizzo/netmap#673]
We have an issue where netmap is enabled on a low memory system after the device has been running for a while. The number of free pages is very low, but the file cache is very large. Hence we get "page allocation failure"s for 0 order pages when trying to allocate buffers for netmap.

That is because the code in bsd_glue.h passes the GFP_ATOMIC flag to alloc_pages, which prevents memory reclaim.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/gfp.h#n105

Can GFP_USER be used?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/gfp.h#n258
e.g.
-       struct page *p_ = alloc_pages(GFP_ATOMIC | __GFP_ZERO,  \
+       struct page *p_ = alloc_pages(GFP_USER | __GFP_ZERO,  \

**Comment by giuseppelettieri** [comment]
Well, I can see no reason preventing that.  Can you test the change and report back, please?

**Comment by carlgsmith** [comment]
Sure, have made the change locally and are running through a bunch of our tests.
