### ISSUE TITLE
any replacement of `netem` on `netmap`?

### ISSUE THREAD

**Issue by Winters123** [luigirizzo/netmap#676]
Hi,
I noticed that `netem` is bypassed when I'm using `netmap` as the building-block of a network stack. Is there any replacement of `netem` so that I can play with packet loss, packet reordering and metrics like that?

**Comment by Winters123** [comment]
`tlem` to my knowledge doesn't support the experiments in which two servers are connected together and all the traffic between them needs to go through the user-space stack.

**Comment by giuseppelettieri** [comment]
May you elaborate on your network setup? If the servers are using netmap you can interpose tlem using netmap pipes, for example.

**Comment by Winters123** [comment]
solved, thanks ;)
