### ISSUE TITLE
Broadcom bnx2x not supported anymore?

### ISSUE THREAD

**Issue by kartoffelbaer** [luigirizzo/netmap#68]
Hi,

i found traces of bnx2x support in netmap at google, but seems to be gone.. will it be supported again in the near future? Why is there no support for bnx2x anymore?

greetings,
kartoffelbaer

**Comment by vmaffione** [comment]
Maybe there was some initial support,bit a complete support never made it through. I think preliminary tests showed that The hardware is not ready to do more than 2mpps at 60 bytes,so adding proper support was considered to be not worthwhile
