### ISSUE TITLE
Cannot allocate RX_ring error; ixgbe CentOS 7.6

### ISSUE THREAD

**Issue by Bsynamedia** [luigirizzo/netmap#685]
Hi all,
I am recieving an error trying to run the pkt-gen; I was able to install netmap using
./configure --select-version=ixgbe:5.5.5;
Installed the "netmap.ko" and "ixgbe.ko" confirmed with lsmod

./build-apps/pkt-gen/pkt-gen -v -i enp14s0f0 -f tx -l 60 -w 2
When attempting to execute the pkt-gen application. I get the following errors;

349.287845 main [2916] interface is enp14s0f0
349.287922 main [3039] using default burst size: 512
349.288169 main [3047] running on 1 cpus (have 72)
349.290782 extract_mac_range [497] extract MAC range from 00:00:00:00:00:00
349.290807 extract_mac_range [519] 00:00:00:00:00:00 starts at 0:0:0:0:0:0
349.290817 extract_mac_range [497] extract MAC range from ff:ff:ff:ff:ff:ff
349.290837 extract_mac_range [519] ff:ff:ff:ff:ff:ff starts at ff:ff:ff:ff:ff:ff
349.290846 extract_ip_range [422] extract IP range from 10.0.0.1
349.290863 extract_ip_range [478] range is 10.0.0.1:1234 to 10.0.0.1:1234
349.290869 extract_ip_range [422] extract IP range from 10.1.0.1
349.290878 extract_ip_range [478] range is 10.1.0.1:1234 to 10.1.0.1:1234
enp14s0f0: Cannot allocate memory
349.391935 main [3215] aborting

dmesg logs
=========
[2874312.442803] 349.389259 [1018] netmap_obj_malloc         netmap_ring request size 65792 too large
[2874312.443946] 349.390403 [1922] netmap_mem2_rings_create  Cannot allocate RX_ring

I have attempted to change the ring size in "/sys/module/netmap/parameters" (currently set to 4096)
but it doesnt seem to have any affect; the error message still requests 65792 size.

Does the netmap use the parameters in "/sys/module/netmap/parameters" ?
Any suggestions ?

**Comment by giuseppelettieri** [comment]
Yes, netmap uses those values, but you need to stop all netmap applications first. Moreover, the ```ring_size``` parameter is a size in bytes, not slots. Just use the value that ```dmesg``` says:
```
echo 65792 > /sys/module/netmap/parameters/ring_size
```

**Comment by Bsynamedia** [comment]
Hi Giuseppe,
I changed the ring size to 65792 then i got an error regarding  "no more netmap_ring objects"
I changed the ring_num to 1000 (orig 4)
following post #

Now the error is 
[2893250.366211] 286.042671 [1023] netmap_obj_malloc         no more netmap_buf objects
[2893250.367191] 286.043652 [1192] netmap_new_bufs           no more buffers after 4094 of 4096
[2893250.368066] 286.044527 [1947] netmap_mem2_rings_create  Cannot allocate buffers for RX_ring

looking at issue #183 I understand that netmap pre-allocates its buffers on initilization
and we can control the "ring_num", "ring_size", "buf_size", "buf_num"
But I am not understading what I need to tweak to get the sample pkt-gen to work.
i.e. how do I size my rings and buffers ?


https://github.com/luigirizzo/netmap/issues/183

**Comment by giuseppelettieri** [comment]
If your interface has _n_ combined channels (```ethtool -l```), each one with _m_ slots (```ethtool -g```), you need at least _2+2m(n+2)_ buffers (```buf_num```), i.e., one buffer for each ring (2 per channel) and the two host rings, plus two more buffers. You also need at least _2n+2_ netmap rings (```num_rings```). The problem is, netmap may be unable to preallocate from the system all the buffers you need for your configuration, especially if you have also increased the size of each buffer (```buf_size```, which you should leave at 2048). You can read the actual number of preallocated buffers in ```buf_curr_num```, which is updated the first time you try to run a netmap application following a change in ```buf_num```. If ```buf_curr_num``` doesn't give you enough buffers, you may have to use smaller rings.

**Comment by Bsynamedia** [comment]
Thanks guiseppelettieri, using that formula I was able to assign the proper number of buffers for the netmap application.
