### ISSUE TITLE
virtio_net rx NOK after 256 packets

### ISSUE THREAD

**Issue by beefke** [luigirizzo/netmap#69]
Hypervisor kernel: centos 3.10.0-123.9.3.el7
Guest kernel: same kernel (centos 7)
KVM-Qemu is used

First of all, I had to change the file virtio_netmap.h because the definition for DECR_NUM should be the void version (otherwise I had the issue like https://github.com/djwmarks/netmap/issues/55)

I made some kind of traffic generator with netmap that is running well with e1000e, ixgbe and virtio_net non-native mode. If I use the native (netmap) virtio_net mode, the first 256 rx packets (this is not an exact number, could be 255 or 257) are ok, but after that I have the impression that NETMAP_BUF is returning the wrong pointer. 256 is also the number of slots in the rx ring.

A few example packets:

sent (ok)

2015-08-04 16:28:59.830225 - sending data packet with len 128
00 00 00 00 00 00 00 00 00 00 01 00 00 02 01 01 01 04 00 02 04 00 00 02 de ac 72 0e 03 00 00 00 00 00 d2 12 01 01 00 04 00 08 22 4a 31 5b 81 00 a0 01 81 00 00 01 86 dd 60 00 03 ab 00 20 06 40 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 c3 14 01 bb a8 ae 66 e5 7b 35 92 c2 80 10 21 0a 60 8f 00 00 01 01 08 0a 00 08 25 aa 91 a4 e5 9a 

2015-08-04 16:28:59.830715 - sending data packet with len 128
00 00 00 00 00 00 00 00 00 00 01 00 00 02 01 01 01 04 00 02 04 00 00 02 de ac 72 0e 03 00 00 00 00 00 d2 12 01 01 00 04 00 08 22 4a 31 5b 81 00 a0 01 81 00 00 01 86 dd 60 00 03 ac 00 20 06 40 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 a1 77 01 bb c3 81 c7 41 59 a1 13 6d 80 10 20 dc 2c e8 00 00 01 01 08 0a 00 08 25 ad 90 34 62 34 

2015-08-04 16:28:59.831184 - sending data packet with len 593
00 00 00 00 00 00 00 00 00 00 01 00 00 02 01 01 01 04 00 02 04 00 00 02 de ac 72 0e 03 00 00 00 00 00 d2 12 01 01 00 04 00 08 22 4a 31 5b 81 00 a0 01 81 00 00 01 86 dd 60 00 03 ad 01 f1 06 40 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 c3 14 01 bb a8 ae 66 e5 7b 35 92 c2 80 18 21 0a 7e 59 00 00 01 01 08 0a 00 08 25 d0 91 a4 e5 9a 17 03 01 01 cc d5 f3 3b 78 bc 05 8f b7 c2 3e 66 8f 38 99 ff 61 4b 64 c3 90 66 49 b1 95 ce 6a 4b 06 b3 ea 28 b8 d3 6c 4c fc 1c 83 1a d1 29 88 4f 6a f6 2f 39 09 7e 48 3a 9c cd b4 82 f9 b1 47 a8 78 df 55 fc 0b 74 bf b4 c5 9c d0 71 66 23 19 ee bd ed d0 fc b2 a7 b5 0e b3 28 02 98 90 90 3a ef b4 9b ad 68 3c 9a ee c6 12 a7 c4 e7 f0 88 2c 40 fa a8 7c af 83 f3 45 ee 14 e5 35 46 58 c4 c9 16 a7 52 ff aa af 29 b5 1e 06 d0 61 be 7e 91 35 bc d5 09 6c 8b 31 8c 81 be d8 2b 9e 5a a8 43 c8 d1 ee 63 b0 12 21 09 bf e1 7e d7 dc 5c 8a 99 ca f7 c0 87 41 86 5f 55 e8 16 69 de 74 c8 f6 1c 92 18 6c f0 ef 8e 05 52 d5 4a d0 89 7d f0 8e f3 0f ba 49 00 31 1b a9 45 0a 4b f8 da 99 67 c9 6e 12 1c d7 2b 52 ba 8f a1 10 81 1b 88 9c fd 05 ad cb 4d 7d 17 5c 08 e3 e3 a7 91 a4 a2 bd 69 8d c8 0f 03 2a 01 66 9f ab 18 16 af 05 db 45 04 72 97 f8 28 23 92 14 81 5d 30 65 34 ef 2e e7 02 1b 89 74 17 58 b9 1e f7 b6 3e 89 6e ae 8d 9c bd 43 cf 59 90 5e 35 cf a4 4f 7c f1 05 51 1d df 8f d0 9c 39 a2 d0 16 ac ee 87 2e 7a 3b 09 2c 91 cb 99 42 f3 3c fb 00 39 59 b7 a5 55 7b 3b af c7 a8 f0 ee bb a2 13 aa 18 1e a5 36 ad 4b c4 ce c8 76 9f fa f5 94 fd b6 be 28 82 e1 16 20 dc 04 aa 01 c9 c3 8e 2b 1d 5b d6 3e 77 60 64 69 f4 95 ee 29 04 c6 48 e3 e4 f1 4a 71 48 d5 29 01 9d ab 0b 40 16 ef 24 9c 79 04 c7 2c 71 3a 91 f1 92 f0 83 46 0f f7 23 fa fc 88 38 bf c6 bb 34 3c 98 3c 85 7e 6f 0e 6a 46 be 5e dc 18 6c c9 38 46 8a 2c 9f 59 8f 88 22 50 38 

received (nok)

00 00 00 00 00 00 00 00 00 00 01 00 00 02 05 00 00 02 00 02 01 01 01 05 de ac 73 0e 03 00 00 00 00 00 fa ac 66 69 20 02 d2 12 01 01 00 05 81 00 00 0a 86 dd 60 00 03 ab 00 20 06 3f 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 c3 14 01 bb a8 ae 66 e5 7b 35 92 c2 80 10 21 0a 60 8f 00 00 01 01 08 0a 00 08 25 aa 91 a4 e5 9a 
=>packet 1 is ok

00 00 00 00 00 00 00 00 00 00 01 00 00 02 05 00 00 02 00 02 01 01 01 05 de ac 73 0e 03 00 00 00 00 00 fa ac 66 69 20 02 d2 12 01 01 00 05 81 00 00 0a 86 dd 60 00 03 ac 00 20 06 3f 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 a1 77 01 bb c3 81 c7 41 59 a1 13 6d 80 10 20 dc 2c e8 00 00 01 01 08 0a 00 08 25 ad 90 34 62 34 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
=>packet 2:This one take the length of the next packet??

00 00 00 00 00 00 00 00 00 00 01 00 00 02 05 00 00 02 00 02 01 01 01 05 de ac 73 0e 03 00 00 00 00 00 fa ac 66 69 20 02 d2 12 01 01 00 05 81 00 00 0a 86 dd 60 00 02 d5 01 f1 06 3f 20 01 ca fe 00 00 00 00 00 00 00 00 00 00 00 01 2a 00 14 50 40 0c 0c 09 00 00 00 00 00 00 00 71 a1 77 01 bb c3 81 b9 e6 59 a0 4a e2 80 18 20 dc 51 61 00 00 01 01 08 0a 00 08 25 77 90 34 5f f1 17 03 01 01 cc 02 b2 02 d3 b7 b7 81 65 c6 50 95 04 e4 9d ae aa 1f db 55 12 a5 ac 8c c7 10 ff d3 98 d6 86 13 db 5c aa c4 31 dc 10 71 7c 67 72 81 73 09 56 bf 5f a9 90 b9 f1 40 ca 19 55 f4 e9 6d 3c cc 7a e5 e2 a3 87 22 71 a9 79 ef 79 c5 87 87 58 3a 60 ab 4a 58 b2 ef 22 3d 32 3f 0a cd 49 32 93 e4 36 ca 8c 8f b1 ce f8 f0 5c 3f 4c 48 61 f1 a3 30 69 06 de 75 f9 b9 73 98 7f 79 9f 73 37 3d 40 ea e8 53 f1 56 f8 cb f1 30 8a ee 1f 82 a1 90 a8 4a 96 ac fc e8 42 6c 2a 1a 25 0e be 5a d8 84 c7 03 ce 91 9a 9b 52 b3 17 5d 58 4e 0d 40 93 ac de 59 ff 2f 1a 5b bb f8 f9 da a9 ec 5f 77 3b 88 fc 29 e0 dd 01 1b 76 d3 dc 55 23 52 87 be 4c c1 be e9 4d e3 12 e3 03 e8 7d ab b8 6b da da f6 81 c0 cc 3a 7a 77 ba 38 52 25 76 4f ee 52 ed ef 4f 2f 89 e8 08 09 6b a3 99 e4 39 be 36 29 70 c1 90 92 28 e5 de 36 f9 34 bb f4 2b 5d 20 a7 63 80 a0 ae ef c8 80 8c bb d1 d4 da 0f 9e 00 a0 53 6c da cf df c2 29 7c 25 29 7e 16 46 1c 64 7c 7d 21 d3 9d 4b 74 20 04 01 13 7c 02 f0 00 0c 1e 9a 73 ac 23 f6 bb 8c f4 c3 07 f6 91 6b fe c6 5f b1 6c fb 82 79 f9 8c 3c 82 d1 7b 62 8f c3 7d 4f 38 be 81 d2 1f 60 97 17 a6 cd 6c db b6 9d 24 6d 19 9e 0a 80 ac 40 3e 16 f0 61 51 37 ca c2 d5 f7 b1 6d 09 
=> packet 3: this is a completely wrong packet (one of the previous packet that arrived 3 seconds ago)

dmesg output:

[  239.461267] device eth2 entered promiscuous mode
[  239.461899] 533.019319 [ 512] virtio_netmap_config      virtio config txq=1, txd=256 rxq=1, rxd=256
[  239.545117] 533.102535 [ 512] virtio_netmap_config      virtio config txq=1, txd=256 rxq=1, rxd=256
[  239.545978] 533.103399 [ 183] virtio_netmap_free_rx_unused_bufs [1] freed 256 rx unused bufs on queue 0
[  239.546696] 533.104117 [ 488] virtio_netmap_init_buffers added 255 inbufs on queue 0
[  239.547253] 533.104674 [1750] netmap_ioctl              requested 1000000 extra buffers
[  239.547819] 533.105240 [ 509] netmap_extra_alloc        allocate buffer 1026 -> 0
[  239.548348] 533.105769 [ 509] netmap_extra_alloc        allocate buffer 1027 -> 1026
[  239.548887] 533.106308 [ 509] netmap_extra_alloc        allocate buffer 1028 -> 1027
[  239.549445] 533.106866 [ 509] netmap_extra_alloc        allocate buffer 1029 -> 1028
[  239.550046] 533.107467 [ 509] netmap_extra_alloc        allocate buffer 1030 -> 1029
[  239.555722] 533.113142 [ 391] netmap_obj_malloc         no more netmap_buf objects
[  239.556306] 533.113727 [ 505] netmap_extra_alloc        no more buffers after 261118 of 1000000
[  239.556914] 533.114335 [1753] netmap_ioctl              got 261118 extra buffers
[  239.574171] 533.131591 [ 512] virtio_netmap_config      virtio config txq=1, txd=256 rxq=1, rxd=256
[  239.574819] 533.132240 [ 512] virtio_netmap_config      virtio config txq=1, txd=256 rxq=1, rxd=256
[  322.261995] 615.819412 [ 183] virtio_netmap_free_rx_unused_bufs [0] freed 255 rx unused bufs on queue 0
[  322.263100] 615.820521 [ 526] netmap_extra_free         freeing the extra list
[  322.280653] 615.838073 [ 537] netmap_extra_free         freed 261118 buffers

**Comment by vmaffione** [comment]
Hi, can you please try it again now? A lot of fixes have recently gone in virtio-net netmap support.
