### ISSUE TITLE
Netmap Application Design

### ISSUE THREAD

**Issue by Bsynamedia** [luigirizzo/netmap#695]
Hi
I am new to netmap; I am trying to understand how I would structure my application; I have a couple of questions; 
Overview I would like to design a system that has multiple applications each recieving different multicast streams (each application may need to recieve possible more that one multicast stream) on the same ethernet/NIC interface)

1) As I understand when you open (nm_open netmap:eth0) an netmap inteface it disconnects it from the host;
in the default mode it opens all TX and RX rings associated with the ethernet/NIC;
How does the application know which RX ring/s will be used ? 
Will the NIC put the data on multiple Rx rings if it runs out of slots on the initial ring it is using ?

2) If each application opens up multiple netmap interfaces (nm_open netmap:eth0-N) each one binding to a specific ring pair (N) how do you then bind a specific multicast traffic to its specific rx ring ?

3) would one need to have a separate application to open up the interface/NIC in netmap mode
and act as a de-muxer to request for the incoming data to its Rx ring/s and then forward it to the other applications ?
I assume the other applications would be in netmap mode binded to different Rx rings on the same ethernet/NIC ?

4) If the same input multicast stream was need by multiple applications then the duplication of the data would need to be managed by the "de-muxer" application ?

Thanks
Brian

**Comment by jhk098** [comment]
> Hi
> I am new to netmap; I am trying to understand how I would structure my application; I have a couple of questions;
> Overview I would like to design a system that has multiple applications each recieving different multicast streams (each application may need to recieve possible more that one multicast stream) on the same ethernet/NIC interface)
> 
>     1. As I understand when you open (nm_open netmap:eth0) an netmap inteface it disconnects it from the host;
>        in the default mode it opens all TX and RX rings associated with the ethernet/NIC;
Yes.
>        How does the application know which RX ring/s will be used ?
>        Will the NIC put the data on multiple Rx rings if it runs out of slots on the initial ring it is using ?
This is not how things work. Netmap has no control on how received packets are mapped to the RX rings. It's up to the NIC receive hardware to decide which packets go to which RX ring. If a RX ring has no available slots, the NIC won't normally use the another one, but simply drop the packets. Normally, packets belonging to the same TCP or UDP flow will go to the same RX ring.
Depending on the specific NIC, you may be able to have some control on how to map RX packets to RX rings, e.g. using `ethtool` on Linux. You may look at Intel Flow Director, as an example.
> 
>     2. If each application opens up multiple netmap interfaces (nm_open netmap:eth0-N) each one binding to a specific ring pair (N) how do you then bind a specific multicast traffic to its specific rx ring ?
See above, you need hardware support for this, and it's something outside of netmap scope.
Netmap comes into play after the NIC has pushed the received buffers to the RX rings, to consume them.
> 
>     3. would one need to have a separate application to open up the interface/NIC in netmap mode
>        and act as a de-muxer to request for the incoming data to its Rx ring/s and then forward it to the other applications ?
>        I assume the other applications would be in netmap mode binded to different Rx rings on the same ethernet/NIC ?
> 
>     4. If the same input multicast stream was need by multiple applications then the duplication of the data would need to be managed by the "de-muxer" application ?
> 
> 
> Thanks
> Brian
