### ISSUE TITLE
What does netmap do to NICs on same host.

### ISSUE THREAD

**Issue by WqyJh** [luigirizzo/netmap#696]
I have two NICs on my host, both of which are Internal Network Interface of Virtualbox.
```bash
6: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:9b:cc:2b brd ff:ff:ff:ff:ff:ff
    inet 192.168.55.6/24 brd 192.168.55.255 scope global enp0s8
       valid_lft forever preferred_lft forever
7: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:6a:c7:f9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.55.8/24 brd 192.168.55.255 scope global enp0s9
       valid_lft forever preferred_lft forever
```
I used `pkt-gen` to send packets from enp0s8 and received packets from enp0s9, which works well. 
```bash
# rx
sudo pkt-gen -i enp0s8 -f rx
# tx
sudo pkt-gen -i enp0s9 -f tx -n 500111222 -l 60 -w 5
```
But when I tried to send packets from enp0s8 using `tcpreplay` and receive packets from enp0s9 using `tcpdump`, it's not worked.
```bash
# rx
sudo tcpdump -i enp0s9
# tx
sudo tcpreplay -i enp0s8 a.pcap
```
The latter one is as expected, while the `pkt-gen` is out of my expectation. It's weired that sending packets from one interface and receiving them from another interface.

So what's going on? Does netmap somehow make the two interfaces connected?

**Comment by gravity64** [comment]
I think that those `enp0s8` and `enp0s9` are attached to the same virtual switch/bridge, and since pkt-gen transmits broadcast packets (dst mac = `0xffffffffffff`), then you get on `enp0s9` what you transmitted on `enp0s8`.
The same is not true for tcpreplay, I guess, because it does not use broadcast.

**Comment by WqyJh** [comment]
Thank you! I think you are right.
