### ISSUE TITLE
Netmap.ko netmap_lin.ko is missing

### ISSUE THREAD

**Issue by najamsaleem** [luigirizzo/netmap#699]
Hi,

I am trying to install netmap in debian and i got problem in loading netmap.

By typing this command 
'sudo insmod ./netmap.ko'

i got error 
'insmod: ERROR: could not insert module ./netmap.ko: File exists'

**Comment by giuseppelettieri** [comment]
Have you any previous netmap module already loaded? If yes, remove it first: ```rmmod netmap``` (you may also need to remove any netmap driver first)

**Comment by najamsaleem** [comment]
yes this solved but 'sudo insmod ./netmap_lin.ko' is showing same error'
and this one also
'sudo insmod ./ixgbe/ixgbe.ko'
'insmod: ERROR: could not load module ./ixgbe/ixgbe.ko: No such file or directory
'

plus i am getting this error when running tcpreplay with netmap 

$ sudo tcpreplay -i  enp1s0f1 -t --netmap both.pcap

/usr/local/bin/tcpreplay: illegal option -- netmap
tcpreplay (tcpreplay) - Replay network traffic stored in pcap files
Usage:  tcpreplay [ -<flag> [<val>] | --<name>[{=| }<val>] ]... <pcap_file(s)>

   -q, --quiet                Quiet mode
   -T, --timer=str            Select packet timing mode: select, ioport, gtod, nano
       --maxsleep=num         Sleep for no more then X milliseconds between packets
   -K, --preload-pcap         Preloads packets into RAM before sending
   -c, --cachefile=str        Split traffic via a tcpprep cache file
   -2, --dualfile             Replay two files at a time from a network tap
   -i, --intf1=str            Client to server/RX/primary traffic output interface
   -I, --intf2=str            Server to client/TX/secondary traffic output interface
       --listnics             List available network interfaces and exit
   -l, --loop=num             Loop through the capture file X times
       --loopdelay-ms=num     Delay between loops in milliseconds
       --pktlen               Override the snaplen and use the actual packet len
   -L, --limit=num            Limit the number of packets to send
       --duration=num         Limit the number of seconds to send
   -x, --multiplier=str       Modify replay speed to a given multiple
   -p, --pps=str              Replay packets at a given packets/sec
   -M, --mbps=str             Replay packets at a given Mbps
   -t, --topspeed             Replay packets as fast as possible
   -o, --oneatatime           Replay one packet at a time for each user input
       --pps-multi=num        Number of packets to send for each time interval
       --unique-ip            Modify IP addresses each loop iteration to generate unique flows
       --unique-ip-loops=str  Number of times to loop before assigning new unique ip
       --no-flow-stats        Suppress printing and tracking flow count, rates and expirations
       --flow-expiry=num      Number of inactive seconds before a flow is considered expired
   -P, --pid                  Print the PID of tcpreplay at startup
       --stats=num            Print statistics every X seconds, or every loop if '0'
   -V, --version              Print version information
   -h, --less-help            Display less usage information and exit
   -H, --help                 display extended usage information and exit
   -!, --more-help            extended usage information passed thru pager
       --save-opts[=arg]      save the option state to a config file
       --load-opts=str        load options from a config file

Options are specified by doubled hyphens and their name or by a single
hyphen and the flag character.
tcpreplay is a tool for replaying network traffic from files saved with
tcpdump or other tools which write pcap(3) files.

Please send bug reports to:  <tcpreplay-users@lists.sourceforge.net>

**Comment by giuseppelettieri** [comment]
Not sure what you are trying to do. ```netmap_lin.ko``` is the (very) old name of the netmap module. Please follow the instructions in ```README.md```.

**Comment by najamsaleem** [comment]
I want to use netmap in tcpreplay to speed up process but this commad is not working.

sudo tcpreplay -i eth0 -t --loop 500 --netmap smallFlows.pcap

this commad is not working

**Comment by najamsaleem** [comment]
Thanks for replying, problem is solved. Seems like netmap.ko file was present in LINUX folder of netmap.

remember to use tcpreplay with netmap we have to write these commands 
'./configure' 'make' and then 'sudo make install'
 first in netmap LINUX folder then in tcpreplay directory.

Problem was to 'sudo insmod netmap.ko' run this command but showing error in tcpreplay directory because this file was presnet in kernel directory.

Thanks solved
