### ISSUE TITLE
Jumbo frame support for i40e

### ISSUE THREAD

**Issue by luxl** [luigirizzo/netmap#701]
Hi,
I'm investigating if jumbo frame is supported by netmap with i40e. 
I checked [#466](https://github.com/luigirizzo/netmap/issues/466), which says only ixgbe is supported.
Will it work if set buf_size = MTU?
Currently I have no i40e device but going to buy one. What if doesn't support, any solutions if I insist using i40e?

**Comment by giuseppelettieri** [comment]
yes, jumbo frames are supported on i40e.
