### ISSUE TITLE
kernel crash - FreeBSD 12.1 - vtnet

### ISSUE THREAD

**Issue by muratbalaban43** [luigirizzo/netmap#706]
While the traffic is flowing, if you close a netmap application, this results in a kernel panic. 

Steps to reproduce:

On the GW:
1. run bridge application with host rings: (all hw offloadings disabled)

`bridge -i netmap:vtnet0 -i netmap:vtnet0^`

2. scp a big file from another device 

`scp biggie.iso gw:`

3. While the traffic is flowing, try to close / re-open bridge application.

Crash dump file attached. 

[textdump.tar.vtnet_trunk.gz](https://github.com/luigirizzo/netmap/files/4773635/textdump.tar.vtnet_trunk.gz)
[textdump.tar.vtnet_trunk_and_vlan.gz](https://github.com/luigirizzo/netmap/files/4773637/textdump.tar.vtnet_trunk_and_vlan.gz)

**Comment by giuseppelettieri** [comment]
@vmaffione  has recently fixed a bug in vtnet (commit r362183 in FreeBSD-CURRENT) that may be related to this crash. It will land in 12-stable in about a week.

**Comment by muratbalaban43** [comment]
That's great to hear. @vmaffione , any chances that you can get this patch committed also?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236584

This is related to vlan(4) and em(4) not working with netmap(4).

**Comment by muratbalaban43** [comment]
@giuseppelettieri , @vmaffione fyi: we were able to test this vtnet crash on several systems. Looks like it does fix the crash problem. Thanks.
