### ISSUE TITLE
pkt-gen reports 1.309 Tbps speed

### ISSUE THREAD

**Issue by SteveElp** [luigirizzo/netmap#709]
I'm a uni prof and programmed netmap bindings for the Julia programming language with a student. Now I'm running different benchmarks.

I'm not sure that 1.309 Tbps is correct for a netmap pipe.

BENCH:
sudo pkt-gen -i netmap:pipe}0 -f rx -p 1
sudo pkt-gen -i netmap:pipe{0 -f tx -l 2048 -p 1

RESULT:
556.904538 main_thread [2661] 80.119 Mpps (80.203 Mpkts 1.313 Tbps in 1001040 usec) 511.50 avg_batch 1 min_space			    
Sent 989478415 packets 2026451793920 bytes 1934463 events 2048 bytes each in 12.38 seconds.
			    
#Speed: 79.905 Mpps Bandwidth: 1.309 Tbps (raw 1.309 Tbps). Average batch: 511.50 pkts

CPU is AMD 3700x.

Is the pkt-gen Bandwith of 1.309 Tbps (as reported) correct?

Thank you very much!

**Comment by giuseppelettieri** [comment]
Well, pipes share memory and just switch packet pointers between them without actually moving data, so it is possible.
