### ISSUE TITLE
Compile Error on Debian 8

### ISSUE THREAD

**Issue by hwnahm** [luigirizzo/netmap#71]
CC [M]  /usr/src/netmap/LINUX/netmap_linux.o
/usr/src/netmap/LINUX/netmap_linux.c: In function ‘linux_netmap_init’:
/usr/src/netmap/LINUX/netmap_linux.c:2029:2: error: implicit declaration of function ‘nm_os_pt_memdev_init’ [-Werror=implicit-function-declaration]
  return nm_os_pt_memdev_init();
  ^
/usr/src/netmap/LINUX/netmap_linux.c: In function ‘linux_netmap_fini’:
/usr/src/netmap/LINUX/netmap_linux.c:2035:9: error: implicit declaration of function ‘nm_os_pt_memdev_uninit’ [-Werror=implicit-function-declaration]
         nm_os_pt_memdev_uninit();
         ^
cc1: some warnings being treated as errors
/usr/src/netmap/LINUX/Kbuild:31: recipe for target '/usr/src/netmap/LINUX/netmap_linux.o' failed
make[4]: *** [/usr/src/netmap/LINUX/netmap_linux.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/Makefile:1350: recipe for target '_module_/usr/src/netmap/LINUX' failed
make[3]: *** [_module_/usr/src/netmap/LINUX] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
netmap.mak:52: recipe for target 'all' failed
make: *** [all] Error 2
root@debian:/usr/src/netmap/LINUX#

**Comment by giuseppelettieri** [comment]
It should be fixed by the commit I just posted. May you confirm, please?

**Comment by hwnahm** [comment]
It's fixed. Thanks.
