### ISSUE TITLE
Problems compiling libnetmap on FreeBSD-12.1/STABLE and 12.1/RELEASE

### ISSUE THREAD

**Issue by bmeeks8** [luigirizzo/netmap#717]
I am attempting to use the new libnetmap library in a derivation of the Snort DAQ package that supports host rings with netmap. The library fails to compile on FreeBSD-12.1 installations due to a recent (May 2020) commit to _sys/net/netmap.h_ that has not made it into FreeBSD-12.1 yet. That commit added the `nmreq_opt_offsets` structure to _netmap.h_. This structure is referenced in _libnetmap/nmport.c_.

Here are a few questions stemming from the above issue.

1. When will the updated _sys/net/netmap.h_ be available in FreeBSD-12.1/STABLE and RELEASE?

2. Why was the `nm_open()` API deprecated? Why can't the option for multiple host rings be added there? I have current code in DAQ that uses this netmap API, but it can't access the new multiple host rings functionality. That's why I was trying to use the new libnetmap API.

3. Could you outline the minimum steps required to establish a netmap pathway between a physical NIC and the host using multiple host rings? This is to create an inline IPS mode of operation on a firewall device. This will be a dedicated one-off setup, so it does not need to support all of the potential options that a general-purpose netmap program might require. Can that narrowing of scope eliminate some of the extra steps I see in the new CTRL API utilities?

4. And last question, are there advantages to using the new multiple host rings configuration in single-threaded applications such as Snort's DAQ module running in netmap mode? Or is the current single pair of host rings exposed in the older `nm_open()` API as good as it gets for single-threaded apps?

Thanks!

**Comment by giuseppelettieri** [comment]
1.  Libnetmap is being imported into FreeBSD 12-stable, see  [here](https://reviews.freebsd.org/D26171). I am not sure about the timing, though.
2. It was a mess.
3. I am not sure how familiar you are with the lower level API, i.e., below ```nm_open()```. In general you need to open ```/dev/netmap```, issue an ```ioctl()``` to register a port, then ```mmap()``` and get access to the rings and buffers. I'll stop before the ```mmap()``` part, since nothing is changed from that point on. To create the desired number of host rings you need to initialize the ```nr_num_host_tx_rings``` and ```nr_num_host_rx_rings``` fields of the ```netmap_register``` structure:

```
    struct netmap_header hdr;
    struct netmap_register reg;

    /* initialize the hdr */
    memset(&hdr, 0, sizeof(hdr));
    hdr.nr_version = NETMAP_API;
    /* fill the hdr.nr_name with the name of the port. Just the interface name
     * (without the netmap: prefix) or a valeXXX:YYY name, possibly followed
     * by either { or } and a pipe name. No options and or flags are allowed.
     */
    snprintf(hdr.nr_name, ...); /* or whatever */
    hdr.nr_reqtype = NETMAP_REQ_REGISTER;
    hdr.nr_body = (uintptr_t)&reg;

    /* initialize the reg */
    memset(&reg, 0, sizeof(reg));
    /* fill in the number of host rings. 
     * Note: this will have no effect if the port is already open */
    reg.nr_num_host_tx_rings = ....;
    reg.nr_num_host_rx_rings = ....;
```
You now have several options for ```nr_mode```, depending on the subset of rings that you want to open (all hw and host, all hw, all host, only one hw pair, only one host pair). See the ```NR_REG_*``` constants in ```netmap.h```. In case you want only one ring pair (either hw or host), you also need to set the ```nr_ringid``` field. You can also set the ```NR_TX_RINGS_ONLY``` or ```NR_RX_RINGS_ONLY``` flags in the ```nr_flags``` field to restrict the ring selection to only one direction. E.g., to open only the third host tx ring:
```
     reg.nr_mode = NR_REG_ONE_SW;
     reg.nr_ringid = 2; /* 0-based ring number */
     reg.nr_flags = NR_TX_RINGS_ONLY;

     fd = open("/dev/netmap");
     ioctl(fd, NIOCCTL, &hdr);
```
4.  I don't think there is any advantage in having more than one host ring, other than trying to increase the throughput by running on several cores.

**Comment by bmeeks8** [comment]
Thank you for the quick and detailed reply. This helps me out. I maintain the Snort and Suricata packages for the pfSense firewall distro. Using the host rings is the method chosen for the pfSense setup because we want to do IPS between the NIC and the host stack. For Suricata, I am using the code from upstream unchanged. However, for Snort, since it uses its own DAQ (data acquistion) library, I had to make some customizations in the netmap code within DAQ as it currently only supports physical NIC rings and no host rings. I initially made those customizations using `netmap_user.h` and `nm_open()` API.

So one more question if I may. On the initial request to open a netmap port, will the system return to me the number of host rings available for the port, or do I need specify how many I want? And if I have to specify the number I want, how do I know how many are available?

Thanks!

**Comment by giuseppelettieri** [comment]
Host rings are entirely software and their number is up to you. There is no point in querying the system for their number, as you would simply get the default value (one per direction).

That said, it may be a good idea to have as many host rings as there are hardware ones, so you should query the system for the latter number, instead. You can get the number of hardware rings via Linux APIs, of course, but also via netmap using the ```NETMAP_REQ_PORT_INFO_GET``` request.

**Comment by bmeeks8** [comment]
Ah...thank you for that insight. I was not sure how, if at all, the hardware NIC side of things played into the host rings scenario. Meaning I was not sure if the internal netmap code would match up Host rings with HW rings when a port was opened with Host rings and automatically supply that number of Host rings.

I will indeed use your insight and query the system for the supported number of HW rings and then make a request for a matching number of Host rings.

Thank you again for your patience answering my questions.
Bill
