### ISSUE TITLE
lost python bindings

### ISSUE THREAD

**Issue by sanyacomua** [luigirizzo/netmap#72]
https://code.google.com/p/netmap/ redirects to github now, but on github there are no files in private/extra/python/

**Comment by giuseppelettieri** [comment]
We have temporarily removed them, since there is no maintainer for now. Anyway, they have not changed in a bit, so you may have luck by just using the files from some old version.

**Comment by emctoo** [comment]
@giuseppelettieri Maybe you should consider bring it back, at least people are interested in it. Language binding is good thing, should encourage.

**Comment by vmaffione** [comment]
Bringing back Python bindings is in the plan, and it will happen as soon as possible.

**Comment by vmaffione** [comment]
https://github.com/luigirizzo/netmap/tree/master/extra/python

**Comment by emctoo** [comment]
@vmaffione Great job!
