### ISSUE TITLE
# Netmap can run on virtual machine vnware workstation or not?

### ISSUE THREAD

**Issue by laulpt** [luigirizzo/netmap#74]
Hello luigirizzo,

I am using netmap support for tcpreplay tool to replay packets with high rate.
I used VM ware workstation to run ubuntu 14.04.2 i386 as virtual machine.
Linux kernel version: 3.19.5
Does netmap supports for VN ware workstation virutal machine?
Thank you so much!
Tuong
But I got a problem as following:
#
tuong@ubuntu:~/work$ sudo tcpreplay -i eth0 -t -K --netmap smallFlows.pcap 
Switching network driver for eth0 to netmap bypass mode... Warning: ioctl error -1 35142:31
failed!
Switching network driver for eth0 to normal mode... 
Fatal Error: failed to open device eth0: nm_do_ioctl: Operation not supported
#

**Comment by gureedo** [comment]
Netmap works fine on VMWare workstation with Linux.
Are you shure you have installed netmap drivers properly?
Can you provide more information of loaded drivers and it versions?
