### ISSUE TITLE
How to handle packet drop from RX queue due to latency in reading the packets from the queue

### ISSUE THREAD

**Issue by dnwick** [luigirizzo/netmap#743]
Hi,

Currently I have written a client and server program to read a file like we do in ftp via netmap. In my client side as soon as packets are received from rx queue, I do a file write with those data. when the file is 200mb or bigger i have seen a packet drop. I believe this is because it is taking time to write to a file and that causes a rx queue to filled up and it's dropping the packets to get the new packets in. I believe that is the reason because if I do a simple packet count and print it, it will print the correct packet count. 
To mitigate this I tried enabling flow control in my network drivers in both machines but I could not hence I'm trying to find a different way to handle this on my own using the netmap api. 
Is there a way to identify from netmap API side whether rx queue is about to drop packets ? or is it using nm_ring_space is the only way ? My plan is it to send some kind of pause packet to server so that it will stop sending packets till rx queue is free for some extend. Is there a better approach to handle this ? I even tried putting the receiving packets directly to a buffer without doing the file write with same thread but I still see packet drops. 
Any help would be appreciated.

**Comment by jhk098** [comment]
Yes, you basically need to reimplement flow control like in TCP. There is no special trick already in place.

**Comment by dnwick** [comment]
Thanks for your reply
