### ISSUE TITLE
How to determine the flow direction after receiving traffic from the interface

### ISSUE THREAD

**Issue by xiaojin2630** [luigirizzo/netmap#745]
I use `nm_open("netmap:eth5/r", ...)`, I can receive traffic into eth5
I use `nm_open("netmap:eth5/t", ...)`, I can receive traffic from eth5

But I only use `nm_open("netmap:eth5", ...)` now, how can I judge the direction of the received traffic? This is very important to me.

**Comment by giuseppelettieri** [comment]
You are perfectly right, there was an idea to set a flag in the slots according to the direction of the captured traffic, but its not implemented in the current code. In the meantime, you can probably open both ```/r``` and ```/t``` and poll the two file descriptors.

**Comment by xiaojin2630** [comment]
Thanks for the reply, 
I still expect what you said to be implemented directly in the code.
If you plan to implement it later, what is the approximate time for this

**Comment by giuseppelettieri** [comment]
Hi, may you please try the latest commit? monitors should now set the new NS_TXMON flag in the slot->flags for packets captured in the tx direction.

**Comment by xiaojin2630** [comment]
Thank you very much. I will take the time to test and let you know when I have the latest results.

**Comment by xiaojin2630** [comment]
I tested it with commit (f621df211), and it did have NS_TXMON. By using this flag, I clarified the direction of traffic. Works fine.

I did this:

$ vale-ctl -a vale0:ethX
`
nm_open("netmap:ethX/tr", ...);
`
