### ISSUE TITLE
Can't build virtio_net.c on Ubuntu 20.04

### ISSUE THREAD

**Issue by rperper** [luigirizzo/netmap#751]
When attempting to build virtio_net.c on Ubuntu 20.04 I get the attached build errors.  Any help would be appreciated.
Thanks,

Bob Perper
rperper@litespeedtech.com

[config (1).log](https://github.com/luigirizzo/netmap/files/5838584/config.1.log)

**Comment by giuseppelettieri** [comment]
Hi, may you please try the latest master?

**Comment by rperper** [comment]
I'm testing it on an Ubuntu 20.10 system with the 10.5 kernel and it works great!  I'll keep you apprised but the speeds are terrific and we couldn't be happier!

I'll close the ticket in a day or two if things continue the really good way they have been so far.

Bob Perper
rperper@litespeedtech.com
