### ISSUE TITLE
Debian 10 - Compiling Issues (Invalid Module Format Netmap.Ko)

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#756]
Hi, guys.

I've prepared the build environment and got the following configure result (based in my adjustments):

--

root@MGX-01:/netmap-master# ./configure --kernel-dir=/usr/src/linux-source-4.19 --no-apps --drivers=ixgbe --disable-vale --disable-pipe --disable-monitor --disable-generic --disable-ptnetmap

*** We are trying to download the original sources for driver
*** ixgbe using the following command:

***   test -e /netmap-master/LINUX/ext-drivers/ixgbe-5.7.1.tar.gz || wget https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.7.1/ixgbe-5.7.1.tar.gz -P /netmap-master/LINUX/ext-drivers/

*** If this fails, please download the above file and put it
*** in /netmap-master/LINUX/ext-drivers/, then run configure again.

*** Running some preliminary tests to customize the build enviroment.

*** Now running compile tests to adapt the code to your
*** kernel version. Please wait.

kernel directory            /usr/src/linux-source-4.19
kernel sources              /usr/src/linux-source-4.19
linux version               413ab  [4.19.171]
module file                 netmap.ko

subsystems                  null
apps                        
native drivers              ixgbe

Contents of the drivers.mak file:
ixgbe@conf := CONFIG_IXGBE
ixgbe@src := tar xf /netmap-master/LINUX/ext-drivers/ixgbe-5.7.1.tar.gz && ln -s ixgbe-5.7.1/src ixgbe
ixgbe@patch := patches/intel--ixgbe--5.7.1

--

Until this part, everything is OK.

The compilation time, is also OK, no problems with this.

However, when I try to load the netmap module, this is what happens:

--

root@MGX-01:/netmap-master# insmod netmap.ko
insmod: ERROR: could not insert module netmap.ko: Invalid module format

--

What could be the cause for this ?

**Comment by giuseppelettieri** [comment]
Is there any relevant message in the kernel logs?

**Comment by Fr3DBr** [comment]
Feb  2 11:36:38 MGX-01 kernel: [14603.284011] netmap: no symbol version for module_layout

**Comment by giuseppelettieri** [comment]
Are you sure you are compiling for your running kernel? Since you are using the external drivers you don't need the full kernel sources. What happens if you run ```configure``` again, but without the ```--kernel-dir``` argument?

**Comment by Fr3DBr** [comment]
Thanks for the hint/input. You're right, I was using the full sources, but the headers package, has already fixed this.
