### ISSUE TITLE
Unable to see VLAN packets from NIC to Host in bridge application with generic netmap adapter.

### ISSUE THREAD

**Issue by NAYANSEN90** [luigirizzo/netmap#761]
I am trying to run the bridge application on a VLAN parent interface and see VLAN traffic traversing through it.  I am using the generic netmap adapter on an e1000 interface.

The application starts but I only see packets being logged for the path (host --> nic). The incoming packets are not logged in the application, but the packets definitely reach the host linux stack. I am using a ping application to check the path and the ping succeeds. In case of non-VLAN traffic, I see both direction prints in the APP.

I have set the rxvlan off txvlan off  on the NIC using ethtool commands.

Reason for not using patched e1000 driver is the error with SW-IOMMU space, and netmap unable to map buffers.  

Bridge application output is :

./build-apps/bridge/bridge built Feb 13 2021 11:42:02

746.455395 main [268] same interface, endpoint 0 goes to host
746.455866 main [290] ------- zerocopy supported
746.455877 main [297] Wait 4 secs for link to come up...
750.456528 main [301] Ready to go, ens34 0x1/1 <-> ens34 0x0/1.
752.959183 main [365] poll timeout [0] ev 1 0 rx 0@0 tx 255, [1] ev 1 0 rx 0@0 tx 255
755.461828 main [365] poll timeout [0] ev 1 0 rx 0@0 tx 255, [1] ev 1 0 rx 0@0 tx 255
756.535486 main [365] poll ok [0] ev 1 1 rx 1@0 tx 255, [1] ev 1 0 rx 0@0 tx 255
756.535509 main [365] poll ok [0] ev 0 0 rx 1@0 tx 255, [1] ev 5 4 rx 0@0 tx 255
756.535516 rings_move [128] ens34:host --> ens34:nic fwd 1 packets: rxring 1 --> txring 0
757.536431 main [365] poll ok [0] ev 1 1 rx 1@0 tx 255, [1] ev 1 0 rx 0@0 tx 255
757.536455 main [365] poll ok [0] ev 0 0 rx 1@0 tx 255, [1] ev 5 4 rx 0@0 tx 255
757.536458 rings_move [128] ens34:host --> ens34:nic fwd 1 packets: rxring 1 --> txring 0
760.039070 main [365] poll timeout [0] ev 1 0 rx 0@0 tx 255, [1] ev 1 0 rx 0@0 tx 255
^C760.756048 main [365] poll timeout [0] ev 1 0 rx 0@0 tx 255, [1] ev 1 0 rx 0@0 tx 255

 I have also observed similar behaviour in vmxnet3 interface with netmap generic driver as well.

Kernel version : RHEL 7.6 3.10.0-957.el7.x86_64
Netmap code : latest github master version

Confgure script calling:
./configure --kernel-sources=/home/polaris/rpmbuild/BUILD/kernel-3.10.0-957.el7/linux-3.10.0-957.el7.x86_64/ --kernel-dir=/usr/src/kernels/3.10.0-957.el7.x86_64/ --enable-extmem --drivers=vmxnet3,virtio_net.c,igb,e1000,e1000e,ixgbe,ixgbevf,i40e,mlx5 --select-version=ixgbe:5.9.4,ixgbevf:4.9.3,e1000e:3.8.7,i40e:2.9.21,igb:5.5.2

**Comment by jhk098** [comment]
If you want to combine netmap and VLANs, you should avoid creating the virtual (child) interfaces (e.g., ens4.100), and have your netmap application strip/insert/handle the VLAN header if necessary. This is true irrespective of you using the native or emulated netmap adapter. The emulated adapter has some quirks like the one that you describe, because of how received packets are intercepted. If you used the native adapter, you would not see anything on the virtual interface.

**Comment by NAYANSEN90** [comment]
We have opened the netmap fd on the parent device itself, and plan to manipulate the packet including stripping and  inserting the vlan header as necessary. What we also want is that such a VLAN interface to be available by normal LINUX commands, where the user can specify the IP address, routes etc.  We would filter the packets received by the app and send some of the packets  to the LINUX host stack9using HOST rings) and process the rest in the application itself. The user should retain the normal ability of ping via the VLAN interface. 

Are you saying that using the generic adapter VLAN header consisting packets cannot be seen by the netmap fd? I can see them when I use a native patched driver adapter. In the case of e1000, the patched adapter had a problem with SW-IOMMU, for which we shifted to emulated adapter.  So the behaviour between emulated and native adapter are different in this regard?

**Comment by jhk098** [comment]
Yes, the behaviour is different in this regard, IIRC because the Linux RX hook (used by emulated netmap as well as other kernel subsystems) is invoked after the VLAN dispatch hook (which consumes the packet), and thus the received packet does not reach the RX hook if there is a matching VLAN interface. This is a limitation of the emulated adapter.

To bypass the SW-IOMMU problem you could use 2GB of RAM if running within a VM.

**Comment by NAYANSEN90** [comment]
Thanks, that clears the concept for me, as to how the two adapters differ.  Reducing the RAM requirement will not be an option. Lets see what else we can do which will work for us. Thanks once again.
