### ISSUE TITLE
Make Clean (Cannot Replace Driver)

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#766]
I'm facing an issue, after I clone the master repository and use ./configure, if I try to switch the driver version, it won't build/compile the new version, but instead, it will keep using the old version of the driver.

Basically, trying to clear the build, reconfigure and making again, won't work.

The only way I found to deal with this, is by cloning the repository again and starting all over, is this expected ?

**Comment by giuseppelettieri** [comment]
You should run
```
make distclean
```
before running `configure` again. If, for some reason, this does not properly remove all the previous configure files, you can ask git to clean-up everything without the need to clone the repository again:
```
git clean -fdx
```
Better still, you can acquire the habit to configure/build in a separate directory:
```
mkdir build
cd build
../configure --whatever
make
```
Now, all configure/build files will be in the `build` directory and no file will be created in the main source tree.

**Comment by Fr3DBr** [comment]
Oh, nice tips, I will try them so. :-)
