### ISSUE TITLE
Does netmap extmem feature work with POSIX shared memory?

### ISSUE THREAD

**Issue by NAYANSEN90** [luigirizzo/netmap#769]
I am trying to use the extmem feature in netmap. I have been able to use a hugepage backed file to mmap and then register the netmap adapters. It works fine.

I was trying to use posix shared memory by opening the shared memory from the userspace program using shm_open and mmap calls, and then passing the filename "/dev/shm/mynetmapmem" to the netmap using "nmport_extmem_from_file" call. 

I see the following:
[ 7912.604413] 816.714232 [1723] _netmap_mem_private_new   2_buf: adding 984926 more buffers
[ 7912.615960] 816.725780 [1191] netmap_vale_vp_create     max frame size 1514
[ 7912.615966] 816.725787 [1801] netmap_mem_private_new    req if 100*1024 ring 200*36864 buf 60000*2048
[ 7912.615978] 816.725800 [ 433] netmap_init_obj_allocator_bitmap 2_if free 100
[ 7912.615982] 816.725804 [ 433] netmap_init_obj_allocator_bitmap 2_ring free 0
[ 7912.615984] 816.725807 [ 436] netmap_init_obj_allocator_bitmap 2_ring: no objects available
[ 7912.615994] 816.725816 [ 433] netmap_init_obj_allocator_bitmap 2_if free 100
[ 7912.615997] 816.725819 [ 433] netmap_init_obj_allocator_bitmap 2_ring free 200
[ 7912.619452] 816.729272 [ 433] netmap_init_obj_allocator_bitmap 2_buf free 1044926

The ring memory seems to have been depleted. But I am trying to open a pipe in this case. 

Any ideas? Is it possible or is my fundamental idea flawed?

**Comment by giuseppelettieri** [comment]
It should work in theory. The problem you are seeing, however, is unrelated to that and you would just as likely see it with any other kind of memory. The netmap rings need contiguous physical memory that is larger than the page size, and it is hard to guarantee that from userspace. One way to do that is to use hugepages (```MAP_HUGETLB``` in ```mmap()```, for example). I don't know if you can do that with posix shared memory too.

**Comment by NAYANSEN90** [comment]
Thanks got it. Now its clear. I'll see if that is possible using POSIX shared memory. If so I'll definitely share it. Thanks once again.

**Comment by NAYANSEN90** [comment]
I

**Comment by NAYANSEN90** [comment]
So it seems there is no way to guarantee contiguous kernel memory without going deep into pagemap and trying to individually find contiguous pages. Best to use hugepage here.
