### ISSUE TITLE
Recommended Kernel / Linux Distribution

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#775]
Hi, folks.

This is not exactly an issue, but some questions, to go for the best possible path:

1) Which is the current Kernel Version / Linux Distribution, recommended for most stability in a production environment when using netmap ? Or do you actually, recommend FreeBSD itself, since netmap is part of it nowadays ?

2) Is there any specific netmap build recommended as well ?

Thanks. :)

**Comment by jhk098** [comment]
1. Linux and FreeBSD use the same codebase, and thus there should be little difference between kernel versions or Linux/FreeBSD in terms of stability.
2. No, use the master branch.

**Comment by Fr3DBr** [comment]
Ok, thanks !
