### ISSUE TITLE
linux: netmap_obj_malloc         no more netmap_if objects

### ISSUE THREAD

**Issue by JulienHoules** [luigirizzo/netmap#778]
Hello,

I use netmap with the ixgbe driver.
Everything works smoothly most of the time but the following error occurs from time to time:
"netmap_obj_malloc         no more netmap_if objects" in dmesg. The program crashes.
I use netmap on 6 interfaces. I don't remember this problem happened before.
Do you have an idea ?

Thanks,

Julien.

/sys/module/netmap/parameters/if_curr_num = 100
/sys/module/netmap/parameters/if_num = 100
/sys/module/netmap/parameters/if_curr_size = 1024
/sys/module/netmap/parameters/if_size = 1024

kernel : 3.10.0-693.17.1.el7.x86_64

**Comment by Fr3DBr** [comment]
Hi, I also have a similar issue with this as well, but in Debian 10.

**Comment by JulienHoules** [comment]
I found the problem: netmap was not properly closed at each cycle. I close the ticket.

Thanks.
