### ISSUE TITLE
Git lost changes after commits on August 10?

### ISSUE THREAD

**Issue by BombermaG** [luigirizzo/netmap#78]
Example in [examples/bridge.c#L237](https://github.com/luigirizzo/netmap/blob/master/examples/bridge.c#L237)
```C
pb = nm_open(ifb, NULL, NM_OPEN_NO_MMAP, pa);
```
It must be (after this [commit](https://github.com/luigirizzo/netmap/commit/794e1fc538ecdc687159db512d96ad0ecafa5d09)):
```C
pb = nm_open(ifb, NULL, 0, pa);
```
but it's not. 
Or I'm not understanding something?

**Comment by stefano-garzarella** [comment]
Hi BombermaG,
we recently fix this bug.

Now, if parent is specified, even if NM_OPEN_NO_MMAP is set, the nm_open() imports the memory fields from the parent, without doing mmap()

Thanks for your report.

Stefano
