### ISSUE TITLE
i40e (Linux)/ixl (FreeBSD) driver multiqueue RX issues

### ISSUE THREAD

**Issue by ported-pw** [luigirizzo/netmap#781]
We were testing multithreaded netmap applications on Intel XL710 cards and noticed that the RX traffic/interrupts are not split between different queues properly. TX works fine.

This is quite well illustrated by showing CPU interrupts, without any receiving software and core affinities for each queue set.
Using `pkt-gen` with the correct arguments (`-a`, `-p` and `-c` ) will also result in CPU usage only one one core (the one serving the ring ID)

FreeBSD 12.1 (`sysctl -a | grep ixl1`)
```
irq267: ixl1:aq:77 @cpu0(domain0): 155
irq268: ixl1:rxq0:79 @cpu0(domain0): 0
irq269: ixl1:rxq1:81 @cpu1(domain0): 0
irq270: ixl1:rxq2:83 @cpu2(domain0): 0
irq271: ixl1:rxq3:85 @cpu3(domain0): 817
irq272: ixl1:rxq4:87 @cpu4(domain0): 0
irq273: ixl1:rxq5:89 @cpu5(domain0): 0
irq274: ixl1:rxq6:91 @cpu6(domain0): 0
irq275: ixl1:rxq7:93 @cpu7(domain0): 0
```

Linux, Kernel 5.10.0-051000-generic, vanilla driver (patch `vanilla--i40e--50a00--99999`) (`cat /proc/interrupts | grep enp1s0f0`)
```
 34:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524289-edge      i40e_netmap-enp1s0f0-TxRx-0
 35:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524290-edge      i40e_netmap-enp1s0f0-TxRx-1
 36:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524291-edge      i40e_netmap-enp1s0f0-TxRx-2
 37:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524292-edge      i40e_netmap-enp1s0f0-TxRx-3
 38:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524293-edge      i40e_netmap-enp1s0f0-TxRx-4
 39:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524294-edge      i40e_netmap-enp1s0f0-TxRx-5
 40:          0          0          0          0          0          0      47950          0  IR-PCI-MSI 524295-edge      i40e_netmap-enp1s0f0-TxRx-6
 41:          0          0          0          0          0          0          0          0  IR-PCI-MSI 524296-edge      i40e_netmap-enp1s0f0-TxRx-7
 ```
 
As you can see, the packets only arrive in one RX queue/only generate interrupts for one RX queue and thus one core.
 
Transmitting, using `pkt-gen` with the `-a`, `-p` and `-c` options in this case and manually setting irq affinities using Intels `set_irq_affinity` script correctly uses all available queues.
 ```
 55:      32474          0          1          0          0          0          0          0   PCI-MSI 264193-edge      i40e_netmap-ens16f1-TxRx-0
 56:          0      32617          0          1          0          0          0          0   PCI-MSI 264194-edge      i40e_netmap-ens16f1-TxRx-1
 57:          0          0      32546          0          1          0          0          0   PCI-MSI 264195-edge      i40e_netmap-ens16f1-TxRx-2
 58:          0          0          0      33666          0          1          0          0   PCI-MSI 264196-edge      i40e_netmap-ens16f1-TxRx-3
 59:          0          0          0          0      33589          0          1          0   PCI-MSI 264197-edge      i40e_netmap-ens16f1-TxRx-4
 60:          0          0          0          0          0      33024          0          1   PCI-MSI 264198-edge      i40e_netmap-ens16f1-TxRx-5
 61:          1          0          0          0          0          0      32942          0   PCI-MSI 264199-edge      i40e_netmap-ens16f1-TxRx-6
 62:          0          1          0          0          0          0          0      31166   PCI-MSI 264200-edge      i40e_netmap-ens16f1-TxRx-7
 ```
 

We've also excluded a hardware defect by using two different cards from two different hosts in either direction.
Using Ubuntu 18.04 with the out-of-band driver selected by the configure script by default yields the same results.

**Comment by kierank** [comment]
By default the Intel NIC uses RX flow hashing to decide on its queue

**Comment by jhk098** [comment]
By default `pkt-gen` sends the very same UDP packet again and again. It's not surprising that all those packets end up in the same RX NIC queue, because they all have the same hash.
You can try to play with `pkt-gen` `-s` and/or `-d` options to let the UDP packets vary, and thus increasing the chances that they end up in different queues, e.g.
````
# pkt-gen -i ix0 -f tx -s 10.0.0.1-10.0.0.6
````

**Comment by ported-pw** [comment]
Thanks for the hint about RX flow hashing, that was indeed the issue.
