### ISSUE TITLE
Ring Num / Ring Size

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#783]
Hi, guys.

I'm trying use netmap in a setup with 4 NICs, each with 8 Queues and 8 Rx/Tx Host Rings.

From what I understand, each queue, will use 4 rings (rx/tx + hrx/htx) right ?

So I would need a total of 128 netmap rings, for all of it, correct ?

Ok, I've configured netmap module with: ring_num=1024 and ring_size=65536

The problem is, I have to adjust the ixgbe/82599 with a rx/tx ring amount of 1024, if I try to set it to anything above, eg: 2048 or 4096, the application won't work, resulting in this error:

716.277100 thread_job [1771] {1} Interface Opening Error: netmap:ix4s0^1 Cannot allocate memory / ix4s0: Cannot allocate memory

I've checked and it seems, this is related with buf_num ? I've set up the value to 262144 or even 524288, considering that since each ring will take 4096, then I would need 128 * 4096 = 524288, but no luck at all, well, not exactly, now 2048 works, but 4096 still doesn't works and gives me the same error: Cannot allocate memory <

As referecence, these are the values that have worked for me:

256  = OK
512  = OK
1024 = OK 
2048 = OK
3072 = OK (+ 1024)
3584 = OK (+  512)
3840 = OK (+  256)
4000 = OK (+  160)
4072 = OK (+   72)
4096 = NOT OK

What can I do, to fix this ?

**Comment by Fr3DBr** [comment]
I've checked and it seems, this is related with buf_num ? I've set up the value to 262144, as it seems to be the maximum the module can handle ? Using a value above it, doesn't seems to be working (at least not here). Maybe there's a limit in a scenario like mine ?

**Comment by giuseppelettieri** [comment]
Your numbers are correct, but netmap also needs a couple of buffers for internal purposes, so you should try increasing `buf_num` a bit.

**Comment by Fr3DBr** [comment]
Ok, I've increased it to:

1048576 = Same issue.
2097152 = Same issue.
4194304 = Same issue.

I guess these amounts would be enough to cover the extra buffers right ? Maybe the problem is somewhere else ?

**Comment by giuseppelettieri** [comment]
Yep. Is there something in the logs?

**Comment by Fr3DBr** [comment]
In /var/log/messages there's nothing from netmap, only the regular link up/down messages when touching the network cards (opening queues and ect).

**Comment by giuseppelettieri** [comment]
OK, try increasing verbosity: `echo 1 > /sys/module/netmap/verbose` (as root)

**Comment by Fr3DBr** [comment]
Ok, now we have output:

Apr  7 09:31:30 localhost kernel: 290.039582 [ 789] netmap_update_config      configuration changed for eth0: txring 6 x 4096, rxring 6 x 4096, rxbufsz 2048
Apr  7 09:31:30 localhost kernel: 290.039588 [1952] netmap_interp_ringid      eth0: tx [6,7) rx [6,7) id 0
Apr  7 09:31:30 localhost kernel: 290.039611 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:30 localhost kernel: 290.040954 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:30 localhost kernel: 290.042251 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:30 localhost kernel: 290.042257 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:30 localhost kernel: 290.044657 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000
Apr  7 09:31:30 localhost kernel: 290.289004 [1952] netmap_interp_ringid      eth0: tx [7,8) rx [7,8) id 1
Apr  7 09:31:30 localhost kernel: 290.289027 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:30 localhost kernel: 290.290409 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:30 localhost kernel: 290.291750 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:30 localhost kernel: 290.291756 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:30 localhost kernel: 290.294159 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000
Apr  7 09:31:30 localhost kernel: 290.539917 [1952] netmap_interp_ringid      eth0: tx [8,9) rx [8,9) id 2
Apr  7 09:31:30 localhost kernel: 290.539941 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:30 localhost kernel: 290.541370 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:30 localhost kernel: 290.542761 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:30 localhost kernel: 290.542766 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:30 localhost kernel: 290.545169 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000
Apr  7 09:31:30 localhost kernel: 290.789926 [1952] netmap_interp_ringid      eth0: tx [9,10) rx [9,10) id 3
Apr  7 09:31:30 localhost kernel: 290.789950 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:30 localhost kernel: 290.791413 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:30 localhost kernel: 290.792851 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:30 localhost kernel: 290.792857 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:30 localhost kernel: 290.795258 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000
Apr  7 09:31:31 localhost kernel: 291.040765 [1952] netmap_interp_ringid      eth0: tx [10,11) rx [10,11) id 4
Apr  7 09:31:31 localhost kernel: 291.040789 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:31 localhost kernel: 291.042303 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:31 localhost kernel: 291.043790 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:31 localhost kernel: 291.043795 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:31 localhost kernel: 291.046197 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000
Apr  7 09:31:31 localhost kernel: 291.290323 [1952] netmap_interp_ringid      eth0: tx [11,12) rx [11,12) id 5
Apr  7 09:31:31 localhost kernel: 291.290347 [1026] netmap_obj_malloc         netmap_ring request size 65792 too large
Apr  7 09:31:31 localhost kernel: 291.291905 [1999] netmap_mem2_rings_create  Cannot allocate RX_ring
Apr  7 09:31:31 localhost kernel: 291.293407 [ 433] netmap_init_obj_allocator_bitmap netmap_if free 256
Apr  7 09:31:31 localhost kernel: 291.293413 [ 433] netmap_init_obj_allocator_bitmap netmap_ring free 1024
Apr  7 09:31:31 localhost kernel: 291.295814 [ 433] netmap_init_obj_allocator_bitmap netmap_buf free 1000000

**Comment by Fr3DBr** [comment]
Thanks for the verbosity hint, I've finally found out what was wrong by increasing ring_size !! :)

**Comment by Jack-wx** [comment]
@Fr3DBr  I meet the same problem,can you tell me how to solve the problem?
