### ISSUE TITLE
Willing to Pay

### ISSUE THREAD

**Issue by Fr3DBr** [luigirizzo/netmap#785]
Hi, guys.

Currently, there's a crashing problem already reported by me in issues: https://github.com/luigirizzo/netmap/issues/779 and https://github.com/luigirizzo/netmap/issues/774, it's been a month and I still did not find a proper solution for it.

I'm willing to pay some compensation, if we could fix this strange crashing problem. If anyone could reach me, it'd be great.

Thanks. :)

**Comment by giuseppelettieri** [comment]
Hi @Fr3DBr, sorry for the unresponsiveness but we have been a bit busy lately and your bug looks hard to reproduce locally. Paying is a bit complicated, unless the payment is related to a University project. Don't worry about payment, I'll try to look into it as soon as I can.

**Comment by Fr3DBr** [comment]
Hi @giuseppelettieri, if you need anything from me, in regards of this problem, I'm open for helping, I can even open Anydesk and show it happening in real time, causing the issue is quite easy, 2 or 3 attempts will result on it, but I have no clue of what could be causing it at all. I'm not sure if this is specifically related with my hardware, but it happens in 4 different servers (same motherboard, same CPU and same network cards).
