### ISSUE TITLE
netmap can not achieve 14Mpps speed

### ISSUE THREAD

**Issue by Groundsea** [luigirizzo/netmap#79]
Hi Netmap team,

I deployed netmap on two separate blades with intel 82599 NIC. They connect to the same switch(H3C S5820V2-52QF).
It can only get 1.x Mpps speed.
The OS is redhat 7.0. the ixgbe driver version is 3.23.2.1(already merged the patch). The netmap is master branch. 

Output is like below, I want to know if I missing some configuration?
[root@controller build-apps(keystone_admin)]# ./pkt-gen -i netmap:eno2 -f rx 
388.622735 main [1830] interface is netmap:eno2
388.622789 main [1941] running on 1 cpus (have 32)
388.624743 extract_ip_range [362] range is 10.0.0.1:0 to 10.0.0.1:0
388.624748 extract_ip_range [362] range is 10.1.0.1:0 to 10.1.0.1:0
388.625770 main [2039] mapped 334980KB at 0x7f697dbb4000
Receiving from netmap:eno2: 4 queues, 1 threads and 1 cpus.
388.625784 main [2126] Wait 2 secs for phy reset
390.625876 main [2128] Ready...
390.626059 receiver_body [1331] reading from netmap:eno2 fd 3 main_fd 3
391.626973 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1001009 usec) 0.00 avg_batch
391.627104 receiver_body [1338] waiting for initial packets, poll returns 0 0
392.628023 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1001050 usec) 0.00 avg_batch
392.628151 receiver_body [1338] waiting for initial packets, poll returns 0 0
393.629099 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1001076 usec) 0.00 avg_batch
393.629175 receiver_body [1338] waiting for initial packets, poll returns 0 0
394.630171 main_thread [1620] 244.590 Kpps (244.846 Kpkts 117.526 Mbps in 1001048 usec) 165.32 avg_batch
395.631200 main_thread [1620] 1.349 Mpps (1.350 Mpkts 648.007 Mbps in 1001053 usec) 142.15 avg_batch
396.632235 main_thread [1620] 1.256 Mpps (1.257 Mpkts 603.427 Mbps in 1001034 usec) 154.52 avg_batch
397.633288 main_thread [1620] 1.344 Mpps (1.345 Mpkts 645.648 Mbps in 1001053 usec) 167.63 avg_batch
398.634338 main_thread [1620] 1.280 Mpps (1.282 Mpkts 615.147 Mbps in 1001050 usec) 155.96 avg_batch
399.635401 main_thread [1620] 1.183 Mpps (1.184 Mpkts 568.429 Mbps in 1001063 usec) 144.31 avg_batch
400.636486 main_thread [1620] 1.205 Mpps (1.206 Mpkts 578.788 Mbps in 1001085 usec) 148.15 avg_batch
401.637524 main_thread [1620] 1.342 Mpps (1.343 Mpkts 644.757 Mbps in 1001038 usec) 164.39 avg_batch
402.638579 main_thread [1620] 1.320 Mpps (1.321 Mpkts 634.105 Mbps in 1001055 usec) 162.29 avg_batch
403.639646 main_thread [1620] 1.364 Mpps (1.366 Mpkts 655.475 Mbps in 1001067 usec) 145.71 avg_batch
404.640695 main_thread [1620] 1.329 Mpps (1.330 Mpkts 638.459 Mbps in 1001049 usec) 161.68 avg_batch
405.641743 main_thread [1620] 1.233 Mpps (1.234 Mpkts 592.344 Mbps in 1001048 usec) 152.75 avg_batch
406.642808 main_thread [1620] 1.369 Mpps (1.371 Mpkts 658.044 Mbps in 1001064 usec) 169.80 avg_batch

[root@hfxie build-apps]# ./pkt-gen -i netmap:rear1 -f tx -D 38:ea:a7:36:3f:19 -S 00:22:93:74:73:dd 
467.091220 main [1830] interface is netmap:rear1
467.091309 main [1941] running on 1 cpus (have 16)
467.091336 extract_ip_range [362] range is 10.0.0.1:0 to 10.0.0.1:0
467.091359 extract_ip_range [362] range is 10.1.0.1:0 to 10.1.0.1:0
467.104964 main [2039] mapped 334980KB at 0x7f66675a1000
Sending on netmap:rear1: 16 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:22:93:74:73:dd -> 38:ea:a7:36:3f:19)
467.104996 main [2124] Sending 512 packets every  0.000000000 s
467.105000 main [2126] Wait 2 secs for phy reset
469.105103 main [2128] Ready...
469.105336 sender_body [1140] start, fd 3 main_fd 3
469.194974 sender_body [1218] drop copy
470.105304 main_thread [1620] 1.338 Mpps (1.338 Mpkts 642.097 Mbps in 1000071 usec) 461.91 avg_batch
471.105862 main_thread [1620] 1.257 Mpps (1.257 Mpkts 603.515 Mbps in 1000544 usec) 463.96 avg_batch
472.106295 main_thread [1620] 1.341 Mpps (1.342 Mpkts 644.180 Mbps in 1000446 usec) 461.82 avg_batch
473.107931 main_thread [1620] 1.308 Mpps (1.311 Mpkts 629.055 Mbps in 1001638 usec) 462.76 avg_batch
474.108033 main_thread [1620] 1.191 Mpps (1.191 Mpkts 571.798 Mbps in 1000102 usec) 468.26 avg_batch
475.109019 main_thread [1620] 1.164 Mpps (1.165 Mpkts 559.153 Mbps in 1000986 usec) 466.71 avg_batch
476.109765 main_thread [1620] 1.343 Mpps (1.344 Mpkts 645.116 Mbps in 1000747 usec) 464.09 avg_batch
477.110653 main_thread [1620] 1.316 Mpps (1.317 Mpkts 632.309 Mbps in 1000888 usec) 459.95 avg_batch
478.111192 main_thread [1620] 1.369 Mpps (1.370 Mpkts 657.470 Mbps in 1000539 usec) 467.80 avg_batch
479.111347 main_thread [1620] 1.335 Mpps (1.335 Mpkts 640.845 Mbps in 1000154 usec) 466.16 avg_batch
480.111516 main_thread [1620] 1.223 Mpps (1.224 Mpkts 587.318 Mbps in 1000170 usec) 466.30 avg_batch
481.112564 main_thread [1620] 1.363 Mpps (1.365 Mpkts 654.969 Mbps in 1001048 usec) 463.49 avg_batch

**Comment by Groundsea** [comment]
Hi Team,

Currently, the send side can up to 13Mpps, but on receive side, it can only reach 3Mpps. on the switch  , both ports are up to 13Mpps. so the problem should be on pkt-gen receive side.

Here is the statistics info of receive port:
[root@controller ~(keystone_admin)]# ethtool -S eno2|grep -v ": 0"
NIC statistics:
     rx_packets: 40
     tx_packets: 1
     rx_bytes: 3656
     tx_bytes: 70
     multicast: 135
     rx_pkts_nic: 1658520803
     tx_pkts_nic: 2
     rx_bytes_nic: 106145364644
     tx_bytes_nic: 168
     lsc_int: 11
     tx_flow_control_xon: 219567
     tx_flow_control_xoff: 219577
     rx_no_dma_resources: 529324299
     tx_queue_1_packets: 1
     tx_queue_1_bytes: 70
     rx_queue_0_packets: 40
     rx_queue_0_bytes: 3656
     VF 0 Tx Packets: 1
     VF 0 Tx Bytes: 90

It showed that there is so many "rx no dma resources". I try to use multiple core to receive packets, but it core dumped, like below:
Core was generated by `./pkt-gen -i eno2 -f rx -p 8 -c 0xff'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000404720 in receiver_body ()

My question:
1. Does "no dma resources" error correlation with bottleneck of cpu? my cpu is Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
2. How to solve the core dumped problem? when I add -p 8 -c 0xff parameter?

Thank you very much!

**Comment by lazy404** [comment]
try
ethtool -A eno2 autoneg off rx off tx off

on both ends
