### ISSUE TITLE
nm_txsync_prologue() errors on multi-threaded "bridge app

### ISSUE THREAD

**Issue by olg-chk** [luigirizzo/netmap#801]
Hi!
I have multi-threaded app: first thread is placing packets from RX rings of one NIC into some array. The further processing (including TX-ing) a packet in the array can be dispatched to one of 4 threads. These 4 threads are copying a packet into a slot of available TX ring of another NIC. When i generate iperf traffic (max speed available) i immediately receive following errors in my syslog:
> 
> Jun 22 16:52:23 xx kernel: 943.615445 [1791] netmap_ring_reinit called for vmx3 TX0
> Jun 22 16:52:24 xx kernel: 944.148456 [1688] nm_txsync_prologue vmx3 TX0: fail 'head > kring->rtail && head < kring->rhead' h 228 c 228 t 0 rh 229 rc 229 rt 0 hc 229 ht 0

I've tried to add synchronization to make changing **cur** and **head** indexes of used TX ring and **ioctl(..,NIOCTXSYNC,..)** inside mutex-ed section, but it didn't change a bit: i got the same error.  While these errors app is forwarding iperf traffic but definetly not the best way it could.

What am I doing wrong? How can i get rid of the errors quoted above?

Btw, i use function **nm_open(..,NULL,NETMAP_NO_TX_POLL,NULL))** for both of my NICs.

**Comment by jhk098** [comment]
It looks more like you are advancing `txring->cur` and `txring->head` without checking them against `txring->tail` (e.g. with a simple comparison or with `nm_ring_empty(). You have `tail` set to 0, and that doesn't make sense considering the values for `cur`/`head` and `rcur`/`rhead` (e.g. values of `cur`/`head` at the time of the previous `NIOCTXSYNC`).
You need to protect changes to `cur`, `head` and `ioctl(NIOCTXSYNC)` only if there are multiple threads accessing the same ring concurrently.

**Comment by olg-chk** [comment]
@jhk098 Thanks for the answer, yes the problem was that two threads accessed the same TX-ring in concurrently. When I enclosed the whole section accessing TX ring in mutex the problem is resolved.
