### ISSUE TITLE
Kernel 5.13.0-1.el7.elrepo.x86_64 is not supported 

### ISSUE THREAD

**Issue by traveler0007** [luigirizzo/netmap#803]
ixgbe version not suport 
make[1]: Entering directory `/usr/src/kernels/5.13.0-1.el7.elrepo.x86_64'
  CC [M]  /home/netmap-master/ixgbe-5.3.8/src/ixgbe_main.o
In file included from /home/netmap-master/ixgbe-5.3.8/src/ixgbe_osdep.h:38,
                 from /home/netmap-master/ixgbe-5.3.8/src/ixgbe_type.h:66,
                 from /home/netmap-master/ixgbe-5.3.8/src/ixgbe_dcb.h:28,
                 from /home/netmap-master/ixgbe-5.3.8/src/ixgbe.h:45,
                 from /home/netmap-master/ixgbe-5.3.8/src/ixgbe_main.c:52:
/home/netmap-master/ixgbe-5.3.8/src/kcompat.h:2730:10: fatal error: linux/pci-aspm.h: No such file or directory
 #include <linux/pci-aspm.h>

**Comment by traveler0007** [comment]
Intel driver does not support

**Comment by giuseppelettieri** [comment]
That is an error in the original Intel driver, please try with a more recent one. You can look at the available patches in `LINUX/final-patches`. For example, to use 5.11.3, configure with
```
./configure --select-version=ixgbe:5.11.3
```
