### ISSUE TITLE
Patch for virtio_net.c version 3.10.87 failed

### ISSUE THREAD

**Issue by RichieB2B** [luigirizzo/netmap#81]
While compiling netmap for Linux kernel 3.10.87 I got:
```
cp -Rp /root/src/linux-3.10.87/drivers/net/virtio_net.c virtio_net.c
patch --posix --quiet --force -p1 < patches/diff--virtio_net.c--30800--30b00;
1 out of 7 hunks FAILED -- saving rejects to file virtio_net.c.rej
make: *** [get-virtio_net.c] Error 1
```
In virtio_net.c on line 648 I see:
```
        unsigned int r, len, received = 0;
```
while the patch expects:
```
        unsigned int len, received = 0;
```
after correcting diff--virtio_net.c--30800--30b00 everything compiled smoothly.

**Comment by vmaffione** [comment]
Hi, Currently we don't provide patches for LTS kernels.

The patch we have for 3.10 correctly compiles on the "Linux 3.10 commit" (8bb495e3f02401ee6f76d1b1d77f3ac9f079e376) in the linux git.
