### ISSUE TITLE
Bridge app slow performance in TCP (but not UDP)

### ISSUE THREAD

**Issue by kkanungo17** [luigirizzo/netmap#815]
Hi,

I've been testing out netmap and the bridge example code, where bridge is bridging together the NIC and the host stack. When I run iperf3 in UDP mode, I can easily saturate the gigabit link, but in TCP mode, the speed drops drastically to about 70kbits/second.

Are there any configuration errors on my side?

**Comment by jhk098** [comment]
Have you disabled checksum offload and TCP offload as advised in `LINUX/README.md`?
In any case, the test you are doing is mostly a functionality test, since there cannot be any performance advantage (actually, you'll only go slower) when using netmap in that way.
