### ISSUE TITLE
Linux modules built with wrong module version

### ISSUE THREAD

**Issue by raybellis** [luigirizzo/netmap#82]
Following the supplied instructions on a Fedora 21 system my compiled modules came out built for 4.1.6, instead of 4.1.6-100.fc21.x86_64 and therefore won't `insmod` correctly.

To fix this I had to:

```
setenv subver 100
setenv fedver fc21
setenv arch x86_64
```

before building.

**Comment by vmaffione** [comment]
Can you try to update the code and use just ./configure and make in the root directory?
