### ISSUE TITLE
Make fails with --disable-vale option

### ISSUE THREAD

**Issue by udosan174** [luigirizzo/netmap#845]
I set --disable-vale option. Make fails.

kernel directory            /home/xxxxxx/rt-lts/linux-rt-lts/src/linux-rt-lts
kernel sources              /home/xxxxxx/rt-lts/linux-rt-lts/src/linux-rt-lts
linux version               50f1b  [5.15.27]
module file                 netmap.ko

subsystems                  null generic
apps
native drivers

[xxxxxx@arch07 netmap]$ make
make -C /home/xxxxxx/rt-lts/linux-rt-lts/src/linux-rt-lts M=/home/xxxxxx/rt-lts/netmap_new/netmap EXTRA_CFLAGS='-I/home/xxxxxx/rt-lts/netmap_new/netmap -I/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX -I/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX/../sys -I/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_GENERIC' -Wno-error=stringop-truncation modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory '/home/xxxxxx/rt-lts/linux-rt-lts/src/linux-rt-lts'
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_mem2.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_mbq.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_legacy.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_bdg.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_kloop.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_generic.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_null.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_common.o
  CC [M]  /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_linux.o
/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX/netmap_linux.c: In function ‘netmap_pernet_init’:
/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX/netmap_linux.c:1575:27: error: ‘vale_max_bridges’ undeclared (first use in this function)
 1575 |         ns->num_bridges = vale_max_bridges;
      |                           ^~~~~~~~~~~~~~~~
/home/xxxxxx/rt-lts/netmap_new/netmap/LINUX/netmap_linux.c:1575:27: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [/home/xxxxxx/rt-lts/netmap_new/netmap/Kbuild:29: /home/xxxxxx/rt-lts/netmap_new/netmap/netmap_linux.o] Error 1
make[1]: *** [Makefile:1868: /home/xxxxxx/rt-lts/netmap_new/netmap] Error 2
make[1]: Leaving directory '/home/xxxxxx/rt-lts/linux-rt-lts/src/linux-rt-lts'
make: *** [netmap.mak:80: netmap.ko] Error 2

**Comment by giuseppelettieri** [comment]
This should be fixed now, can you confirm/close the issue?

**Comment by udosan174** [comment]
I confirmed that the issue was fixed. Thanks.
