### ISSUE TITLE
igb: NM_WRITE_SRRCTL writes wrong register

### ISSUE THREAD

**Issue by hessenud** [luigirizzo/netmap#849]
One implementation of NM_WRITE_SRRCTLwrite to TDH instead of SRRCTL rendering the tx path dysfunctional.

`diff -urN netmap-master/LINUX/if_igb_netmap.h netmap/LINUX/if_igb_netmap.h                                                                                                          
--- netmap-master/LINUX/if_igb_netmap.h 2022-04-03 09:24:30.000000000 +0200                                                                                                         
+++ netmap/LINUX/if_igb_netmap.h        2022-04-21 07:50:53.583862696 +0200                                                                                                         
@@ -82,7 +82,7 @@                                                                                                                                                                   
        u32 srrctl)                                                                                                                                                                 
 {                                                                                                                                                                                  
        struct e1000_hw *hw = &adapter->hw;                                                                                                                                         
-       wr32(E1000_TDH(rxr->reg_idx), srrctl);                                                                                                                                      
+       wr32(E1000_SRRCTL(rxr->reg_idx), srrctl);                                                                                                                                   
 }                                                                                                                                                                                  
 #else                                                                                                                                                                              
 #define NM_WRITE_RCTL(_adapter, _rxr, _rxdctl) \                                                                                                                                   
                      `

**Comment by giuseppelettieri** [comment]
Thanks, would you like to prepare a pull request?

**Comment by hessenud** [comment]
Hello Giuseppe,

Sorry can’t do that (in the foreseeable future). Git isn’t working here and probably won’t for quite a while.
Its really just correcting the address macro from E1000_TDH to E1000_SRRCTL. So please just do it for me.
 Obviously nobody else uses IGB in this configuration so I wanted to feed back this issue along with the fix, so it won’t get forgotten.

Cheers and thanks everybody for netmap ;-)
Udo

**Comment by giuseppelettieri** [comment]
Done!

Cheers,
Giuseppe
