### ISSUE TITLE
problem in defines of i40e and ice

### ISSUE THREAD

**Issue by mohammadkhanjani** [luigirizzo/netmap#862]
i have a vm with kernel 4.15.25 and want to build with this configuration:
./configure --drivers=ice,ixgbe,i40e
version of ext-drivers:
i40e:2.18.9
ice:1.8.8
ixgbe:5.14.6
when i build with this configuration it get error becuase can not find defines of I40E_PTR_ARRAY and ICE_PTR_ARRAY.
i checked run_tests in configuration. tests of ice and i40e can not be passed while i can build i40e and ice driver directly without any error. when i run their tests manually, i see auxiliary_bus error that can not find this header file. file was at that path in linux folder. how i can fix this?

**Comment by pkitszel** [comment]
Have you tried with newer patches (eg for ice 1.8.9)?

**Comment by mohammadkhanjani** [comment]
no, but i have problem with 1.7.16 and 1.8.8

**Comment by mohammadkhanjani** [comment]
it's not the driver problem because ice driver itself can be installed without any problem. it could ice patch problem for ice.7.gz

**Comment by giuseppelettieri** [comment]
IIUC, you are getting an error from `make install` because `ice.7.gz` is missing. I have now updated the patches to skip that step in the `Makefile`. May you please try the current master?

**Comment by mohammadkhanjani** [comment]
thanks, it worked correctly

**Comment by pkitszel** [comment]
@enum-class 
@giuseppelettieri 

Why manpage .gz file preparation is skipped for ice? It's not crucial ofc, but maybe it will be easier to keep it, in order to have patches smaller in both size & scope.
