### ISSUE TITLE
netmap for ubuntu 22.04

### ISSUE THREAD

**Issue by mohammadkhanjani** [luigirizzo/netmap#874]
Hi
netmap can be build and installed but cannot send packets in ubuntu 22.04. i tested it by ixgbe 5.15.2

it get me error in running pkt-gen:

/dev/netmap: no such file or directory

could you help me?

**Comment by ptrckcrg** [comment]
Is the module built and loaded? i.e. do you see netmap with ```lsmod```? If so, are the perms correctly set on it?

**Comment by mohammadkhanjani** [comment]
Yes, I set parameters the same as Ubuntu 16.04. By i40e, pkt-gen can be run, but do not send any packets. Send rate was 0.

**Comment by mohammadkhanjani** [comment]
It fixed by multiple restarting OS
