### ISSUE TITLE
Kernel Version Dependency on Netmap 

### ISSUE THREAD

**Issue by amey-k** [luigirizzo/netmap#88]
Hello Netmap team, 

I am trying to get netmap working on Linux by following the README available at LINUX/. I synced the master ToT(latest code) of netmap today (30 th september).  Below are my observations 

1. When I try to make netmap.ko on Ububtu 12.04 LTS , which has kernel version 3.5.0-18, I get warnings 
nm_os_ifnet_fini [<local_path>/netmap.ko] undefined! 
nm_os_ifnet_init [<local_path>/netmap.ko] undefined! 
nm_os_ifnet_lock [<local_path>/netmap.ko] undefined! 
nm_os_ifnet_unlock [<local_path>/netmap.ko] undefined! 

and consequently. during insmod, I get error - Unknown symbol in module. 

2. When I try to make netmap.ko on Ububtu 14.04 LTS, which has kernel version 3.13.0-32, things happen smooth and I could successfully do insmod netmap.ko. 

So, from the observations, I suspect that the present netmap ToT has some dependency over kernel version.  In case 1, i.e. in Ubuntu 12.04, it seems to be a linker issue.  

Would you please comment on whether this is a known issue ? Or am I missing anything which is required for 3.5.0 kernel versions. If the latest netmap is not supposed to work on older kernel versions, is it possible to point to an older commit ID which will be compatible with kernel 3.5.0

Thanks in advance, 

-Amey Kulkarni

**Comment by john-gress** [comment]
I have this exact same problem compiling for CentOS 6.5, kernel version 2.6.32-573.7.1. I appreciate hearing if there is an older commit which will work. Thanks.

**Comment by morphyno** [comment]
John:

I ran into an issue with netmap and CentOS 6.5 last year. Netmap patches
the kernel from kernel.org but Redhat heavily modified their own kernels so
the patches break. You literally have to patch the patches by hand. I had
to patch ixgbe.c manually and while I was able to get netmap and modified
ixgbe to work, it was very painful. This would also apply fir virtio,
e1000e drivers as well.

Morgan

On Fri, Oct 2, 2015 at 1:05 PM, john-gress <notifications@github.com> wrote:

> I have this exact same problem compiling for CentOS 6.5, kernel version
> 2.6.32-573.7.1. I appreciate hearing if there is an older commit which will
> work. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/luigirizzo/netmap/issues/88#issuecomment-145142129>.
>



-- 
All in a can, just add water and stir goodness

**Comment by john-gress** [comment]
Morphyno - would you consider sharing your patch?

**Comment by giuseppelettieri** [comment]
Hi all,

the problem you are seeing is not related to driver patching. It is just a trivial mistake where a misplaced #ifdef was causing the nm_os_ifnet_* functions to be compiled out on kernels without IOMMU support. May you please try the commit I just pushed?

**Comment by john-gress** [comment]
That fixed it. Thank you very much.

**Comment by amey-k** [comment]
Hi all, 

I also now can see that the issue I opened is now fixed. I now close this issue. 
Thanks much for the help.
