### ISSUE TITLE
Warning seen during compilation on Oracle Linux 7.9 with 4.14.35 uek kernel.

### ISSUE THREAD

**Issue by VenkateshPottem** [luigirizzo/netmap#885]
The below warning is seen during compilation on Oracle Linux 7.9 with kernel 4.14.35-2047.508.3.2.el7uek.x86_64.

Compilation log
===========
[root@hpdl380g10 netmap]# make
make -C /lib/modules/4.14.35-2047.508.3.2.el7uek.x86_64/build M=/root/netmap EXTRA_CFLAGS='-I/root/netmap -I/root/netmap/LINUX -I/root/netmap/LINUX/../sys -I/root/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory `/usr/src/kernels/4.14.35-2047.508.3.2.el7uek.x86_64'
  CC [M]  /root/netmap/netmap_mem2.o
  CC [M]  /root/netmap/netmap_mbq.o
  CC [M]  /root/netmap/netmap_legacy.o
  CC [M]  /root/netmap/netmap_bdg.o
  CC [M]  /root/netmap/netmap_kloop.o
/root/netmap/LINUX/../sys/dev/netmap/netmap_kloop.c: In function ‘netmap_sync_kloop’:
/root/netmap/LINUX/../sys/dev/netmap/netmap_kloop.c:702:6: warning: passing argument 2 of ‘init_poll_funcptr’ from incompatible pointer type [enabled by default]
      sync_kloop_poll_table_queue_proc);
      ^
In file included from /root/netmap/LINUX/bsd_glue.h:44:0,
                 from /root/netmap/LINUX/../sys/dev/netmap/netmap_kloop.c:48:
./include/linux/poll.h:82:20: note: expected ‘poll_queue_proc’ but argument is of type ‘void (*)(struct file *, struct wait_queue_head_t *, struct poll_table *)’
 static inline void init_poll_funcptr(poll_table *pt, poll_queue_proc qproc)
                    ^
  CC [M]  /root/netmap/netmap_vale.o
  CC [M]  /root/netmap/netmap_offloadings.o
  CC [M]  /root/netmap/netmap_pipe.o
  CC [M]  /root/netmap/netmap_monitor.o
  CC [M]  /root/netmap/netmap_generic.o

Git info
======
[root@hpdl380g10 netmap]# git log | head -10
commit b140c84f98a97810241fe4a7038098ddc29f3f7d
Author: Giuseppe Lettieri <g.lettieri@iet.unipi.it>
Date:   Tue Oct 18 15:22:18 2022 +0200

    linux: check for put/get_online_cpus()

OS and kernel info
============
[root@hpdl380g10 ~]# uname -r
4.14.35-2047.508.3.2.el7uek.x86_64
[root@hpdl380g10 ~]# cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"

**Comment by giuseppelettieri** [comment]
May you please try again with the latest master? Thanks!

**Comment by VenkateshPottem** [comment]
Issue is fixed with latest master, thanks for fixing it.

[root@hpdl380g10 netmap]# git log | head -10
commit d67a604e805b67efb563ea8d5eb2d1318acf6ed8
Author: Giuseppe Lettieri <giuseppe.lettieri@unipi.it>
Date:   Sat Oct 22 16:16:49 2022 +0200

    linux/e1000,e1000e,igb: don't return partial frames

[root@hpdl380g10 netmap]#
[root@hpdl380g10 netmap]#
[root@hpdl380g10 netmap]# make
make -C /lib/modules/4.14.35-2047.508.3.2.el7uek.x86_64/build M=/root/netmap EXTRA_CFLAGS='-I/root/netmap -I/root/netmap/LINUX -I/root/netmap/LINUX/../sys -I/root/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m  O_DRIVERS="" NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory `/usr/src/kernels/4.14.35-2047.508.3.2.el7uek.x86_64'
  CC [M]  /root/netmap/netmap_mem2.o
  CC [M]  /root/netmap/netmap_mbq.o
  CC [M]  /root/netmap/netmap_legacy.o
  CC [M]  /root/netmap/netmap_bdg.o
  CC [M]  /root/netmap/netmap_kloop.o
  CC [M]  /root/netmap/netmap_vale.o
  CC [M]  /root/netmap/netmap_offloadings.o
  CC [M]  /root/netmap/netmap_pipe.o
  CC [M]  /root/netmap/netmap_monitor.o
  CC [M]  /root/netmap/netmap_generic.o
  CC [M]  /root/netmap/netmap_null.o
  CC [M]  /root/netmap/netmap_common.o
  CC [M]  /root/netmap/netmap_linux.o
  CC [M]  /root/netmap/netmap_ptnet.o
  LD [M]  /root/netmap/netmap.o
  Building modules, stage 2.
  MODPOST 1 modules
  SDTINF  /root/netmap/netmap.sdtinfo.c
  CC      /root/netmap/netmap.mod.o
  SDTSTB  /root/netmap/netmap.sdtstub.S
  AS      /root/netmap/netmap.sdtstub.o
  CTF
  LD [M]  /root/netmap/netmap.ko
make[1]: Leaving directory `/usr/src/kernels/4.14.35-2047.508.3.2.el7uek.x86_64'
make -C build-libnetmap SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-libnetmap'
cc -O2 -pipe -Wall -Werror -g -I /root/netmap/LINUX/../sys   -c -o nmctx-pthreads.o /root/netmap/LINUX/../libnetmap/nmctx-pthreads.c
cc -O2 -pipe -Wall -Werror -g -I /root/netmap/LINUX/../sys   -c -o nmctx.o /root/netmap/LINUX/../libnetmap/nmctx.c
cc -O2 -pipe -Wall -Werror -g -I /root/netmap/LINUX/../sys   -c -o nmport.o /root/netmap/LINUX/../libnetmap/nmport.c
cc -O2 -pipe -Wall -Werror -g -I /root/netmap/LINUX/../sys   -c -o nmreq.o /root/netmap/LINUX/../libnetmap/nmreq.c
ar r libnetmap.a nmctx-pthreads.o nmctx.o nmport.o nmreq.o
ar: creating libnetmap.a
make[1]: Leaving directory `/root/netmap/build-libnetmap'
make -C build-apps/dedup SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/dedup'
cc -O2 -pipe -g -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -Wextra   -c -o dedup.o /root/netmap/LINUX/../apps/dedup/dedup.c
cc -O2 -pipe -g -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -Wextra   -c -o dedup-main.o /root/netmap/LINUX/../apps/dedup/dedup-main.c
cc   dedup.o dedup-main.o  -lpthread -lrt        -o dedup
make[1]: Leaving directory `/root/netmap/build-apps/dedup'
make -C build-apps/vale-ctl SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/vale-ctl'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../apps/vale-ctl/vale-ctl.c  -lnetmap -o vale-ctl
make[1]: Leaving directory `/root/netmap/build-apps/vale-ctl'
make -C build-apps/nmreplay SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/nmreplay'
cc -O2  -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../apps/nmreplay/nmreplay.c  -lnetmap -lpthread -lrt     -lm -o nmreplay
make[1]: Leaving directory `/root/netmap/build-apps/nmreplay'
make -C build-apps/tlem SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/tlem'
cc -O2 -pipe -g -Werror -Wall -Wunused-function -Wno-address-of-packed-member -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I/root/netmap/LINUX/../libnetmap -Wextra  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../apps/tlem/tlem.c  -lnetmap -lpthread -lrt        -lm -o tlem
make[1]: Leaving directory `/root/netmap/build-apps/tlem'
make -C build-apps/lb SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/lb'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra   -c -o lb.o /root/netmap/LINUX/../apps/lb/lb.c
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra   -c -o pkt_hash.o /root/netmap/LINUX/../apps/lb/pkt_hash.c
cc -L /root/netmap/build-libnetmap  lb.o pkt_hash.o  -lnetmap -lpthread -lm -lrt         -o lb
make[1]: Leaving directory `/root/netmap/build-apps/lb'
make -C build-apps/bridge SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/bridge'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I/root/netmap/LINUX/../libnetmap -Wextra  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../apps/bridge/bridge.c  -lnetmap -lrt       -o bridge
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I/root/netmap/LINUX/../libnetmap -Wextra -DBUSYWAIT -c /root/netmap/LINUX/../apps/bridge/bridge.c -o bridge-b.o
cc -L /root/netmap/build-libnetmap  bridge-b.o  -lnetmap -lrt    -o bridge-b
make[1]: Leaving directory `/root/netmap/build-apps/bridge'
make -C build-apps/pkt-gen SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld"
make[1]: Entering directory `/root/netmap/build-apps/pkt-gen'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra -Wno-address-of-packed-member -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../apps/pkt-gen/pkt-gen.c  -lpthread -lm -lnetmap -lrt      -o pkt-gen
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys -I /root/netmap/LINUX/../apps/include -I /root/netmap/LINUX/../libnetmap -Wextra -Wno-address-of-packed-member -DNO_PCAP -DBUSYWAIT -c /root/netmap/LINUX/../apps/pkt-gen/pkt-gen.c -o pkt-gen-b.o
cc -L /root/netmap/build-libnetmap  pkt-gen-b.o  -lpthread -lm -lnetmap -lrt     -o pkt-gen-b
make[1]: Leaving directory `/root/netmap/build-apps/pkt-gen'
make -C build-utils SRCDIR=/root/netmap/LINUX/.. BUILDDIR=/root/netmap CC="cc" LD="ld" SUBSYS_FLAGS="-DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE"
make[1]: Entering directory `/root/netmap/build-utils'
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/test_select.c  -lnetmap -lpthread -lm -lrt         -o test_select
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/testmmap.c  -lnetmap -lpthread -lm -lrt    -o testmmap
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/test_nm.c  -lnetmap -lpthread -lm -lrt     -o test_nm
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/functional.c  -lnetmap -lpthread -lm -lrt          -o functional
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/ctrl-api-test.c  -lnetmap -lpthread -lm -lrt       -o ctrl-api-test
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/fd_server.c  -lnetmap -lpthread -lm -lrt   -o fd_server
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/functional-legacy.c  -lnetmap -lpthread -lm -lrt   -o functional-legacy
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/fd_server-legacy.c  -lnetmap -lpthread -lm -lrt    -o fd_server-legacy
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/get_avail_tx_packets.c  -lnetmap -lpthread -lm -lrt        -o get_avail_tx_packets
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/get_max_tx_packets.c  -lnetmap -lpthread -lm -lrt          -o get_max_tx_packets
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/extmem-example.c  -lnetmap -lpthread -lm -lrt      -o extmem-example
cc -O2 -pipe -Werror -Wall -Wunused-function -I /root/netmap/LINUX/../sys  -I /root/netmap/LINUX/../libnetmap -Wextra -g -DCONFIG_NETMAP_NULL -DCONFIG_NETMAP_PTNETMAP -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE -DNO_PCAP  -L /root/netmap/build-libnetmap  /root/netmap/LINUX/../utils/sync_kloop_test.c  -lnetmap -lpthread -lm -lrt     -o sync_kloop_test
make[1]: Leaving directory `/root/netmap/build-utils'
[root@hpdl380g10 netmap]#
[root@hpdl380g10 netmap]#
