### ISSUE TITLE
FreeBSD 13.1-STABLE, in netmap mode, running tcpdump on netmap:XX causes POLLERR on the the main app.

### ISSUE THREAD

**Issue by ozkankirik** [luigirizzo/netmap#890]
Hi,

I'm using FreeBSD stable/13. I'm running snort3 in netmap mode as inline IPS between em0 and em1.
snort3 behaves like netmap bridge app between em0 and em1.

Everything works properly if tcpdump not running.
But, when I run `tcpdump -eni netmap:em0`;
- packets are lost randomly.
- Snort throws this error: **Encountered error condition on a packet socket**
- Related code: https://github.com/snort3/libdaq/blob/master/modules/netmap/daq_netmap.c#L560

How can we solve this POLL ERR problem?
Or, is there a safe way for sniffing packets through netmap ?

Have a nice day

**Comment by jhk098** [comment]
The snort3 application and tcpdump are conflicting on em0. In particular, they are trying to access concurrently the RX rings, so they are competing (without cooperation) for the received packets. So yes, those errors are expected.

If you want to "monitor" what's happening on a netmap interface that is being used, you can use a monitor netmap port. In this case, snort3 is the application "owning" em0 and em1, so you need to change the tcpdump port specification:
````
# tcpdump -eni netmap:em0/tr
```` 
or, for zerocopy
````
# tcpdump -eni netmap:em0/z
````
Look at e.g. `libnetmap/libnetmap.h` for some documentation on these suffix flags.

**Comment by ozkankirik** [comment]
Thank you, it works as expected!  sorry for noise
