### ISSUE TITLE
How to configure to avoid packet drops

### ISSUE THREAD

**Issue by an0sv** [luigirizzo/netmap#892]
Is there any limits on how many receive buffers that can be configured in order to avoid incoming packet drops?

Which parameters should be configured? I'm using the latest master code

Currently we get spurious packet loss which is strange as the CPU should be able to handle it

**Comment by an0sv** [comment]
Anyone who knows?

**Comment by jhk098** [comment]
You should play with `ethtool` trying to increase the RX ring size, and adjust interrupt moderation/coalescing (e.g. increase `rx-usecs`)  to limit the interrupt rate, in case you observe a very high one.
Also, you should make sure that the CPU(s) receiving the traffic are not hogged by something else. Interrupt and CPU pinning may help, as well as CPU isolation.

**Comment by an0sv** [comment]
Ok, thanks.

I have tried setting the RX ring sizze using ethtool. The max is 4096 but if I set it to 4096 the whole kernel will crash. Weird, is that an expected behavior. I assume that one shoul dbe able to set it to max? If there other settings thta also need to be adjusted if one changes the RX?


I'm using the i40e driver

**Comment by an0sv** [comment]
A little update.

It seems that netmap crashes setting any value except 512.

Is this something that is fixed on master

**Comment by an0sv** [comment]
I built using latest master and now setting rx descriptors to 4096  on the i40e works without crashing the kernel.
