### ISSUE TITLE
Build issue on --no-ext-drivers with intel drivers

### ISSUE THREAD

**Issue by reinmark** [luigirizzo/netmap#898]
When trying to build the netmap-enabled intel drivers from local kernel sources the script intel-fix.sh is called. It tries to apply a patch to the non-existing external intel driver sources, resulting in a failure message:

[log.txt](https://github.com/luigirizzo/netmap/files/10099195/log.txt)

The build continues on skipping the patch.

Possible workaround to avoid patch: configure with --select-version=driver:nonexisting version

**Comment by giuseppelettieri** [comment]
What is the exact `configure` command that you are using? I can't reproduce the error on my box.

**Comment by reinmark** [comment]
Just re-checked by making a fresh clone & running
`./configure --kernel-sources=/path/to/source --no-ext-drivers --drivers=igb --driver-suffix=_netmap --no-apps --no-utils --disable-vale --disable-pipe --disable-monitor --disable-generic --disable-ptnetmap --disable-sink --disable-extmem`
-> same result

Observation:
- the igb source directory is copied from kernel tree into the netmap build directory (`igb@src`)
- the `intel-fix.sh` script is called trying to patch a non-existing file `igb/common.mk` (`igb@prepare`) resulting in `patch` asking which file to patch / if patch should be skipped respectively

Am I missing something?
Shouldn't the `<driver>@prepare` step be carried out conditionally only if `E_DRIVERS` contains `<driver>`?

**Comment by giuseppelettieri** [comment]
Yes, that would be cleaner. However, I had a quick workaround in my local repo, which I had not pushed to github yet. May you try with the latest master?

**Comment by reinmark** [comment]
Issue is fixed with latest master. Thank you!
