### ISSUE TITLE
Separate Rx/Tx sync for each ring

### ISSUE THREAD

**Issue by kalyazin** [luigirizzo/netmap#90]
Hi,

Currently NIOCTXSYNC and NIOCRXSYNC ioctls as well as poll() try to flush all the Rx/Tx rings in order (via for loop).
How is it possible for a thread within an application to handle a single queue only?
The possible use case for it is to assign a dedicated thread for each queue for higher performance.

**Comment by giuseppelettieri** [comment]
You can reopen /dev/netmap as many times as you wish and bind a single queue to each file descriptor. pkt-gen already does this when you give it the -p option.

If you use nm_open() you can do something like

nm_open("netmap:eth0-2", ....);

to open /dev/netmap and bind only queue 2 (both tx and rx) of interface eth0.

**Comment by kalyazin** [comment]
@giuseppelettieri, nice suggestion! Should think about it. Thanks.

**Comment by giuseppelettieri** [comment]
You are welcome. I am closing the issue.
