### ISSUE TITLE
Mixed mode support

### ISSUE THREAD

**Issue by NTMPUser** [luigirizzo/netmap#900]
Can a Netmap-capable kernel driver support a netmap-enabled application and a vanilla (non-netmap-enabled) application at the same time?

**Comment by jhk098** [comment]
Yes. If you have separate NICs (same driver) there is nothing special you need to do to achieve this result. Netmap applications open the NIC(s) in netmap mode, which means that they are (totally or partially) detached from the vanilla network stack. Other NICs not used in netmap mode are not affected by netmap.

**Comment by NTMPUser** [comment]
Thank you!
