### ISSUE TITLE
Lock-ups in monitor mode

### ISSUE THREAD

**Issue by dkoreshkov** [luigirizzo/netmap#901]
Hello,
I'm experiencing kernel lock-ups while trying to use the monitor mode on Linux
with netmap built from d67a604e805b67efb563ea8d5eb2d1318acf6ed8.
To reproduce, run these commands in separate terminals:
pkt-gen -f tx -i x}0
pkt-gen -f rx -i x{0
pkt-gen -f rx -i x{0/rtz
Everything works except that the packet rate suddenly drops from 40 to 6 mpps after starting the monitor.
Then randomly restart the receiver and the monitor a few times.
At some point the receiver rate becomes 512 pps, then my system usually hangs.
Sometimes only the apps hung, so I saved a couple of dmesg dumps.

[crash1.log](https://github.com/luigirizzo/netmap/files/10148110/crash1.log)
[crash3.log](https://github.com/luigirizzo/netmap/files/10148111/crash3.log)

**Comment by dkoreshkov** [comment]
Thanks, Giuseppe! This version is definitely stabler, although I still managed to crash it once.
[crash6.log](https://github.com/luigirizzo/netmap/files/10197588/crash6.log)

There also seems to be a reference counting bug: when I terminate the receiver first and then the other two apps, lsmod|grep netmap says there is still one use of the module, so I cannot unload it.

**Comment by giuseppelettieri** [comment]
The latest master should fix the reference counting bug. It might also fix the crash that you saw, since it looks related.

**Comment by dkoreshkov** [comment]
Thanks a lot, it works!
