### ISSUE TITLE
Race condition in netmap_grab_packets

### ISSUE THREAD

**Issue by dkoreshkov** [luigirizzo/netmap#923]
Hello!
There's a race condition in netmap_grab_packets: slot->len is read multiple times, particularly because m_devget is a macro.
If an application thread changes slot->len while another thread is syncing a host ring, you might get a panic  like this:

Apr 06 17:18:59 fm1.kur.kdp kernel: skbuff: skb_over_panic: text:ffffffffc0b731ba len:921 put:921 head:ffff8f0256687800 data:ffff8f0256687840 tail:0x3d9 end:0xc0 dev:red
Apr 06 17:18:59 fm1.kur.kdp kernel: ------------[ cut here ]------------
Apr 06 17:18:59 fm1.kur.kdp kernel: kernel BUG at net/core/skbuff.c:112!

Apr 06 17:18:59 fm1.kur.kdp kernel: Call Trace:
Apr 06 17:18:59 fm1.kur.kdp kernel:  <TASK>
Apr 06 17:18:59 fm1.kur.kdp kernel:  skb_put.cold+0x14/0x14
Apr 06 17:18:59 fm1.kur.kdp kernel:  netmap_grab_packets+0x8a/0x250 [netmap]
Apr 06 17:18:59 fm1.kur.kdp kernel:  netmap_txsync_to_host+0x4f/0xa0 [netmap]
Apr 06 17:18:59 fm1.kur.kdp kernel:  ? recalibrate_cpu_khz+0x10/0x10
Apr 06 17:18:59 fm1.kur.kdp kernel:  ? ktime_get_real_ts64+0x55/0xf0
Apr 06 17:18:59 fm1.kur.kdp kernel:  netmap_poll+0x203/0x5f0 [netmap]
Apr 06 17:18:59 fm1.kur.kdp kernel:  linux_netmap_poll+0x46/0x60 [netmap]
Apr 06 17:18:59 fm1.kur.kdp kernel:  do_poll.constprop.0+0x111/0x390
Apr 06 17:18:59 fm1.kur.kdp kernel:  do_sys_poll+0x1c8/0x250

**Comment by giuseppelettieri** [comment]
Thanks, may you try the following patch?
```
diff --git a/sys/dev/netmap/netmap.c b/sys/dev/netmap/netmap.c
index 744ad2887..874818dc3 100644
--- a/sys/dev/netmap/netmap.c
+++ b/sys/dev/netmap/netmap.c
@@ -1245,16 +1245,17 @@ netmap_grab_packets(struct netmap_kring *kring, struct mbq *q, int force)
 	for (n = kring->nr_hwcur; n != head; n = nm_next(n, lim)) {
 		struct mbuf *m;
 		struct netmap_slot *slot = &kring->ring->slot[n];
+		uint16_t len = NM_ACCESS_ONCE(slot->len);
 
 		if ((slot->flags & NS_FORWARD) == 0 && !force)
 			continue;
-		if (slot->len < 14 || slot->len > NETMAP_BUF_SIZE(na)) {
-			nm_prlim(5, "bad pkt at %d len %d", n, slot->len);
+		if (len < 14 || len > NETMAP_BUF_SIZE(na)) {
+			nm_prlim(5, "bad pkt at %d len %d", n, len);
 			continue;
 		}
 		slot->flags &= ~NS_FORWARD; // XXX needed ?
 		/* XXX TODO: adapt to the case of a multisegment packet */
-		m = m_devget(NMB(na, slot), slot->len, 0, na->ifp, NULL);
+		m = m_devget(NMB(na, slot), len, 0, na->ifp, NULL);
 
 		if (m == NULL)
 			break;
```

**Comment by dkoreshkov** [comment]
I've already changed my app, but before that I tried a similar code and it helped.

**Comment by giuseppelettieri** [comment]
OK, thanks. I'll push it to master.
