### ISSUE TITLE
Unable to open network interface in bridge application

### ISSUE THREAD

**Issue by arnavgupta2003** [luigirizzo/netmap#927]
System Conf:
Debian 12 (Freshly Installed)
TP-Link TG 3468 Gigabit Network Adapter

Issue:
nmport_open() return NULL
Error message: (CMD: sudo ./bridge -i eno1 -i eno1^)
     eno1: invalid request, prefix unknown or missing 
     012.577779 main [281] cannot open eno1

**Comment by giuseppelettieri** [comment]
bridge wants the `netmap:` prefix before the port names.
