### ISSUE TITLE
pkt-gen.c does not compile

### ISSUE THREAD

**Issue by john-gress** [luigirizzo/netmap#93]
Building on CentOS 6.5 with an updated kernel: 2.6.32-573.7.1.el6.x86_64

$ make VERBOSE=1 pkt-gen
cc -O2 -pipe -Werror -Wall -Wunused-function -I ../sys  -Wextra -DNO_PCAP   -c -o pkt-gen.o pkt-gen.c
cc1: warnings being treated as errors
pkt-gen.c: In function ‘receiver_body’:
pkt-gen.c:1479: error: ‘cur.t.tv_usec’ may be used uninitialized in this function
pkt-gen.c:1479: error: ‘cur.t.tv_sec’ may be used uninitialized in this function
make: *** [pkt-gen.o] Error 1

**Comment by giuseppelettieri** [comment]
thank you, may you please try the latest commit?

**Comment by john-gress** [comment]
Fixed by Giuseppe Lettieri (ed634309)
