### ISSUE TITLE
nm_open with range of queues

### ISSUE THREAD

**Issue by cygnus2048** [luigirizzo/netmap#941]
Imagine I have 8TX and 8RX queues and I want to process them with 2TX and 2RX threads.  The first thread should handle queues 0-3 and the second thread queues 4-7.  It doesn't look like nm_open() will allow this with the current syntax, but can I just create my own version of nm_open() to populate the nm_desc structure accordingly with appropriate first_tx_ring and last_tx_ring (same for RX) values?

In essence, if nm_open supported a range, I would like to do this...
thread1_nm_d = nm_open("netmap:ens4-0-3", ...);
thread2_nm_d = nm_open("netmap:ens4-4-7", ...);

Thanks.

**Comment by vmaffione** [comment]
Hi,
  It would not be enough to modify `nm_open` or `nmport_open` to support such a syntax.
In the very end, netmap open requests are submitted to the kernel by means of the `struct nmeq_register`, and there is no way to setup that struct to specify a range of rings. Furthermore, there is no kernel support for ranges (see `netmap_interp_ringid`).

However, you could achieve your goal (and potentially more efficiently than using ranges) with the following scheme:
- Thread TX1 would nm_open("netmap:ens4-${N}/T") for N in [0..3], and poll 4 file descriptors
- Thread TX2 would nm_open("netmap:ens4-${N}/T") for N in [4..7], and poll 4 file descriptors
- Thread RX1 would nm_open("netmap:ens4-${N}/R") for N in [0..3], and poll 4 file descriptors
- Thread RX2 would nm_open("netmap:ens4-${N}/R") for N in [4..7], and poll 4 file descriptors

**Comment by cygnus2048** [comment]
I see.  However, I guess I'm not understanding as much as I thought since what you say is not possible seems to be exactly what is done now when I open the device in "all queue" mode using no suffix as "netmap:ens4"?  That is a single fd with multiple rings as well as a single ring_id and it gets access to all the queues.  The descriptor has a "first ring" and "last ring" elements for TX and RX so with this in mind, how is ring_id even used?

My concern using multiple fd's is that in my benchmarking, most of the time is spent in the NIOCTXSYNC and NIOCRXSYNC ioctl() calls and now I will need to have my thread loop those calls over multiple fd's.  Hopefully the total time spent will be roughly the same as in the end, it will be the same number of packets being processed, but I don't know this for a fact.

Also, is there any benefit to having a separate fd for TX and RX?  I currently use a single one for all queues that the TX and RX threads both use and I have not seen any contention.   In other words, using this as opposed to your suggestion above...

- Thread TX1 and RX1 would use the result of nm_open("netmap:ens4-${N}") for N in [0..3], and poll 4 file descriptors
- Thread TX2 and RX2 would use the result of nm_open("netmap:ens4-${N}") for N in [4..7], and poll 4 file descriptors

Thanks.

**Comment by cygnus2048** [comment]
Sorry, I forgot to reply, but thanks for your explanation and information.  I was able to open fd's for each TX and RX queue and just have my threads loop over them when I have less cores than queues.  Thanks again.  Closing this.
