### ISSUE TITLE
Porting xemacps under netmap, found bug in function nm_os_generic_find_num_desc

### ISSUE THREAD

**Issue by ipmce** [luigirizzo/netmap#98]
Porting [xemacps](https://github.com/Xilinx/linux-xlnx/blob/master/drivers/net/ethernet/xilinx/xilinx_emacps.c) under [netmap](http://info.iet.unipi.it/~luigi/netmap/), found bug in function [nm_os_generic_find_num_desc](https://github.com/luigirizzo/netmap/blob/master/LINUX/netmap_linux.c#L445).
in nm_os_generic_find_num_desc:

        *tx = rp.tx_pending;
        *rx = rp.rx_pending;

in [xemacps_get_ringparam](https://github.com/Xilinx/linux-xlnx/blob/master/drivers/net/ethernet/xilinx/xilinx_emacps.c#L2547)

	erp->rx_max_pending = XEMACPS_RECV_BD_CNT;
	erp->tx_max_pending = XEMACPS_SEND_BD_CNT;
	erp->rx_pending = 0;
	erp->tx_pending = 0;

offer in nm_os_generic_find_num_desc:

        *tx = rp.tx_pending;
        if(!*tx) *tx = rp.tx_max_pending;
        *rx = rp.rx_pending;
        if(!*rx) *rx = rp.rx_max_pending;
        if(*tx && *rx) error = 0;

**Comment by giuseppelettieri** [comment]
Thank you, may you please try the latest commit?

**Comment by ipmce** [comment]
Thank you.
