### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [luigirizzo/netmap#99]
I would like to point out that identifiers like "[`_BSD_GLUE_H`](https://github.com/luigirizzo/netmap/blob/f9b54a4579b601eb9e01b3dceeb975e62d2ac39c/LINUX/bsd_glue.h#L32)" and "[`_NET_NETMAP_H_`](https://github.com/luigirizzo/netmap/blob/f8a0214532662ba2186d6abc55497649b677508f/sys/net/netmap.h#L39)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vmaffione** [comment]
This is a good point. I addressed some of these, but we cannot address them all: macros like `_NET_NETMAP_H_` follow the FreeBSD convention, so it makes sense that they remains that way.
Updated code will be published soon.

**Comment by elfring** [comment]
I suggest to reconsider your software development concerns once more.
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by vmaffione** [comment]
I see, but this is not the right place to raise this concern, most of this code is part of the FreeBSD kernel. I think freebsd-net@freebsd.org could be a better place for that.
